
SET_TELEPORT_STATE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT8
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDA @PARAM01
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	STA PSI_TELEPORT_DESTINATION
	LDA @LOCAL00
	AND #$00FF
	STA PSI_TELEPORT_STYLE
	END_C_FUNCTION
