
TELEPORT_MAINLOOP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSL STOP_MUSIC
	JSL WAIT_UNTIL_NEXT_FRAME
	JSR PSI_TELEPORT_FREEZE_OBJECTS
	LDA #1
	STA MOVEMENT_NOT_NORMAL
	MOVE_INT_CONSTANT 0, PSI_TELEPORT_SPEED
	STZ PSI_TELEPORT_STATE
	JSL PARTY_INTANGIBILITY_FLASH
	JSR INITIALIZE_PSI_TELEPORTATION
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::PSI_ALPHA
	BEQ @STYLE_1_OR_5
	CMP #TELEPORT_STYLE::LEARN_ALPHA
	BEQ @STYLE_1_OR_5
	CMP #TELEPORT_STYLE::PSI_BETA
	BEQ @STYLE_2
	CMP #TELEPORT_STYLE::INSTANT
	BEQ @STYLE_3
	CMP #TELEPORT_STYLE::PSI_BETTER
	BEQ @STYLE_4
	BRA @STYLE_OTHER
@STYLE_1_OR_5:
	LOADPTR PSI_TELEPORT_ALPHA_LEADER_TICK, @LOCAL00
	LOADPTR PSI_TELEPORT_FOLLOWER_TICK, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
	BRA @STYLE_OTHER
@STYLE_2:
	LOADPTR PSI_TELEPORT_BETA_LEADER_TICK, @LOCAL00
	LOADPTR PSI_TELEPORT_FOLLOWER_TICK, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
	BRA @STYLE_OTHER
@STYLE_3:
	LDA #1
	STA PSI_TELEPORT_STATE
	BRA @STYLE_OTHER
@STYLE_4:
	LOADPTR PSI_TELEPORT_BETA_LEADER_TICK, @LOCAL00
	LOADPTR PSI_TELEPORT_FOLLOWER_TICK, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
@STYLE_OTHER:
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::INSTANT
	BEQ @UNKNOWN6
	LDA #MUSIC::TELEPORT_OUT
	JSL CHANGE_MUSIC
	BRA @UNKNOWN6
@UNKNOWN5:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSR PSI_TELEPORT_FREEZE_OBJECTS2
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
@UNKNOWN6:
	LDA PSI_TELEPORT_STATE
	BEQ @UNKNOWN5
	LDA PSI_TELEPORT_STATE
	CMP #1
	BEQ @UNKNOWN7
	CMP #2
	BEQ @UNKNOWN8
	BRA @UNKNOWN9
@UNKNOWN7:
	JSR PSI_TELEPORT_DEPART
	JSL PSI_TELEPORT_LOAD_DESTINATION
	JSR PSI_TELEPORT_ARRIVE
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::LEARN_ALPHA
	BNE @UNKNOWN9
	LOADPTR MSG_EVT_MASTER_TLPT, @LOCAL00
	JSL DISPLAY_TEXT_WINDOWLESS
	BRA @UNKNOWN9
@UNKNOWN8:
	JSR PSI_TELEPORT_FAIL
	LDA #10
	JSL PSI_TELEPORT_WAIT_N_FRAMES
@UNKNOWN9:
	LOADPTR PARTY_LEADER_TICK, @LOCAL00
	LOADPTR PARTY_MEMBER_TICK, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
	JSR PSI_TELEPORT_RESTORE_CONTROL
	JSL UNFREEZE_ENTITIES
	STZ MOVEMENT_NOT_NORMAL
	MOVE_INT_CONSTANT NULL, PSI_TELEPORT_SPEED
	STZ PLAYER_INTANGIBILITY_FRAMES
	STZ PSI_TELEPORT_DESTINATION
	END_C_FUNCTION
