
UNUSED_C09E3B:
	STZ ENTITY_ALLOCATION_MIN_SLOT
	LDA #$003C
	STA ENTITY_ALLOCATION_MAX_SLOT
	STZ NEW_ENTITY_VAR1
	STZ NEW_ENTITY_VAR3
	STZ NEW_ENTITY_VAR4
	STZ NEW_ENTITY_VAR5
	STZ NEW_ENTITY_VAR6
	STZ NEW_ENTITY_VAR7
	STZ NEW_ENTITY_POS_Z
	JSR MOVEMENT_DATA_READ16_COPY
	TAX
	JSR MOVEMENT_DATA_READ16_COPY
	STY $94
	STA NEW_ENTITY_VAR0
	LDA $88
	STA NEW_ENTITY_VAR2
	TXA
	AND #$7FFF
	JMP INIT_ENTITY
