
UNUSED_C09ECE:
	JSR MOVEMENT_DATA_READ8_COPY
	TAX
	JSR MOVEMENT_DATA_READ16_COPY
	PHA
	JSR MOVEMENT_DATA_READ8_COPY
	STY $94
	TAY
	PLA
	JMP UNKNOWN_C09403
	LDX CURRENT_ENTITY_OFFSET
	BRA @UNKNOWN0
	LDX $88
	BRA @UNKNOWN0
	ASL
	TAX
@UNKNOWN0:
	LDY #$0000
	SEP #PROC_FLAGS::ACCUM8
	LDA ENTITY_SCREEN_X_TABLE+1,X
	BNE @UNKNOWN1
	LDA ENTITY_SCREEN_Y_TABLE+1,X
	BNE @UNKNOWN1
	DEY
@UNKNOWN1:
	REP #PROC_FLAGS::ACCUM8
	TYA
	RTL
