
UNKNOWN_EF0115: ;$EF0115
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	ASL
	TAX
	LDA WINDOW_EXISTENCE_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS_TABLE)
	TAX
	LDY a:window_stats::tilemap_address,X
	STY $10
	LDY a:window_stats::height,X
	LDA a:window_stats::width,X
	JSL MULT16
	TAX
	STX $0E
	BRA @UNKNOWN2
@UNKNOWN0:
	LDY $10
	LDA RAM,Y
	BEQ @UNKNOWN1
	JSL FREE_TILE_SAFE
@UNKNOWN1:
	LDA #$0040
	LDY $10
	STA RAM,Y
	INY
	INY
	STY $10
	LDX $0E
	DEX
	STX $0E
@UNKNOWN2:
	BNE @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA UNKNOWN_7E9623
	JSL UNKNOWN_C07C5B
	PLD
	RTL
