
UNKNOWN_EF0C87:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	ASL
	TAX
	LDA DELIVERY_ATTEMPTS,X
	END_C_FUNCTION
