
UNKNOWN_EF0C3D: ;$EF0C3D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 14
	LDA #$0003
	JSL LOAD_GAME_SLOT
	LDA GAME_STATE+game_state::leader_x_coord
	STA $04
	LDA GAME_STATE+game_state::leader_y_coord
	STA $02
	LDX #$0001
	TXA
	JSL FADE_OUT
	LDX $02
	LDA $04
	JSL UNKNOWN_C068F4
	LDX $02
	LDA $04
	JSL LOAD_MAP_AT_POSITION
	LDY GAME_STATE+game_state::leader_direction
	LDX $02
	LDA $04
	JSL UNKNOWN_C03FA9
	JSL UNKNOWN_C069AF
	LDX #$0001
	TXA
	JSL FADE_IN
	PLD
	RTL
