
UNKNOWN_EF0C3D:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	END_STACK_VARS
	LDA #3
	JSL LOAD_GAME_SLOT
	LDA GAME_STATE+game_state::leader_x_coord
	STA @VIRTUAL04
	LDA GAME_STATE+game_state::leader_y_coord
	STA @VIRTUAL02
	LDX #1
	TXA
	JSL FADE_OUT
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSL UNKNOWN_C068F4
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSL LOAD_MAP_AT_POSITION
	LDY GAME_STATE+game_state::leader_direction
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSL UNKNOWN_C03FA9
	JSL UNKNOWN_C069AF
	LDX #1
	TXA
	JSL FADE_IN
	END_C_FUNCTION
