
UNKNOWN_EF0C97: ;$EF0C97
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA .LOWORD(CURRENT_ENTITY_SLOT)
	ASL
	TAX
	LDA .LOWORD(ENTITY_SCRIPT_VAR0_TABLE),X
	ASL
	TAX
	STZ .LOWORD(UNKNOWN_7EB511),X
	RTL
