
UNKNOWN_EF0D46: ;$EF0D46
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	STA $0E
	ASL
	PHA
	LDA $0E
	OPTIMIZED_MULT $04, 20
	CLC
	ADC #$0008
	TAX
	LDA TIMED_DELIVERY_TABLE,X
	PLX
	STA UNKNOWN_7EB525,X
	PLD
	RTL
