
UNKNOWN_EF0E8A: ;$EF0E8A
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	OPTIMIZED_MULT @VIRTUAL04, 20
	CLC
	ADC #$0012
	TAX
	LDA TIMED_DELIVERY_TABLE,X
	PLD
	RTL
