
UNKNOWN_EF0F60:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA WINDOW_HEAD
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN1
@UNKNOWN0:
	LDA #1
	BRA @UNKNOWN9
@UNKNOWN1:
@UNKNOWN2:
	LDA ENTITY_FADE_ENTITY
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN3
	LDA #1
	BRA @UNKNOWN9
@UNKNOWN3:
	LDA OVERWORLD_STATUS_SUPPRESSION
	BEQ @UNKNOWN4
	LDA #1
	BRA @UNKNOWN9
@UNKNOWN4:
	LDA GAME_STATE+game_state::current_party_members
	ASL
	TAX
	LDA ENTITY_SPRITEMAP_POINTER_HIGH,X
	AND #$8000
	BEQ @UNKNOWN5
	LDA #1
	BRA @UNKNOWN9
@UNKNOWN5:
	LDA ENTITY_TICK_CALLBACK_HIGH+46
	AND #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	BEQ @UNKNOWN6
	LDA #0
	BRA @UNKNOWN7
@UNKNOWN6:
	LDA PENDING_INTERACTIONS
@UNKNOWN7:
	LDX GAME_STATE + game_state::walking_style
	CPX #WALKING_STYLE::LADDER
	BEQ @UNKNOWN8
	CPX #WALKING_STYLE::ROPE
	BEQ @UNKNOWN8
	CPX #WALKING_STYLE::ESCALATOR
	BEQ @UNKNOWN8
	CPX #WALKING_STYLE::STAIRS
	BNE @UNKNOWN9
@UNKNOWN8:
	LDA #1
@UNKNOWN9:
	END_C_FUNCTION
