
UNKNOWN_EFDA05:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LOADPTR UNKNOWN_7F0000, @VIRTUAL06
	JSL UNKNOWN_C08726
	SEP #PROC_FLAGS::ACCUM8
	LDA #$17
	STA TM_MIRROR
	LDA #$2F
	STA UNKNOWN_7E000B
	REP #PROC_FLAGS::ACCUM8
	STZ UNKNOWN_7EB55D
	STZ UNKNOWN_7EB557
	STZ DEBUG_MENU_CURSOR_POSITION
	STZ UNKNOWN_7EB551
	STZ UNKNOWN_7EB55F
	LDA #9
	JSL UNKNOWN_C08D79
	LDY #VRAM::OVERWORLD_LAYER_1_TILES
	LDX #VRAM::OVERWORLD_LAYER_1_TILEMAP
	LDA #BG_TILEMAP_SIZE::HORIZONTAL
	JSL SET_BG1_VRAM_LOCATION
	LDY #VRAM::OVERWORLD_LAYER_2_TILES
	LDX #VRAM::OVERWORLD_LAYER_2_TILEMAP
	LDA #BG_TILEMAP_SIZE::HORIZONTAL
	JSL SET_BG2_VRAM_LOCATION
	LDY #VRAM::TEXT_LAYER_TILES
	LDX #VRAM::TEXT_LAYER_TILEMAP
	LDA #BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG3_VRAM_LOCATION
	LDA #$02
	JSL SET_OAM_SIZE
	LDA #0
	STA [@VIRTUAL06]
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY #0
	TYX
	SEP #PROC_FLAGS::ACCUM8
	LDA #3
	JSL PREPARE_VRAM_COPY
	.A16
	LOADPTR UNKNOWN_EFF1BB, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 16
	LDA #.LOWORD(CUR_TEXT_PAL)
	JSL MEMCPY16
	JSL UNKNOWN_EFD95E
	STZ ENTITY_ALLOCATION_MIN_SLOT
	LDA #1
	STA ENTITY_ALLOCATION_MAX_SLOT
	LDY #52
	TYX
	LDA #EVENT_SCRIPT::EVENT_000
	JSL INIT_ENTITY_WIPE
	STA UNKNOWN_7EB553
	STZ UNKNOWN_7E4A58
	STZ UNKNOWN_7E4A5A
	END_C_FUNCTION
