
UNKNOWN_EFE6E2:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @LOCAL00
	LDA DEBUG_MODE_NUMBER
	CMP #1
	BNE @UNKNOWN0
	LDA @LOCAL00
	CMP #10
	BLTEQ @UNKNOWN0
	LDA #10
	STA @LOCAL00
@UNKNOWN0:
	LDA @LOCAL00
	END_C_FUNCTION
