
UNKNOWN_EFE708: ;$EFE708
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA #$0000
	STA $0E
	LDA .LOWORD(DEBUG_MODE_NUMBER)
	CMP #$0002
	BNE @UNKNOWN2
	BRA @UNKNOWN1
@UNKNOWN0:
	JSL READ_JOYPAD
@UNKNOWN1:
	LDA a:.LOWORD(PAD_1_STATE)
	AND #PAD::B_BUTTON
	BEQ @UNKNOWN0
	STZ .LOWORD(BATTLE_DEBUG)
	LDA #$FFFF
	STA $0E
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA a:.LOWORD(PAD_1_STATE)
	AND #PAD::Y_BUTTON
	BEQ @UNKNOWN3
	LDA #$FFFF
	STA $0E
@UNKNOWN3:
	LDA $0E
	PLD
	RTL
