
UNKNOWN_EFE895:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL00
	JSL TEST_SRAM_SIZE
	CMP #0
	BEQ @GOOD_SRAM_SIZE
	MOVE_INT RAND_A, UNKNOWN_7EB56D
	LDA UNKNOWN_7E0002
	AND #$00FF
	STA UNKNOWN_7EB571
	LDX @LOCAL00
	STX UNKNOWN_7EB573
@GOOD_SRAM_SIZE:
	END_C_FUNCTION
