
UNKNOWN_EFE895: ;$EFE895
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAX
	STX $0E
	JSL TEST_SRAM_SIZE
	CMP #$0000
	BEQ @GOOD_SRAM_SIZE
	MOVE_INT a:.LOWORD(RAND_A), .LOWORD(UNKNOWN_7EB56D)
	LDA a:.LOWORD(UNKNOWN_7E0002)
	AND #$00FF
	STA .LOWORD(UNKNOWN_7EB571)
	LDX $0E
	STX .LOWORD(UNKNOWN_7EB573)
@GOOD_SRAM_SIZE:
	PLD
	RTL
