
UNKNOWN_EFEA23:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	JSL TEST_SRAM_SIZE
	CMP #0
	BEQ @RETURN ;insufficient SRAM
	LDA UNKNOWN_7EB567
	BEQ @UNKNOWN0
	JSL LOAD_REPLAY_SAVE_SLOT
	LDA GAME_STATE+game_state::leader_x_coord
	STA UNKNOWN_7EB569
	LDA GAME_STATE+game_state::leader_y_coord
	STA UNKNOWN_7EB56B
	BRA @RETURN
@UNKNOWN0:
	JSL SAVE_REPLAY_SAVE_SLOT
@RETURN:
	END_C_FUNCTION
