
BACKGROUND_SLIDE_FRAME_ADVANCE:
	LDA TRANSITION_BACKGROUND_X_VELOCITY
	CLC
	ADC TRANSITION_BACKGROUND_X
	STA TRANSITION_BACKGROUND_X
	LDA TRANSITION_BACKGROUND_X_VELOCITY + 2
	ADC TRANSITION_BACKGROUND_X + 2
	STA TRANSITION_BACKGROUND_X + 2
	STA BG1_X_POS
	STA BG2_X_POS
	LDA TRANSITION_BACKGROUND_Y_VELOCITY
	CLC
	ADC TRANSITION_BACKGROUND_Y
	STA TRANSITION_BACKGROUND_Y
	LDA TRANSITION_BACKGROUND_Y_VELOCITY + 2
	ADC TRANSITION_BACKGROUND_Y + 2
	STA TRANSITION_BACKGROUND_Y + 2
	STA BG1_Y_POS
	STA BG2_Y_POS
	LDA BG1_X_POS
	LDX BG1_Y_POS
	JSL UNKNOWN_C01731
	RTL
