
DISPLAY_ANTI_PIRACY_SCREEN:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSL UNKNOWN_C40B51
	LOADPTR ANTI_PIRACY_NOTICE_GRAPHICS, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
	JSL DECOMP
	LOADPTR ANTI_PIRACY_NOTICE_ARRANGEMENT, @LOCAL00
	LOADPTR BUFFER + $4000, @LOCAL01
	JSL DECOMP
	JSL UNKNOWN_C40B75
	END_C_FUNCTION
