
FADE_OUT:
	PHP
	SEP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	EOR #$00FF
	INC
	STA FADE_PARAMETERS + fade_parameters::step
	STX FADE_PARAMETERS + fade_parameters::delay
	STX FADE_DELAY_FRAMES_LEFT
	PLP
	RTL
