
FINISH_FRAME:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDA RENDER_HPPP_WINDOWS
	AND #$00FF
	BEQ @UNKNOWN0
	JSR UPDATE_FLASH_TEXT_PALETTE
@UNKNOWN0:
	LDA BATTLE_MODE_FLAG
	BEQ @UNKNOWN1
	JSL FINISH_BATTLE_FRAME
	BRA @UNKNOWN2
@UNKNOWN1:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
@UNKNOWN2:
	END_C_FUNCTION
