
GAME_INIT: ;$C0B99A
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL CHECK_SRAM_INTEGRITY
	JSL INITIALIZE_SPC700
	JSL ENABLE_NMI_JOYPAD
	JSL CHECK_HARDWARE
	JSL READ_JOYPAD
	JSL READ_JOYPAD
	.IF DEBUG_BUILD
		LDA .LOWORD(PAD_1_STATE)
		AND #PAD::DOWN | PAD::L_BUTTON
		BEQ @NORMAL
		LDA #1
		STA .LOWORD(DEBUG)
		JSL DEBUG_MENU_LOAD
		BRA @RETURN
	.ENDIF
@NORMAL:
	STZ .LOWORD(DEBUG)
	JSL MAIN_LOOP
@RETURN:
	RTS
