
MAIN_LOOP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	JSL UNKNOWN_C43317
	LDA #.LOWORD(JMP_BUF1)
	JSL SETJMP
	JSL INIT_INTRO
	JSR FILE_SELECT_INIT
	JSR UNKNOWN_C0B67F
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	LDX #1
	TXA
	JSL FADE_IN
	JSL UPDATE_SCREEN
.IF .DEFINED(USA)
	LDA #.LOWORD(JMP_BUF2)
	JSL SETJMP
	JSL UNKNOWN_C43F53
.ENDIF
@LOOP_BEGIN:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL UNKNOWN_C4A7B0
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA CURRENT_QUEUED_INTERACTION
	SEC
	SBC NEXT_QUEUED_INTERACTION
	BEQ @UNKNOWN1
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN1
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @UNKNOWN1
	LDA BATTLE_MODE
	BNE @UNKNOWN1
	JSL PROCESS_QUEUED_INTERACTIONS
	INC INPUT_DISABLE_FRAME_COUNTER
	JMP @UNKNOWN20
@UNKNOWN1:
	LDA GAME_STATE + game_state::unknownB0
	CMP #2
	BEQL @UNKNOWN20
	LDX GAME_STATE+game_state::walking_style
	CPX #WALKING_STYLE::ESCALATOR
	BEQL @UNKNOWN20
	LDA BATTLE_SWIRL_COUNTDOWN
	BNEL @UNKNOWN20
	LDA BATTLE_MODE
	BEQ @UNKNOWN5
	JSL INIT_BATTLE_OVERWORLD
	INC INPUT_DISABLE_FRAME_COUNTER
	BRA @UNKNOWN6
@UNKNOWN5:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @UNKNOWN6
	CPX #3
	BNE @UNKNOWN6
	JSL UNKNOWN_C0943C
	JSL GET_OFF_BICYCLE
	JSL UNKNOWN_C09451
	JMP @LOOP_BEGIN
@UNKNOWN6:
	LDA DEBUG
	BEQ @NO_DEBUG
	LDA PAD_STATE
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @DEBUG_PAD2_B_HELD
	LDA PAD_PRESS
	AND #PAD::R_BUTTON
	BEQ @DEBUG_PAD2_B_HELD
	JSL DEBUG_Y_BUTTON_MENU
	JMP @LOOP_BEGIN
@DEBUG_PAD2_B_HELD:
	LDA PAD_PRESS + 2
	AND #PAD::A_BUTTON
	BEQ @DEBUG_PAD2_A_HELD
	JSL GET_DISTANCE_TO_MAGIC_TRUFFLE
@DEBUG_PAD2_A_HELD:
	LDA PAD_PRESS + 2
	AND #PAD::B_BUTTON
	BEQ @NO_DEBUG
	JSL TEST_YOUR_SANCTUARY_DISPLAY
@NO_DEBUG:
	LDA BATTLE_SWIRL_COUNTDOWN
	BNEL @LOOP_BEGIN
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNEL @LOOP_BEGIN
	LDA INPUT_DISABLE_FRAME_COUNTER
	BNE @UNKNOWN15
	LDA PENDING_INTERACTIONS
	BNE @UNKNOWN16
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BEQ @NO_OPEN_MENU
	JSL OPEN_MENU_BUTTON
	BRA @UNKNOWN16
@NO_OPEN_MENU:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @NO_OPEN_HPPP_DISPLAY
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::BICYCLE
	BEQ @NO_OPEN_HPPP_DISPLAY
	JSL OPEN_HPPP_DISPLAY
	BRA @UNKNOWN16
@NO_OPEN_HPPP_DISPLAY:
	LDA PAD_PRESS
	AND #PAD::X_BUTTON
	BEQ @NO_OPEN_TOWN_MAP
	JSL SHOW_TOWN_MAP
	BRA @UNKNOWN16
@NO_OPEN_TOWN_MAP:
	LDA PAD_PRESS
	AND #PAD::L_BUTTON
	BEQ @UNKNOWN16
	JSL OPEN_MENU_BUTTON_CHECKTALK
	BRA @UNKNOWN16
@UNKNOWN15:
	DEC INPUT_DISABLE_FRAME_COUNTER
@UNKNOWN16:
	LDA PSI_TELEPORT_DESTINATION
	BEQ @UNKNOWN17
	JSL TELEPORT_MAINLOOP
@UNKNOWN17:
	LDA DEBUG
	BEQ @UNKNOWN20
	LDA PAD_PRESS + 2
	AND #PAD::B_BUTTON
	BEQ @UNKNOWN20
	LDA #0
	STA @LOCAL00
	BRA @UNKNOWN19
@UNKNOWN18:
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::max_hp,X
	STA PARTY_CHARACTERS+char_struct::current_hp_target,X
	LDA PARTY_CHARACTERS+char_struct::max_pp,X
	STA PARTY_CHARACTERS+char_struct::current_pp_target,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@UNKNOWN19:
	CMP #TOTAL_PARTY_COUNT
	BCC @UNKNOWN18
@UNKNOWN20:
	JSL UNKNOWN_C04FFE
	CMP #0
	BNE @UNKNOWN21
	JSL SPAWN
	CMP #0
	BEQ @UNKNOWN21
	LDX #0
	LDA #.LOWORD(JMP_BUF1)
	JSL LONGJMP
@UNKNOWN21:
	LDA DEBUG
	BEQL @LOOP_BEGIN
	LDA PAD_STATE
	AND #PAD::START_BUTTON
	BEQL @LOOP_BEGIN
	LDA PAD_STATE
	AND #PAD::SELECT_BUTTON
	BEQL @LOOP_BEGIN
	END_C_FUNCTION
