
OAM_CLEAR:
.IF .DEFINED(JPN)
	PHP
.ENDIF
	SEP #PROC_FLAGS::ACCUM8
	REP #PROC_FLAGS::INDEX8
	LDX #$0000
	STX PRIORITY_0_SPRITE_OFFSET
	STX PRIORITY_1_SPRITE_OFFSET
	STX PRIORITY_2_SPRITE_OFFSET
	STX PRIORITY_3_SPRITE_OFFSET
	LDX NEXT_FRAME_BUF_ID
	DEX
	BNEL @UNKNOWN1
	LDX #.LOWORD(OAM1)
	STX OAM_ADDR
	LDX #.LOWORD(OAM1) + 128 * .SIZEOF(oam_entry)
	STX OAM_END_ADDR
	LDX #.LOWORD(OAM1_HIGH_TABLE)
	STX OAM_HIGH_TABLE_ADDR
	LDA #$80
	STA OAM_HIGH_TABLE_BUFFER
	LDA #$E0
	PHD
	PEA OAM1
	PLD
	STA <(OAM1 + 0 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 1 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 2 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 3 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 4 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 5 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 6 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 7 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 8 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 9 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 10 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 11 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 12 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 13 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 14 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 15 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 16 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 17 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 18 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 19 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 20 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 21 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 22 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 23 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 24 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 25 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 26 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 27 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 28 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 29 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 30 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 31 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 32 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 33 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 34 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 35 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 36 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 37 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 38 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 39 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 40 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 41 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 42 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 43 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 44 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 45 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 46 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 47 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 48 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 49 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 50 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 51 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 52 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 53 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 54 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 55 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 56 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 57 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 58 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 59 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 60 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 61 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 62 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 63 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	PEA OAM1 + $100
	PLD
	STA <(OAM1 + 64 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 65 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 66 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 67 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 68 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 69 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 70 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 71 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 72 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 73 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 74 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 75 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 76 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 77 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 78 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 79 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 80 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 81 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 82 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 83 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 84 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 85 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 86 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 87 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 88 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 89 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 90 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 91 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 92 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 93 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 94 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 95 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 96 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 97 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 98 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 99 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 100 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 101 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 102 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 103 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 104 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 105 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 106 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 107 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 108 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 109 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 110 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 111 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 112 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 113 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 114 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 115 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 116 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 117 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 118 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 119 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 120 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 121 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 122 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 123 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 124 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 125 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 126 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM1 + 127 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	PLD
.IF .DEFINED(JPN)
	PLP
.ELSE
	REP #PROC_FLAGS::ACCUM8
.ENDIF
	RTL
@UNKNOWN1:
	.A8
	LDX #.LOWORD(OAM2)
	STX OAM_ADDR
	LDX #.LOWORD(OAM2) + 128 * .SIZEOF(oam_entry)
	STX OAM_END_ADDR
	LDX #.LOWORD(OAM2_HIGH_TABLE)
	STX OAM_HIGH_TABLE_ADDR
	LDA #$80
	STA OAM_HIGH_TABLE_BUFFER
	LDA #$E0
	PHD
	PEA OAM2
	PLD
	STA <(OAM2 + 0 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 1 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 2 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 3 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 4 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 5 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 6 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 7 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 8 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 9 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 10 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 11 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 12 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 13 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 14 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 15 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 16 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 17 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 18 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 19 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 20 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 21 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 22 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 23 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 24 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 25 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 26 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 27 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 28 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 29 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 30 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 31 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 32 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 33 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 34 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 35 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 36 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 37 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 38 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 39 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 40 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 41 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 42 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 43 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 44 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 45 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 46 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 47 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 48 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 49 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 50 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 51 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 52 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 53 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 54 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 55 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 56 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 57 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 58 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 59 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 60 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 61 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 62 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 63 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	PEA OAM2 + $100
	PLD
	STA <(OAM2 + 64 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 65 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 66 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 67 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 68 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 69 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 70 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 71 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 72 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 73 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 74 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 75 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 76 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 77 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 78 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 79 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 80 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 81 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 82 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 83 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 84 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 85 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 86 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 87 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 88 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 89 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 90 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 91 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 92 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 93 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 94 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 95 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 96 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 97 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 98 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 99 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 100 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 101 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 102 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 103 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 104 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 105 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 106 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 107 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 108 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 109 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 110 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 111 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 112 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 113 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 114 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 115 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 116 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 117 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 118 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 119 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 120 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 121 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 122 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 123 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 124 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 125 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 126 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	STA <(OAM2 + 127 * .SIZEOF(oam_entry) + oam_entry::y_coord)
	PLD
.IF .DEFINED(JPN)
	PLP
.ELSE
	REP #PROC_FLAGS::ACCUM8
.ENDIF
	RTL
