
PERFORM_PALETTE_FADE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL02
	STA @VIRTUAL02
	PROMOTENEARPTR MAP_PALETTE_BACKUP, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	TXA
	JSL MULTIPLY_PALETTES
	LDY @LOCAL02
	TYX
	LDA @VIRTUAL02
	JSL PREPARE_LOADED_PALETTE_FADE_TABLES
	LDA @VIRTUAL02
	CMP #1
	BEQ @UNKNOWN2
	LDA #0
	STA @LOCAL01
	BRA @UNKNOWN1
@UNKNOWN0:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA @LOCAL01
	INC
	STA @LOCAL01
@UNKNOWN1:
	CMP @VIRTUAL02
	BCC @UNKNOWN0
@UNKNOWN2:
	JSL FINISH_PALETTE_FADE
	LDA #24
	JSL PREPARE_PALETTE_UPLOAD
	END_C_FUNCTION
