
PREPARE_VRAM_COPY: ;$C08616
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	STA a:.LOWORD(UNKNOWN_7E0091)
	STX a:.LOWORD(DMA_COPY_SIZE)
	LDA $0E
	STA a:.LOWORD(DMA_COPY_RAM_SRC)
	LDA $10
	STA a:.LOWORD(DMA_COPY_RAM_SRC) + 2
	STY a:.LOWORD(DMA_COPY_VRAM_DEST)
	JMP a:.LOWORD(PREPARE_VRAM_COPY_COMMON)
PREPARE_VRAM_COPY_ENTRY_B:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	STA a:.LOWORD(UNKNOWN_7E0091)
	STX a:.LOWORD(DMA_COPY_SIZE)
	STY a:.LOWORD(DMA_COPY_RAM_SRC)
	LDA $0E
	STA a:.LOWORD(DMA_COPY_RAM_SRC) + 2
	LDA $10
	STA a:.LOWORD(DMA_COPY_VRAM_DEST)
PREPARE_VRAM_COPY_COMMON:
	PHP
	REP #PROC_FLAGS::ACCUM8
	SEP #PROC_FLAGS::INDEX8
	PHD
	PEA $0000
	PLD
	PHB
	LDY #$0000
	PHY
	PLB
	REP #PROC_FLAGS::INDEX8
	JSR a:.LOWORD(COPY_TO_VRAM)
	PLB
	PLD
	PLP
	RTL
