
RECTANGLE_WINDOW_CONFIGURE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL04
	TXY
	STA @VIRTUAL04
	LDX @PARAM03
	STX @VIRTUAL02
	LDA RECTANGLE_WINDOW_BUFFER_INDEX
	AND #$0001
	BEQ @UNKNOWN0
	LDA #0
	STA @LOCAL03
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #766
	STA @LOCAL03
@UNKNOWN1:
	LOADPTR BUFFER, @VIRTUAL06
	LDA @LOCAL03
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	LDX #224
	TYA
	JSR CLAMP_0_UPPER
	STA @LOCAL02
	LDX #224
	LDA @VIRTUAL02
	JSR CLAMP_0_UPPER
	STA @LOCAL03
	LDX #256
	LDA @VIRTUAL04
	JSR CLAMP_0_UPPER
	STA @VIRTUAL04
	LDX #256
	LDA @LOCAL04
	JSR CLAMP_0_UPPER
	STA @VIRTUAL02
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY #127
	LDX #128
	LDA @LOCAL02
	JSR RECTANGLE_WINDOW_ADD_HDMA_ENTRY
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY @VIRTUAL02
	LDX @VIRTUAL04
	LDA @LOCAL03
	SEC
	SBC @LOCAL02
	JSR RECTANGLE_WINDOW_ADD_HDMA_ENTRY
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY #127
	LDX #128
	LDA #224
	SEC
	SBC @LOCAL03
	DEC
	JSR RECTANGLE_WINDOW_ADD_HDMA_ENTRY
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	LDX @LOCAL01
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01+2
	JSL RECTANGLE_WINDOW_ENABLE_HDMA
	INC RECTANGLE_WINDOW_BUFFER_INDEX
	END_C_FUNCTION
