
SET_BG2_VRAM_LOCATION: ;$C08DDE
	PHP
	SEP #PROC_FLAGS::ACCUM8
	REP #PROC_FLAGS::INDEX8
	AND #$0003
	STA a:.LOWORD(UNKNOWN_7E0011)+1
	REP #PROC_FLAGS::ACCUM8
	TXA
	XBA
	SEP #PROC_FLAGS::ACCUM8
	AND #$00FC
	ORA a:.LOWORD(UNKNOWN_7E0011)+1
	STA a:.LOWORD(UNKNOWN_7E0011)+1
	STA f:BG2SC
	LDA a:.LOWORD(BG12NBA_MIRROR)
	AND #$000F
	STA a:.LOWORD(BG12NBA_MIRROR)
	REP #PROC_FLAGS::ACCUM8
	STZ a:.LOWORD(BG2_X_POS)
	STZ a:.LOWORD(BG2_Y_POS)
	TYA
	XBA
	SEP #PROC_FLAGS::ACCUM8
	AND #$00F0
	ORA a:.LOWORD(BG12NBA_MIRROR)
	STA a:.LOWORD(BG12NBA_MIRROR)
	STA f:BG12NBA
	PLP
	RTL
