
SET_BG4_VRAM_LOCATION:
	PHP
	SEP #PROC_FLAGS::ACCUM8
	REP #PROC_FLAGS::INDEX8
	AND #$0003
	STA BG4SC_MIRROR
	REP #PROC_FLAGS::ACCUM8
	TXA
	XBA
	SEP #PROC_FLAGS::ACCUM8
	AND #$00FC
	ORA BG4SC_MIRROR
	STA BG4SC_MIRROR
	STA f:BG4SC
	LDA BG34NBA_MIRROR
	AND #$000F
	STA BG34NBA_MIRROR
	REP #PROC_FLAGS::ACCUM8
	STZ BG4_X_POS
	STZ BG4_Y_POS
	TYA
	XBA
	SEP #PROC_FLAGS::ACCUM8
	AND #$00F0
	ORA BG34NBA_MIRROR
	STA BG34NBA_MIRROR
	STA f:BG34NBA
	PLP
	RTL
