
TEST_SRAM_SIZE: ;$C08391
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0030
	STA f:SRAM_SIZE_1_SCRATCH
	INC
	STA f:SRAM_SIZE_2_SCRATCH
	CMP f:SRAM_SIZE_1_SCRATCH
	BEQ @END_OF_SRAM_FOUND
	INC
	STA f:SRAM_SIZE_3_SCRATCH
	CMP f:SRAM_SIZE_1_SCRATCH
	BEQ @END_OF_SRAM_FOUND
	STA UNKNOWN_7E0A36
@END_OF_SRAM_FOUND:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	LDA UNKNOWN_7E0A36
	RTL
