
TRANSFER_TO_VRAM:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	STA DMA_COPY_MODE
@UNKNOWN0:
	LDA DMA_BYTES_COPIED
	BNE @UNKNOWN0
	MOVE_INT $0E, DMA_COPY_RAM_SRC
	STY DMA_COPY_VRAM_DEST
	CPX #$1201
	BCC @UNKNOWN3
	LDA #$1200
	STA DMA_COPY_SIZE
@UNKNOWN1:
	CPX #$1201
	BCC @UNKNOWN3
@UNKNOWN2:
	LDA DMA_BYTES_COPIED
	BNE @UNKNOWN2
	PHX
	JSL PREPARE_VRAM_COPY_COMMON
	.A16
	LDA DMA_COPY_RAM_SRC
	CLC
	ADC #$1200
	STA DMA_COPY_RAM_SRC
	LDA DMA_COPY_VRAM_DEST
	CLC
	ADC #$0900
	STA DMA_COPY_VRAM_DEST
	PLA
	SEC
	SBC #$1200
	TAX
	BRA @UNKNOWN1
@UNKNOWN3:
	STX DMA_COPY_SIZE
@UNKNOWN4:
	LDA DMA_BYTES_COPIED
	BNE @UNKNOWN4
	JSL PREPARE_VRAM_COPY_COMMON
	.A16
@UNKNOWN5:
	LDA DMA_BYTES_COPIED
	BNE @UNKNOWN5
	RTL
