
CLEAR_UNKNOWN_30X2_TABLE23: ;$C00000
	.A16
	.I16
	STZ .LOWORD(ENTITY_DRAW_SORTING)
	LDX #.LOWORD(ENTITY_DRAW_SORTING)
	LDY #.LOWORD(ENTITY_DRAW_SORTING)+1
	LDA #$003B
	MVN #$7E,#$7E
	LDA #.LOWORD(ENTITY_DRAW_SORTING)
	RTS
