
CHECK_BLOCK_SIGNATURE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int slot
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	TAX
	STX @LOCAL02
	LDY #.SIZEOF(save_block)
	TXA
	JSL MULT16
	STORE_INT1632 @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN SAVE_BASE, @VIRTUAL06
	LOADPTR SRAM_SIGNATURE, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL STRCMP
	CMP #0
	BEQ @UNKNOWN0
	LDX @LOCAL02
	TXA
	JSR ERASE_SAVE_BLOCK
	LDA #TRUE
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #FALSE
@UNKNOWN1:
	END_C_FUNCTION
