
LOAD_GAME_SLOT:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
.IF !.DEFINED(JPN)
	STACK_RESERVE_INT16 "UNKNOWN_EB_LOCAL"
.ENDIF
	STACK_RESERVE_INT32 "LOCAL03"
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
.IF .DEFINED(JPN)
	@VIRTUAL_TMP_A = @VIRTUAL0A
.ELSE
	@VIRTUAL_TMP_A = @VIRTUAL06
.ENDIF
	LDY #$0A00
	JSL MULT16
	STORE_INT1632 @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN SAVE_BASE + .SIZEOF(save_header), @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	PROMOTENEARPTR GAME_STATE, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL02
.IF .DEFINED(JPN)
	LDA #$007E
	STA @LOCAL02 + 2
.ELSE
	TDC
	CLC
	ADC #$0018
	TAX
	STX @UNKNOWN_EB_LOCAL
	LDA #$007E
	STA __BSS_START__,X
.ENDIF
	MOVE_INT @LOCAL02, @VIRTUAL_TMP_A
	MOVE_INT @VIRTUAL_TMP_A, @LOCAL00
	MOVE_INT @LOCAL03, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA #.SIZEOF(game_state)
	JSL MEMCPY24
	LDA #.SIZEOF(game_state)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL03
	LDA @VIRTUAL06 + 2
	STA @LOCAL03 + 2
	PROMOTENEARPTR PARTY_CHARACTERS, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA #$007E
.IF .DEFINED(JPN)
	STA @LOCAL02 + 2
.ELSE
	LDX @UNKNOWN_EB_LOCAL
	STA __BSS_START__,X
.ENDIF
	MOVE_INT @LOCAL02, @VIRTUAL_TMP_A
	MOVE_INT @VIRTUAL_TMP_A, @LOCAL00
	MOVE_INT @LOCAL03, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA #.SIZEOF(char_struct)*6
	JSL MEMCPY24
	LDA #.SIZEOF(char_struct)*6
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL03
	LDA @VIRTUAL06 + 2
	STA @LOCAL03 + 2
	PROMOTENEARPTR EVENT_FLAGS, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA #$007E
.IF .DEFINED(JPN)
	STA @LOCAL02 + 2
.ELSE
	LDX @UNKNOWN_EB_LOCAL
	STA __BSS_START__,X
.ENDIF
	MOVE_INT @LOCAL02, @VIRTUAL_TMP_A
	MOVE_INT @VIRTUAL_TMP_A, @LOCAL00
	MOVE_INT @LOCAL03, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA #$0080
	JSL MEMCPY24
	MOVE_INT GAME_STATE + game_state::timer, @VIRTUAL06
	MOVE_INT @VIRTUAL06, TIMER
	PLD
	RTL
