
VALIDATE_SAVE_BLOCK_CHECKSUMS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int slot
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	TAX
	STX @LOCAL00
	TXA
	JSR CALC_SAVE_BLOCK_ADD_CHECKSUM
	STA @VIRTUAL04
	LDX @LOCAL00
	TXA
	JSR CALC_SAVE_BLOCK_XOR_CHECKSUM
	STA @VIRTUAL02
	LDY #.SIZEOF(save_block)
	LDX @LOCAL00
	TXA
	JSL MULT16
	STORE_INT1632 @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN SAVE_BASE + save_header::checksum, @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN SAVE_BASE + save_header::checksum_complement, @VIRTUAL0A
	LDA [@VIRTUAL06]
	CMP @VIRTUAL04
	BNE @UNKNOWN0
	LDA [@VIRTUAL0A]
	CMP @VIRTUAL02
	BEQ @UNKNOWN1
@UNKNOWN0:
	LDA #.LOWORD(-1)
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA #0
@UNKNOWN2:
	END_C_FUNCTION
