
INIT_INTRO:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
.IF .DEFINED(JPN) || .DEFINED(PROTOTYPE19950327)
	STACK_RESERVE_INT16
.ENDIF
	END_STACK_VARS
.IF .DEFINED(JPN) || .DEFINED(PROTOTYPE19950327)
	.DEFINE _BEQL BEQ
	LDY #0
	STY @LOCAL01
.ELSE
	.DEFINE _BEQL BEQL ;the final build of earthbound introduced some code for the logo and title screens, so some cases need long branches
	LDA #0
	STA @VIRTUAL02
.ENDIF
	LDA #1
	STA DISABLED_TRANSITIONS
	LDA #2
	JSL UNKNOWN_C0AC0C
	JSL UNKNOWN_C0927C
	JSL UNKNOWN_C200D9
	JSL UNKNOWN_C432B1
	LDA #1
	STA DISABLE_MUSIC_CHANGES
.IF .DEFINED(USA)
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
.ENDIF
@UNKNOWN0:
.IF .DEFINED(JPN) || .DEFINED(PROTOTYPE19950327)
	LDY @LOCAL01
	TYA
.ELSE
	LDA @VIRTUAL02
.ENDIF
	BEQ @UNKNOWN11
	CMP #1
	_BEQL @UNKNOWN14
	CMP #2
	_BEQL @UNKNOWN17
	CMP #3
	_BEQL @UNKNOWN18
	CMP #4
	_BEQL @UNKNOWN19
	CMP #5
	_BEQL @UNKNOWN20
	CMP #6
	BEQL @UNKNOWN21
	CMP #7
	BEQL @UNKNOWN22
	CMP #8
	BEQL @UNKNOWN23
	CMP #9
	BEQL @UNKNOWN24
	CMP #10
	BEQL @UNKNOWN25
	JMP @UNKNOWN26
@UNKNOWN11:
	JSL LOGO_SCREEN
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	CMP #0
	BEQ @UNKNOWN13
	LDA #2
	JSL UNKNOWN_C0AC0C
	LDA INIDISP_MIRROR
	AND #$00FF
	CMP #$80
	BEQ @UNKNOWN12
	LDY #0
	LDX #1
	LDA #4
	JSL FADE_OUT_WITH_MOSAIC
@UNKNOWN12:
	LDA #MUSIC::TITLE_SCREEN
	JSL CHANGE_MUSIC
	LDA #1
	JSL SHOW_TITLE_SCREEN
	TAX
	STX @LOCAL00
	LDA #2
	STA @VIRTUAL02
	JMP @UNKNOWN27
@UNKNOWN13:
	LDX #0
.ELSE
	TAX
.ENDIF
	STX @LOCAL00
	JMP @UNKNOWN27
@UNKNOWN14:
	LDA #MUSIC::GAS_STATION
	JSL CHANGE_MUSIC
	JSL GAS_STATION
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	CMP #0
	BEQ @UNKNOWN16
	LDA #2
	JSL UNKNOWN_C0AC0C
	LDA INIDISP_MIRROR
	AND #$00FF
	CMP #$80
	BEQ @UNKNOWN15
	LDY #0
	LDX #1
	LDA #4
	JSL FADE_OUT_WITH_MOSAIC
@UNKNOWN15:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA f:CGADSUB
	STA f:CGWSEL
	LDA #1
	STA TM_MIRROR
	STZ TD_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA #MUSIC::TITLE_SCREEN
	JSL CHANGE_MUSIC
	LDA #1
	JSL SHOW_TITLE_SCREEN
	TAX
	STX @LOCAL00
	INC @VIRTUAL02
	JMP @UNKNOWN27
@UNKNOWN16:
	LDX #0
.ELSE
	TAX
.ENDIF
	STX @LOCAL00
	JMP @UNKNOWN27
@UNKNOWN17:
	LDA #MUSIC::TITLE_SCREEN
	JSL CHANGE_MUSIC
	LDA #0
	JSL SHOW_TITLE_SCREEN
	TAX
	STX @LOCAL00
	BRA @UNKNOWN27
@UNKNOWN18:
	LDA #MUSIC::ATTRACT_MODE
	JSL CHANGE_MUSIC
	LDA #0
	JSL UNKNOWN_C4D989
	TAX
	STX @LOCAL00
	BRA @UNKNOWN27
@UNKNOWN19:
	LDA #2
	JSL UNKNOWN_C4D989
	TAX
	STX @LOCAL00
	BRA @UNKNOWN27
@UNKNOWN20:
	LDA #3
	JSL UNKNOWN_C4D989
	TAX
	STX @LOCAL00
	BRA @UNKNOWN27
@UNKNOWN21:
	LDA #4
	JSL UNKNOWN_C4D989
	TAX
	STX @LOCAL00
	BRA @UNKNOWN27
@UNKNOWN22:
	LDA #5
	JSL UNKNOWN_C4D989
	TAX
	STX @LOCAL00
	BRA @UNKNOWN27
@UNKNOWN23:
	LDA #6
	JSL UNKNOWN_C4D989
	TAX
	STX @LOCAL00
	BRA @UNKNOWN27
@UNKNOWN24:
	LDA #7
	JSL UNKNOWN_C4D989
	TAX
	STX @LOCAL00
	BRA @UNKNOWN27
@UNKNOWN25:
	LDA #9
	JSL UNKNOWN_C4D989
	TAX
	STX @LOCAL00
	BRA @UNKNOWN27
@UNKNOWN26:
.IF .DEFINED(JPN) || .DEFINED(PROTOTYPE19950327)
	LDY #1
	STY @LOCAL01
.ELSE
	LDA #1
	STA @VIRTUAL02
.ENDIF
@UNKNOWN27:
.IF .DEFINED(JPN) || .DEFINED(PROTOTYPE19950327)
	LDY @LOCAL01
	INY
	STY @LOCAL01
.ELSE
	INC @VIRTUAL02
.ENDIF
	LDX @LOCAL00
	BEQL @UNKNOWN0
	LDA #2
	JSL UNKNOWN_C0AC0C
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	SEP #PROC_FLAGS::ACCUM8
	STZ FADE_PARAMETERS + fade_parameters::step
	REP #PROC_FLAGS::ACCUM8
.ENDIF
	LDA INIDISP_MIRROR
	AND #$00FF
	CMP #$80
	BEQ @UNKNOWN29
	LDY #0
	LDX #1
	LDA #4
	JSL FADE_OUT_WITH_MOSAIC
@UNKNOWN29:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	STA f:CGADSUB
	STA f:CGWSEL
	LDA #$01
	STA TM_MIRROR
	STZ TD_MIRROR
	REP #PROC_FLAGS::ACCUM8
	STZ DISABLE_MUSIC_CHANGES
	END_C_FUNCTION
