
SHOW_TITLE_SCREEN:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	STA TITLE_SCREEN_QUICK_MODE
	JSL UNKNOWN_C08726
	LDA @VIRTUAL04
	BNE @T001
	JSL UNKNOWN_C0927C
	BRA @UNKNOWN1
@T001:
	LDY #0
	LDX #1
	TXA
	JSL FADE_OUT_WITH_MOSAIC
	LDA #0
	STA @LOCAL03
	BRA @T002
@UNKNOWN0:
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #$8000
	STA __BSS_START__,X
	LDA @LOCAL03
	INC
	STA @LOCAL03
@T002:
	CMP #MAX_ENTITIES
	BCC @UNKNOWN0
@UNKNOWN1:
	LDA #11
	JSL UNKNOWN_C08D79
	LDA #3
	JSL SET_OAM_SIZE
	LDY #$0000
	LDX #$5800
	TYA ;BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG1_VRAM_LOCATION
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
	JSL UNKNOWN_C0EBE0
	SEP #PROC_FLAGS::ACCUM8
	LDA #$11
	STA TM_MIRROR
	JSL OAM_CLEAR
	.A16
	LDY #0
	TYX
	LDA #EVENT_SCRIPT::TITLE_SCREEN_1
	JSL INIT_ENTITY_WIPE
	STZ ACTIONSCRIPT_STATE
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	STZ @LOCAL00
	LDX #.LOWORD(PALETTES)
	REP #PROC_FLAGS::ACCUM8
	LDA #BPP4PALETTE_SIZE * 16
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	JSL UNKNOWN_C08744
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0F
	STA INIDISP_MIRROR
	JSL WAIT_UNTIL_NEXT_FRAME
	SEP #PROC_FLAGS::ACCUM8
	STZ PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
	LOADPTR UNKNOWN_E1AE7C, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	LDA #BPP4PALETTE_SIZE * 8
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	JSL DECOMP
	JSL UNKNOWN_C496F9
	SEP #PROC_FLAGS::ACCUM8
	STZ @LOCAL00
	LDX #.LOWORD(PALETTES)
	REP #PROC_FLAGS::ACCUM8
	LDA #BPP4PALETTE_SIZE * 16
	JSL MEMSET16
	LDX #$0100
	LDA #60
	JSL UNKNOWN_C496E7
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	LDX #0
	STX @LOCAL03
	BRA @UNKNOWN4
@UNKNOWN3:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL UNKNOWN_C1004E
	LDX @LOCAL03
	INX
	STX @LOCAL03
@UNKNOWN4:
	STX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA #60
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @UNKNOWN3
	LDA #0
@UNKNOWN7:
	STA @VIRTUAL02
	BRA @T005
@T004:
	LDA @VIRTUAL04
	BNE @T006
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BNE @T003
	LDA PAD_PRESS
	AND #PAD::B_BUTTON
	BNE @T003
	LDA PAD_PRESS
	AND #PAD::START_BUTTON
	BEQ @T006
@T003:
	LDA #1
	STA @VIRTUAL02
	BRA @T007
@T006:
	JSL UNKNOWN_C1004E
@T005:
	LDA ACTIONSCRIPT_STATE
	BEQ @T004
@T007:
	LDY #0
	LDX #4
	LDA #1
	JSL FADE_OUT_WITH_MOSAIC
	LDA @VIRTUAL04
	BNE @UNKNOWN18
	STZ ACTIONSCRIPT_STATE
	LDA #0
	JSL UNKNOWN_C474A8
	JSL UNKNOWN_C0927C
	LDA @VIRTUAL02
	BRA @UNKNOWN23
@UNKNOWN18:
	LDX #0
	STX @LOCAL02
	BRA @UNKNOWN22
@UNKNOWN19:
	TXA
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #EVENT_SCRIPT::TITLE_SCREEN_1
	BCC @UNKNOWN21
	CMP #EVENT_SCRIPT::TITLE_SCREEN_11
	BGT @UNKNOWN21
	LDX @LOCAL02
	TXA
	JSL UNKNOWN_C09C35
@UNKNOWN21:
	LDX @LOCAL02
	TXA
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAY
	LDA __BSS_START__,Y
	AND #$7FFF
	STA __BSS_START__,Y
	INX
	STX @LOCAL02
@UNKNOWN22:
	CPX #MAX_ENTITIES
	BCC @UNKNOWN19
	JSL UNKNOWN_C08726
	JSL RELOAD_MAP
	JSL UNDRAW_FLYOVER_TEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA #$17
	STA TM_MIRROR
	LDX #1
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL FADE_IN
@UNKNOWN23:
	END_C_FUNCTION
