
CLEAR_ENTITY_DRAW_SORTING_TABLE:
	.A16
	.I16
	STZ ENTITY_DRAW_SORTING
	LDX #.LOWORD(ENTITY_DRAW_SORTING)
	LDY #.LOWORD(ENTITY_DRAW_SORTING)+1
	LDA #$003B
	MVN #$7E,#$7E
	LDA #.LOWORD(ENTITY_DRAW_SORTING)
	RTS
