
ENEMY_TELEPORT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL02
	JSL TEST_PARTY_LEADER_DISTANCE_FAR
	CMP #0
	BNE @UNKNOWN0
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_PATHFINDING_STATES,X
	BEQ @UNKNOWN0
	LDA GAME_STATE+game_state::leader_x_coord
	STA ENTITY_ABS_X_TABLE,X
	LDA GAME_STATE+game_state::leader_y_coord
	STA ENTITY_ABS_Y_TABLE,X
	LDA #.LOWORD(-1)
	BRA @UNKNOWN2
@UNKNOWN0:
	JSL TEST_ENTITY_MOVEMENT_ACTIVE
	LDA #4
	STA @LOCAL00
	LDY @VIRTUAL02
	LDX ENTITY_MOVEMENT_PROSPECTIVE_Y
	LDA ENTITY_MOVEMENT_PROSPECTIVE_X
	JSL GET_MOVEMENT_COLLISION_FLAGS
	AND #$00C0
	BEQ @UNKNOWN1
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(ENTITY_MOVEMENT_SPEEDS)
	TAX
	LDA __BSS_START__,X
	SEC
	SBC #$1000
	STA __BSS_START__,X
	LDA #0
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_MOVEMENT_PROSPECTIVE_X
	STA ENTITY_ABS_X_TABLE,X
	LDA ENTITY_MOVEMENT_PROSPECTIVE_Y
	STA ENTITY_ABS_Y_TABLE,X
	LDA #.LOWORD(-1)
@UNKNOWN2:
	END_C_FUNCTION
