
TEST_PARTY_LEADER_DISTANCE_CLOSE_INTANGIBILITY:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_PATHFINDING_STATES,X
	BEQ @UNKNOWN0
	LDA #$0000
	BRA @UNKNOWN2
@UNKNOWN0:
	LDA PLAYER_INTANGIBILITY_FRAMES
	BNE @UNKNOWN1
	JSL TEST_PARTY_LEADER_DISTANCE_CLOSE
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA #$FFFF
@UNKNOWN2:
	RTL
