
ACTIONSCRIPT_UPDATE_SPRITE_DIRECTION:
	LDX $88
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	BNE @UNKNOWN0
	JSL MOVEMENT_DATA_READ8
	STY $94
	STA ENTITY_DIRECTIONS,X
	JSL MOVEMENT_DATA_READ8
	STY $94
	STA ENTITY_ANIMATION_FRAME,X
	STA USE_SECOND_SPRITE_FRAME
	TXY
	JSL UPDATE_ENTITY_SPRITE_OFFSET
	RTL
@UNKNOWN0:
	LDX $88
	JSL MOVEMENT_DATA_READ8
	STY $94
	STA ENTITY_DIRECTIONS,X
	JSL MOVEMENT_DATA_READ8
	STY $94
	ASL
	STA ENTITY_ANIMATION_FRAME,X
	STX SPRITE_UPDATE_ENTITY_OFFSET
	JSR UPDATE_ENTITY_SPRITE_FRAME_CURRENT
	RTL
