
UNKNOWN_C42439:
	SEP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	STA f:CGADSUB
	LDA ACTIONSCRIPT_COLDATA_BLUE
	ORA #$0080
	STA f:FIXED_COLOR_DATA
	LDA ACTIONSCRIPT_COLDATA_GREEN
	ORA #$0040
	STA f:FIXED_COLOR_DATA
	LDA ACTIONSCRIPT_COLDATA_RED
	ORA #$0020
	STA f:FIXED_COLOR_DATA
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	RTL
