
UNKNOWN_C426C7: ;$C426C7
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	LDX #$0000
@UNKNOWN0:
	LDA ENTITY_SCRIPT_TABLE,X
	BMI @UNKNOWN1
	LDA ENTITY_ABS_X_TABLE,X
	SEC
	SBC BG1_X_POS
	STA ENTITY_SCREEN_X_TABLE,X
	LDA ENTITY_ABS_Y_TABLE,X
	SEC
	SBC BG1_Y_POS
	STA ENTITY_SCREEN_Y_TABLE,X
@UNKNOWN1:
	INX
	INX
	CPX #$003C
	BNE @UNKNOWN0
	RTL
