
UNKNOWN_C426C7: ;$C426C7
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	LDX #$0000
@UNKNOWN0:
	LDA .LOWORD(LOADED_SPRITE_MOVEMENT_CODES_TABLE),X
	BMI @UNKNOWN1
	LDA .LOWORD(SPRITE_ABS_X_TABLE),X
	SEC
	SBC a:.LOWORD(BG1_X_POS)
	STA .LOWORD(SPRITE_SCREEN_X_TABLE),X
	LDA .LOWORD(SPRITE_ABS_Y_TABLE),X
	SEC
	SBC a:.LOWORD(BG1_Y_POS)
	STA .LOWORD(SPRITE_SCREEN_Y_TABLE),X
@UNKNOWN1:
	INX
	INX
	CPX #$003C
	BNE @UNKNOWN0
	RTL
