
;A: DMA channel
UNKNOWN_C429E8:
	TAY
	ASL
	ASL
	ASL
	ASL
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #^__BSS_START__
	STA f:A1B0,X
	STA f:DASB0,X
	LDA #$002C
	STA f:BBAD0,X
	LDA #DMA_TRANSFER_UNIT::WORD
	STA f:DMAP0,X
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(LETTERBOX_HDMA_TABLE)
	STA f:A1T0L,X
	SEP #PROC_FLAGS::ACCUM8
	TYX
	LDA HDMAEN_MIRROR
	ORA DMA_FLAGS,X
	STA HDMAEN_MIRROR
	REP #PROC_FLAGS::ACCUM8
	RTL
