
UNKNOWN_C4343E:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	DEC
	STA @VIRTUAL02
	LOADINT32 3600, @VIRTUAL0A
	LOADPTRPTR TIMER, @VIRTUAL06
	JSL DIVISION32
	LOADINT32 60000, @VIRTUAL0A
	CLC
	LDA @VIRTUAL0A
	SBC @VIRTUAL06
	LDA @VIRTUAL0A+2
	SBC @VIRTUAL06+2
	BRANCHLTEQS @UNKNOWN2
	LDA @VIRTUAL06
	STA @LOCAL02
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA #59999
	STA @LOCAL02
@UNKNOWN3:
	LDA @VIRTUAL02
	ASL
	ASL
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA @LOCAL02
	STA a:game_state::saved_photo_states,X
.ELSE
	TAX
	LDA @LOCAL02
	STA GAME_STATE + game_state::saved_photo_states,X
.ENDIF
	LDY #0
	STY @LOCAL01
	JMP @UNKNOWN10
@UNKNOWN4:
	REP #PROC_FLAGS::ACCUM8
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	STA @LOCAL02
	CLC
	ADC #game_state::unknown96
	TAX
	STX @LOCAL00
	LDA __BSS_START__,X
	AND #$00FF
	BNE @UNKNOWN5
	STY @VIRTUAL04
	LDA @VIRTUAL02
	ASL
	ASL
	ASL
	CLC
.IF .DEFINED(JPN)
	ADC #.LOWORD(GAME_STATE)
	CLC
	ADC @VIRTUAL04
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:game_state::saved_photo_states + photo_state::party,X
	JMP @UNKNOWN9
.ELSE
	ADC @VIRTUAL04
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE + game_state::saved_photo_states + photo_state::party,X
	BRA @UNKNOWN9
.ENDIF
@UNKNOWN5:
	.A16
	LDA @LOCAL02
	TAX
	LDA __BSS_START__+game_state::player_controlled_party_members,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	STA @LOCAL02
	STA CURRENT_PARTY_MEMBER_TICK
	LDX @LOCAL00
	LDA __BSS_START__,X
	AND #$00FF
	TAX
	STX @LOCAL00
	LDA @LOCAL02
	TAX
	LDA a:char_struct::afflictions,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BNE @UNKNOWN6
	LDX @LOCAL00
	TXA
	ORA #$0020
	TAX
	STX @LOCAL00
	BRA @UNKNOWN7
@UNKNOWN6:
	CMP #STATUS_0::DIAMONDIZED
	BNE @UNKNOWN7
	LDX @LOCAL00
	TXA
	ORA #$0040
	TAX
	STX @LOCAL00
@UNKNOWN7:
	LDX CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::afflictions+STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::MUSHROOMIZED
	BNE @UNKNOWN8
	LDX @LOCAL00
	TXA
	ORA #$0080
	TAX
	STX @LOCAL00
@UNKNOWN8:
	LDY @LOCAL01
	STY @VIRTUAL04
	LDA @VIRTUAL02
	ASL
	ASL
	ASL
	CLC
.IF .DEFINED(JPN)
	ADC #.LOWORD(GAME_STATE)
	CLC
	ADC @VIRTUAL04
	PHA
	LDX @LOCAL00
	TXA
	SEP #PROC_FLAGS::ACCUM8
	PLX
	STA a:game_state::saved_photo_states + photo_state::party,X
.ELSE
	ADC @VIRTUAL04
	PHA
	LDX @LOCAL00
	TXA
	SEP #PROC_FLAGS::ACCUM8
	PLX
	STA GAME_STATE + game_state::saved_photo_states + photo_state::party,X
.ENDIF
@UNKNOWN9:
	INY
	STY @LOCAL01
@UNKNOWN10:
	CPY #6
	BCCL @UNKNOWN4
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
