
UNKNOWN_C435E4:
.IF .DEFINED(JPN)
	BEGIN_C_FUNCTION
.ELSE
	BEGIN_C_FUNCTION_FAR
.ENDIF
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_FLASHING_ROW
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN6
	LDA CURRENT_FLASHING_ROW
	BEQ @UNKNOWN0
	LDX NUM_BATTLERS_IN_BACK_ROW
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX NUM_BATTLERS_IN_FRONT_ROW
@UNKNOWN1:
	STX @VIRTUAL02
	LDX #0
	STX @LOCAL00
	BRA @UNKNOWN5
@UNKNOWN2:
	LDA CURRENT_FLASHING_ROW
	BEQ @UNKNOWN3
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE + battler::unknown74,X
	BRA @UNKNOWN4
@UNKNOWN3:
	.A16
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE + battler::unknown74,X
@UNKNOWN4:
	LDX @LOCAL00
	INX
	STX @LOCAL00
@UNKNOWN5:
	REP #PROC_FLAGS::ACCUM8
	TXA
	CMP @VIRTUAL02
	BCC @UNKNOWN2
	STZ ENEMY_TARGETTING_FLASHING
	LDA #.LOWORD(-1)
	STA CURRENT_FLASHING_ROW
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
@UNKNOWN6:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
