
UNKNOWN_C43657:
.IF .DEFINED(JPN)
	BEGIN_C_FUNCTION
.ELSE
	BEGIN_C_FUNCTION_FAR
.ENDIF
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL00
	LDA CURRENT_FLASHING_ROW
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN0
.IF .DEFINED(JPN)
	JSR UNKNOWN_C435E4
.ELSE
	JSL UNKNOWN_C435E4
.ENDIF
@UNKNOWN0:
	LDX @LOCAL00
	STX CURRENT_FLASHING_ROW
	LDA CURRENT_FLASHING_ROW
	BEQ @UNKNOWN1
	LDA NUM_BATTLERS_IN_BACK_ROW
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA NUM_BATTLERS_IN_FRONT_ROW
@UNKNOWN2:
	STA @VIRTUAL02
	LDX #0
	STX @LOCAL00
	BRA @UNKNOWN6
@UNKNOWN3:
	LDA CURRENT_FLASHING_ROW
	BEQ @UNKNOWN4
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA BATTLERS_TABLE + battler::unknown74,X
	BRA @UNKNOWN5
@UNKNOWN4:
	.A16
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA BATTLERS_TABLE + battler::unknown74,X
@UNKNOWN5:
	LDX @LOCAL00
	INX
	STX @LOCAL00
@UNKNOWN6:
	REP #PROC_FLAGS::ACCUM8
	TXA
	CMP @VIRTUAL02
	BCC @UNKNOWN3
	LDA #1
	STA ENEMY_TARGETTING_FLASHING
	SEP #PROC_FLAGS::ACCUM8
	STA REDRAW_ALL_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
