
UNKNOWN_C43739:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	STA @LOCAL02
	LDA @VIRTUAL02
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	STA @VIRTUAL04
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDY WINDOW_STATS+window_stats::width,X
	LDA WINDOW_STATS+window_stats::text_y,X
	JSL MULT16
	ASL
	ASL
	CLC
	ADC WINDOW_STATS+window_stats::tilemap_address,X
	TAY
	STY @LOCAL01
	LDX #0
	STX @LOCAL00
	BRA @UNKNOWN1
@UNKNOWN0:
	LDY @LOCAL01
	LDA __BSS_START__,Y
	INY
	INY
	STY @LOCAL01
	JSL FREE_TILE
	LDX @LOCAL00
	INX
	STX @LOCAL00
@UNKNOWN1:
	LDA @VIRTUAL04
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS+window_stats::width,X
	ASL
	STA @VIRTUAL02
	LDX @LOCAL00
	TXA
	CMP @VIRTUAL02
	BNE @UNKNOWN0
	LDA @LOCAL02
	STA @VIRTUAL02
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS+window_stats::text_y,X
	TAX
	LDA @VIRTUAL02
	JSL UNKNOWN_C436D7
	END_C_FUNCTION
