
UNKNOWN_C43CD2:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;NEAR menu_option* menuEntry
	STACK_RESERVE_PARAM_INT16 ;int x
	STACK_RESERVE_PARAM_INT16 ;int y
	END_STACK_VARS
	STY @VIRTUAL02
	TXY
	STA @VIRTUAL04
	LDX @VIRTUAL02
	TYA
	JSL REDIRECT_C438A5
	LDX @VIRTUAL04
	LDA a:menu_option::pixel_align,X
	AND #$00FF
	BEQ @UNKNOWN0
	AND #$00FF
	CLC
	ADC VWF_X
	STA VWF_X
	LDA VWF_TILE
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(VWF_BUFFER)
	STA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA @LOCAL00
	LDX #32
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	JSL MEMSET16
@UNKNOWN0:
.IF !.DEFINED(PROTOTYPE19950327)
	SEP #PROC_FLAGS::ACCUM8
	STZ RESTORE_MENU_BACKUP
	REP #PROC_FLAGS::ACCUM8
.ENDIF
	END_C_FUNCTION
