
UNKNOWN_C43D95: ;$C43D95
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STA $10
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA WINDOW_EXISTENCE_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS_TABLE+window_stats::text_x,X
	ASL
	ASL
	ASL
	STA $02
	LDA $10
	CLC
	ADC $02
	STA $10
	LDA UNKNOWN_7E5E73
	AND #$00FF
	STA $02
	LDA $10
	CLC
	ADC $02
	STA $0E
	LDA WINDOW_STATS_TABLE+window_stats::text_y,X
	TAX
	LDA $0E
	JSL UNKNOWN_C43D75
	PLD
	RTL
