
UNKNOWN_C43DDB:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;NEAR menu_option* menuEntry
	END_STACK_VARS
	STA @VIRTUAL02
	CLC
	ADC #menu_option::text_x
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CLC
	ADC #menu_option::text_y
	TAY
	STY @LOCAL01
	LDA __BSS_START__,Y
	TAX
	STX @LOCAL00
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	LDX @LOCAL00
	JSL REDIRECT_C438A5
	LDA #47
	JSL UNKNOWN_C43F77
	JSL UNKNOWN_C43CAA
	LDX @VIRTUAL02
	LDA a:menu_option::pixel_align,X
	AND #$00FF
	BEQ @UNKNOWN0
	LDY @LOCAL01
	LDA __BSS_START__,Y
	TAY
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	TAX
	INX
	LDA @VIRTUAL02
	JSL UNKNOWN_C43CD2
@UNKNOWN0:
	END_C_FUNCTION
