
UNKNOWN_C43EF8:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	STA @LOCAL03
	MOVE_INT @PARAM01, @VIRTUAL06
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
	STX @LOCAL02
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL03
	JSL UNKNOWN_C43E31
	STA @VIRTUAL02
	LDX @LOCAL02
	LDA a:window_stats::width,X
	ASL
	ASL
	ASL
	SEC
	SBC @VIRTUAL02
	LSR
	STA @LOCAL01
	LDA a:window_stats::text_y,X
	TAX
	LDA @LOCAL01
	JSL UNKNOWN_C43D75
	SEP #PROC_FLAGS::ACCUM8
	STZ FORCE_CENTRE_TEXT_ALIGNMENT
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
