
UNKNOWN_C43E31:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL03
	MOVE_INT @PARAM01, @VIRTUAL06
	LDX #0
	STX @LOCAL02
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @VIRTUAL02
	STA @LOCAL01
.IF .DEFINED(PROTOTYPE19950327)
	BRA @UNKNOWN3
.ELSE
	JMP @UNKNOWN3
.ENDIF
@UNKNOWN0:
	DEY
	STY @LOCAL03
	AND #$00FF
	SEC
	SBC #$50
	AND #$007F
	STA @LOCAL00
	INC @VIRTUAL06
.IF !.DEFINED(PROTOTYPE19950327)
	LDA FORCE_NORMAL_FONT_FOR_LENGTH_CALCULATIONS
	AND #$00FF
	BEQ @UNKNOWN1
	MOVE_INT FONT_PTR_TABLE, @VIRTUAL0A
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BRA @UNKNOWN2
.ENDIF
@UNKNOWN1:
	LOADPTR FONT_PTR_TABLE, @VIRTUAL0A
	LDA @LOCAL01
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA a:window_stats::font,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(font_table_entry)
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL0A
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
@UNKNOWN2:
	STA @VIRTUAL02
	LDA CHARACTER_PADDING
	AND #$00FF
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
	LDX @LOCAL02
	TXA
	CLC
	ADC @VIRTUAL04
	TAX
	STX @LOCAL02
@UNKNOWN3:
	LDA [@VIRTUAL06]
	AND #$00FF
	BEQ @UNKNOWN4
	LDY @LOCAL03
.IF .DEFINED(PROTOTYPE19950327)
	BNE @UNKNOWN0
.ELSE
	BNEL @UNKNOWN0
.ENDIF
@UNKNOWN4:
	LDX @LOCAL02
	TXA
	END_C_FUNCTION
