
UNKNOWN_C442AC:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	STY @LOCAL06
	STX @LOCAL05
	JSL WAIT_UNTIL_NEXT_FRAME
	STZ VWF_TILE
	STZ VWF_X
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA @LOCAL00
	LDX #32 * 26
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(VWF_BUFFER)
	JSL MEMSET16
	STZ TEXT_RENDER_STATE + 2
	STZ TEXT_RENDER_STATE
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL04
	LDA @LOCAL06
	CMP #.LOWORD(-1)
	BNE @UNKNOWN2
	LDA NEXT_KEYBOARD_INPUT_INDEX
	BNE @UNKNOWN0
	LDA #TRUE
	JMP @RETURN
@UNKNOWN0:
	LDA NEXT_KEYBOARD_INPUT_INDEX
	CMP @LOCAL05
	BCS @UNKNOWN1
	LDA #83
	JSR UNKNOWN_C4424A
@UNKNOWN1:
	DEC NEXT_KEYBOARD_INPUT_INDEX
	LDA #112
	JSR UNKNOWN_C4424A
	BRA @UNKNOWN4
@UNKNOWN2:
	LDA @LOCAL05
	DEC
	CMP NEXT_KEYBOARD_INPUT_INDEX
	BCS @UNKNOWN3
	LDA #FALSE
	JMP @RETURN
@UNKNOWN3:
	LDA @LOCAL06
	JSR UNKNOWN_C4424A
	LDA NEXT_KEYBOARD_INPUT_INDEX
	INC
	STA NEXT_KEYBOARD_INPUT_INDEX
	CMP @LOCAL05
	BCS @UNKNOWN4
	LDA #112
	JSR UNKNOWN_C4424A
@UNKNOWN4:
	LOADPTR FONT_PTR_TABLE, @VIRTUAL06
	LDY #font_table_entry::width
	LDA [@VIRTUAL06],Y
	STA @VIRTUAL04
	LDX @LOCAL04
	STZ a:window_stats::text_x,X
	LDY #font_table_entry::height
	LDA [@VIRTUAL06],Y
	STA @LOCAL03
	LDA #0
	STA @VIRTUAL02
	BRA @UNKNOWN8
@UNKNOWN5:
	MOVE_INT FONT_PTR_TABLE + font_table_entry::graphics, @VIRTUAL06
	LDX @VIRTUAL02
	LDA KEYBOARD_INPUT_CHARACTER_OFFSETS,X
	AND #$00FF
	TAY
	LDA @LOCAL03
	JSL MULT16
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDX @VIRTUAL02
	LDA KEYBOARD_INPUT_CHARACTER_WIDTHS,X
	AND #$00FF
	TAY
	STY @LOCAL02
	BRA @UNKNOWN7
@UNKNOWN6:
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @VIRTUAL04
	LDA #8
	JSL UNKNOWN_C44B3A
	LDY @LOCAL02
	TYA
	SEC
	SBC #8
	TAY
	STY @LOCAL02
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
@UNKNOWN7:
	CPY #8
	BCS @UNKNOWN6
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @VIRTUAL04
	TYA
	JSL UNKNOWN_C44B3A
	INC @VIRTUAL02
@UNKNOWN8:
	LDA @VIRTUAL02
	CMP @LOCAL05
	BCC @UNKNOWN5
	LDX @LOCAL04
	STZ a:window_stats::text_x,X
	LDA #VRAM::TEXT_LAYER_TILES + $1700
	STA @VIRTUAL04
	LDY #window_stats::width
	LDA (@LOCAL04),Y
	STA @LOCAL01
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL02
	BRA @UNKNOWN10
@UNKNOWN9:
	LDA @LOCAL02
	STA @VIRTUAL02
	ASL
	ASL
	ASL
	ASL
	ASL
	STA @LOCAL04
	CLC
	ADC #.LOWORD(VWF_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY @VIRTUAL04
	LDX #16
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDA @LOCAL04
	CLC
	ADC #.LOWORD(VWF_BUFFER) + 16
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	COPY_TO_VRAM1OFFSET @VIRTUAL06, @VIRTUAL04, 16, 8, 0
	.A16
	LDA @VIRTUAL04
	CLC
	ADC #16
	STA @VIRTUAL04
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL02
@UNKNOWN10:
	LDA @VIRTUAL02
	PHA
	LDA @LOCAL01
	STA @VIRTUAL02
	INC @VIRTUAL02
	PLA
	CMP @VIRTUAL02
	BCCL @UNKNOWN9
	LDA #1
	STA DMA_TRANSFER_FLAG
	LDY #0
	STY @LOCAL05
	BRA @UNKNOWN13
@UNKNOWN12:
	TYA
	ASL
	CLC
	ADC #$02E0
	TAX
	INX
	JSR UNKNOWN_C44C8C
	LDY @LOCAL05
	INY
	STY @LOCAL05
@UNKNOWN13:
	LDA @LOCAL01
	STA @VIRTUAL02
	INC @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BCC @UNKNOWN12
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP WINDOW_TAIL
	BEQ @UNKNOWN14
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
@UNKNOWN14:
	REP #PROC_FLAGS::ACCUM8
	LDA TEXT_SOUND_MODE
	CMP #2
	BNE @UNKNOWN15
	LDX #1
	BRA @UNKNOWN17
@UNKNOWN15:
	LDA TEXT_SOUND_MODE
	CMP #3
	BNE @UNKNOWN16
	LDX #0
	BRA @UNKNOWN17
@UNKNOWN16:
	LDX #0
	LDA BLINKING_TRIANGLE_FLAG
	BNE @UNKNOWN17
	LDX #1
@UNKNOWN17:
	CPX #0
	BEQ @UNKNOWN18
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @UNKNOWN18
	LDA @LOCAL06
	CMP #32
	BEQ @UNKNOWN18
	LDA #SFX::TEXT_PRINT
	JSL PLAY_SOUND
@UNKNOWN18:
	LDX SELECTED_TEXT_SPEED
	INX
	STX @LOCAL06
	BRA @UNKNOWN20
@UNKNOWN19:
	JSL WINDOW_TICK
	LDX @LOCAL06
	DEX
	STX @LOCAL06
@UNKNOWN20:
	BNE @UNKNOWN19
	LDA #FALSE
@RETURN:
	END_C_FUNCTION
