
UNKNOWN_C445E1:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	TAY
	MOVE_INT @PARAM01, @VIRTUAL0A
	LDX #0
	STX @LOCAL04
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQL @UNKNOWN14
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAY
	STY @LOCAL02
@UNKNOWN1:
	LDA [@VIRTUAL0A]
	AND #$00FF
	BEQ @UNKNOWN2
	AND #$00FF
	INC @VIRTUAL0A
	BRA @UNKNOWN3
@UNKNOWN2:
	MOVE_INT @LOCAL03, @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	INC @VIRTUAL06
	MOVE_INTX @VIRTUAL06, @LOCAL03
@UNKNOWN3:
	CMP #$15
	BEQ @DICT1
	CMP #$16
	BEQ @DICT2
	CMP #$17
	BEQL @DICT3
	JMP @UNKNOWN8
@DICT1:
	MOVE_INT @LOCAL03, @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	ASL
	ASL
	PHA
	LOADPTR COMPRESSED_TEXT_PTRS, @VIRTUAL06
	PLA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @LOCAL03, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA [@VIRTUAL0A]
	AND #$00FF
	INC @VIRTUAL0A
	JMP @UNKNOWN8
@DICT2:
	MOVE_INT @LOCAL03, @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	ASL
	ASL
	PHA
	LOADPTR COMPRESSED_TEXT_PTRS+1024, @VIRTUAL06
	PLA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @LOCAL03, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA [@VIRTUAL0A]
	AND #$00FF
	INC @VIRTUAL0A
	BRA @UNKNOWN8
@DICT3:
	MOVE_INT @LOCAL03, @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	ASL
	ASL
	PHA
	LOADPTR COMPRESSED_TEXT_PTRS+2048, @VIRTUAL06
	PLA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @LOCAL03, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA [@VIRTUAL0A]
	AND #$00FF
	INC @VIRTUAL0A
@UNKNOWN8:
	CMP #$50
	BEQ @UNKNOWN11
	CMP #$20
	BCC @UNKNOWN11
	INC UPCOMING_WORD_LENGTH
	CMP #$2F
	BNE @UNKNOWN9
	LDA #8
	BRA @UNKNOWN10
@UNKNOWN9:
	SEC
	SBC #$50
	AND #$007F
	STA @VIRTUAL02
	LDY @LOCAL02
	LDA a:window_stats::font,Y
	STA @LOCAL01
	LOADPTR FONT_PTR_TABLE, @VIRTUAL06
	LDA @LOCAL01
	OPTIMIZED_MULT @VIRTUAL04, 12
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @LOCAL01
	LDA CHARACTER_PADDING
	AND #$00FF
	STA @VIRTUAL02
	LDA @LOCAL01
	CLC
	ADC @VIRTUAL02
@UNKNOWN10:
	STA @VIRTUAL02
	LDX @LOCAL04
	TXA
	CLC
	ADC @VIRTUAL02
	TAX
	STX @LOCAL04
	JMP @UNKNOWN1
@UNKNOWN11:
	LDY @LOCAL02
	LDA a:window_stats::text_x,Y
	STA @LOCAL00
	BEQ @UNKNOWN12
	LDA VWF_X
	AND #$0007
	STA @VIRTUAL04
	LDA @LOCAL00
	DEC
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL04
	STA @VIRTUAL02
	LDX @LOCAL04
	TXA
	CLC
	ADC @VIRTUAL02
	BRA @UNKNOWN13
@UNKNOWN12:
	LDA VWF_X
	AND #$0007
	STA @VIRTUAL02
	LDX @LOCAL04
	TXA
	CLC
	ADC @VIRTUAL02
@UNKNOWN13:
	STA @VIRTUAL02
	LDA a:window_stats::width,Y
	ASL
	ASL
	ASL
	CMP @VIRTUAL02
	BCS @UNKNOWN14
	JSL REDIRECT_PRINT_NEWLINE
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA VWF_INDENT_NEW_LINE
@UNKNOWN14:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
