
UNKNOWN_C4487C:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM01, @VIRTUAL0A
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR WORD_SPLITTING_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL03
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL0A]
	STA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	STX @LOCAL01
	LDA @VIRTUAL00
	AND #$00FF
	MOVE_INTY @LOCAL03, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL0A
	CPX #CHAR::SPACE
	BEQ @UNKNOWN1
	CPX #0
	BNE @UNKNOWN3
@UNKNOWN1:
	CPX #CHAR::SPACE
	BNE @UNKNOWN2
	LDA @VIRTUAL00
	AND #$00FF
	MOVE_INTX @LOCAL03, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #CHAR::SPACE
	STA [@VIRTUAL06]
	INC @VIRTUAL00
@UNKNOWN2:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	MOVE_INTX @LOCAL03, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @LOCAL03, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #.LOWORD(-1)
	JSL UNKNOWN_C447FB
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR WORD_SPLITTING_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL03
	BRA @UNKNOWN4
@UNKNOWN3:
	SEP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL00
@UNKNOWN4:
	LDX @LOCAL01
	BNEL @UNKNOWN0
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
