
UNKNOWN_C4507A:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_ARRAY 6, 1
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL06
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQL @UNKNOWN5
	SEP #PROC_FLAGS::ACCUM8
	LDA VWF_INDENT_NEW_LINE
	STA @VIRTUAL00
	STZ VWF_INDENT_NEW_LINE
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAY
	STY @LOCAL09
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL UNKNOWN_C10C55
	STA @VIRTUAL02
	STA @LOCAL08
	LDA #7
	SEC
	SBC @VIRTUAL02
	CLC
	ADC #.LOWORD(NUMBER_TEXT_BUFFER)
	STA @LOCAL07
	STA @LOCAL06
	LDY @LOCAL09
	LDA a:window_stats::text_x,Y
	STA @LOCAL05
	LDA a:window_stats::text_y,Y
	STA @LOCAL04
	LDX #4
	LDA CHARACTER_PADDING
	AND #$00FF
	STA @VIRTUAL02
	LOADPTR FONT_PTR_TABLE, @VIRTUAL06
	LDA a:window_stats::font,Y
	OPTIMIZED_MULT @VIRTUAL04, 12
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	TXA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
	LDX #0
	STX @LOCAL03
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA @LOCAL07
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC #CHAR::ZERO
	LDX @LOCAL03
	STA @LOCAL01,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	INC
	STA @LOCAL07
	INX
	STX @LOCAL03
@UNKNOWN2:
	LDA @LOCAL08
	STA @VIRTUAL02
	TXA
	CMP @VIRTUAL02
	BCC @UNKNOWN1
	TDC
	CLC
	ADC #@LOCAL01
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY @LOCAL09
	LDA a:window_stats::font,Y
	TAX
	LDA @VIRTUAL02
	JSL UNKNOWN_C44FF3
	PHA
	LDA @VIRTUAL04
	PLY
	STY @VIRTUAL04
	CLC
	ADC @VIRTUAL04
	STA @LOCAL02
	LDA CHARACTER_PADDING
	AND #$00FF
	STA @VIRTUAL04
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL04
	STA @LOCAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA FORCE_LEFT_TEXT_ALIGNMENT
	LDY @LOCAL09
	REP #PROC_FLAGS::ACCUM8
	LDA a:window_stats::text_y,Y
	TAX
	LDA @LOCAL02
	STA @VIRTUAL04
	LDA a:window_stats::width,Y
	DEC
	ASL
	ASL
	ASL
	SEC
	SBC @VIRTUAL04
	JSL UNKNOWN_C43D75
	LDA #CHAR::DOLLAR
	JSL REDIRECT_PRINT_LETTER
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA (@LOCAL06)
	AND #$00FF
	CLC
	ADC #CHAR::ZERO
	INC @LOCAL06
	JSL REDIRECT_PRINT_LETTER
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
@UNKNOWN4:
	LDA @VIRTUAL02
	BNE @UNKNOWN3
	SEP #PROC_FLAGS::ACCUM8
	STZ FORCE_LEFT_TEXT_ALIGNMENT
	LDY @LOCAL09
	REP #PROC_FLAGS::ACCUM8
	LDA a:window_stats::text_y,Y
	TAX
	LDA a:window_stats::width,Y
	DEC
	JSL REDIRECT_C438A5
	LDA #36
	JSL UNKNOWN_C43F77
	LDX @LOCAL04
	LDA @LOCAL05
	JSL REDIRECT_C438A5
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	STA VWF_INDENT_NEW_LINE
@UNKNOWN5:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
