
UNKNOWN_C451FA:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL0D
	STX @LOCAL0C
	STA @LOCAL0B
	LDA #0
	STA @VIRTUAL04
	STA @VIRTUAL02
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL0A
	CLC
	ADC #window_stats::current_option
	TAX
	LDA __BSS_START__,X
	CMP #.LOWORD(-1)
	BEQL @UNKNOWN24
	LDA @LOCAL0B
	LDY #window_stats::unknown49
	STA (@LOCAL0A),Y
	LDA __BSS_START__,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAY
	STY @LOCAL09
	SEP #PROC_FLAGS::ACCUM8
	STZ @LOCAL00
	LDX #4
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(MENU_OPTION_LABEL_LENGTHS)
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA @LOCAL00
	LDX #4
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(UNKNOWN_7E9691)
	JSL MEMSET16
	LDA @LOCAL0D
	BEQL @UNKNOWN5
@UNKNOWN1:
	LDY @LOCAL09
	TYA
	CLC
	ADC #menu_option::label
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #30
	JSL UNKNOWN_C43E31
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC #8
	LDX @VIRTUAL04
	STA MENU_OPTION_LABEL_LENGTHS,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	PHA
	LDA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL02
	LDY @LOCAL09
	LDA menu_option::next,Y
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN2
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAY
	STY @LOCAL09
	INC @VIRTUAL04
	BRA @UNKNOWN1
@UNKNOWN2:
	LDY #window_stats::width
	LDA (@LOCAL0A),Y
	LDY #$0800
	JSL MULT16
	LDY @VIRTUAL02
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @LOCAL08
	BRA @UNKNOWN4
@UNKNOWN3:
	LDX @VIRTUAL04
	LDA MENU_OPTION_LABEL_LENGTHS,X
	AND #$00FF
	TAY
	LDA @LOCAL08
	JSL MULT16
	XBA
	AND #$00FF
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL04
	STA UNKNOWN_7E9691,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	DEC
	STA @VIRTUAL04
@UNKNOWN4:
	LDA @VIRTUAL04
	CMP #.LOWORD(-1)
	BNE @UNKNOWN3
	LDY #window_stats::current_option
	LDA (@LOCAL0A),Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAY
	STY @LOCAL09
	LDA #0
	STA @VIRTUAL04
	BRA @UNKNOWN6
@UNKNOWN5:
	LDY @LOCAL0C
	LDA @LOCAL0B
	DEC
	JSL MULT16
	LDY #window_stats::width
	CLC
	ADC (@LOCAL0A),Y
	LDY @LOCAL0B
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @LOCAL07
@UNKNOWN6:
	LDY #window_stats::height
	LDA (@LOCAL0A),Y
	LSR
	TAX
	STX @LOCAL06
	LDY #window_stats::current_option
	LDA (@LOCAL0A),Y
	JSL REDIRECT_C1138D
	LDX @LOCAL06
	STX @VIRTUAL02
	LDY @LOCAL0B
	CLC
	ADC @LOCAL0B
	DEC
	JSL DIVISION16S_DIVISOR_POSITIVE
	CMP @VIRTUAL02
	BLTEQ @UNKNOWN7
	DEX
	DEX
@UNKNOWN7:
	STX @LOCAL06
	LDA #0
	STA @LOCAL08
	LDA #1
	STA @LOCAL05
@UNKNOWN8:
	LDY #window_stats::text_y
	LDA (@LOCAL0A),Y
	STA @VIRTUAL02
	STA @LOCAL04
	LDA @LOCAL06
	STA @LOCAL0C
	JMP @UNKNOWN19
@UNKNOWN9:
	LDX @LOCAL0B
	STX @LOCAL03
	JMP @UNKNOWN17
@UNKNOWN10:
	LDA @LOCAL0D
	BEQL @UNKNOWN15
	LDA @VIRTUAL04
	CLC
	ADC #.LOWORD(UNKNOWN_7E9691)
	STA @LOCAL02
	LDX @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDA (@LOCAL02)
	SEC
	SBC MENU_OPTION_LABEL_LENGTHS,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	PHA
	ASL
	PLA
	ROR
	ASL
	PHP
	LSR
	LSR
	LSR
	LSR
	PLP
	BCC @UNKNOWN12
	ORA #$F000
@UNKNOWN12:
	STA @VIRTUAL02
	LDA @LOCAL08
	CLC
	ADC @VIRTUAL02
	LDY @LOCAL09
	STA a:menu_option::text_x,Y
	LDA @LOCAL04
	STA @VIRTUAL02
	STA a:menu_option::text_y,Y
	LDA @LOCAL05
	STA a:menu_option::page,Y
	LDA a:menu_option::next,Y
	TAY
	CPY #.LOWORD(-1)
	BEQL @UNKNOWN21
	LDA (@LOCAL02)
	AND #$00FF
	CLC
	ADC #7
	ASL
	PHP
	LSR
	LSR
	LSR
	LSR
	PLP
	BCC @UNKNOWN14
	ORA #$F000
@UNKNOWN14:
	STA @VIRTUAL02
	LDA @LOCAL08
	CLC
	ADC @VIRTUAL02
	STA @LOCAL08
	INC @VIRTUAL04
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAY
	STY @LOCAL09
	BRA @UNKNOWN16
@UNKNOWN15:
	LDA @LOCAL08
	LDY @LOCAL09
	STA __BSS_START__+8,Y
	LDA @LOCAL04
	STA @VIRTUAL02
	STA __BSS_START__+10,Y
	LDA @LOCAL05
	STA __BSS_START__+6,Y
	LDA __BSS_START__+2,Y
	TAY
	CPY #.LOWORD(-1)
	BEQ @UNKNOWN21
	LDA @LOCAL08
	CLC
	ADC @LOCAL07
	STA @LOCAL08
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAY
	STY @LOCAL09
@UNKNOWN16:
	LDX @LOCAL03
	DEX
	STX @LOCAL03
@UNKNOWN17:
	BNEL @UNKNOWN10
	LDA #0
	STA @LOCAL08
	LDA @LOCAL04
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL04
	DEC @LOCAL0C
@UNKNOWN19:
	LDA @LOCAL0C
	BNEL @UNKNOWN9
	INC @LOCAL05
	JMP @UNKNOWN8
@UNKNOWN21:
	LDA @LOCAL0A
	CLC
	ADC #window_stats::current_option
	TAX
	STX @LOCAL07
	LDA __BSS_START__,X
	JSL REDIRECT_C1138D
	STA @LOCAL0D
	LDY #window_stats::height
	LDA (@LOCAL0A),Y
	LSR
	STA @VIRTUAL02
	LDY @LOCAL0B
	LDA @LOCAL0D
	CLC
	ADC @LOCAL0B
	DEC
	JSL DIVISION16S_DIVISOR_POSITIVE
	CMP @VIRTUAL02
	BLTEQ @UNKNOWN24
	LDX @LOCAL07
	LDA __BSS_START__,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAX
	LDY @LOCAL0B
	DEY
	STY @LOCAL07
	BRA @UNKNOWN23
@UNKNOWN22:
	DEY
	STY @LOCAL07
	LDA a:menu_option::next,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAX
@UNKNOWN23:
	LDY @LOCAL07
	BNE @UNKNOWN22
	LOADPTR UNKNOWN_C3E44C, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #window_stats::height
	LDA (@LOCAL0A),Y
	LSR
	TAY
	DEY
	LDX #0
	TXA
	JSL UNKNOWN_C10BFE
	LDY #window_stats::option_count ; also .SIZEOF(menu_option) for the following multiplication
	LDA (@LOCAL0A),Y
	JSL MULT168
	TAX
	STZ MENU_OPTIONS + menu_option::page,X
@UNKNOWN24:
	END_C_FUNCTION
