
UNKNOWN_C46125:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL02
	TAX
	JSL UNKNOWN_C46028
	STA @LOCAL01
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN2
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	STA ENTITY_PREPARED_X_COORDINATE
	LDA ENTITY_ABS_Y_TABLE,X
	STA ENTITY_PREPARED_Y_COORDINATE
	LDA ENTITY_DIRECTIONS,X
	STA ENTITY_PREPARED_DIRECTION
	LDY @LOCAL02
	CPY #6
	BEQ @UNKNOWN0
	LOADPTR UNKNOWN_C3A209, @LOCAL00
	BRA @UNKNOWN1
@UNKNOWN0:
	LOADPTR EVENT_35, @LOCAL00
@UNKNOWN1:
	LDY @LOCAL00+2
	LDA @LOCAL01
	TAX
	LDA @LOCAL00
	JSL INIT_ENTITY_UNKNOWN1
@UNKNOWN2:
	END_C_FUNCTION
