
UNKNOWN_C4617C:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL01
	TAX
	JSL UNKNOWN_C4605A
	TAX
	CPX #.LOWORD(-1)
	BEQ @UNKNOWN0
	LOADPTR EVENT_SCRIPT_POINTERS, @VIRTUAL06
	LDY @LOCAL01
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 3
	STA @LOCAL00
	INC
	INC
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAY
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	JSL INIT_ENTITY_UNKNOWN1
@UNKNOWN0:
	END_C_FUNCTION
