
UNKNOWN_C46397:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LDY #0
	STY @LOCAL01
	BRA @UNKNOWN4
@UNKNOWN0:
.IF .DEFINED(JPN)
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknown96,X
.ELSE
	LDA GAME_STATE + game_state::unknown96,Y
.ENDIF
	AND #$00FF
	STA @VIRTUAL04
	LDA #16
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @UNKNOWN3
	TYA
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknownA2,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::unknownA2,X
.ENDIF
	STA @LOCAL00
	ASL
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAX
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BEQ @UNKNOWN3
	LDA @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL00
	JSL UNKNOWN_C0A780
@UNKNOWN3:
	LDY @LOCAL01
	INY
	STY @LOCAL01
@UNKNOWN4:
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	STA @VIRTUAL04
	TYA
	CMP @VIRTUAL04
	BCC @UNKNOWN0
	END_C_FUNCTION
