
UNKNOWN_C46534:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 "SPRITE" ;int
	STACK_RESERVE_PARAM_INT16 "ACTIONSCRIPT" ;int
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	STA @LOCAL02
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	STA @LOCAL00
	LDA ENTITY_ABS_Y_TABLE,X
	STA @LOCAL01
	LDY #.LOWORD(-1)
	LDX @VIRTUAL02
	LDA @LOCAL02
	JSL CREATE_ENTITY
	END_C_FUNCTION
