
UNKNOWN_C46579: ;$C46579
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL UNKNOWN_C46028
	CMP #$FFFF
	BEQ @UNKNOWN0
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA RAM,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA RAM,X
@UNKNOWN0:
	RTL
