
UNKNOWN_C467C2: ;$C467C2
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 14
	JSL RAND
	AND #$001F
	STA $02
	LDA .LOWORD(UNKNOWN_7E1A42)
	ASL
	TAX
	LDA #$0100
	SEC
	SBC .LOWORD(SPRITE_SCREEN_Y_TABLE),X
	LSR
	LSR
	CLC
	ADC $02
	PLD
	RTL
