
UNKNOWN_C46903:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	LDX #FALSE
	CMP GAME_STATE+game_state::leader_y_coord
	BLTEQ @UNKNOWN0
	LDX #TRUE
@UNKNOWN0:
	TXA
	END_C_FUNCTION
