
UNKNOWN_C46B79: ;$C46B79
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA .LOWORD(CURRENT_ENTITY_SLOT)
	ASL
	TAX
	LDA .LOWORD(UNKNOWN_7E9E2D)
	STA .LOWORD(ENTITY_SCRIPT_VAR6_TABLE),X
	LDA .LOWORD(UNKNOWN_7E9E2F)
	STA .LOWORD(ENTITY_SCRIPT_VAR7_TABLE),X
	RTL
