
UNKNOWN_C46B65: ;$C46B65
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA .LOWORD(UNKNOWN_7E1A42)
	ASL
	TAX
	LDA .LOWORD(GAME_STATE)+game_state::leader_x_coord
	STA .LOWORD(UNKNOWN_30X2_TABLE_9),X
	LDA .LOWORD(GAME_STATE)+game_state::leader_y_coord
	STA .LOWORD(UNKNOWN_30X2_TABLE_10),X
	RTL
