
UNKNOWN_C46B8D: ;$C46B8D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	TAX
	LDY CURRENT_ENTITY_SLOT
	STY $10
	TXA
	JSL UNKNOWN_C4605A
	STA $0E
	LDY $10
	TYA
	ASL
	TAY
	LDA $0E
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	STA ENTITY_SCRIPT_VAR6_TABLE,Y
	LDA ENTITY_ABS_Y_TABLE,X
	STA ENTITY_SCRIPT_VAR7_TABLE,Y
	PLD
	RTL
