
UNKNOWN_C46B8D:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	LDY CURRENT_ENTITY_SLOT
	STY @LOCAL01
	TXA
	JSL UNKNOWN_C4605A
	STA @LOCAL00
	LDY @LOCAL01
	TYA
	ASL
	TAY
	LDA @LOCAL00
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	STA ENTITY_SCRIPT_VAR6_TABLE,Y
	LDA ENTITY_ABS_Y_TABLE,X
	STA ENTITY_SCRIPT_VAR7_TABLE,Y
	END_C_FUNCTION
