
UNKNOWN_C46CF5: ;$C46CF5
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 14
	STX $02
	TAY
	LDA .LOWORD(UNKNOWN_7E1A42)
	ASL
	TAX
	LDA $02
	CLC
	ADC a:.LOWORD(BG1_X_POS)
	STA .LOWORD(ENTITY_ABS_X_TABLE),X
	TYA
	CLC
	ADC a:.LOWORD(BG1_Y_POS)
	STA .LOWORD(ENTITY_ABS_Y_TABLE),X
	LDA #$8000
	STA .LOWORD(ENTITY_ABS_Y_FRACTION_TABLE),X
	STA .LOWORD(ENTITY_ABS_X_FRACTION_TABLE),X
	PLD
	RTL
