
UNKNOWN_C46C87:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR6_TABLE,X
	STA ENTITY_ABS_X_TABLE,X
	LDA ENTITY_SCRIPT_VAR7_TABLE,X
	STA ENTITY_ABS_Y_TABLE,X
	END_C_FUNCTION
