
UNKNOWN_C46C45: ;$C46C45
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	STA ENTITY_SCRIPT_VAR0_TABLE,X
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_ABS_Y_TABLE,X
	STA ENTITY_SCRIPT_VAR1_TABLE,X
	RTL
