
UNKNOWN_C46C9B: ;$C46C9B
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	LDX .LOWORD(UNKNOWN_7E1A42)
	STX $10
	JSL UNKNOWN_C4608C
	STA $0E
	LDX $10
	TXA
	ASL
	TAY
	LDA $0E
	ASL
	TAX
	LDA .LOWORD(SPRITE_ABS_X_TABLE),X
	STA .LOWORD(SPRITE_ABS_X_TABLE),Y
	LDA .LOWORD(SPRITE_ABS_Y_TABLE),X
	STA .LOWORD(SPRITE_ABS_Y_TABLE),Y
	PLD
	RTL
