
UNKNOWN_C46C5E: ;$C46C5E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STA $0E
	LDA .LOWORD(CURRENT_ENTITY_SLOT)
	ASL
	TAY
	TXA
	CLC
	ADC .LOWORD(ENTITY_ABS_X_TABLE),Y
	STA .LOWORD(ENTITY_SCRIPT_VAR0_TABLE),Y
	LDA .LOWORD(CURRENT_ENTITY_SLOT)
	ASL
	TAX
	LDA $0E
	CLC
	ADC .LOWORD(ENTITY_ABS_Y_TABLE),X
	STA .LOWORD(ENTITY_SCRIPT_VAR1_TABLE),X
	PLD
	RTL
