
UNKNOWN_C46C45:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	STA ENTITY_SCRIPT_VAR0_TABLE,X
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_ABS_Y_TABLE,X
	STA ENTITY_SCRIPT_VAR1_TABLE,X
	END_C_FUNCTION
