
UNKNOWN_C46C5E: ;$C46C5E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STA $0E
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAY
	TXA
	CLC
	ADC ENTITY_ABS_X_TABLE,Y
	STA ENTITY_SCRIPT_VAR0_TABLE,Y
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA $0E
	CLC
	ADC ENTITY_ABS_Y_TABLE,X
	STA ENTITY_SCRIPT_VAR1_TABLE,X
	PLD
	RTL
