
UNKNOWN_C46CF5: ;$C46CF5
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	TAY
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA @VIRTUAL02
	CLC
	ADC BG1_X_POS
	STA ENTITY_ABS_X_TABLE,X
	TYA
	CLC
	ADC BG1_Y_POS
	STA ENTITY_ABS_Y_TABLE,X
	LDA #$8000
	STA ENTITY_ABS_Y_FRACTION_TABLE,X
	STA ENTITY_ABS_X_FRACTION_TABLE,X
	PLD
	RTL
