
UNKNOWN_C46D4B:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY SPAWNING_TRAVELLING_PHOTOGRAPHER_ID
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LOADPTR PHOTOGRAPHER_CFG_TABLE, @VIRTUAL06
	TYA
	LDY #.SIZEOF(photographer_config_entry)
	JSL MULT168
	STA @LOCAL00
	CLC
	ADC #photographer_config_entry::photographer_x
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	ASL
	ASL
	ASL
	STA ENTITY_ABS_X_TABLE,X
	LDA @LOCAL00
	CLC
	ADC #photographer_config_entry::photographer_y
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	ASL
	ASL
	ASL
	STA ENTITY_ABS_Y_TABLE,X
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	STZ ENTITY_ABS_Y_FRACTION_TABLE,X
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	STZ ENTITY_ABS_X_FRACTION_TABLE,X
	END_C_FUNCTION
