
UNKNOWN_C46DAD: ;$C46DAD
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	BEQ @UNKNOWN0
	CMP #$0001
	BEQ @UNKNOWN1
	BRA @UNKNOWN2
@UNKNOWN0:
	LDX .LOWORD(CURRENT_ENTITY_SLOT)
	STX $0E
	BRA @UNKNOWN2
@UNKNOWN1:
	LDX .LOWORD(GAME_STATE)+game_state::current_party_members
	STX $0E
@UNKNOWN2:
	LDX $0E
	TXA
	ASL
	TAX
	LDA .LOWORD(ENTITY_ABS_X_TABLE),X
	STA .LOWORD(ENTITY_PREPARED_X_COORDINATE)
	LDA .LOWORD(ENTITY_ABS_Y_TABLE),X
	STA .LOWORD(ENTITY_PREPARED_Y_COORDINATE)
	LDA .LOWORD(ENTITY_DIRECTIONS),X
	STA .LOWORD(ENTITY_PREPARED_DIRECTION)
	PLD
	RTL
