
UNKNOWN_C47044:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL02
	ASL
	TAY
	STY @LOCAL03
	LDA ENTITY_MOVEMENT_SPEEDS,Y
	TAX
	LDA @VIRTUAL04
	JSL UNKNOWN_C41FFF
	MOVE_INT @VIRTUAL06, @LOCAL00
	STA @LOCAL02
	AND #$8000
	BEQ @UNKNOWN0
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA @LOCAL02
	JSL ASR8_UNKNOWN1
	ORA #$FF00
	REP #PROC_FLAGS::INDEX8
	LDY @LOCAL03
	STA ENTITY_DELTA_X_TABLE,Y
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA @LOCAL02
	JSL ASL16_ENTRY2
	ORA #$00FF
	REP #PROC_FLAGS::INDEX8
	LDY @LOCAL03
	STA ENTITY_DELTA_X_FRACTION_TABLE,Y
	BRA @UNKNOWN1
@UNKNOWN0:
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA @LOCAL02
	JSL ASR8_UNKNOWN1
	AND #$00FF
	REP #PROC_FLAGS::INDEX8
	LDY @LOCAL03
	STA ENTITY_DELTA_X_TABLE,Y
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA @LOCAL02
	JSL ASL16_ENTRY2
	AND #$FF00
	REP #PROC_FLAGS::INDEX8
	LDY @LOCAL03
	STA ENTITY_DELTA_X_FRACTION_TABLE,Y
@UNKNOWN1:
	LDA @LOCAL00 + fixed_point::fraction
	STA @LOCAL02
	AND #$8000
	BEQ @UNKNOWN2
	LDA @VIRTUAL02
	ASL
	TAX
	STX @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDA #8
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	JSL ASR8_UNKNOWN1
	ORA #$FF00
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL01
	STA ENTITY_DELTA_Y_TABLE,X
	SEP #PROC_FLAGS::ACCUM8
	LDA #8
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	JSL ASL16_ENTRY2
	ORA #$00FF
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL01
	STA ENTITY_DELTA_Y_FRACTION_TABLE,X
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA @VIRTUAL02
	ASL
	TAX
	STX @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDA #8
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	JSL ASR8_UNKNOWN1
	AND #$00FF
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL01
	STA ENTITY_DELTA_Y_TABLE,X
	SEP #PROC_FLAGS::ACCUM8
	LDA #8
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	JSL ASL16_ENTRY2
	AND #$FF00
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL01
	STA ENTITY_DELTA_Y_FRACTION_TABLE,X
@UNKNOWN3:
	LDA @VIRTUAL04
	END_C_FUNCTION
