
UNKNOWN_C47269: ;$C47269
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA .LOWORD(CURRENT_ENTITY_SLOT)
	ASL
	TAX
	LDA .LOWORD(ENTITY_ABS_X_TABLE),X
	LDY .LOWORD(ENTITY_ABS_Y_TABLE),X
	CMP .LOWORD(ENTITY_SCRIPT_VAR0_TABLE),X
	BCS @UNKNOWN0
	LDA #$0003
	BRA @UNKNOWN4
@UNKNOWN0:
	CMP .LOWORD(ENTITY_SCRIPT_VAR1_TABLE),X
	BCC @UNKNOWN1
	BEQ @UNKNOWN1
	LDA #$0007
	BRA @UNKNOWN4
@UNKNOWN1:
	TYA
	CMP .LOWORD(ENTITY_SCRIPT_VAR2_TABLE),X
	BCS @UNKNOWN2
	LDA #$0005
	BRA @UNKNOWN4
@UNKNOWN2:
	TYA
	CMP .LOWORD(ENTITY_SCRIPT_VAR3_TABLE),X
	BCC @UNKNOWN3
	BEQ @UNKNOWN3
	LDA #$0001
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA #$0000
@UNKNOWN4:
	RTL
