
UNKNOWN_C472A8:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL02
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL02
	ASL
	TAX
	LDY ENTITY_SCRIPT_VAR0_TABLE,X
	STY @LOCAL01
	TYA
	JSL UNKNOWN_C47044
	LDY @LOCAL01
	TYA
	JSL UNKNOWN_C46B51
	TAY
	STY @LOCAL01
	LDX @LOCAL02
	BEQ @UNKNOWN0
	TYA
	JSL UNKNOWN_C46B37
	TAY
	STY @LOCAL01
@UNKNOWN0:
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAX
	LDA __BSS_START__,X
	STA @LOCAL00
	TYA
	STA __BSS_START__,X
	LDA @LOCAL00
	JSL UNKNOWN_C46AA3
	TAX
	STX @LOCAL02
	LDY @LOCAL01
	TYA
	JSL UNKNOWN_C46AA3
	STA @VIRTUAL04
	LDX @LOCAL02
	TXA
	CMP @VIRTUAL04
	BEQ @UNKNOWN1
	LDA @VIRTUAL02
	JSL UNKNOWN_C0A443_ENTRY2
@UNKNOWN1:
	END_C_FUNCTION
