
UNKNOWN_C4730E:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	CLC
	ADC #.LOWORD(ENTITY_DELTA_Y_TABLE)
	TAX
	LDA __BSS_START__,X
	STA @LOCAL00
	AND #$8000
	STA @VIRTUAL02
	LDA @LOCAL00
	LSR
	ORA @VIRTUAL02
	STA __BSS_START__,X
	END_C_FUNCTION
