
UNKNOWN_C4730E: ;$C4730E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA CURRENT_ENTITY_SLOT
	ASL
	CLC
	ADC #.LOWORD(ENTITY_DELTA_Y_TABLE)
	TAX
	LDA __BSS_START__,X
	STA $0E
	AND #$8000
	STA $02
	LDA $0E
	LSR
	ORA $02
	STA __BSS_START__,X
	PLD
	RTL
