
UNKNOWN_C47765:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @VIRTUAL02
	TAY
	LOADPTR BUFFER + $900 + 760, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	TXA
	SEC
	SBC BG1_Y_POS
	STA @LOCAL02
	CMP #127
	BLTEQ @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	LDA #127
	STA [@VIRTUAL0A]
	REP #PROC_FLAGS::ACCUM8
	LOADPTR BUFFER + $900 + 761, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	LOADPTR BUFFER + $900 + 762, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	LOADPTR BUFFER + $900 + 763, @VIRTUAL06
	LDA @LOCAL02
	SEC
	SBC #127
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	TYA
	SEC
	SBC BG1_X_POS
	TAY
	LDA @VIRTUAL02
	SEC
	SBC BG1_X_POS
	STA @LOCAL01
	LDX #0
	BRA @UNKNOWN2
@UNKNOWN1:
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	INY
	LDA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	LDA @LOCAL01
	DEC
	STA @LOCAL01
	INX
@UNKNOWN2:
	CPX #16
	BCC @UNKNOWN1
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #128
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #127
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	LDX @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00+2
	JSL UNKNOWN_C42542
	END_C_FUNCTION
