
UNKNOWN_C4789E:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_RETURN_INT32
	END_STACK_VARS
	STY @VIRTUAL02
	TXY
	TAX
	STX @LOCAL01
	MOVE_INT @PARAM03, @VIRTUAL06
	CPX #0
	BEQ @UNKNOWN1
	CPX #128
	BCS @UNKNOWN0
	TXA
	SEP #PROC_FLAGS::ACCUM8
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	BRA @UNKNOWN1
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA #127
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	SEP #PROC_FLAGS::INDEX8
	STY @VIRTUAL00
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA @LOCAL00
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL01
	TXA
	SEP #PROC_FLAGS::ACCUM8
	SEC
	SBC #127
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
@UNKNOWN1:
	MOVE_INT @VIRTUAL06, @RETURNVAL
	END_C_FUNCTION
