
UNKNOWN_C47A6B:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	STA @LOCAL01
	CLC
	ADC #.LOWORD(ENTITY_ABS_Y_TABLE)
	TAX
	STX @LOCAL00
	LDA @LOCAL01
	TAX
	LDA ENTITY_SCRIPT_VAR7_TABLE,X
	STA @LOCAL01
	STA @VIRTUAL04
	LDX @LOCAL00
	LDA __BSS_START__,X
	SEC
	SBC @VIRTUAL04
	STA @VIRTUAL02
	LDA @LOCAL01
	SEC
	SBC @VIRTUAL02
	STA __BSS_START__,X
	END_C_FUNCTION
