
UNKNOWN_C4827B:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL05
	TXA
	SEC
	SBC #$50
	AND #$007F
	TAY
	STY @LOCAL04
	LOADPTR FONT_PTR_TABLE, @VIRTUAL0A
	LDA @LOCAL05
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(font_table_entry)
	TAX
	CLC
	ADC #font_table_entry::height
	MOVE_INTY @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA @LOCAL03
	TXA
	INC
	INC
	INC
	INC
	MOVE_INTY @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	LDY @LOCAL04
	LDA @LOCAL03
	JSL MULT16
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL02
	LDA @VIRTUAL06+2
	STA @LOCAL02+2
	TXA
	CLC
	ADC #font_table_entry::width
	MOVE_INTY @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA @VIRTUAL02
	TXA
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL0A
	LDY @LOCAL04
	TYA
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	STA @LOCAL01
	LDA CHARACTER_PADDING
	AND #$00FF
	STA @VIRTUAL04
	LDA @LOCAL01
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL01
	CPY #8
	BLTEQ @UNKNOWN1
@UNKNOWN0:
	MOVE_INT @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @VIRTUAL02
	LDA #8
	JSL UNKNOWN_C44B3A
	LDY @LOCAL01
	TYA
	SEC
	SBC #8
	TAY
	STY @LOCAL01
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL02
	LDA @VIRTUAL06+2
	STA @LOCAL02+2
	CPY #8
	BGT @UNKNOWN0
@UNKNOWN1:
	MOVE_INT @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @VIRTUAL02
	TYA
	JSL UNKNOWN_C44B3A
	END_C_FUNCTION
