
UNKNOWN_C48B3B:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @LOCAL04
	LDA FRAME_COUNTER
	AND #$00FF
	AND #$0001
	BNEL @UNKNOWN6
	STZ @LOCAL03
	BRA @UNKNOWN5
@UNKNOWN1:
.IF .DEFINED(JPN)
	LDA @LOCAL03
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknown96,X
.ELSE
	LDY #.LOWORD(GAME_STATE) + game_state::unknown96
	LDA (@LOCAL03),Y
.ENDIF
	AND #$00FF
	STA @VIRTUAL02
	LDA #16
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN4
	LDA @LOCAL03
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknownA2,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::unknownA2,X
.ENDIF
	STA @VIRTUAL04
	ASL
	STA @VIRTUAL02
	LDA @LOCAL04
	ASL
	TAX
	LDA ENTITY_ABS_Y_TABLE,X
	STA @LOCAL00
	LDY ENTITY_ABS_X_TABLE,X
	LDX @VIRTUAL02
	LDA ENTITY_ABS_Y_TABLE,X
	TAX
	STX @LOCAL02
	LDX @VIRTUAL02
	LDA ENTITY_ABS_X_TABLE,X
	LDX @LOCAL02
	JSL UNKNOWN_C41EFF
	LDY #$2000
	CLC
	ADC #$1000
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @LOCAL01
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAX
	LDA @LOCAL01
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BEQ @UNKNOWN4
	LDA @LOCAL01
	STA __BSS_START__,X
	LDA @VIRTUAL04
	JSL UNKNOWN_C0A780
@UNKNOWN4:
	INC @LOCAL03
@UNKNOWN5:
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	CMP @LOCAL03
	BGTL @UNKNOWN1
@UNKNOWN6:
	END_C_FUNCTION
