
UNKNOWN_C48C3E: ;$C48C3E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA .LOWORD(CURRENT_ENTITY_SLOT)
	ASL
	TAY
	LDA .LOWORD(ENTITY_ABS_Y_TABLE),Y
	CLC
	ADC .LOWORD(ENTITY_SCRIPT_VAR1_TABLE),Y
	TAX
	LDA .LOWORD(ENTITY_ABS_X_TABLE),Y
	CLC
	ADC .LOWORD(ENTITY_SCRIPT_VAR0_TABLE),Y
	JSL CENTER_SCREEN
	RTL
