
UNKNOWN_C48C3E:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAY
	LDA ENTITY_ABS_Y_TABLE,Y
	CLC
	ADC ENTITY_SCRIPT_VAR1_TABLE,Y
	TAX
	LDA ENTITY_ABS_X_TABLE,Y
	CLC
	ADC ENTITY_SCRIPT_VAR0_TABLE,Y
	JSL CENTER_SCREEN
	END_C_FUNCTION
