
UNKNOWN_C48C97:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	STA @LOCAL01
	LDA AUTO_MOVEMENT_DEMO_INDEX
	BNE @UNKNOWN0
	LDX #.LOWORD(AUTO_MOVEMENT_DEMO_BUFFER+1)
	STX @LOCAL00
	STX @VIRTUAL02
	LDA AUTO_MOVEMENT_DEMO_INDEX
	OPTIMIZED_MULT @VIRTUAL04, 3
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	BNE @UNKNOWN0
	LDA @LOCAL01
	STA @VIRTUAL04
	LDX @LOCAL00
	STA __BSS_START__,X
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA AUTO_MOVEMENT_DEMO_BUFFER
	BRA @UNKNOWN4
@UNKNOWN0:
	.A16
	LDA AUTO_MOVEMENT_DEMO_INDEX
	OPTIMIZED_MULT @VIRTUAL04, 3
	STA @LOCAL00
	LDA #.LOWORD(AUTO_MOVEMENT_DEMO_BUFFER+1)
	STA @VIRTUAL02
	LDA @LOCAL01
	STA @VIRTUAL04
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	CMP @VIRTUAL04
	BNE @UNKNOWN1
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(AUTO_MOVEMENT_DEMO_BUFFER)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
	BRA @UNKNOWN4
@UNKNOWN1:
	LDA AUTO_MOVEMENT_DEMO_INDEX
	INC
	STA AUTO_MOVEMENT_DEMO_INDEX
	CMP #64
	BRK
	BNE @UNKNOWN3
@UNKNOWN2:
	BRA @UNKNOWN2
@UNKNOWN3:
	OPTIMIZED_MULT @VIRTUAL04, 3
	CLC
	ADC @VIRTUAL02
	TAX
	LDA @LOCAL01
	STA @VIRTUAL04
	STA __BSS_START__,X
	LDA AUTO_MOVEMENT_DEMO_INDEX
	OPTIMIZED_MULT @VIRTUAL04, 3
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA AUTO_MOVEMENT_DEMO_BUFFER,X
@UNKNOWN4:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
