
UNKNOWN_C48E95:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA AUTO_MOVEMENT_DEMO_INDEX
	INC
	STA AUTO_MOVEMENT_DEMO_INDEX
	OPTIMIZED_MULT @VIRTUAL04, 3
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ AUTO_MOVEMENT_DEMO_BUFFER,X
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR AUTO_MOVEMENT_DEMO_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL UNKNOWN_C0402B
	END_C_FUNCTION
