
UNKNOWN_C491EE: ;$C491EE
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	TXA
	SEC
	SBC @VIRTUAL02
	XBA
	AND #$FF00
	JSL DIVISION16
	PLD
	RTS
