
UNKNOWN_C496F9:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	END_STACK_VARS
	PROMOTENEARPTR CUR_TEXT_PAL, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA #^CUR_TEXT_PAL
	STA @LOCAL02+2
	LOADPTR UNKNOWN_7F0000, @LOCAL00
	MOVE_INT @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA #.LOWORD(CUR_TEXT_PAL)
	JSL MEMCPY24
	END_C_FUNCTION
