
UNKNOWN_C4978E:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA #.LOWORD(CUR_TEXT_PAL) ;why is preparing the destination pointer for this memcpy so needlessly expensive?
	STORE_INT1632 @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN CUR_TEXT_PAL & $FF0000, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 16
	LDA #.LOWORD(UNKNOWN_7E4476)
	JSL MEMCPY16
	END_C_FUNCTION
