
UNKNOWN_C49875:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	STY @LOCAL05
	STA @LOCAL04
	MOVE_INT @PARAM03, @VIRTUAL0A
	LDY #8
	LDA FLYOVER_PIXEL_OFFSET
	JSL MODULUS16
	STA @LOCAL03
	LDA FLYOVER_BYTE_OFFSET
	CLC
	ADC @LOCAL05
	STA @VIRTUAL02
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	LDA @VIRTUAL02
	STA @LOCAL02
	LDA #0
	STA @VIRTUAL04
	BRA @UNKNOWN3
@UNKNOWN0:
	LDY #0
	STY @LOCAL01
	BRA @UNKNOWN2
@UNKNOWN1:
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	EOR #$00FF
	LDY @LOCAL03
	SEP #PROC_FLAGS::INDEX8
	JSL ASR8_UNKNOWN1
	EOR #$00FF
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	INX
	STA @VIRTUAL00
	LDA __BSS_START__,X
	AND @VIRTUAL00
	STA __BSS_START__,X
	LDX @VIRTUAL02
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDY @LOCAL01
	INY
	STY @LOCAL01
	INC @VIRTUAL06
@UNKNOWN2:
	CPY #8
	BCC @UNKNOWN1
	LDA @LOCAL02
	CLC
	ADC #416
	STA @VIRTUAL02
	INC @VIRTUAL04
@UNKNOWN3:
	LDA #2
	CLC
	SBC @VIRTUAL04
	BRANCHGTS @UNKNOWN0
	LDA FLYOVER_PIXEL_OFFSET
	CLC
	ADC @LOCAL04
	STA FLYOVER_PIXEL_OFFSET
	LSR
	LSR
	LSR
	CMP FLYOVER_BYTE_OFFSET
	BEQL @UNKNOWN12
	ASL
	ASL
	ASL
	ASL
	STA @LOCAL04
	STA FLYOVER_BYTE_OFFSET
	LDA #8
	SEC
	SBC @LOCAL03
	STA @LOCAL02
	LDA @LOCAL04
	CLC
	ADC @LOCAL05
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	STA @LOCAL03
	STA @VIRTUAL02
	LDA #0
	STA @VIRTUAL04
	BRA @UNKNOWN10
@UNKNOWN7:
	LDY #0
	STY @LOCAL00
	BRA @UNKNOWN9
@UNKNOWN8:
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	EOR #$00FF
	LDY @LOCAL02
	SEP #PROC_FLAGS::INDEX8
	JSL ASL16_ENTRY2
	EOR #$00FF
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	INX
	STA @VIRTUAL00
	LDA __BSS_START__,X
	AND @VIRTUAL00
	STA __BSS_START__,X
	LDX @VIRTUAL02
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDY @LOCAL00
	INY
	STY @LOCAL00
	INC @VIRTUAL06
@UNKNOWN9:
	CPY #8
	BCC @UNKNOWN8
	LDA @LOCAL03
	CLC
	ADC #416
	STA @VIRTUAL02
	INC @VIRTUAL04
@UNKNOWN10:
	LDA #2
	CLC
	SBC @VIRTUAL04
	BRANCHGTS @UNKNOWN7
@UNKNOWN12:
	END_C_FUNCTION
