
UNKNOWN_C4A7B0: ;$C4A7B0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 23
	LDA UNKNOWN_7EAEC2
	AND #$00FF
	BEQL @UNKNOWN34
	LDY #.LOWORD(UNKNOWN_7EAECC)
	MOVE_INT_CONSTANT NULL, $06
	MOVE_INT_YPTRSRC __BSS_START__, $0A
	CMP $08
	BNE @UNKNOWN1
	LDA $0A
	CMP $06
@UNKNOWN1:
	BEQL @UNKNOWN19
	LDX #.LOWORD(UNKNOWN_7EAEC2)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA UNKNOWN_7EAEC2
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @UNKNOWN9
	MOVE_INT_YPTRSRC __BSS_START__, $0A
	SEP #PROC_FLAGS::ACCUM8
	LDA [$0A]
	STA UNKNOWN_7EAEC2
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @UNKNOWN4
	MOVE_INT_YPTRDEST $06, __BSS_START__
	JMP @UNKNOWN34
@UNKNOWN4:
	MOVE_INT_YPTRSRC __BSS_START__, $06
	LDY #$0002
	LDA [$06],Y
	CMP #$8000
	BEQ @UNKNOWN5
	STA UNKNOWN_7EAED0
@UNKNOWN5:
	MOVE_INT UNKNOWN_7EAECC, $06
	LDY #$0004
	LDA [$06],Y
	CMP #$8000
	BEQ @UNKNOWN6
	STA UNKNOWN_7EAED2
@UNKNOWN6:
	MOVE_INT UNKNOWN_7EAECC, $06
	LDY #$0006
	LDA [$06],Y
	CMP #$8000
	BEQ @UNKNOWN7
	STA UNKNOWN_7EAED4
@UNKNOWN7:
	MOVE_INT UNKNOWN_7EAECC, $06
	LDY #$0008
	LDA [$06],Y
	CMP #$8000
	BEQ @UNKNOWN8
	STA UNKNOWN_7EAED6
@UNKNOWN8:
	LDY #.LOWORD(UNKNOWN_7EAECC)
	STY $15
	MOVE_INT_YPTRSRC __BSS_START__, $06
	LDY #$000A
	LDA [$06],Y
	STA UNKNOWN_7EAED8
	LDY $15
	MOVE_INT_YPTRSRC __BSS_START__, $06
	LDY #$000C
	LDA [$06],Y
	STA UNKNOWN_7EAEDA
	LDY $15
	MOVE_INT_YPTRSRC __BSS_START__, $06
	LDY #$000E
	LDA [$06],Y
	STA UNKNOWN_7EAEDC
	LDY $15
	MOVE_INT_YPTRSRC __BSS_START__, $06
	LDY #$0010
	LDA [$06],Y
	STA UNKNOWN_7EAEDE
	LDY $15
	MOVE_INT_YPTRSRC __BSS_START__, $06
	LDY #$0012
	LDA [$06],Y
	STA UNKNOWN_7EAEE0
	LDY $15
	MOVE_INT_YPTRSRC __BSS_START__, $06
	LDY #$0014
	LDA [$06],Y
	STA UNKNOWN_7EAEE2
	LDY $15
	MOVE_INT_YPTRSRC __BSS_START__, $06
	LDA #$0016
	CLC
	ADC $06
	STA $06
	STA __BSS_START__,Y
	LDA $08
	STA __BSS_START__+2,Y
@UNKNOWN9:
	LDX #.LOWORD(UNKNOWN_7EAED0)
	LDA __BSS_START__,X
	CLC
	ADC UNKNOWN_7EAED8
	STA __BSS_START__,X
	LDX #.LOWORD(UNKNOWN_7EAED2)
	LDA __BSS_START__,X
	CLC
	ADC UNKNOWN_7EAEDA
	STA __BSS_START__,X
	LDX #.LOWORD(UNKNOWN_7EAEDC)
	LDA __BSS_START__,X
	CLC
	ADC UNKNOWN_7EAEE0
	STA __BSS_START__,X
	LDY #.LOWORD(UNKNOWN_7EAEDE)
	LDA __BSS_START__,Y
	CLC
	ADC UNKNOWN_7EAEE2
	STA __BSS_START__,Y
	LDA __BSS_START__,X
	STA $15
	STA $02
	LDA #$0000
	CLC
	SBC $02
	BRANCHLTEQS @UNKNOWN12
	LDX #.LOWORD(UNKNOWN_7EAED4)
	LDA $15
	EOR #$FFFF
	INC
	STA $02
	LDA __BSS_START__,X
	CMP $02
	BCS @UNKNOWN12
	LDA #$0000
	STA __BSS_START__,X
	BRA @UNKNOWN13
@UNKNOWN12:
	LDX #.LOWORD(UNKNOWN_7EAED4)
	LDA __BSS_START__,X
	CLC
	ADC UNKNOWN_7EAEDC
	STA __BSS_START__,X
@UNKNOWN13:
	LDA UNKNOWN_7EAEDE
	STA $15
	STA $02
	LDA #$0000
	CLC
	SBC $02
	BRANCHLTEQS @UNKNOWN16
	LDX #.LOWORD(UNKNOWN_7EAED6)
	LDA $15
	EOR #$FFFF
	INC
	STA $02
	LDA __BSS_START__,X
	CMP $02
	BCS @UNKNOWN16
	LDA #$0000
	STA __BSS_START__,X
	BRA @UNKNOWN17
@UNKNOWN16:
	LDX #.LOWORD(UNKNOWN_7EAED6)
	LDA __BSS_START__,X
	CLC
	ADC UNKNOWN_7EAEDE
	STA __BSS_START__,X
@UNKNOWN17:
	LDA UNKNOWN_7EAED4
	BNE @UNKNOWN18
	LDA UNKNOWN_7EAED6
	BNE @UNKNOWN18
	SEP #PROC_FLAGS::ACCUM8
	STZ UNKNOWN_7EAEC2
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT_CONSTANT NULL, UNKNOWN_7EAECC
	JMP @UNKNOWN34
@UNKNOWN18:
	LDA UNKNOWN_7EAED6
	XBA
	AND #$00FF
	STA $0E
	LDA UNKNOWN_7EAED4
	XBA
	AND #$00FF
	TAY
	LDX UNKNOWN_7EAED2
	LDA UNKNOWN_7EAED0
	JSL UNKNOWN_C0B149
	LDX #$0041
	LDA #$0003
	JSL UNKNOWN_C0B0EF
	LDA UNKNOWN_7EAEC6
	AND #$00FF
	TAX
	LDA UNKNOWN_7EAEC8
	AND #$00FF
	JSL SET_WINDOW_MASK
	JMP @UNKNOWN34
@UNKNOWN19:
	LDX #.LOWORD(UNKNOWN_7EAEC2)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA UNKNOWN_7EAEC2
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @UNKNOWN34
@UNKNOWN20:
	LDX #.LOWORD(UNKNOWN_7EAEC4)
	STX $15
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	BEQL @UNKNOWN24
	SEP #PROC_FLAGS::ACCUM8
	LDA UNKNOWN_7EAEC3
	STA UNKNOWN_7EAEC2
	LDY #.LOWORD(UNKNOWN_7EAEC9)
	STY $13
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	AND #$00FF
	INC
	INC
	INC
	JSL UNKNOWN_C0AE34
	LDY $13
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	INC
	STA __BSS_START__,Y
	AND #$0001
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	LDA UNKNOWN_7EAEC7
	AND #$00FF
	BNE @UNKNOWN22
	LDX #.LOWORD(UNKNOWN_7EAEC5)
	STX $15
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA $12
	REP #PROC_FLAGS::ACCUM8
	LOADPTR SWIRL_DATA&$FF0000, $06
	LDA $12
	AND #$00FF
	ASL
	TAX
	LDA f:SWIRL_POINTER_TABLE,X
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA $12
	INC
	LDX $15
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDA __BSS_START__,Y
	AND #$00FF
	INC
	INC
	INC
	JSL UNKNOWN_C0B0B8
	BRA @UNKNOWN23
@UNKNOWN22:
	LDX #.LOWORD(UNKNOWN_7EAEC5)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA $12
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LOADPTR SWIRL_DATA&$FF0000, $06
	LDA $12
	AND #$00FF
	ASL
	TAX
	LDA f:SWIRL_POINTER_TABLE,X
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDA __BSS_START__,Y
	AND #$00FF
	INC
	INC
	INC
	JSL UNKNOWN_C0B0B8
@UNKNOWN23:
	LDA UNKNOWN_7EAEC6
	AND #$00FF
	TAX
	LDA UNKNOWN_7EAEC8
	AND #$00FF
	JSL SET_WINDOW_MASK
	LDX #.LOWORD(UNKNOWN_7EAEC4)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	JMP @UNKNOWN34
@UNKNOWN24:
	.A16
	LDA #.LOWORD(UNKNOWN_7EAEE4)
	STA $02
	LDX $02
	LDA __BSS_START__,X
	AND #$00FF
	BEQL @UNKNOWN32
	LDY #.LOWORD(UNKNOWN_7EAEE6)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	DEC
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @UNKNOWN27
	LOADPTR SWIRL_PRIMARY_TABLE, $06
	LDX $02
	LDA __BSS_START__,X
	AND #$00FF
	ASL
	ASL
	INC
	INC
	MOVE_INTX $06, $0A
	CLC
	ADC $0A
	STA $0A
	SEP #PROC_FLAGS::ACCUM8
	LDA [$0A]
	LDX $15
	STA __BSS_START__,X
	LDY #.LOWORD(UNKNOWN_7EAEC5)
	LDX $02
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	ASL
	ASL
	INC
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	STA $12
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	LDA UNKNOWN_7EAEC7
	AND #$00FF
	BEQL @UNKNOWN20
	LDX $15
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA $00
	LDA $12
	CLC
	ADC $00
	STA __BSS_START__,Y
	JMP @UNKNOWN20
@UNKNOWN27:
	LDX #.LOWORD(UNKNOWN_7EAEE5)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN28
	CMP #$0002
	BEQ @UNKNOWN29
	CMP #$0003
	BEQ @UNKNOWN30
	BRA @UNKNOWN31
@UNKNOWN28:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0004
	STA __BSS_START__,Y
	LDA #$0003
	STA UNKNOWN_7EAEC3
	BRA @UNKNOWN31
@UNKNOWN29:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0006
	STA __BSS_START__,Y
	LDA #$0002
	STA UNKNOWN_7EAEC3
	BRA @UNKNOWN31
@UNKNOWN30:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$000C
	STA __BSS_START__,Y
	LDA #$0001
	STA UNKNOWN_7EAEC3
@UNKNOWN31:
	REP #PROC_FLAGS::ACCUM8
	LDA UNKNOWN_7EAEE6
	AND #$00FF
	BNEL @UNKNOWN20
@UNKNOWN32:
	LDX #.LOWORD(UNKNOWN_7EAECA)
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @UNKNOWN33
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA UNKNOWN_7EAEC2
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	BRA @UNKNOWN34
@UNKNOWN33:
	.A16
	LDA UNKNOWN_7EAECB
	AND #$00FF
	BEQ @UNKNOWN34
	LDA UNKNOWN_7EAEC9
	AND #$00FF
	INC
	INC
	INC
	JSL UNKNOWN_C0AE34
	LDX #$0000
	TXA
	JSL SET_WINDOW_MASK
	JSL UNKNOWN_C2DE96
	LDY #$0000
	TYX
	TYA
	JSL SET_COLDATA
	LDA UNKNOWN_7EAD8A
	JSL UNKNOWN_C0AFCD
@UNKNOWN34:
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
