
UNKNOWN_C4A7B0:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA UNKNOWN_7EAEC2
	AND #$00FF
	BEQL @UNKNOWN34
	LDY #.LOWORD(UNKNOWN_7EAECC)
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	CMP @VIRTUAL06+2
	BNE @UNKNOWN1
	LDA @VIRTUAL0A
	CMP @VIRTUAL06
@UNKNOWN1:
	BEQL @UNKNOWN19
	LDX #.LOWORD(UNKNOWN_7EAEC2)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA UNKNOWN_7EAEC2
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @UNKNOWN9
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL0A]
	STA UNKNOWN_7EAEC2
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @UNKNOWN4
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	JMP @UNKNOWN34
@UNKNOWN4:
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::centre_x
	LDA [@VIRTUAL06],Y
	CMP #$8000
	BEQ @UNKNOWN5
	STA UNKNOWN_7EAED0
@UNKNOWN5:
	MOVE_INT UNKNOWN_7EAECC, @VIRTUAL06
	LDY #oval_window::centre_y
	LDA [@VIRTUAL06],Y
	CMP #$8000
	BEQ @UNKNOWN6
	STA UNKNOWN_7EAED2
@UNKNOWN6:
	MOVE_INT UNKNOWN_7EAECC, @VIRTUAL06
	LDY #oval_window::initial_width
	LDA [@VIRTUAL06],Y
	CMP #$8000
	BEQ @UNKNOWN7
	STA UNKNOWN_7EAED4
@UNKNOWN7:
	MOVE_INT UNKNOWN_7EAECC, @VIRTUAL06
	LDY #oval_window::initial_height
	LDA [@VIRTUAL06],Y
	CMP #$8000
	BEQ @UNKNOWN8
	STA UNKNOWN_7EAED6
@UNKNOWN8:
	LDY #.LOWORD(UNKNOWN_7EAECC)
	STY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::centre_x_add
	LDA [@VIRTUAL06],Y
	STA UNKNOWN_7EAED8
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::centre_y_add
	LDA [@VIRTUAL06],Y
	STA UNKNOWN_7EAEDA
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::width_velocity
	LDA [@VIRTUAL06],Y
	STA UNKNOWN_7EAEDC
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::height_velocity
	LDA [@VIRTUAL06],Y
	STA UNKNOWN_7EAEDE
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::width_acceleration
	LDA [@VIRTUAL06],Y
	STA UNKNOWN_7EAEE0
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::height_acceleration
	LDA [@VIRTUAL06],Y
	STA UNKNOWN_7EAEE2
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDA #.SIZEOF(oval_window)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA __BSS_START__,Y
	LDA @VIRTUAL06+2
	STA __BSS_START__+2,Y
@UNKNOWN9:
	LDX #.LOWORD(UNKNOWN_7EAED0)
	LDA __BSS_START__,X
	CLC
	ADC UNKNOWN_7EAED8
	STA __BSS_START__,X
	LDX #.LOWORD(UNKNOWN_7EAED2)
	LDA __BSS_START__,X
	CLC
	ADC UNKNOWN_7EAEDA
	STA __BSS_START__,X
	LDX #.LOWORD(UNKNOWN_7EAEDC)
	LDA __BSS_START__,X
	CLC
	ADC UNKNOWN_7EAEE0
	STA __BSS_START__,X
	LDY #.LOWORD(UNKNOWN_7EAEDE)
	LDA __BSS_START__,Y
	CLC
	ADC UNKNOWN_7EAEE2
	STA __BSS_START__,Y
	LDA __BSS_START__,X
	STA @LOCAL03
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN12
	LDX #.LOWORD(UNKNOWN_7EAED4)
	LDA @LOCAL03
	EOR #$FFFF
	INC
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BCS @UNKNOWN12
	LDA #0
	STA __BSS_START__,X
	BRA @UNKNOWN13
@UNKNOWN12:
	LDX #.LOWORD(UNKNOWN_7EAED4)
	LDA __BSS_START__,X
	CLC
	ADC UNKNOWN_7EAEDC
	STA __BSS_START__,X
@UNKNOWN13:
	LDA UNKNOWN_7EAEDE
	STA @LOCAL03
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN16
	LDX #.LOWORD(UNKNOWN_7EAED6)
	LDA @LOCAL03
	EOR #$FFFF
	INC
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BCS @UNKNOWN16
	LDA #0
	STA __BSS_START__,X
	BRA @UNKNOWN17
@UNKNOWN16:
	LDX #.LOWORD(UNKNOWN_7EAED6)
	LDA __BSS_START__,X
	CLC
	ADC UNKNOWN_7EAEDE
	STA __BSS_START__,X
@UNKNOWN17:
	LDA UNKNOWN_7EAED4
	BNE @UNKNOWN18
	LDA UNKNOWN_7EAED6
	BNE @UNKNOWN18
	SEP #PROC_FLAGS::ACCUM8
	STZ UNKNOWN_7EAEC2
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT_CONSTANT NULL, UNKNOWN_7EAECC
	JMP @UNKNOWN34
@UNKNOWN18:
	LDA UNKNOWN_7EAED6
	XBA
	AND #$00FF
	STA @LOCAL00
	LDA UNKNOWN_7EAED4
	XBA
	AND #$00FF
	TAY
	LDX UNKNOWN_7EAED2
	LDA UNKNOWN_7EAED0
	JSL UNKNOWN_C0B149
	LDX #65
	LDA #3
	JSL UNKNOWN_C0B0EF
	LDA UNKNOWN_7EAEC6
	AND #$00FF
	TAX
	LDA UNKNOWN_7EAEC8
	AND #$00FF
	JSL SET_WINDOW_MASK
	JMP @UNKNOWN34
@UNKNOWN19:
	LDX #.LOWORD(UNKNOWN_7EAEC2)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA UNKNOWN_7EAEC2
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @UNKNOWN34
@UNKNOWN20:
	LDX #.LOWORD(UNKNOWN_7EAEC4)
	STX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	BEQL @UNKNOWN24
	SEP #PROC_FLAGS::ACCUM8
	LDA UNKNOWN_7EAEC3
	STA UNKNOWN_7EAEC2
	LDY #.LOWORD(UNKNOWN_7EAEC9)
	STY @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	AND #$00FF
	INC
	INC
	INC
	JSL UNKNOWN_C0AE34
	LDY @LOCAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	INC
	STA __BSS_START__,Y
	AND #$0001
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	LDA UNKNOWN_7EAEC7
	AND #$00FF
	BNE @UNKNOWN22
	LDX #.LOWORD(UNKNOWN_7EAEC5)
	STX @LOCAL03
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL01
	REP #PROC_FLAGS::ACCUM8
	LOADPTR SWIRL_DATA & $FF0000, @VIRTUAL06
	LDA @LOCAL01
	AND #$00FF
	ASL
	TAX
	LDA f:SWIRL_POINTER_TABLE,X
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	LDX @LOCAL03
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA __BSS_START__,Y
	AND #$00FF
	INC
	INC
	INC
	JSL UNKNOWN_C0B0B8
	BRA @UNKNOWN23
@UNKNOWN22:
	LDX #.LOWORD(UNKNOWN_7EAEC5)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA @LOCAL01
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LOADPTR SWIRL_DATA & $FF0000, @VIRTUAL06
	LDA @LOCAL01
	AND #$00FF
	ASL
	TAX
	LDA f:SWIRL_POINTER_TABLE,X
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA __BSS_START__,Y
	AND #$00FF
	INC
	INC
	INC
	JSL UNKNOWN_C0B0B8
@UNKNOWN23:
	LDA UNKNOWN_7EAEC6
	AND #$00FF
	TAX
	LDA UNKNOWN_7EAEC8
	AND #$00FF
	JSL SET_WINDOW_MASK
	LDX #.LOWORD(UNKNOWN_7EAEC4)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	JMP @UNKNOWN34
@UNKNOWN24:
	.A16
	LDA #.LOWORD(UNKNOWN_7EAEE4)
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	BEQL @UNKNOWN32
	LDY #.LOWORD(UNKNOWN_7EAEE6)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	DEC
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @UNKNOWN27
	LOADPTR SWIRL_PRIMARY_TABLE, @VIRTUAL06
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	ASL
	ASL
	INC
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL0A]
	LDX @LOCAL03
	STA __BSS_START__,X
	LDY #.LOWORD(UNKNOWN_7EAEC5)
	LDX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	ASL
	ASL
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @LOCAL01
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	LDA UNKNOWN_7EAEC7
	AND #$00FF
	BEQL @UNKNOWN20
	LDX @LOCAL03
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @VIRTUAL00
	LDA @LOCAL01
	CLC
	ADC @VIRTUAL00
	STA __BSS_START__,Y
	JMP @UNKNOWN20
@UNKNOWN27:
	LDX #.LOWORD(UNKNOWN_7EAEE5)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP #1
	BEQ @UNKNOWN28
	CMP #2
	BEQ @UNKNOWN29
	CMP #3
	BEQ @UNKNOWN30
	BRA @UNKNOWN31
@UNKNOWN28:
	SEP #PROC_FLAGS::ACCUM8
	LDA #4
	STA __BSS_START__,Y
	LDA #3
	STA UNKNOWN_7EAEC3
	BRA @UNKNOWN31
@UNKNOWN29:
	SEP #PROC_FLAGS::ACCUM8
	LDA #6
	STA __BSS_START__,Y
	LDA #2
	STA UNKNOWN_7EAEC3
	BRA @UNKNOWN31
@UNKNOWN30:
	SEP #PROC_FLAGS::ACCUM8
	LDA #12
	STA __BSS_START__,Y
	LDA #1
	STA UNKNOWN_7EAEC3
@UNKNOWN31:
	REP #PROC_FLAGS::ACCUM8
	LDA UNKNOWN_7EAEE6
	AND #$00FF
	BNEL @UNKNOWN20
@UNKNOWN32:
	LDX #.LOWORD(UNKNOWN_7EAECA)
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @UNKNOWN33
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA UNKNOWN_7EAEC2
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	BRA @UNKNOWN34
@UNKNOWN33:
	.A16
	LDA UNKNOWN_7EAECB
	AND #$00FF
	BEQ @UNKNOWN34
	LDA UNKNOWN_7EAEC9
	AND #$00FF
	INC
	INC
	INC
	JSL UNKNOWN_C0AE34
	LDX #0
	TXA
	JSL SET_WINDOW_MASK
	JSL UNKNOWN_C2DE96
	LDY #0
	TYX
	TYA
	JSL SET_COLDATA
	LDA UNKNOWN_7EAD8A
	JSL UNKNOWN_C0AFCD
@UNKNOWN34:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
