
;Y is subsprite ID? 0xFF is special. A is sprite height?
UNKNOWN_C4B1B8:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 "VRAM_BASE" ;unsigned int
	STACK_RESERVE_PARAM_INT16 "SPRITE_ID" ;int
	STACK_RESERVE_PARAM_INT16 "FRAME" ;int
	STACK_RESERVE_RETURN_INT16 ;unsigned int
	END_STACK_VARS
	STY @LOCAL02
	STA @VIRTUAL04
	CPY #$00FF
	BNE @UNKNOWN0
	LDA @VIRTUAL04
	JMP @UNKNOWN1
@UNKNOWN0:
	LOADPTR SPRITE_GROUPING_PTR_TABLE, @VIRTUAL0A
	TXA
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_grouping::width
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ASL
	STA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_grouping::spritebank
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @LOCAL01+2
	LDY @LOCAL02
	TYA
	ASL
	CLC
	ADC #sprite_grouping::spritepointerarray
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$FFFE
	STA @LOCAL01
	STA @VIRTUAL06
	LDA @LOCAL01+2
	STA @VIRTUAL06+2
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY @VIRTUAL04
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDA @VIRTUAL02
	CLC
	ADC @LOCAL01
	STA @LOCAL01
	STA @VIRTUAL06
	LDA @LOCAL01+2
	STA @VIRTUAL06+2
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @VIRTUAL04
	CLC
	ADC #256
	TAY
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	LDA @VIRTUAL02
	LSR
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
@UNKNOWN1:
	END_C_FUNCTION
