
UNKNOWN_C4B7A5:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	END_STACK_VARS
	LDX #0
	BRA @UNKNOWN1
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA #253
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT UNKNOWN_7EB3FC, @VIRTUAL06
	LDA UNKNOWN_7EB402
	DEC
	STA @VIRTUAL02
	LDY UNKNOWN_7EB402
	TXA
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT UNKNOWN_7EB3FC, @VIRTUAL06
	LDY UNKNOWN_7EB402
	TXA
	JSL MULT16
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA [@VIRTUAL06]
	INX
@UNKNOWN1:
	CPX UNKNOWN_7EB400
	BCC @UNKNOWN0
	LDX #0
	BRA @UNKNOWN3
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	LDA #253
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT UNKNOWN_7EB3FC, @VIRTUAL06
	STX @VIRTUAL02
	LDY UNKNOWN_7EB402
	LDA UNKNOWN_7EB400
	DEC
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT UNKNOWN_7EB3FC, @VIRTUAL06
	TXA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA [@VIRTUAL06]
	INX
@UNKNOWN3:
	CPX UNKNOWN_7EB402
	BCC @UNKNOWN2
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
