
;mother 2 only
UNKNOWN_C4B721:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT8
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @LOCAL06
	LDA @PARAM03
	STA @VIRTUAL02
	LDA UNKNOWN_7EB4CF
	ASL
	ASL
	ASL
	ASL
	STORE_INT1632 @VIRTUAL0A
	CLC
	VAR_ADD_CONST_INT_ASSIGN BUFFER + $2000, @VIRTUAL0A
	LDA @LOCAL06
	ASL
	ASL
	ASL
	ASL
	STORE_INT1632 @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN BUFFER, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL05
	TYA
	ASL
	ASL
	ASL
	ASL
	TAY
	STY @LOCAL04
	CPX #8
	BNEL @UNKNOWN6
	LDA @VIRTUAL02
	BEQL @UNKNOWN3
	LDX #0
	STX @LOCAL03
	BRA @UNKNOWN2
@UNKNOWN1:
	SEP #PROC_FLAGS::ACCUM8
	LDA [@LOCAL05]
	EOR #$00FF
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL01
	SEP #PROC_FLAGS::INDEX8
	LDY @VIRTUAL01
	LDA @VIRTUAL00
	JSL ASR8_UNKNOWN1
	STA @VIRTUAL00
	LDA [@VIRTUAL0A]
	ORA @VIRTUAL00
	STA [@VIRTUAL0A]
	REP #PROC_FLAGS::INDEX8
	LDY #256
	LDA [@LOCAL05],Y
	EOR #$00FF
	STA @VIRTUAL00
	SEP #PROC_FLAGS::INDEX8
	LDY @VIRTUAL01
	LDA @VIRTUAL00
	JSL ASR8_UNKNOWN1
	STA @VIRTUAL00
	REP #PROC_FLAGS::INDEX8
	LDY @LOCAL04
	REP #PROC_FLAGS::ACCUM8
	TYA
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	ORA @VIRTUAL00
	STA [@VIRTUAL06]
	LDX @LOCAL03
	INX
	STX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @LOCAL05, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL05
	INC @VIRTUAL0A
@UNKNOWN2:
	CPX #16
	BCCL @UNKNOWN1
@UNKNOWN3:
	LDA @LOCAL06
	ASL
	ASL
	ASL
	ASL
	STORE_INT1632 @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN BUFFER, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDX #0
	STX @LOCAL03
	BRA @UNKNOWN5
@UNKNOWN4:
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	EOR #$00FF
	STA @LOCAL01
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	SEP #PROC_FLAGS::INDEX8
	LDY @VIRTUAL00
	LDA @LOCAL01
	JSL ASL16_ENTRY2
	STA [@VIRTUAL0A]
	REP #PROC_FLAGS::INDEX8
	LDY #256
	LDA [@VIRTUAL06],Y
	EOR #$00FF
	SEP #PROC_FLAGS::INDEX8
	LDY @VIRTUAL00
	JSL ASL16_ENTRY2
	STA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	LDY @LOCAL04
	REP #PROC_FLAGS::ACCUM8
	TYA
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA [@VIRTUAL06]
	LDX @LOCAL03
	INX
	STX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @LOCAL02, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	INC @VIRTUAL0A
@UNKNOWN5:
	CPX #16
	BCC @UNKNOWN4
	INC UNKNOWN_7EB4CF
	BRA @UNKNOWN9
@UNKNOWN6:
	LDX #0
	BRA @UNKNOWN8
@UNKNOWN7:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL0A]
	REP #PROC_FLAGS::ACCUM8
	TYA
	PHA
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	PLA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	INX
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @LOCAL05, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL05
	INC @VIRTUAL0A
@UNKNOWN8:
	CPX #16
	BCC @UNKNOWN7
@UNKNOWN9:
	LDA UNKNOWN_7EB4CF
	CLC
	ADC #$2200
	END_C_FUNCTION
