
UNKNOWN_C4BD9A:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL0F
	STX @LOCAL0E
	TAX
	LDA __BSS_START__,X
	STA @LOCAL0D
	LDA __BSS_START__+2,X
	STA @LOCAL0C
	LDY #0
	STY @LOCAL0B
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDY PATH_MATRIX_COLUMNS
	LDA @LOCAL0D
	JSL MULT16
	CLC
	ADC @LOCAL0C
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @VIRTUAL00
	CMP #<-5
	BLTEQ @UNKNOWN0
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	JMP @UNKNOWN14
@UNKNOWN0:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0E
	BNE @UNKNOWN1
	LDA #0
	JMP @UNKNOWN14
@UNKNOWN1:
	LDX @LOCAL0F
	LDA @LOCAL0D
	STA __BSS_START__,X
	LDA @LOCAL0C
	STA __BSS_START__+2,X
	LDA #1
	STA @LOCAL0A
	JMP @UNKNOWN12
@UNKNOWN2:
	LDA #666
	STA @LOCAL09
	STA @LOCAL08
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	DEC
	STA @VIRTUAL00
	LDY @LOCAL0B
	STY @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	STA @LOCAL07
	STZ @LOCAL0B
	JMP @UNKNOWN7
@UNKNOWN3:
	LDA @VIRTUAL02
	ASL
	ASL
	TAY
	LDA PATH_CARDINAL_INDEX + pathfinder_coords::y_coord,Y
	CLC
	ADC @LOCAL0D
	TAX
	LDA PATH_CARDINAL_INDEX + pathfinder_coords::x_coord,Y
	CLC
	ADC @LOCAL0C
	STA @LOCAL06
	LDA @VIRTUAL02
	INC
	AND #$0003
	STA @VIRTUAL04
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @LOCAL06
	STA @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	TXA
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP @VIRTUAL00
	BNEL @UNKNOWN6
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL09
	CMP #666
	BNE @UNKNOWN5
	LDA @LOCAL07
	STA @VIRTUAL02
	STA @LOCAL09
	STX @LOCAL00
	LDA @LOCAL06
	STA @LOCAL01
@UNKNOWN5:
	LDA @LOCAL07
	STA @VIRTUAL02
	ASL
	ASL
	TAX
	LDA PATH_DIAGONAL_INDEX + pathfinder_coords::y_coord,X
	CLC
	ADC @LOCAL0D
	STA @LOCAL05
	LDA PATH_DIAGONAL_INDEX + pathfinder_coords::x_coord,X
	CLC
	ADC @LOCAL0C
	TAY
	STY @LOCAL04
	LDA @VIRTUAL00
	AND #$00FF
	DEC
	PHA
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	STY @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA @LOCAL05
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	PLY
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BNE @UNKNOWN6
	LDA @VIRTUAL04
	ASL
	ASL
	TAX
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA PATH_CARDINAL_INDEX + pathfinder_coords::x_coord,X
	CLC
	ADC @LOCAL0C
	STA @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA PATH_CARDINAL_INDEX + pathfinder_coords::y_coord,X
	CLC
	ADC @LOCAL0D
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP @VIRTUAL00
	BNE @UNKNOWN6
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	STA @VIRTUAL02
	STA @LOCAL08
	LDA @LOCAL05
	STA @LOCAL02
	LDY @LOCAL04
	STY @LOCAL03
	BRA @UNKNOWN8
@UNKNOWN6:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	STA @VIRTUAL02
	STA @LOCAL07
	INC @LOCAL0B
@UNKNOWN7:
	LDA @LOCAL0B
	CMP #4
	BCCL @UNKNOWN3
@UNKNOWN8:
	LDA @LOCAL08
	CMP #666
	BEQ @UNKNOWN9
	LDA @LOCAL02
	STA @LOCAL0D
	LDA @LOCAL03
	STA @LOCAL0C
	LDY @LOCAL08
	STY @LOCAL0B
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	DEC
	STA @VIRTUAL00
	BRA @UNKNOWN10
@UNKNOWN9:
	.A16
	LDA @LOCAL09
	CMP #666
	BEQ @UNKNOWN13
	LDA @LOCAL00
	STA @LOCAL0D
	LDA @LOCAL01
	STA @LOCAL0C
	LDY @LOCAL09
	STY @LOCAL0B
@UNKNOWN10:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0E
	CMP @LOCAL0A
	BNE @UNKNOWN11
	LDA @LOCAL0A
	BRA @UNKNOWN14
@UNKNOWN11:
	LDA @LOCAL0A
	ASL
	ASL
	CLC
	ADC @LOCAL0F
	TAX
	LDA @LOCAL0D
	STA __BSS_START__,X
	LDA @LOCAL0C
	STA __BSS_START__+2,X
	INC @LOCAL0A
@UNKNOWN12:
	LDA @VIRTUAL00
	AND #$00FF
	BNEL @UNKNOWN2
@UNKNOWN13:
	LDA @LOCAL0A
@UNKNOWN14:
	END_C_FUNCTION
