
UNKNOWN_C4C58F:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	PROMOTENEARPTR PALETTES, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA #^PALETTES
	STA @LOCAL01+2
	MOVE_INT @LOCAL01, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #100
	JSL UNKNOWN_C4954C
	LDX #.LOWORD(-1)
	LDA @VIRTUAL02
	JSL UNKNOWN_C496E7
	LDA #0
	STA @LOCAL02
	BRA @UNKNOWN1
@UNKNOWN0:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA @LOCAL02
	INC
	STA @LOCAL02
@UNKNOWN1:
	CMP @VIRTUAL02
	BCC @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA @LOCAL00
	LDX #BPP4PALETTE_SIZE * 16
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PALETTES)
	JSL MEMSET16
	LDA #24
	JSL UNKNOWN_C0856B
	JSL WAIT_UNTIL_NEXT_FRAME
	END_C_FUNCTION
