
UNKNOWN_C4EC6E:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	ASL
	ASL
	ASL
	ASL
	ASL
	STORE_INT1632 @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN $7F7000, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 1
	LDA #.LOWORD(CUR_TEXT_PAL) + BPP4PALETTE_SIZE * 12
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	LDA #16
	STA UNKNOWN_7E0030
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
