; A = sprite ID, X = movement ID
UNKNOWN_C4ECAD: ;$C4ECAD
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STX $02
	STA $12
	LDA UNKNOWN_7EB4D3
	AND #$0003
	STA NEW_ENTITY_VAR0
	INC UNKNOWN_7EB4D3
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	STA $0E
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	CLC
	ADC BG3_Y_POS
	STA $10
	LDY #$FFFF
	LDX $02
	LDA $12
	JSL CREATE_ENTITY
	PLD
	RTL
