
UNKNOWN_C4EFC4:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	STY @VIRTUAL02
	TXY
	SEP #PROC_FLAGS::ACCUM8
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @PARAM03, @VIRTUAL06
	LDA CREDITS_DMA_QUEUE_START
	OPTIMIZED_MULT @VIRTUAL04, 9
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	TYA
	STA __BSS_START__+1,X
	TXY
	INY
	INY
	INY
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDA @VIRTUAL02
	STA __BSS_START__+7,X
	LDA CREDITS_DMA_QUEUE_START
	INC
	STA CREDITS_DMA_QUEUE_START
	AND #$007F
	STA CREDITS_DMA_QUEUE_START
	END_C_FUNCTION
