
UNKNOWN_C4F01D: ;$C4F01D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	LDA .LOWORD(UNKNOWN_7EB4F5)
	CMP .LOWORD(UNKNOWN_7EB4F3)
	BEQ @RETURN
	LDA .LOWORD(UNKNOWN_7EB4F3)
	STA $04
	ASL
	ASL
	ASL
	ADC $04
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	STA $14
	TAY
	INY
	INY
	INY
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $06
	MOVE_INT $06, $0E
	LDA $14
	TAX
	LDY a:.LOWORD(RAM)+7,X
	TAX
	LDA a:.LOWORD(RAM)+1,X
	TAX
	STX $12
	LDA $14
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM),X
	LDX $12
	JSL PREPARE_VRAM_COPY
	.A16
	LDA .LOWORD(UNKNOWN_7EB4F3)
	INC
	STA .LOWORD(UNKNOWN_7EB4F3)
	AND #$007F
	STA .LOWORD(UNKNOWN_7EB4F3)
@RETURN:
	PLD
	RTL
