
FILL_CHARACTER_HP_TILE_BUFFER: ;$C20F08
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	PHA
	TDC
	ADC #$FFF0
	TCD
	PLA
	STY $0E
	STA $02
	TXA
	JSR a:.LOWORD(SEPARATE_DECIMAL_DIGITS)
	LDY $0E
	LDX #$0000
	LDA $02
	JSR a:.LOWORD(FILL_HP_PP_TILE_BUFFER)
	PLD
	RTS
