
UNDRAW_HP_PP_WINDOW:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	TAX
	STX @LOCAL01
	LDA #1
	STA HPPP_METER_AREA_NEEDS_UPDATE
	SEP #PROC_FLAGS::INDEX8
	TXY
	JSL ASL16_ENTRY2
	EOR #$FFFF
	AND CURRENTLY_DRAWN_HPPP_WINDOWS
	STA CURRENTLY_DRAWN_HPPP_WINDOWS
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL01
	CPX BATTLE_MENU_CURRENT_CHARACTER_ID
	BNE @UNKNOWN0
	LDA #ACTIVE_HPPP_WINDOW_Y_OFFSET
	STA @LOCAL00
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #NORMAL_HPPP_WINDOW_Y_OFFSET
	STA @LOCAL00
@UNKNOWN1:
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 7
	PHA
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 7
	PHA
	ASL
	PLA
	ROR
	STA @VIRTUAL02
	LDA #16
	SEC
	SBC @VIRTUAL02
	PLY
	STY @VIRTUAL04
	CLC
	ADC @VIRTUAL04
	ASL
	STA @VIRTUAL02
	LDA @LOCAL00
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	TAX
	LDY #HPPP_WINDOW_HEIGHT
	BRA @UNKNOWN5
@UNKNOWN2:
	LDA #HPPP_WINDOW_WIDTH
	STA @LOCAL00
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA #0
	STA __BSS_START__,X
	INX
	INX
	LDA @LOCAL00
	DEC
	STA @LOCAL00
@UNKNOWN4:
	BNE @UNKNOWN3
	TXA
	CLC
	ADC #64 - HPPP_WINDOW_WIDTH * 2
	TAX
	DEY
@UNKNOWN5:
	BNE @UNKNOWN2
	END_C_FUNCTION
