
CLEAR_INSTANT_PRINTING:
.IF .DEFINED(JPN)
	BEGIN_C_FUNCTION
.ELSE
	BEGIN_C_FUNCTION_FAR
.ENDIF
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STZ INSTANT_PRINTING
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
