
CLEAR_CURRENT_TEXT_LINE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL00
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS + window_stats::text_y,X
	TAX
	LDA @LOCAL00
	JSR CLEAR_TEXT_LINE
	END_C_FUNCTION
