
DISPLAY_TEXT_WINDOWLESS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL06
	LDA #<-1
	JSL DISABLE_ENTITY_BY_CHARACTER_OR_PARTY
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #8
	JSL QUEUE_INTERACTION
	END_C_FUNCTION
