
FIX_TARGET_NAME:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
.IF !.DEFINED(JPN)
	STACK_RESERVE_INT16 "LOCALX"
.ENDIF
	STACK_RESERVE_INT16 "LOCAL01"
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
.IF .DEFINED(JPN)
	LDA #0
	STA @LOCAL00
.ELSE
	STZ PRINT_TARGET_ARTICLE
	STZ @LOCAL00
.ENDIF
	LDX #.SIZEOF(enemy_data::name) + 2
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(TARGET_NAME_ADJUST_SCRATCH)
	JSL MEMSET16
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BEQ @UNKNOWN0
	LDX CURRENT_TARGET
	LDA a:battler::npc_id,X
	AND #$00FF
	BEQL @UNKNOWN4
@UNKNOWN0:
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL06
	LDX CURRENT_TARGET
	LDA __BSS_START__,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
.IF !.DEFINED(JPN)
	INC
.ENDIF
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL08
	STA @LOCAL00 + 2
	LDX #.SIZEOF(enemy_data::name)
	LDA #.LOWORD(TARGET_NAME_ADJUST_SCRATCH)
	JSR COPY_ENEMY_NAME
	TAX
	STX @LOCAL01
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @UNKNOWN2
	LDX CURRENT_TARGET
	LDA a:battler::the_flag,X
	AND #$00FF
	CMP #1
	BNE @UNKNOWN1
	LDX CURRENT_TARGET
	LDA __BSS_START__+76,X
	JSL UNKNOWN_C2B66A
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP #2
	BEQ @UNKNOWN2
@UNKNOWN1:
.IF .DEFINED(JPN)
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	@LETTER_POSITION = @LOCAL01
.ELSE
	SEP #PROC_FLAGS::ACCUM8
	LDA #CHAR::SPACE
	LDX @LOCAL01
	STA __BSS_START__,X
	INX
	STX @LOCALX
	LDA #1
	STA PRINT_TARGET_ARTICLE
	LDX CURRENT_TARGET
	@LETTER_POSITION = @LOCALX
.ENDIF
	LDA a:battler::the_flag,X
	CLC
	ADC #CHAR::A_ - 1
	LDX @LETTER_POSITION
	STA __BSS_START__,X
@UNKNOWN2:
	LDX CURRENT_TARGET
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CMP #ENEMY::MY_PET
	BNE @UNKNOWN3
	PROMOTENEARPTR GAME_STATE + game_state::pet_name, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #6
	LDA #.LOWORD(TARGET_NAME_ADJUST_SCRATCH)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TARGET_NAME_ADJUST_SCRATCH+6
@UNKNOWN3:
.IF .DEFINED(JPN)
	LDX #.SIZEOF(enemy_data::name) + 1
.ELSE ; earthbound also adds a space before the letter
	LDX #.SIZEOF(enemy_data::name) + 2
.ENDIF
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(TARGET_NAME_ADJUST_SCRATCH)
	JSL REDIRECT_C1ACA1
.IF !.DEFINED(JPN)
	LDX CURRENT_TARGET
	LDA __BSS_START__,X
	STA TARGET_ENEMY_ID
.ENDIF
	BRA @UNKNOWN6
@UNKNOWN4:
	LDX CURRENT_TARGET
	LDA __BSS_START__,X
	CMP #4
	BGT @UNKNOWN6
	LDX #.SIZEOF(char_struct::name)
	STX @LOCAL01
	LDX CURRENT_TARGET
	LDA a:battler::row,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	LDX @LOCAL01
	JSL REDIRECT_C1ACA1
@UNKNOWN6:
	END_C_FUNCTION
