
FIX_TARGET_NAME: ;$C23D05
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 20
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	STA $0E
	LDX #.SIZEOF(enemy_data::name) + 2
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(TARGET_NAME_ADJUST_SCRATCH)
	JSL MEMSET16
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN0
	LDX CURRENT_TARGET
	LDA a:battler::npc_id,X
	AND #$00FF
	BEQL @UNKNOWN4
@UNKNOWN0:
	LOADPTR ENEMY_CONFIGURATION_TABLE, $06
	LDX CURRENT_TARGET
	LDA RAM,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDX #.SIZEOF(enemy_data::name)
	LDA #.LOWORD(TARGET_NAME_ADJUST_SCRATCH)
	JSR COPY_ENEMY_NAME
	TAX
	STX $12
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN2
	LDX CURRENT_TARGET
	LDA a:battler::the_flag,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN1
	LDX CURRENT_TARGET
	LDA RAM+76,X
	JSL UNKNOWN_C2B66A
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP #$0002
	BEQ @UNKNOWN2
@UNKNOWN1:
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::the_flag,X
	CLC
	ADC #$0040
	LDX $12
	STA RAM,X
@UNKNOWN2:
	LDX CURRENT_TARGET
	REP #PROC_FLAGS::ACCUM8
	LDA RAM,X
	CMP #$00A0
	BNE @UNKNOWN3
	PROMOTENEARPTR GAME_STATE + game_state::pet_name, $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDX #$0006
	LDA #.LOWORD(TARGET_NAME_ADJUST_SCRATCH)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TARGET_NAME_ADJUST_SCRATCH+6
@UNKNOWN3:
	LDX #.SIZEOF(enemy_data::name) + 1
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(TARGET_NAME_ADJUST_SCRATCH)
	JSL REDIRECT_C1ACA1
	BRA @UNKNOWN6
@UNKNOWN4:
	LDX CURRENT_TARGET
	LDA RAM,X
	CMP #$0004
	BGT @UNKNOWN6
	LDX #$0004
	STX $12
	LDX CURRENT_TARGET
	LDA a:battler::row,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT)
	LDX $12
	JSL REDIRECT_C1ACA1
@UNKNOWN6:
	PLD
	RTL
