
GET_WORKING_MEMORY: ;$C1040A
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	TDC
	ADC #$FFF2
	TCD
	JSR a:.LOWORD(GET_ACTIVE_WINDOW_ADDRESS)
	CLC
	ADC #window_stats::wram_address
	TAY
	LDA a:.LOWORD(RAM),Y
	STA $06
	LDA a:.LOWORD(RAM)+2,Y
	STA $08
	LDA $06
	STA $14
	LDA $08
	STA $16
	PLD
	RTS
