
GET_PSI_NAME:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	CMP #1
	BNE @NOT_ROCKIN
	PROMOTENEARPTR GAME_STATE + game_state::favourite_thing, @VIRTUAL06
	BRA @UNKNOWN1
@NOT_ROCKIN:
	.A16
	LOADPTR PSI_NAME_TABLE, @VIRTUAL06
	LDA @LOCAL01
	DEC
	OPTIMIZED_MULT @VIRTUAL04, PSI_NAME_SIZE
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
@UNKNOWN1:
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #.LOWORD(-1)
.IF .DEFINED(JPN)
	JSR PRINT_STRING
.ELSE
	JSL UNKNOWN_C447FB
.ENDIF
	END_C_FUNCTION
