
GET_WORKING_MEMORY: ;$C1040A
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 14
	JSR a:.LOWORD(GET_ACTIVE_WINDOW_ADDRESS)
	CLC
	ADC #window_stats::wram_address
	TAY
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $06
	MOVE_INT $06, $14
	PLD
	RTS
