
GET_ARGUMENT_MEMORY: ;$C103DC
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	TDC
	ADC #$FFF2
	TCD
	JSR a:.LOWORD(GET_ACTIVE_WINDOW_ADDRESS)
	CLC
	ADC #window_stats::argument_memory
	TAY
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $06
	MOVE_INT $06, $14
	PLD
	RTS
