
GET_CHARACTER_AT_CURSOR_POSITION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LOADPTR NAME_INPUT_WINDOW_SELECTION_LAYOUT_POINTERS, @VIRTUAL0A
	TYA
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 14
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:NAME_ENTRY_GRID_CHARACTER_OFFSET_TABLE,X
	AND #$00FF
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	END_C_FUNCTION
