
HIDE_HPPP_WINDOWS: ;$C10A1D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	TDC
	ADC #$FFF0
	TCD
	JSL UNKNOWN_C3E6F8
	SEP #PROC_FLAGS::ACCUM8
	STZ $89C9
	REP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(BATTLE_MODE_FLAG)
	BNE @UNKNOWN2
	LDY #$0000
	STY $0E
	BRA @UNKNOWN1
@UNKNOWN0:
	TYA
	JSL UNKNOWN_C207E1
	LDY $0E
	LDA .LOWORD(GAME_STATE)+122,Y
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT)
	TAX
	LDA a:.LOWORD(RAM)+char_struct::current_hp_target,X
	STA a:.LOWORD(RAM)+char_struct::current_hp,X
	LDA a:.LOWORD(RAM)+char_struct::current_pp_target,X
	STA a:.LOWORD(RAM)+char_struct::current_pp,X
	STZ a:.LOWORD(RAM)+73,X
	STZ a:.LOWORD(RAM)+67,X
	LDY $0E
	INY
	STY $0E
@UNKNOWN1:
	LDA .LOWORD(GAME_STATE)+game_state::player_controlled_party_count
	AND #$00FF
	STA $02
	TYA
	CMP $02
	BNE @UNKNOWN0
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA .LOWORD(UNKNOWN_7E9623)
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTS
