
OPEN_EQUIP_SELECT_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL01
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL BACKUP_CURRENT_WINDOW_TEXT_ATTRIBUTES
	JSR SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::EQUIP_SELECT_ITEM
	LOADPTR MISC_TARGET_TEXT, @VIRTUAL06
	LDX @LOCAL01
	TXA
	OPTIMIZED_MULT @VIRTUAL04, MISC_TARGET_TEXT_LENGTH
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #MISC_TARGET_TEXT_LENGTH
	JSR PRINT_STRING
	JSR CLEAR_INSTANT_PRINTING
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL RESTORE_CURRENT_WINDOW_TEXT_ATTRIBUTES
	END_C_FUNCTION
