
PRINT_LETTER:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 "CHAR" ;int
	END_STACK_VARS
	TAX
	STX @LOCAL01
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS + window_stats::font,X
	BEQ @UNKNOWN2
	LDX @LOCAL01
	TXA
	JSR UNKNOWN_C1C046
	LDX @LOCAL01
	CPX #$0060
	BCC @UNKNOWN3
	TXA
	AND #$000F
	CMP #3
	BEQ @UNKNOWN0
	CMP #5
	BEQ @UNKNOWN0
	CMP #7
	BEQ @UNKNOWN0
	CMP #10
	BEQ @UNKNOWN0
	CMP #11
	BEQ @UNKNOWN1
	BRA @UNKNOWN3
@UNKNOWN0:
	LDA #26
	JSR UNKNOWN_C1C046
	BRA @UNKNOWN3
@UNKNOWN1:
	LDA #27
	JSR UNKNOWN_C1C046
	BRA @UNKNOWN3
@UNKNOWN2:
	LDX @LOCAL01
	TXA
	JSR UNKNOWN_C10BA1
@UNKNOWN3:
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE + window_stats::prev,X
	CMP WINDOW_TAIL
	BEQ @UNKNOWN4
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
@UNKNOWN4:
	REP #PROC_FLAGS::ACCUM8
	LDA TEXT_SOUND_MODE
	CMP #2
	BEQ @UNKNOWN5
	LDA TEXT_SOUND_MODE
	CMP #3
	BEQ @UNKNOWN6
	LDA BLINKING_TRIANGLE_FLAG
	BNE @UNKNOWN6
@UNKNOWN5:
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @UNKNOWN6
	LDX @LOCAL01
	CPX #32
	BEQ @UNKNOWN6
	LDA #SFX::TEXT_PRINT
	JSL PLAY_SOUND
@UNKNOWN6:
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @UNKNOWN9
	LDA SELECTED_TEXT_SPEED
	INC
	STA @LOCAL00
	BRA @UNKNOWN8
@UNKNOWN7:
	JSL WINDOW_TICK
	LDA @LOCAL00
	DEC
	STA @LOCAL00
@UNKNOWN8:
	BNE @UNKNOWN7
@UNKNOWN9:
	END_C_FUNCTION
