
PRINT_EQUIPMENT_AND_STATS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL00
	STZ COMPARE_EQUIPMENT_MODE
	TXA
	JSR PRINT_EQUIPMENT
	LDX @LOCAL00
	TXA
	JSL PRINT_EQUIPMENT_STATS
	END_C_FUNCTION
