
PRINT_NEWLINE: ;$C438B1
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA .LOWORD(CURRENT_FOCUS_WINDOW)
	ASL
	TAX
	LDA .LOWORD(WINDOW_EXISTENCE_TABLE),X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS_TABLE)
	TAY
	STY $10
	JSL UNKNOWN_C45E96
	LDY $10
	LDA a:.LOWORD(RAM)+21,Y
	BEQ @UNKNOWN0
	JSL UNKNOWN_C45E96
@UNKNOWN0:
	LDY $10
	TYA
	CLC
	ADC #$0010
	TAX
	LDA a:.LOWORD(RAM),X
	STA $0E
	LDA a:.LOWORD(RAM)+12,Y
	LSR
	DEC
	STA $02
	LDA $0E
	CMP $02
	BEQ @UNKNOWN1
	INC
	STA a:.LOWORD(RAM),X
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA .LOWORD(CURRENT_FOCUS_WINDOW)
	JSL UNKNOWN_C437B8
@UNKNOWN2:
	LDY $10
	TYX
	STZ a:.LOWORD(RAM)+14,X
	PLD
	RTL
