
PRINT_LETTER:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 "CHAR" ;int
	END_STACK_VARS
	TAY
	STY @LOCAL01
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQL @UNKNOWN9
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS+window_stats::font,X
	LDY @LOCAL01
	TYX
	JSL UNKNOWN_C44E61
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP WINDOW_TAIL
	BEQ @UNKNOWN1
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
@UNKNOWN1:
	REP #PROC_FLAGS::ACCUM8
	LDA TEXT_SOUND_MODE
	CMP #2
	BNE @UNKNOWN2
	LDX #1
	BRA @UNKNOWN5
@UNKNOWN2:
	LDA TEXT_SOUND_MODE
	CMP #3
	BNE @UNKNOWN3
	LDX #0
	BRA @UNKNOWN5
@UNKNOWN3:
	LDX #0
	LDA BLINKING_TRIANGLE_FLAG
	BNE @UNKNOWN5
	LDX #1
@UNKNOWN5:
	CPX #0
	BEQ @UNKNOWN6
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @UNKNOWN6
	LDY @LOCAL01
	CPY #32
	BEQ @UNKNOWN6
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	CPY #CHAR::SPACE
	BEQ @UNKNOWN6
.ENDIF
	LDA #SFX::TEXT_PRINT
	JSL PLAY_SOUND
@UNKNOWN6:
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @UNKNOWN9
	LDX SELECTED_TEXT_SPEED
	INX
	STX @LOCAL00
	BRA @UNKNOWN8
@UNKNOWN7:
	JSL WINDOW_TICK
	LDX @LOCAL00
	DEX
	STX @LOCAL00
@UNKNOWN8:
	BNE @UNKNOWN7
@UNKNOWN9:
	END_C_FUNCTION
