
PRINT_SMAAAASH:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #3
	JSR WINDOW_SET_TEXT_COLOR
	LOADPTR SMAAAASH_TILES, @VIRTUAL06
	BRA @UNKNOWN3
@UNKNOWN0:
	INC @VIRTUAL06
	INC @VIRTUAL06
	JSR DRAW_TALL_TEXT_TILE_FOCUSED_REDRAW
	LDX #1
	STX @LOCAL00
	BRA @UNKNOWN2
@UNKNOWN1:
	JSL WINDOW_TICK
@UNKNOWN2:
	LDX @LOCAL00
	TXA
	DEX
	STX @LOCAL00
	CMP #0
	BNE @UNKNOWN1
@UNKNOWN3:
	LDA [@VIRTUAL06]
	BNE @UNKNOWN0
	LDA #0
	JSR WINDOW_SET_TEXT_COLOR
	END_C_FUNCTION
