
SELECTION_MENU_ITEM_SETUP: ;$C1DDDA
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 24
	STA $16
	MOVE_INT $2A, $06
	MOVE_INT $26, $0A
	MOVE_INT $0A, $0E
	MOVE_INT $06, $12
	LDA $16
	JSR UNKNOWN_C1153B
	PLD
	RTL
