
SELECTION_MENU: ;$C11A6A
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 42
	STA $28
	LDA CURRENT_FOCUS_WINDOW
	STA $26
	CMP #$FFFF
	BNE @UNKNOWN0
	LDA #$0000
	JMP @UNKNOWN44
@UNKNOWN0:
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA WINDOW_EXISTENCE_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS_TABLE)
	STA $24
	LDY #window_stats::selected_option
	LDA ($24),Y
	CMP #$FFFF
	BEQ @UNKNOWN4
	TAX
	STX $22
	STA $20
	LDY #window_stats::current_option
	LDA ($24),Y
	LDY #.SIZEOF(menu_option)
	JSL MULT168
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA $04
	BRA @UNKNOWN3
@UNKNOWN2:
	DEX
	STX $22
	LDX $04
	LDA __BSS_START__+2,X
	LDY #.SIZEOF(menu_option)
	JSL MULT168
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA $04
@UNKNOWN3:
	LDX $22
	BNE @UNKNOWN2
	JSL SET_INSTANT_PRINTING
	LDX $04
	LDY a:menu_option::text_y,X
	LDX $04
	LDA a:menu_option::text_x,X
	TAX
	INX
	LDA $04
	JSL UNKNOWN_C43CD2
	LDA $04
	CLC
	ADC #menu_option::label
	PROMOTENEARPTRA $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDX #$0000
	LDA #$FFFF
	JSL UNKNOWN_C43BB9
	BRA @UNKNOWN5
@UNKNOWN4:
	STZ $20
	LDY #window_stats::current_option
	LDA ($24),Y
	LDY #.SIZEOF(menu_option)
	JSL MULT168
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA $04
@UNKNOWN5:
	STZ $22
	LDA $04
	CLC
	ADC #menu_option::script
	TAY
	STY $1E
	MOVE_INT_CONSTANT NULL, $0A
	MOVE_INT_YPTRSRC __BSS_START__, $06
	CMP $0C
	BNE @UNKNOWN6
	LDA $06
	CMP $0A
@UNKNOWN6:
	BEQ @UNKNOWN7
	JSL SET_INSTANT_PRINTING
	LDY $1E
	MOVE_INT_YPTRSRC __BSS_START__, $06
	MOVE_INT $06, $0E
	JSL DISPLAY_TEXT
@UNKNOWN7:
	MOVE_INT_CONSTANT NULL, $0A
	LDA $24
	CLC
	ADC #window_stats::cursor_move_callback
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, $06
	CMP $0C
	BNE @UNKNOWN8
	LDA $06
	CMP $0A
@UNKNOWN8:
	BEQ @UNKNOWN11
	LDX $04
	LDA a:menu_option::unknown0,X
	CMP #$0001
	BNE @UNKNOWN9
	LDA $20
	INC
	BRA @UNKNOWN10
@UNKNOWN9:
	LDX $04
	LDA a:menu_option::userdata,X
@UNKNOWN10:
	STA $1C
	LDA $24
	CLC
	ADC #window_stats::cursor_move_callback
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, $06
	LDA $1C
	PHA
	MOVE_INT $06, UNKNOWN_7E00BC
	PLA
	JSL UNKNOWN_C09279
	LDA $26
	JSR SET_WINDOW_FOCUS
@UNKNOWN11:
	JSL CLEAR_INSTANT_PRINTING
	LDX $04
	LDY a:menu_option::text_y,X
	LDX $04
	LDA a:menu_option::text_x,X
	TAX
	LDA $04
	JSL UNKNOWN_C43CD2
	LDA #$0001
	JSR UNKNOWN_C10FEA
	LDA #$0021
	JSR UNKNOWN_C10D60
	LDA #$0000
	JSR UNKNOWN_C10FEA
	JSL WINDOW_TICK
	LDA #$0001
	STA $02
@UNKNOWN13:
	LDA $02
	EOR #$0001
	STA $02
	STA $1A
	LDY #window_stats::text_y
	LDA ($24),Y
	ASL
	LDY #window_stats::window_y
	CLC
	ADC ($24),Y
	ASL
	ASL
	ASL
	ASL
	ASL
	STA $02
	LDY #window_stats::window_x
	LDA ($24),Y
	LDY #window_stats::text_x
	CLC
	ADC ($24),Y
	CLC
	ADC $02
	CLC
	ADC #$7C20
	STA $1E
	LDA $1A
	STA $02
	ASL
	STA $18
	LOADPTR UNKNOWN_C3E3F8+14, $06
	LDA $18
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDY $1E
	LDX #$0002
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	JSL PREPARE_VRAM_COPY
	.A16
	LOADPTR UNKNOWN_C3E3F8+18, $06
	LDA $18
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDA $1E
	CLC
	ADC #$0020
	TAY
	LDX #$0002
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	JSL PREPARE_VRAM_COPY
	.A16
	LDX #$0000
	STX $1E
	JMP @UNKNOWN37
@UNKNOWN14:
	JSL UNKNOWN_C12E42
	LDA PAD_PRESS
	AND #PAD::UP
	BEQ @UNKNOWN15
	LDX $04
	LDA a:menu_option::text_x,X
	STA $1E
	STZ $0E
	LDA #SFX::CURSOR3
	STA $10
	LDA $1E
	STA $12
	LDY #window_stats::height
	LDA ($24),Y
	LSR
	STA $14
	LDY #$FFFF
	LDX $04
	LDA a:menu_option::text_y,X
	TAX
	LDA $1E
	JSL MOVE_CURSOR
	STA $1C
	JMP @UNKNOWN39
@UNKNOWN15:
	LDA PAD_PRESS
	AND #PAD::LEFT
	BEQ @UNKNOWN16
	LDX $04
	LDA a:menu_option::text_y,X
	STA $22
	LDA #$FFFF
	STA $0E
	LDA #SFX::CURSOR2
	STA $10
	LDY #window_stats::width
	LDA ($24),Y
	STA $12
	LDA $22
	STA $14
	LDY #$0000
	TAX
	STX $16
	LDX $04
	LDA a:menu_option::text_x,X
	LDX $16
	JSL MOVE_CURSOR
	STA $1C
	JMP @UNKNOWN39
@UNKNOWN16:
	LDA PAD_PRESS
	AND #PAD::DOWN
	BEQ @UNKNOWN17
	LDX $04
	LDA a:menu_option::text_x,X
	STA $1E
	STZ $0E
	LDA #SFX::CURSOR3
	STA $10
	LDA $1E
	STA $12
	LDA #$FFFF
	STA $14
	LDY #$0001
	LDX $04
	LDA a:menu_option::text_y,X
	TAX
	LDA $1E
	JSL MOVE_CURSOR
	STA $1C
	JMP @UNKNOWN39
@UNKNOWN17:
	LDA PAD_PRESS
	AND #PAD::RIGHT
	BEQ @UNKNOWN18
	LDX $04
	LDA a:menu_option::text_y,X
	STA $22
	LDA #$0001
	STA $0E
	LDA #SFX::CURSOR2
	STA $10
	LDA #$FFFF
	STA $12
	LDA $22
	STA $14
	LDY #$0000
	TAX
	STX $1C
	LDX $04
	LDA a:menu_option::text_x,X
	LDX $1C
	JSL MOVE_CURSOR
	STA $1C
	JMP @UNKNOWN39
@UNKNOWN18:
	LDA PAD_HELD
	AND #PAD::UP
	BEQ @UNKNOWN19
	STZ $0E
	LDA #SFX::CURSOR3
	STA $10
	LDY #$FFFF
	LDX $04
	LDA a:menu_option::text_y,X
	TAX
	STX $1A
	LDX $04
	LDA a:menu_option::text_x,X
	LDX $1A
	JSL UNKNOWN_C20B65
	STA $1C
	JMP @UNKNOWN39
@UNKNOWN19:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @UNKNOWN20
	LDA #$FFFF
	STA $0E
	LDA #SFX::CURSOR2
	STA $10
	LDY #$0000
	LDX $04
	LDA a:menu_option::text_y,X
	TAX
	STX $1A
	LDX $04
	LDA a:menu_option::text_x,X
	LDX $1A
	JSL UNKNOWN_C20B65
	STA $1C
	JMP @UNKNOWN39
@UNKNOWN20:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQ @UNKNOWN21
	STZ $0E
	LDA #SFX::CURSOR3
	STA $10
	LDY #$0001
	LDX $04
	LDA a:menu_option::text_y,X
	TAX
	STX $16
	LDX $04
	LDA a:menu_option::text_x,X
	LDX $16
	JSL UNKNOWN_C20B65
	STA $1C
	JMP @UNKNOWN39
@UNKNOWN21:
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @UNKNOWN22
	LDA #$0001
	STA $0E
	LDA #SFX::CURSOR2
	STA $10
	LDY #$0000
	LDX $04
	LDA a:menu_option::text_y,X
	TAX
	STX $1C
	LDX $04
	LDA a:menu_option::text_x,X
	LDX $1C
	JSL UNKNOWN_C20B65
	STA $1C
	JMP @UNKNOWN39
@UNKNOWN22:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQL @UNKNOWN33
	JSL SET_INSTANT_PRINTING
	LDX $04
	LDA a:menu_option::page,X
	BEQL @UNKNOWN30
	LDX $04
	LDA a:menu_option::sound_effect,X
	AND #$00FF
	JSL PLAY_SOUND
	LDX $04
	LDY a:menu_option::text_y,X
	LDX $04
	LDA a:menu_option::text_x,X
	TAX
	LDA $04
	JSL UNKNOWN_C43CD2
	LDA #$002F
	JSR UNKNOWN_C10D60
	LDA #$0006
	JSR UNKNOWN_C10FEA
	LDA UNKNOWN_7E5E6E
	BEQ @UNKNOWN27
	LDA f:UNKNOWN_7EB49D
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN26
	LDA CURRENT_FOCUS_WINDOW
	CMP #$0013
	BNE @UNKNOWN25
	JSL UNKNOWN_C43B15
	BRA @UNKNOWN28
@UNKNOWN25:
	LDA $04
	CLC
	ADC #menu_option::label
	PROMOTENEARPTRA $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDX #$0001
	LDA #$0004
	JSL UNKNOWN_C43BB9
	BRA @UNKNOWN28
@UNKNOWN26:
	LDA $04
	CLC
	ADC #menu_option::label
	STA $06
	PHB
	SEP #PROC_FLAGS::ACCUM8
	PLA
	STA $08
	STZ $09
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDX #$0001
	LDA #$FFFF
	JSL UNKNOWN_C43BB9
	BRA @UNKNOWN28
@UNKNOWN27:
	JSL UNKNOWN_C43B15
@UNKNOWN28:
	LDA #$0000
	JSR UNKNOWN_C10FEA
	JSL CLEAR_INSTANT_PRINTING
	LDA $20
	LDY #window_stats::selected_option
	STA ($24),Y
	LDX $04
	LDA a:menu_option::unknown0,X
	CMP #$0001
	BNE @UNKNOWN29
	LDA $20
	INC
	JMP @UNKNOWN44
@UNKNOWN29:
	LDX $04
	LDA a:menu_option::userdata,X
	JMP @UNKNOWN44
@UNKNOWN30:
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	JSR UNKNOWN_C10FA3
	LDA $24
	CLC
	ADC #window_stats::menu_page_number
	TAX
	STX $22
	LDA __BSS_START__,X
	STA $1E
	LDX $04
	LDA a:menu_option::previous,X
	LDY #.SIZEOF(menu_option)
	JSL MULT168
	TAX
	LDA $1E
	CMP MENU_OPTIONS + menu_option::page,X
	BNE @UNKNOWN31
	LDA #$0001
	LDX $22
	STA __BSS_START__,X
	BRA @UNKNOWN32
@UNKNOWN31:
	INC
	LDX $22
	STA __BSS_START__,X
@UNKNOWN32:
	JSL CLEAR_INSTANT_PRINTING
	LDA $26
	JSL UNKNOWN_C209A0
	JSL WINDOW_TICK
	JSR PRINT_MENU_ITEMS
	JSL SET_INSTANT_PRINTING
	JMP @UNKNOWN5
@UNKNOWN33:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @UNKNOWN34
	LDA $28
	CMP #$0001
	BNE @UNKNOWN34
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	LDA #$0000
	JMP @UNKNOWN44
@UNKNOWN34:
	INC $22
	LDA WINDOW_EXISTENCE_TABLE
	CMP WINDOW_TAIL
	BNE @UNKNOWN36
	LDA $22
	CMP #$003C
	BLTEQ @UNKNOWN36
	LDA WINDOW_EXISTENCE_TABLE+20
	CMP #$FFFF
	BNE @UNKNOWN35
	JSR UNKNOWN_C1134B
@UNKNOWN35:
	LDA #$0000
	JSR SET_WINDOW_FOCUS
	JMP @UNKNOWN5
@UNKNOWN36:
	LDX $1E
	INX
	STX $1E
@UNKNOWN37:
	CPX #$000A
	BCCL @UNKNOWN14
	JMP @UNKNOWN13
@UNKNOWN39:
	CMP #$FFFF
	BEQL @UNKNOWN5
	LDA #$0000
	STA $02
	LDY #window_stats::current_option
	LDA ($24),Y
	LDY #.SIZEOF(menu_option)
	JSL MULT168
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA $22
	LDA $1C
	AND #$00FF
	TAX
	LDA $1C
	AND #$FF00
	XBA
	AND #$00FF
	STA $1C
	BRA @UNKNOWN42
@UNKNOWN41:
	INC $02
	LDY #menu_option::next
	LDA ($22),Y
	LDY #.SIZEOF(menu_option)
	JSL MULT168
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA $22
@UNKNOWN42:
	LDY #menu_option::text_x
	TXA
	CMP ($22),Y
	BNE @UNKNOWN41
	LDY #menu_option::text_y
	LDA $1C
	CMP ($22),Y
	BNE @UNKNOWN41
	LDY #menu_option::page
	LDA ($22),Y
	TAY
	STY $20
	TYA
	LDY #window_stats::menu_page_number
	CMP ($24),Y
	BEQ @UNKNOWN43
	LDY $20
	BNE @UNKNOWN41
@UNKNOWN43:
	LDX $04
	LDY a:menu_option::text_y,X
	LDX $04
	LDA a:menu_option::text_x,X
	TAX
	LDA $04
	JSL UNKNOWN_C43CD2
	LDA #$002F
	JSR UNKNOWN_C10D60
	LDA $02
	STA $20
	LDA $22
	STA $04
	JMP @UNKNOWN5
@UNKNOWN44:
	PLD
	RTS
