
SET_EVENT_FLAG:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	TXY
	STY @LOCAL02
	TAX
	DEC
	STA @LOCAL01
	LSR
	LSR
	LSR
	CLC
	ADC #.LOWORD(EVENT_FLAGS)
	TAX
	STX @LOCAL00
	LDY #8
	LDA @LOCAL01
	JSL MODULUS16
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:POWERS_OF_TWO_8BIT,X
	LDY @LOCAL02
	BEQ @UNKNOWN0
	STA @VIRTUAL00
	LDX @LOCAL00
	LDA __BSS_START__,X
	ORA @VIRTUAL00
	BRA @UNKNOWN1
@UNKNOWN0:
	EOR #$00FF
	STA @VIRTUAL00
	LDX @LOCAL00
	LDA __BSS_START__,X
	AND @VIRTUAL00
@UNKNOWN1:
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	END_C_FUNCTION
