
SET_SECONDARY_MEMORY: ;$C10443
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAY
	STY $0E
	JSR GET_ACTIVE_WINDOW_ADDRESS
	TAX
	LDY $0E
	TYA
	STA __BSS_START__+31,X
	TYA
	PLD
	RTS
