
SET_WORKING_MEMORY: ;$C1045D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_RETURN_INT32
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL06
	JSR GET_ACTIVE_WINDOW_ADDRESS
	CLC
	ADC #window_stats::working_memory
	TAY
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	MOVE_INT @VIRTUAL06, @RETURNVAL
	PLD
	RTS
