
SET_HPPP_WINDOW_MODE_ITEM:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
.IF .DEFINED(JPN)
	STACK_RESERVE_INT16
.ENDIF
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL04
.IF .DEFINED(JPN)
	STA @LOCAL03
.ENDIF
	LDY #$0000
	STY @LOCAL02
	JMP @UNKNOWN17
@UNKNOWN0:
.IF .DEFINED(JPN)
	LDA @LOCAL03
	STA @VIRTUAL04
.ENDIF
	LDX @VIRTUAL04
	TYA
	INC
	JSL UNKNOWN_C3EE14
	CMP #$0000
	BNE @UNKNOWN1
	LDA #$0C00
	STA @LOCAL01
	JMP @UNKNOWN16
@UNKNOWN1:
	LDA @VIRTUAL04
	JSR GET_ITEM_TYPE
	CMP #$0002
	BEQ @UNKNOWN2
	LDA #$0400
	STA @LOCAL01
	JMP @UNKNOWN16
@UNKNOWN2:
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #$000C
	BEQ @UNKNOWN3
	CMP #$0004
	BEQ @UNKNOWN4
	CMP #$0008
	BEQ @UNKNOWN5
	CMP #$000C
	BEQ @UNKNOWN6
	BRA @UNKNOWN7
@UNKNOWN3:
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	STA @VIRTUAL02
	STA @LOCAL00
	BRA @UNKNOWN7
@UNKNOWN4:
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	STA @VIRTUAL02
	STA @LOCAL00
	BRA @UNKNOWN7
@UNKNOWN5:
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	STA @VIRTUAL02
	STA @LOCAL00
	BRA @UNKNOWN7
@UNKNOWN6:
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	STA @VIRTUAL02
	STA @LOCAL00
@UNKNOWN7:
	LDA @LOCAL00
	STA @VIRTUAL02
	BEQ @UNKNOWN9
	LDX #$0000
	STX @LOCAL01
	LDY @LOCAL02
	CPY #$0003
	BNE @UNKNOWN8
	LDX #$0001
	STX @LOCAL01
@UNKNOWN8:
	LDA @VIRTUAL02
	DEC
.IF .DEFINED(JPN)
	STA @VIRTUAL04
.ELSE
	STA @VIRTUAL02
.ENDIF
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
.IF .DEFINED(JPN)
	ADC @VIRTUAL04
.ELSE
	ADC @VIRTUAL02
.ENDIF
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	LDX @LOCAL01
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	BRA @UNKNOWN10
@UNKNOWN9:
	LDA #$0000
@UNKNOWN10:
	LDX #$0000
	LDY @LOCAL02
	CPY #$0003
	BNE @UNKNOWN11
	LDX #$0001
@UNKNOWN11:
	PHA
	STX @VIRTUAL02
.IF .DEFINED(JPN)
	LDA @LOCAL03
	STA @VIRTUAL04
.ELSE
	LDA @VIRTUAL04
.ENDIF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	PLY
	STY @VIRTUAL02
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN14
	LDX #$1400
	BRA @UNKNOWN15
@UNKNOWN14:
	LDX #$0400
@UNKNOWN15:
	TXA
	STA @LOCAL01
@UNKNOWN16:
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA @LOCAL01
	STA PARTY_CHARACTERS+char_struct::hp_pp_window_options,X
	LDY @LOCAL02
	INY
	STY @LOCAL02
@UNKNOWN17:
	CPY #PLAYER_CHAR_COUNT
	BCCL @UNKNOWN0
	LDA #$0001
	STA REDRAW_ALL_WINDOWS
	END_C_FUNCTION
