
SHOW_HPPP_WINDOWS:
	BEGIN_C_FUNCTION
	END_STACK_VARS
	JSR RESET_ACTIVE_PARTY_MEMBER_HP_PP_WINDOW
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA RENDER_HPPP_WINDOWS
	STA REDRAW_ALL_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(-1)
	STA CURRENTLY_DRAWN_HPPP_WINDOWS
	END_C_FUNCTION
