
TRANSFER_STORAGE_MEM_ACTIVE: ;$C10380
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	JSR a:.LOWORD(GET_ACTIVE_WINDOW_ADDRESS)
	STA $0E
	CLC
	ADC #$0021
	TAY
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $06
	LDA $0E
	CLC
	ADC #window_stats::wram_address
	TAY
	MOVE_INT_YPTRDEST $06, a:.LOWORD(RAM)
	LDA $0E
	CLC
	ADC #$0025
	TAY
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $06
	LDA $0E
	CLC
	ADC #window_stats::argument_memory
	TAY
	MOVE_INT_YPTRDEST $06, a:.LOWORD(RAM)
	LDA $0E
	PHA
	TAX
	LDA a:.LOWORD(RAM)+41,X
	PLX
	STA a:.LOWORD(RAM)+31,X
	PLD
	RTS
