
UNDRAW_FLYOVER_TEXT:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
.IF .DEFINED(JPN)
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
.ENDIF
	LDY #$6000
	LDX #$7C00
	LDA #BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG3_VRAM_LOCATION
	JSL UNKNOWN_C2038B
	JSL LOAD_WINDOW_GFX
.IF .DEFINED(JPN)
	COPY_TO_VRAM3 BUFFER, $6000, $3800, @VIRTUAL00
.ELSE
	LDA #$0002
	JSL UNKNOWN_C44963
.ENDIF
	JSL UNKNOWN_C47F87
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
.IF .DEFINED(JPN)
	PLD
.ENDIF
	RTL
