
WINDOW_TICK:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL RAND
	LDA EARLY_TICK_EXIT
	AND #$00FF
	BEQ @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	STZ EARLY_TICK_EXIT
	BRA @UNKNOWN4
@UNKNOWN0:
	.A16
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @UNKNOWN4
	LDA REDRAW_ALL_WINDOWS
	AND #$00FF
	BNE @UNKNOWN1
	LDA WINDOW_HEAD
	CMP #$FFFF
	BEQ @UNKNOWN2
	LDA WINDOW_TAIL
	JSL DRAW_WINDOW
	BRA @UNKNOWN2
@UNKNOWN1:
	JSL DRAW_OPEN_WINDOWS
	SEP #PROC_FLAGS::ACCUM8
	STZ REDRAW_ALL_WINDOWS
@UNKNOWN2:
	JSL HP_PP_ROLLER
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA UPLOAD_HPPP_METER_TILES
	JSL UPDATE_HPPP_METER_TILES
	LDA DISABLED_TRANSITIONS
	BNE @UNKNOWN3
	JSR CHECK_TEXT_PALETTE_RELOAD_REQUIRED
	CMP #$0000
	BRK
	BEQ @UNKNOWN3
	JSL LOAD_TEXT_PALETTE
@UNKNOWN3:
	STZ HPPP_METER_AREA_NEEDS_UPDATE
	JSL UPLOAD_FULL_TEXT_TILEMAP
	JSL FINISH_FRAME
@UNKNOWN4:
	REP #PROC_FLAGS::ACCUM8
	RTL
