
UNKNOWN_C3E75D:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	BNE @UNKNOWN1
	LDA UNKNOWN_7E9658
	CMP #.LOWORD(-1)
	BNE @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	STZ UNKNOWN_7E5E77
	BRA @RETURN
@UNKNOWN0:
	.A16
	LDA UNKNOWN_7E5E77
	AND #$00FF
	BNE @RETURN
	LDA UNKNOWN_7E9658
	BRA @UNKNOWN3
@UNKNOWN1:
	.A16
	LDA UNKNOWN_7E965A
	CMP #.LOWORD(-1)
	BNE @UNKNOWN2
	SEP #PROC_FLAGS::ACCUM8
	STZ UNKNOWN_7E5E78
	BRA @RETURN
@UNKNOWN2:
	.A16
	LDA UNKNOWN_7E5E78
	AND #$00FF
	BNE @RETURN
	LDA UNKNOWN_7E965A
@UNKNOWN3:
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(enemy_data)
	.A16
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	BEQ @RETURN
	LDA UNKNOWN_7E5E76
	AND #$00FF
	CMP #CHAR::BULLET
	BNE @LOWERCASE_THE
	LOADPTR THETHE, @LOCAL00
	LDA #4
	JSL UNKNOWN_C447FB
	BRA @RETURN
@LOWERCASE_THE:
	LOADPTR THETHE+4, @LOCAL00
	LDA #4
	JSL UNKNOWN_C447FB
@RETURN:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
