
UNKNOWN_C3E9F7:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	TAX
	TXY
	DEY
	STY @LOCAL00
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(char_struct)
	TAX
	LDA PARTY_CHARACTERS + char_struct::equipment + EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	BEQ @UNKNOWN0
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @UNKNOWN0
	LDA #1
	JMP @UNKNOWN4
@UNKNOWN0:
	LDY @LOCAL00
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(char_struct)
	TAX
	LDA PARTY_CHARACTERS + char_struct::equipment + EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	BEQ @UNKNOWN1
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @UNKNOWN1
	LDA #1
	BRA @UNKNOWN4
@UNKNOWN1:
	LDY @LOCAL00
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(char_struct)
	TAX
	LDA PARTY_CHARACTERS + char_struct::equipment + EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	BEQ @UNKNOWN2
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @UNKNOWN2
	LDA #1
	BRA @UNKNOWN4
@UNKNOWN2:
	LDY @LOCAL00
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(char_struct)
	TAX
	LDA PARTY_CHARACTERS + char_struct::equipment + EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	BEQ @UNKNOWN3
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @UNKNOWN3
	LDA #1
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA #0
@UNKNOWN4:
	END_C_FUNCTION
