
UNKNOWN_C3E9A0: ;$C3E9A0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 14
	STX $02
	TAX
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA .LOWORD(CHAR_STRUCT)+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	CMP $02
	BNE @UNKNOWN0
	LDA #$0001
	BRA @UNKNOWN4
@UNKNOWN0:
	LDA .LOWORD(CHAR_STRUCT)+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	CMP $02
	BNE @UNKNOWN1
	LDA #$0001
	BRA @UNKNOWN4
@UNKNOWN1:
	LDA .LOWORD(CHAR_STRUCT)+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	CMP $02
	BNE @UNKNOWN2
	LDA #$0001
	BRA @UNKNOWN4
@UNKNOWN2:
	LDA .LOWORD(CHAR_STRUCT)+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	CMP $02
	BNE @UNKNOWN3
	LDA #$0001
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA #$0000
@UNKNOWN4:
	PLD
	RTL
