
UNKNOWN_C3F5F9:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @VIRTUAL04
	LDA TILEMAP_UPDATE_TILE_COUNT
	ASL
	STA @LOCAL03
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL02
	BRA @UNKNOWN2
@UNKNOWN0:
	LDA TILEMAP_UPDATE_TILE_X
	AND #$001F
	STA @VIRTUAL02
	LDA TILEMAP_UPDATE_TILE_Y
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC TILEMAP_UPDATE_BASE_ADDRESS
	CLC
	ADC @VIRTUAL02
	STA @LOCAL01
	MOVE_INT TILEMAP_UPDATE_REMAINING_TILES, @VIRTUAL06
	LDA @VIRTUAL04
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA @LOCAL01
	TAY
	LDX @LOCAL03
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	LDA @VIRTUAL04
	CLC
	ADC TILEMAP_UPDATE_TILE_WIDTH
	STA @VIRTUAL04
	LDX TILEMAP_UPDATE_TILE_Y
	INX
	STX TILEMAP_UPDATE_TILE_Y
	CPX #32
	BNE @UNKNOWN1
	STZ TILEMAP_UPDATE_TILE_Y
@UNKNOWN1:
	LDA @LOCAL02
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL02
@UNKNOWN2:
	LDA @VIRTUAL02
	CMP TILEMAP_UPDATE_TILE_HEIGHT
	BCC @UNKNOWN0
	END_C_FUNCTION
