
UNKNOWN_C3FAC9:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	TXY
	TAX
	STX @LOCAL00
	LDX CURRENT_TARGET
	LDA a:battler::npc_id,X
	AND #$00FF
	CMP #ENEMY::TINY_LIL_GHOST
	BNE @UNKNOWN0
	LDA #TRUE
	BRA @UNKNOWN2
@UNKNOWN0:
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @UNKNOWN1
	LDX @LOCAL00
	TXA
	JSR UNKNOWN_C3F981
	LDA #FALSE
	BRA @UNKNOWN2
@UNKNOWN1:
	TYA
	JSR UNKNOWN_C3F981
	LDA #TRUE
@UNKNOWN2:
	END_C_FUNCTION
