
CALC_RESISTANCES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16 ;int characterID
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	TAX
	DEX
	STX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL01
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	TAY
	BEQ @UNKNOWN0
	TYA
	DEC
	STA @VIRTUAL02
	LDA @LOCAL01
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$0003
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #$0000
@UNKNOWN1:
	STA @LOCAL00
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	TAY
	BEQ @UNKNOWN2
	TYA
	DEC
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$0003
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL02
	STA @LOCAL00
@UNKNOWN2:
	LDA @LOCAL00
	CLC
	SBC #$0003
	BRANCHLTEQS @UNKNOWN5
	LDY #$0003
	STY @LOCAL01
	BRA @UNKNOWN6
@UNKNOWN5:
	LDA @LOCAL00
	TAY
	STY @LOCAL01
@UNKNOWN6:
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL00
	TAX
	LDY @LOCAL01
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA PARTY_CHARACTERS+char_struct::fire_resist,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	TAY
	BEQ @UNKNOWN7
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0002
	PHA
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$000C
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR16
	BRA @UNKNOWN8
@UNKNOWN7:
	LDA #$0000
@UNKNOWN8:
	STA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	TAY
	BEQ @UNKNOWN9
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0002
	PHA
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$000C
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR16
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL02
	STA @LOCAL00
@UNKNOWN9:
	LDA @LOCAL00
	CLC
	SBC #$0003
	BRANCHLTEQS @UNKNOWN12
	REP #PROC_FLAGS::INDEX8
	LDY #$0003
	STY @LOCAL01
	BRA @UNKNOWN13
@UNKNOWN12:
	LDA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	TAY
	STY @LOCAL01
@UNKNOWN13:
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL00
	TAX
	LDY @LOCAL01
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA PARTY_CHARACTERS+char_struct::freeze_resist,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	TAY
	BEQ @UNKNOWN14
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0004
	PHA
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$0030
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR16
	BRA @UNKNOWN15
@UNKNOWN14:
	LDA #$0000
@UNKNOWN15:
	STA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	TAY
	BEQ @UNKNOWN16
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0004
	PHA
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$0030
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR16
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL02
	STA @LOCAL00
@UNKNOWN16:
	LDA @LOCAL00
	CLC
	SBC #$0003
	BRANCHLTEQS @UNKNOWN19
	REP #PROC_FLAGS::INDEX8
	LDY #$0003
	STY @LOCAL01
	BRA @UNKNOWN20
@UNKNOWN19:
	LDA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	TAY
	STY @LOCAL01
@UNKNOWN20:
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL00
	TAX
	LDY @LOCAL01
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA PARTY_CHARACTERS+char_struct::flash_resist,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	TAY
	BEQ @UNKNOWN21
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0006
	PHA
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$00C0
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR16
	BRA @UNKNOWN22
@UNKNOWN21:
	LDA #$0000
@UNKNOWN22:
	STA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	TAY
	BEQ @UNKNOWN23
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0006
	PHA
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$00C0
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR16
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL02
	STA @LOCAL00
@UNKNOWN23:
	LDA @LOCAL00
	CLC
	SBC #$0003
	BRANCHLTEQS @UNKNOWN26
	REP #PROC_FLAGS::INDEX8
	LDY #$0003
	STY @LOCAL01
	BRA @UNKNOWN27
@UNKNOWN26:
	LDA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	TAY
	STY @LOCAL01
@UNKNOWN27:
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL00
	TAX
	LDY @LOCAL01
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA PARTY_CHARACTERS+char_struct::paralysis_resist,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	TAY
	BEQ @UNKNOWN28
	TYA
	DEC
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @LOCAL01
	BRA @UNKNOWN29
@UNKNOWN28:
	LDA #$0000
	STA @LOCAL01
@UNKNOWN29:
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	STA PARTY_CHARACTERS+char_struct::hypnosis_brainshock_resist,X
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
