
CHECK_DEAD_PLAYERS: ;$C2BB18
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 24
	LDA #$0000
	STA $04
	JMP @UNKNOWN9
@UNKNOWN0:
	LDA $04
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAY
	STY $16
	LDA .LOWORD(BATTLERS_TABLE)+battler::consciousness,Y
	AND #$00FF
	BNE @UNKNOWN1
	JMP @UNKNOWN8
@UNKNOWN1:
	LDA .LOWORD(BATTLERS_TABLE)+battler::ally_or_enemy,Y
	AND #$00FF
	BEQ @UNKNOWN2
	JMP @UNKNOWN8
@UNKNOWN2:
	LDA .LOWORD(BATTLERS_TABLE)+battler::npc_id,Y
	AND #$00FF
	BEQ @UNKNOWN3
	JMP @UNKNOWN8
@UNKNOWN3:
	LDA .LOWORD(BATTLERS_TABLE)+16,Y
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT)
	STA $02
	STA $14
	LDY $16
	TYA
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)+battler::hp
	TAX
	STX $12
	LDX $02
	LDA a:char_struct::current_hp,X
	LDX $12
	STA a:.LOWORD(RAM),X
	LDX $02
	LDA a:char_struct::current_pp,X
	STA .LOWORD(BATTLERS_TABLE)+battler::pp,Y
	LDX $12
	LDA a:.LOWORD(RAM),X
	BNE @UNKNOWN4
	LDA .LOWORD(BATTLERS_TABLE)+battler::afflictions,Y
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @UNKNOWN4
	TYA
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	STA .LOWORD(CURRENT_TARGET)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #STATUS_0::UNCONSCIOUS
	STA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	LDX .LOWORD(CURRENT_TARGET)
	STZ a:battler::afflictions + STATUS_GROUP::SHIELD,X
	LDX .LOWORD(CURRENT_TARGET)
	STZ a:battler::afflictions + STATUS_GROUP::HOMESICKNESS,X
	LDX .LOWORD(CURRENT_TARGET)
	STZ a:battler::afflictions + STATUS_GROUP::CONCENTRATION,X
	LDX .LOWORD(CURRENT_TARGET)
	STZ a:battler::afflictions + STATUS_GROUP::STRANGENESS,X
	LDX .LOWORD(CURRENT_TARGET)
	STZ a:battler::afflictions + STATUS_GROUP:: TEMPORARY,X
	LDX .LOWORD(CURRENT_TARGET)
	STZ a:battler::afflictions + STATUS_GROUP::PERSISTENT_HARDHEAL,X
	JSL FIX_TARGET_NAME
	.A16
	LDX .LOWORD(WINDOW_EXISTENCE_TABLE)+28
	STX $16
	CREATE_WINDOW_FAR #WINDOW::TEXT_BATTLE
	DISPLAY_BATTLE_TEXT_PTR TEXT_BATTLE_GOT_HURT_AND_COLLAPSED
	LDX $16
	CPX #$FFFF
	BNE @UNKNOWN4
	JSL REDIRECT_CLOSE_FOCUS_WINDOW
@UNKNOWN4:
	LDX #$0000
	STX $12
	BRA @UNKNOWN6
@UNKNOWN5:
	REP #PROC_FLAGS::ACCUM8
	LDA $14
	STA $02
	STX $02
	CLC
	ADC $02
	PHA
	STX $02
	LDA $04
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)+battler::afflictions
	CLC
	ADC $02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM),X
	PLX
	STA a:char_struct::afflictions,X
	LDX $12
	INX
	STX $12
@UNKNOWN6:
	CPX #$0007
	BCC @UNKNOWN5
	REP #PROC_FLAGS::ACCUM8
	LDA $14
	STA $02
	CLC
	ADC #char_struct::afflictions + 4
	TAX
	LDA a:.LOWORD(RAM),X
	AND #$00FF
	BEQ @UNKNOWN7
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA a:.LOWORD(RAM),X
@UNKNOWN7:
	JSL UPDATE_PARTY
@UNKNOWN8:
	INC $04
@UNKNOWN9:
	.A16
	LDA $04
	CMP #TOTAL_PARTY_COUNT
	BCS @UNKNOWN10
	BEQ @UNKNOWN10
	JMP @UNKNOWN0
@UNKNOWN10:
	PLD
	RTL
