
COUNT_CHARS: ;$C2BAC5
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 14
	STA $04
	LDA #$0000
	STA $02
	LDX #.LOWORD(BATTLERS_TABLE)
	TAY
	BRA @UNKNOWN2
@UNKNOWN0:
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @UNKNOWN1
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP $04
	BNE @UNKNOWN1
	LDA a:battler::npc_id,X
	AND #$00FF
	BNE @UNKNOWN1
	LDA a:battler::afflictions,X
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN1
	CMP #$0002
	BEQ @UNKNOWN1
	INC $02
@UNKNOWN1:
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	INY
@UNKNOWN2:
	CPY #$0020
	BCC @UNKNOWN0
	LDA $02
	PLD
	RTL
