
ENEMY_FLASHING_OFF: ;$EF0000
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA UNKNOWN_7E89D0
	CMP #$FFFF
	BEQ @UNKNOWN2
	LDA UNKNOWN_7E89D2
	BEQ @UNKNOWN0
	LDX UNKNOWN_7E89D0
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE+74,X
	BRA @UNKNOWN1
@UNKNOWN0:
	.A16
	LDX UNKNOWN_7E89D0
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE+74,X
@UNKNOWN1:
	REP #PROC_FLAGS::ACCUM8
	STZ UNKNOWN_7EADA2
	LDA #$FFFF
	STA UNKNOWN_7E89D0
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA UNKNOWN_7E9623
@UNKNOWN2:
	REP #PROC_FLAGS::ACCUM8
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	RTL
.ELSE
	RTS
.ENDIF
