
ENEMY_SELECT_MODE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STA @VIRTUAL04
	STA @LOCAL0A
	LDA @VIRTUAL04
	STA @LOCAL09
	JSR SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::TEXT_BATTLE
	LDA OPEN_WINDOW_TABLE + WINDOW::TEXT_BATTLE * 2
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
	LDA a:window_stats::text_x,X
	STA @LOCAL08
	LDA a:window_stats::text_y,X
	STA @LOCAL07
	LDA #1
	STA @LOCAL06
	STA @LOCAL05
@UNKNOWN0:
	JSR SET_INSTANT_PRINTING
	LDX @LOCAL07
	LDA @LOCAL08
	JSR UNKNOWN_C438A5
	LDA @LOCAL0A
	STA @VIRTUAL04
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR UNKNOWN_C10D7C
	STA @VIRTUAL02
	LDA #7
	SEC
	SBC @VIRTUAL02
	CLC
	ADC #.LOWORD(NUMBER_TEXT_BUFFER)
	TAY
	STY @LOCAL04
	LDX #3
	STX @LOCAL03
	BRA @UNKNOWN4
@UNKNOWN1:
	CPX @LOCAL06
	BNE @UNKNOWN2
.IF CLEAN_ROM
	LDA #CHAR::JZERO_UNDERLINED
.ELSE
	LDA #CHAR::ZERO
.ENDIF
	BRA @UNKNOWN3
@UNKNOWN2:
.IF CLEAN_ROM
	LDA #CHAR::JZERO
.ELSE
	LDA #CHAR::ZERO
.ENDIF
@UNKNOWN3:
	JSR PRINT_LETTER
	LDX @LOCAL03
	DEX
	STX @LOCAL03
@UNKNOWN4:
	TXA
	CMP @VIRTUAL02
	BGT @UNKNOWN1
	BRA @UNKNOWN9
@UNKNOWN6:
	CPX @LOCAL06
	BNE @UNKNOWN7
.IF CLEAN_ROM
	LDA #CHAR::JZERO_UNDERLINED
.ELSE
	LDA #CHAR::ZERO
.ENDIF
	BRA @UNKNOWN8
@UNKNOWN7:
.IF CLEAN_ROM
	LDA #CHAR::JZERO
.ELSE
	LDA #CHAR::ZERO
.ENDIF
@UNKNOWN8:
	STA @VIRTUAL02
	LDY @LOCAL04
	LDA __BSS_START__,Y
	AND #$00FF
	CLC
	ADC @VIRTUAL02
	INY
	STY @LOCAL04
	JSR PRINT_LETTER
	LDX @LOCAL03
	DEX
	STX @LOCAL03
@UNKNOWN9:
	CPX #0
	BNE @UNKNOWN6
	JSR CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
@UNKNOWN10:
	JSL WINDOW_TICK
	LDA PAD_PRESS
	AND #PAD::LEFT
	BEQ @UNKNOWN11
	LDA @LOCAL06
	CMP #3
	BCS @UNKNOWN11
	INC @LOCAL06
	LDA @LOCAL05
	OPTIMIZED_MULT @VIRTUAL04, 10
	STA @LOCAL05
	JMP @UNKNOWN0
@UNKNOWN11:
	LDA PAD_PRESS
	AND #PAD::RIGHT
	BEQ @UNKNOWN12
	LDA @LOCAL06
	CMP #1
	BLTEQ @UNKNOWN12
	DEC @LOCAL06
	MOVE_INT_CONSTANT 10, @VIRTUAL0A
	MOVE_INT1632 @LOCAL05, @VIRTUAL06
	JSL DIVISION32
	LDA @VIRTUAL06
	STA @LOCAL05
	JMP @UNKNOWN0
@UNKNOWN12:
	LDA PAD_HELD
	AND #PAD::UP
	BEQ @UNKNOWN15
	MOVE_INT_CONSTANT 10, @VIRTUAL0A
	LDY @LOCAL05
	LDA @VIRTUAL04
	JSL DIVISION16S_DIVISOR_POSITIVE
	STORE_INT1632 @VIRTUAL06
	JSL MODULUS32S
	MOVE_INT_CONSTANT 9, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @UNKNOWN14
	LDA @VIRTUAL04
	CLC
	ADC @LOCAL05
	STA @VIRTUAL04
	STA @LOCAL0A
	JMP @UNKNOWN21
@UNKNOWN14:
	LDA @LOCAL05
	OPTIMIZED_MULT @VIRTUAL04, 9
	STA @VIRTUAL02
	LDA @LOCAL0A
	STA @VIRTUAL04
	SEC
	SBC @VIRTUAL02
	STA @VIRTUAL04
	STA @LOCAL0A
	JMP @UNKNOWN21
@UNKNOWN15:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQ @UNKNOWN18
	MOVE_INT_CONSTANT 10, @VIRTUAL0A
	LDY @LOCAL05
	LDA @VIRTUAL04
	JSL DIVISION16S_DIVISOR_POSITIVE
	STORE_INT1632 @VIRTUAL06
	JSL MODULUS32S
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @UNKNOWN17
	LDA @VIRTUAL04
	SEC
	SBC @LOCAL05
	STA @VIRTUAL04
	STA @LOCAL0A
	BRA @UNKNOWN21
@UNKNOWN17:
	LDA @LOCAL05
	OPTIMIZED_MULT @VIRTUAL04, 9
	STA @VIRTUAL02
	LDA @LOCAL0A
	STA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
	STA @LOCAL0A
	BRA @UNKNOWN21
@UNKNOWN18:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @UNKNOWN19
	LDX @VIRTUAL04
	STX @LOCAL03
	JMP @UNKNOWN31
@UNKNOWN19:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQL @UNKNOWN10
	LDX @LOCAL09
	STX @LOCAL03
	JMP @UNKNOWN31
@UNKNOWN21:
	LDA @VIRTUAL04
	BEQL @UNKNOWN0
	LDA @VIRTUAL04
	CMP #ENEMY_GROUP::UNKNOWN_482
	BLTEQ @UNKNOWN23
	LDA #ENEMY_GROUP::UNKNOWN_482
	STA @VIRTUAL04
	STA @LOCAL0A
@UNKNOWN23:
	LDA @VIRTUAL04
	STA CURRENT_BATTLE_GROUP
	LOADPTR BTL_ENTRY_PTR_TABLE, @VIRTUAL0A
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, 8
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDY #battle_entry_ptr_entry::pointer+2
	LDA [@VIRTUAL0A],Y
	TAY
	LDA [@VIRTUAL0A]
	STA @VIRTUAL06
	STY @VIRTUAL06+2
	STZ ENEMIES_IN_BATTLE
	BRA @UNKNOWN26
@UNKNOWN24:
	LDA ENEMIES_IN_BATTLE
	ASL
	TAX
	LDY #battle_group_entry::id
	LDA [@VIRTUAL06],Y
	STA ENEMIES_IN_BATTLE_IDS,X
	INC ENEMIES_IN_BATTLE
@UNKNOWN25:
	LDX @LOCAL02
	TXY
	DEX
	STX @LOCAL02
	CPY #0
	BNE @UNKNOWN24
	LDA #.SIZEOF(battle_group_entry)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
@UNKNOWN26:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAX
	STX @LOCAL02
	CPX #$00FF
	BNE @UNKNOWN25
	JSL UNKNOWN_C08726
	JSL UNKNOWN_C2EEE7
	LDY #8
	STY @LOCAL03
	BRA @UNKNOWN28
@UNKNOWN27:
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #.SIZEOF(battler)
	REP #PROC_FLAGS::ACCUM8
	TYA
	TXY
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	JSL MEMSET16
	LDY @LOCAL03
	INY
	STY @LOCAL03
@UNKNOWN28:
	CPY #BATTLER_COUNT
	BCC @UNKNOWN27
	LDY #0
	STY @LOCAL04
	BRA @UNKNOWN30
@UNKNOWN29:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 8)
	TAX
	STX @LOCAL01
	LDY @LOCAL04
	TYA
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
	LDX @LOCAL01
	JSL BATTLE_INIT_ENEMY_STATS
	LDY @LOCAL04
	INY
	STY @LOCAL04
@UNKNOWN30:
	CPY ENEMIES_IN_BATTLE
	BCC @UNKNOWN29
	JSL UNKNOWN_C2F121
	LDA #24
	JSL UNKNOWN_C0856B
	JSL UNKNOWN_C08744
	LDX #1
	TXA
	JSL FADE_IN
	JMP @UNKNOWN0
@UNKNOWN31:
	LDA #WINDOW::TEXT_BATTLE
	JSR SET_WINDOW_FOCUS
	JSR CLOSE_FOCUS_WINDOW
	LDX @LOCAL03
	TXA
	END_C_FUNCTION
