
ENEMY_FLASHING_OFF:
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	BEGIN_C_FUNCTION_FAR
.ELSE
	BEGIN_C_FUNCTION
.ENDIF
	LDA CURRENT_FLASHING_ENEMY
	CMP #$FFFF
	BEQ @UNKNOWN2
	LDA CURRENT_FLASHING_ENEMY_ROW
	BEQ @UNKNOWN0
	LDX CURRENT_FLASHING_ENEMY
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE+74,X
	BRA @UNKNOWN1
@UNKNOWN0:
	.A16
	LDX CURRENT_FLASHING_ENEMY
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE+74,X
@UNKNOWN1:
	REP #PROC_FLAGS::ACCUM8
	STZ ENEMY_TARGETTING_FLASHING
	LDA #$FFFF
	STA CURRENT_FLASHING_ENEMY
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA REDRAW_ALL_WINDOWS
@UNKNOWN2:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
