
GET_SHIELD_TARGETTING: ;$C23FEA
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	CMP #$002A
	BEQ @SINGLETARGET
	CMP #$002B
	BEQ @SINGLETARGET
	CMP #$002E
	BEQ @SINGLETARGET
	CMP #$002F
	BNE @MULTITARGET
@SINGLETARGET:
	LDA #$0001
	BRA @RETURN
@MULTITARGET:
	LDA #$0000
@RETURN:
	RTL
