
GET_ENEMY_TYPE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_PARAM_INT16 ;int enemy
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::type
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	END_C_FUNCTION
