
GET_ENEMY_TYPE: ;$C269A8
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::type
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	RTS
