
LOAD_ENEMY_BATTLE_SPRITES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA #9
	JSL UNKNOWN_C08D79
	LDY #$0000
	LDX #$5800
	TYA ;BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG1_VRAM_LOCATION
	LDY #$1000
	LDX #$5C00
	LDA #BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG2_VRAM_LOCATION
	LDY #$6000
	LDX #$7C00
	LDA #BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG3_VRAM_LOCATION
	LDA #$0061
	JSL SET_OAM_SIZE
	LOADPTR BUFFER + $8000, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	COPY_TO_VRAM1P @VIRTUAL06, $7C00, $800, 3
	END_C_FUNCTION
