
BATTLE_ROUTINE: ;$C24821
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	TDC
	ADC #$FFC9
	TCD
	LDA .LOWORD(BATTLE_DEBUG)
	BNE @UNKNOWN0
	LDA #$0001
	STA $35
	STA $33
	SEP #PROC_FLAGS::ACCUM8
	STA .LOWORD(GAME_STATE)+game_state::player_controlled_party_count
	LDY #.LOWORD(GAME_STATE)+122
	STY $31
	STZ $0E
	LDX #$0006
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSL MEMSET16
	LDA #.LOWORD(GAME_STATE)+150
	STA $02
	SEP #PROC_FLAGS::ACCUM8
	STZ $0E
	LDX #$0006
	REP #PROC_FLAGS::ACCUM8
	LDA $02
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	LDY $31
	STA a:.LOWORD(RAM),Y
	LDX $02
	STA a:.LOWORD(RAM),X
	REP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA .LOWORD(ENEMIES_IN_BATTLE)
	STA .LOWORD(CURRENT_BATTLE_GROUP)
	LDA f:BTL_ENTRY_PTR_TABLE+.SIZEOF(battle_entry_ptr_entry)+battle_entry_ptr_entry::pointer
	STA $06
	LDA f:BTL_ENTRY_PTR_TABLE+.SIZEOF(battle_entry_ptr_entry)+battle_entry_ptr_entry::pointer+2
	STA $08
	LDY #$0001
	LDA [$06],Y
	STA .LOWORD(UNKNOWN_7E9F8C)
@UNKNOWN0:
	STZ .LOWORD(GIYGAS_PHASE)
	LDA .LOWORD(CURRENT_BATTLE_GROUP)
	CMP #$01DB
	BNE @UNKNOWN1
	LDA #GIYGAS_PHASES::BATTLE_STARTED
	STA .LOWORD(GIYGAS_PHASE)
@UNKNOWN1:
	LOADPTR BTL_ENTRY_BG_TABLE, $06
	LDA .LOWORD(CURRENT_BATTLE_GROUP)
	ASL
	ASL
	STA $2F
	LDX $06
	STX $0A
	LDX $08
	STX $0C
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	STA $2D
	LDA $2F
	INC
	INC
	CLC
	ADC $06
	STA $06
	LDA [$06]
	STA $2B
	LDA .LOWORD(CURRENT_BATTLE_GROUP)
	ASL
	ASL
	ASL
	CLC
	ADC #battle_entry_ptr_entry::letterbox_style
	TAX
	LDA f:BTL_ENTRY_PTR_TABLE,X
	AND #$00FF
	STA $29
@UNKNOWN2:
	REP #PROC_FLAGS::ACCUM8
	STZ .LOWORD(MIRROR_ENEMY)
	STZ $27
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA .LOWORD(UNKNOWN_7EA97C)
	REP #PROC_FLAGS::ACCUM8
	STZ $25
	STZ .LOWORD(BATTLE_MONEY_SCRATCH)
	LDA #$0000
	STA .LOWORD(BATTLE_EXP_SCRATCH)
	LDA #$0000
	STA .LOWORD(BATTLE_EXP_SCRATCH)+2
	JSL UNKNOWN_C08726
	JSL UNKNOWN_C2E0E7
	JSL LOAD_ENEMY_BATTLE_SPRITES
	JSL LOAD_WINDOW_GFX
	LDA #$0001
	JSL UNKNOWN_C44963
	LDY $29
	LDX $2B
	LDA $2D
	JSL LOAD_BATTLE_BG
	JSL UNKNOWN_C2EEE7
	LDY #$0000
	STY $31
	BRA @UNKNOWN4
@UNKNOWN3:
	SEP #PROC_FLAGS::ACCUM8
	STZ $0E
	LDX #.SIZEOF(battler)
	REP #PROC_FLAGS::ACCUM8
	TYA
	TXY
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	JSL MEMSET16
	LDY $31
	INY
	STY $31
@UNKNOWN4:
	CPY #BATTLER_COUNT
	BCC @UNKNOWN3
	STZ .LOWORD(UNKNOWN_7EAA0C)
	LDY #$0000
	STY $23
	STZ $31
	JMP a:.LOWORD(@UNKNOWN9)
@UNKNOWN5:
	LDY #$986F
	LDA ($31),Y
	AND #$00FF
	STA $04
	STA $21
	LDA $04
	BEQ @UNKNOWN7
	LDA $04
	CMP #$0004
	BEQ @UNKNOWN6
	BCS @UNKNOWN7
@UNKNOWN6:
	LDA $31
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
	LDA $04
	JSL BATTLE_INIT_PLAYER_STATS
	BRA @UNKNOWN8
@UNKNOWN7:
	LDA $04
	CMP #$0005
	BCC @UNKNOWN8
	LDA $31
	LDY #.SIZEOF(battler)
	JSL MULT168
	STA $02
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
	STX $1F
	LDA $04
	ASL
	TAX
	INX
	LDA f:NPC_AI_TABLE,X
	AND #$00FF
	LDX $1F
	JSL BATTLE_INIT_ENEMY_STATS
	LDX $02
	SEP #PROC_FLAGS::ACCUM8
	STZ .LOWORD(BATTLERS_TABLE)+battler::ally_or_enemy,X
	REP #PROC_FLAGS::ACCUM8
	LDA $04
	SEP #PROC_FLAGS::ACCUM8
	LDX $02
	STA .LOWORD(BATTLERS_TABLE)+battler::npc_id,X
	LDY $23
	REP #PROC_FLAGS::ACCUM8
	TYA
	SEP #PROC_FLAGS::ACCUM8
	LDX $02
	STA .LOWORD(BATTLERS_TABLE)+16,X
	REP #PROC_FLAGS::ACCUM8
	TYA
	ASL
	TAX
	LDA .LOWORD(GAME_STATE)+game_state::party_npc_1_hp,X
	LDX $02
	STA .LOWORD(BATTLERS_TABLE)+battler::hp_target,X
	LDX $02
	STA .LOWORD(BATTLERS_TABLE)+battler::hp,X
	INY
	STY $23
	LDX $02
	STZ .LOWORD(BATTLERS_TABLE)+battler::pp_target,X
	LDX $02
	STZ .LOWORD(BATTLERS_TABLE)+battler::pp,X
@UNKNOWN8:
	INC $31
@UNKNOWN9:
	LDA $31
	CMP #$0006
	BCS @UNKNOWN10
	BEQ @UNKNOWN10
	JMP a:.LOWORD(@UNKNOWN5)
@UNKNOWN10:
	JSL UNKNOWN_C2F0D1
	LDY #$0000
	STY $31
	BRA @UNKNOWN12
@UNKNOWN11:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #$A21C
	TAX
	STX $1F
	LDY $31
	TYA
	ASL
	TAX
	LDA .LOWORD(UNKNOWN_7E9F8C),X
	LDX $1F
	JSL BATTLE_INIT_ENEMY_STATS
	LDY $31
	INY
	STY $31
@UNKNOWN12:
	CPY .LOWORD(ENEMIES_IN_BATTLE)
	BCC @UNKNOWN11
	JSL UNKNOWN_C2F121
	JSL UNKNOWN_C2F8F9
	JSL UNKNOWN_C47F87
	LDA #$0018
	JSL UNKNOWN_C0856B
	LDA #$0001
	STA .LOWORD(BATTLE_MODE_FLAG)
	LDA .LOWORD(UNKNOWN_7E9F8C)
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::music
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	JSL CHANGE_MUSIC
	JSL UNKNOWN_C08744
	LDX #$0001
	TXA
	JSL UNKNOWN_C0886C
	LDA .LOWORD(BATTLE_DEBUG)
	BEQ @UNKNOWN13
	JMP a:.LOWORD(@UNKNOWN40)
@UNKNOWN13:
	LDA $35
	JSL UNKNOWN_C1DCCB
	LDA #$0000
	STA $02
	TAY
	STY $31
	JMP a:.LOWORD(@UNKNOWN19)
@UNKNOWN14:
	REP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(GAME_STATE)+122,Y
	AND #$00FF
	STA $04
	STA $21
	LDA $04
	BEQ @UNKNOWN16
	LDA $04
	CMP #$0004
	BEQ @UNKNOWN15
	BCS @UNKNOWN16
@UNKNOWN15:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
	LDA $04
	JSL BATTLE_INIT_PLAYER_STATS
	JMP a:.LOWORD(@UNKNOWN18)
@UNKNOWN16:
	LDA $04
	CMP #$0005
	BCS @UNKNOWN17
	BEQ @UNKNOWN17
	JMP a:.LOWORD(@UNKNOWN18)
@UNKNOWN17:
	LOADPTR NPC_AI_TABLE, $06
	LDA $04
	ASL
	STA $1D
	LDX $06
	STX $0A
	LDX $08
	STX $0C
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	AND #$00FF
	AND #$0001
	BEQ @UNKNOWN18
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	STA $23
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
	LDA $1D
	INC
	CLC
	ADC $06
	STA $06
	LDA [$06]
	AND #$00FF
	JSL BATTLE_INIT_ENEMY_STATS
	LDA $02
	SEP #PROC_FLAGS::ACCUM8
	LDY #$9FBC
	STA ($23),Y
	REP #PROC_FLAGS::ACCUM8
	LDA $02
	ASL
	TAX
	LDA .LOWORD(GAME_STATE)+game_state::party_npc_1_hp,X
	LDY #$9FBF
	STA ($23),Y
	LDY #$9FBD
	STA ($23),Y
	INC $02
	LDX $23
	STZ .LOWORD(BATTLERS_TABLE)+battler::pp_target,X
	LDX $23
	STZ .LOWORD(BATTLERS_TABLE)+battler::pp,X
	LDX $23
	SEP #PROC_FLAGS::ACCUM8
	STZ .LOWORD(BATTLERS_TABLE)+battler::ally_or_enemy,X
	REP #PROC_FLAGS::ACCUM8
	LDA $04
	SEP #PROC_FLAGS::ACCUM8
	LDY #$9FBB
	STA ($23),Y
@UNKNOWN18:
	LDY $31
	INY
	STY $31
@UNKNOWN19:
	CPY #$0006
	BCS @UNKNOWN20
	BEQ @UNKNOWN20
	JMP a:.LOWORD(@UNKNOWN14)
@UNKNOWN20:
	JSL REDIRECT_SHOW_HPPP_WINDOWS
	JSL UNKNOWN_C12DD5
@UNKNOWN21:
	.A16
	JSL READ_JOYPAD
	JSL UNKNOWN_C2DB3F
	LDA a:.LOWORD(PAD_1_PRESS)
	AND #PAD::START_BUTTON
	BEQ @UNKNOWN22
	JMP a:.LOWORD(@UNKNOWN39)
@UNKNOWN22:
	LDA a:.LOWORD(PAD_1_PRESS)
	AND #PAD::SELECT_BUTTON
	BEQ @UNKNOWN23
	LDA .LOWORD(CURRENT_BATTLE_GROUP)
	JSL ENEMY_SELECT_MODE
	STA $31
	STA .LOWORD(CURRENT_BATTLE_GROUP)
	LOADPTR BTL_ENTRY_BG_TABLE, $06
	LDA $31
	ASL
	ASL
	TAX
	LDY $06
	STY $0A
	LDY $08
	STY $0C
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	STA $2D
	TXA
	INC
	INC
	CLC
	ADC $06
	STA $06
	LDA [$06]
	STA $2B
	LDA $31
	ASL
	ASL
	ASL
	CLC
	ADC #battle_entry_ptr_entry::letterbox_style
	TAX
	LDA f:BTL_ENTRY_PTR_TABLE,X
	AND #$00FF
	STA $29
	JMP a:.LOWORD(@UNKNOWN32)
@UNKNOWN23:
	LDA a:.LOWORD(PAD_1_HELD)
	AND #PAD::RIGHT
	BEQ @UNKNOWN24
	LDA $33
	CMP #$000F
	BCS @UNKNOWN25
	INC $33
	JMP a:.LOWORD(@UNKNOWN32)
@UNKNOWN24:
	LDA a:.LOWORD(PAD_1_HELD)
	AND #PAD::LEFT
	BEQ @UNKNOWN25
	LDA $33
	CMP #$0001
	BCC @UNKNOWN25
	BEQ @UNKNOWN25
	DEC $33
	JMP a:.LOWORD(@UNKNOWN32)
@UNKNOWN25:
	LDA a:.LOWORD(PAD_1_HELD)
	AND #PAD::DOWN
	BEQ @UNKNOWN26
	LDA $35
	CMP #$0001
	BCC @UNKNOWN27
	BEQ @UNKNOWN27
	DEC $35
	BRA @UNKNOWN32
@UNKNOWN26:
	LDA a:.LOWORD(PAD_1_HELD)
	AND #PAD::UP
	BEQ @UNKNOWN27
	LDA $35
	CMP #MAX_LEVEL
	BCS @UNKNOWN27
	INC $35
	BRA @UNKNOWN32
@UNKNOWN27:
	LDA a:.LOWORD(PAD_1_PRESS)
	AND #PAD::X_BUTTON
	BEQ @UNKNOWN28
	LDA .LOWORD(UNKNOWN_7EAA0C)
	STA $35
	BRA @UNKNOWN32
@UNKNOWN28:
	LDA a:.LOWORD(PAD_1_PRESS)
	AND #PAD::A_BUTTON
	BEQ @UNKNOWN29
	LDA .LOWORD(UNKNOWN_7EAA70)
	JSL SHOW_PSI_ANIMATION
	LDX .LOWORD(UNKNOWN_7EAA70)
	INX
	STX .LOWORD(UNKNOWN_7EAA70)
	CPX #$0022
	BNE @UNKNOWN29
	STZ .LOWORD(UNKNOWN_7EAA70)
@UNKNOWN29:
	LDA a:.LOWORD(PAD_1_PRESS)
	AND #PAD::B_BUTTON
	BNE @UNKNOWN30
	JMP a:.LOWORD(@UNKNOWN21)
@UNKNOWN30:
	LDX .LOWORD(UNKNOWN_7EAA74)
	LDA .LOWORD(UNKNOWN_7EAA72)
	JSL UNKNOWN_C4A67E
	LDX .LOWORD(UNKNOWN_7EAA72)
	INX
	STX .LOWORD(UNKNOWN_7EAA72)
	CPX #$0008
	BEQ @UNKNOWN31
	JMP a:.LOWORD(@UNKNOWN21)
@UNKNOWN31:
	STZ .LOWORD(UNKNOWN_7EAA72)
	LDA .LOWORD(UNKNOWN_7EAA74)
	INC
	AND #$0003
	STA .LOWORD(UNKNOWN_7EAA74)
	JMP a:.LOWORD(@UNKNOWN21)
@UNKNOWN32:
	LDX #$0000
	LDA $33
	AND #$0001
	BEQ @UNKNOWN33
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA .LOWORD(GAME_STATE)+122
	LDX #$0001
@UNKNOWN33:
	REP #PROC_FLAGS::ACCUM8
	LDA $33
	AND #$0002
	BEQ @UNKNOWN34
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0002
	STA .LOWORD(GAME_STATE)+122,X
	INX
@UNKNOWN34:
	REP #PROC_FLAGS::ACCUM8
	LDA $33
	AND #$0004
	BEQ @UNKNOWN35
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0003
	STA .LOWORD(GAME_STATE)+122,X
	INX
@UNKNOWN35:
	REP #PROC_FLAGS::ACCUM8
	LDA $33
	AND #$0008
	BEQ @UNKNOWN36
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0004
	STA .LOWORD(GAME_STATE)+122,X
	INX
@UNKNOWN36:
	REP #PROC_FLAGS::ACCUM8
	TXA
	SEP #PROC_FLAGS::ACCUM8
	STA .LOWORD(GAME_STATE)+game_state::player_controlled_party_count
	BRA @UNKNOWN38
@UNKNOWN37:
	STZ .LOWORD(GAME_STATE)+122,X
	INX
@UNKNOWN38:
	CPX #$0006
	BCC @UNKNOWN37
	JMP a:.LOWORD(@UNKNOWN2)
@UNKNOWN39:
	LDA .LOWORD(UNKNOWN_7E9F8C)
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	.A16
	CLC
	ADC #enemy_data::music
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	JSL CHANGE_MUSIC
@UNKNOWN40:
	LDA #EVENT_FLAG::BUZZ_BUZZ_IN_PARTY
	JSL GET_EVENT_FLAG
	CMP #$0000
	BEQ @UNKNOWN41
	LDX #.LOWORD(BATTLERS_TABLE)+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)
	LDA #ENEMY::BUZZ_BUZZ
	JSL BATTLE_INIT_ENEMY_STATS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA .LOWORD(BATTLERS_TABLE)+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+16
	STZ .LOWORD(BATTLERS_TABLE)+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::ally_or_enemy
	LDA #ENEMY::BUZZ_BUZZ
	STA .LOWORD(BATTLERS_TABLE)+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::npc_id
@UNKNOWN41:
	LDX #$0000
	STX $1F
	BRA @UNKNOWN45
@UNKNOWN42:
	REP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(GAME_STATE)+122,X
	AND #$00FF
	STA $04
	STA $21
	LDA $04
	BEQ @UNKNOWN44
	LDA $04
	CMP #$0004
	BEQ @UNKNOWN43
	BCS @UNKNOWN44
@UNKNOWN43:
	LDA $04
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT)+char_struct::afflictions
	TAX
	LDA a:STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::POSSESSED
	BNE @UNKNOWN44
	LDX #.LOWORD(BATTLERS_TABLE)+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)
	LDA #ENEMY::TINY_LIL_GHOST
	JSL BATTLE_INIT_ENEMY_STATS
	SEP #PROC_FLAGS::ACCUM8
	LDA #ENEMY::TINY_LIL_GHOST
	STA .LOWORD(BATTLERS_TABLE)+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::npc_id
	BRA @UNKNOWN46
@UNKNOWN44:
	LDX $1F
	INX
	STX $1F
@UNKNOWN45:
	CPX #TOTAL_PARTY_COUNT
	BCC @UNKNOWN42
@UNKNOWN46:
	JSL REDIRECT_SHOW_HPPP_WINDOWS
	LDA .LOWORD(ENEMIES_IN_BATTLE)
	JSR a:.LOWORD(RAND_LIMIT)
	.A16
	ASL
	TAX
	LDA .LOWORD(UNKNOWN_7E9F8C),X
	STA $2F
	LOADPTR ENEMY_CONFIGURATION_TABLE, $06
	LDA $2F
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	.A16
	STA $2F
	CLC
	ADC #enemy_data::item_dropped
	LDX $06
	STX $0A
	LDX $08
	STX $0C
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	AND #$00FF
	STA .LOWORD(ITEM_DROPPED)
	LDA $2F
	CLC
	ADC #enemy_data::item_drop_rate
	CLC
	ADC $06
	STA $06
	LDA [$06]
	AND #$00FF
	BEQ @RARITY_ZERO
	CMP #$0001
	BEQ @RARITY_ONE
	CMP #$0002
	BEQ @RARITY_TWO
	CMP #$0003
	BEQ @RARITY_THREE
	CMP #$0004
	BEQ @RARITY_FOUR
	CMP #$0005
	BEQ @RARITY_FIVE
	CMP #$0006
	BEQ @RARITY_SIX
	BRA @RARITY_SEVEN
@RARITY_ZERO:
	JSL RAND
	AND #$007F ;1/2
	BEQ @RARITY_SEVEN
	STZ .LOWORD(ITEM_DROPPED)
	BRA @RARITY_SEVEN
@RARITY_ONE:
	JSL RAND
	AND #$003F ;1/4
	BEQ @RARITY_SEVEN
	STZ .LOWORD(ITEM_DROPPED)
	BRA @RARITY_SEVEN
@RARITY_TWO:
	JSL RAND
	AND #$001F ;1/8
	BEQ @RARITY_SEVEN
	STZ .LOWORD(ITEM_DROPPED)
	BRA @RARITY_SEVEN
@RARITY_THREE:
	JSL RAND
	AND #$000F ;1/16
	BEQ @RARITY_SEVEN
	STZ .LOWORD(ITEM_DROPPED)
	BRA @RARITY_SEVEN
@RARITY_FOUR:
	JSL RAND
	AND #$0007 ;1/32
	BEQ @RARITY_SEVEN
	STZ .LOWORD(ITEM_DROPPED)
	BRA @RARITY_SEVEN
@RARITY_FIVE:
	JSL RAND
	AND #$0003 ;1/64
	BEQ @RARITY_SEVEN
	STZ .LOWORD(ITEM_DROPPED)
	BRA @RARITY_SEVEN
@RARITY_SIX:
	JSL RAND
	AND #$0001 ;1/128
	BEQ @RARITY_SEVEN
	STZ .LOWORD(ITEM_DROPPED)
@RARITY_SEVEN: ;Item dropped or 0% chance of drop occurring
	LDA .LOWORD(ITEM_DROPPED)
	BEQ @NO_ITEM_DROPPED
	JMP a:.LOWORD(@END_ITEM_DROP)
@NO_ITEM_DROPPED:
	LDX #$0000
	STX $31
	BRA @CONSOLATION_OUTER_LOOP_ENTRY
@CONSOLATION_OUTER_LOOP_BEGIN:
	LDY #$0008
	STY $2F
	BRA @CONSOLATION_INNER_LOOP_ENTRY
@CONSOLATION_INNER_LOOP_BEGIN:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	.A16
	STA $23
	TAX
	LDA .LOWORD(BATTLERS_TABLE)+battler::consciousness,X
	AND #$00FF
	BEQ @ENEMY_NOT_IN_CONSOLATION_TABLE
	LOADPTR CONSOLATION_ITEM_TABLE, $06
	LDX $31
	TXA
	STA $04
	ASL
	ASL
	ASL
	ADC $04
	STA $02
	LDA $23
	TAX
	LDA $02
	LDY $06
	STY $0A
	LDY $08
	STY $0C
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	AND #$00FF
	CMP .LOWORD(BATTLERS_TABLE) + battler::id,X
	BNE @ENEMY_NOT_IN_CONSOLATION_TABLE
	LDA #$0007
	JSR a:.LOWORD(RAND_LIMIT)
	PHA
	LDA $02
	PLY
	STY $02
	CLC
	ADC $02
	INC
	CLC
	ADC $06
	STA $06
	LDA [$06]
	AND #$00FF
	STA .LOWORD(ITEM_DROPPED)
@ENEMY_NOT_IN_CONSOLATION_TABLE:
	LDY $2F
	INY
	STY $2F
@CONSOLATION_INNER_LOOP_ENTRY:
	CPY #BATTLER_COUNT
	BCC @CONSOLATION_INNER_LOOP_BEGIN
	LDX $31
	INX
	STX $31
@CONSOLATION_OUTER_LOOP_ENTRY:
	CPX #$0002
	BCS @END_ITEM_DROP
	BEQ @END_ITEM_DROP
	JMP a:.LOWORD(@CONSOLATION_OUTER_LOOP_BEGIN)
@END_ITEM_DROP:
	STZ $1D
	LDA .LOWORD(BATTLE_INITIATIVE)
	BEQ @UNKNOWN64
	CMP #$0001
	BEQ @UNKNOWN62
	CMP #$0002
	BEQ @UNKNOWN63
	BRA @UNKNOWN64
@UNKNOWN62:
	LDA #INITIATIVE::PARTY_FIRST
	STA $1D
	BRA @UNKNOWN64
@UNKNOWN63:
	LDA #INITIATIVE::ENEMIES_FIRST
	STA $1D
@UNKNOWN64:
	STZ .LOWORD(BATTLE_INITIATIVE)
	CREATE_WINDOW_FAR #WINDOW::TEXT_BATTLE
	;TODO: why 8?
	LDA #.LOWORD(BATTLERS_TABLE)+8*.SIZEOF(battler)
	STA .LOWORD(CURRENT_ATTACKER)
	LDA #$0001
	JSL FIX_ATTACKER_NAME
	LOADPTR ENEMY_CONFIGURATION_TABLE, $0A
	LDA .LOWORD(UNKNOWN_7E9F8C)
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::encounter_text_ptr
	CLC
	ADC $0A
	STA $0A
	LDY #$0002
	LDA [$0A],Y
	TAY
	LDA [$0A]
	STA $06
	STY $08
	LDA $06
	STA $0E
	LDA $08
	STA $10
	JSL DISPLAY_IN_BATTLE_TEXT
	LDA $1D
	CMP #INITIATIVE::PARTY_FIRST
	BNE @UNKNOWN65
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF78D8
@UNKNOWN65:
	LDA #$0000
	STA $31
	BRA @UNKNOWN70
@UNKNOWN66:
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)+8*.SIZEOF(battler)
	STA .LOWORD(CURRENT_TARGET)
	JSL FIX_TARGET_NAME
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::afflictions+2,X
	AND #$00FF
	CMP #STATUS_2::ASLEEP
	BNE @UNKNOWN67
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF843F
@UNKNOWN67:
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::afflictions+4,X
	AND #$00FF
	BEQ @UNKNOWN68
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF8444
@UNKNOWN68:
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::afflictions+3,X
	AND #$00FF
	CMP #STATUS_3::STRANGE
	BNE @UNKNOWN69
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF8445
@UNKNOWN69:
	LDA $31
	INC
	STA $31
@UNKNOWN70:
	CMP .LOWORD(ENEMIES_IN_BATTLE)
	BCC @UNKNOWN66
	JSL REDIRECT_CLOSE_FOCUS_WINDOW
	STZ $23
	LDA $23
	STA .LOWORD(UNKNOWN_7EAA0E)
	JMP a:.LOWORD(@UNKNOWN236)
@UNKNOWN71:
	INC $25
	JSL UNKNOWN_C2F917
	LDY #.LOWORD(BATTLERS_TABLE)
	STY $31
	LDX #$0000
	STX $1B
	BRA @UNKNOWN74
@UNKNOWN72:
	TYX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:.LOWORD(RAM)+13,X
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::consciousness,Y
	AND #$00FF
	BEQ @UNKNOWN73
	TYA
	CLC
	ADC #$0046
	STA $02
	LDA a:battler::speed,Y
	JSR a:.LOWORD(FIFTY_PERCENT_VARIANCE)
	LDX $02
	STA a:.LOWORD(RAM),X
	CMP #$0000
	BNE @UNKNOWN73
	LDA #$0001
	LDX $02
	STA a:.LOWORD(RAM),X
@UNKNOWN73:
	LDY $31
	TYA
	CLC
	ADC #.SIZEOF(battler)
	TAY
	STY $31
	LDX $1B
	INX
	STX $1B
@UNKNOWN74:
	CPX #BATTLER_COUNT
	BCC @UNKNOWN72
	LDA #$0000
	STA $31
	BRA @UNKNOWN76
@UNKNOWN75:
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ .LOWORD(CHAR_STRUCT)+94,X
	REP #PROC_FLAGS::ACCUM8
	LDA $31
	INC
	STA $31
@UNKNOWN76:
	CMP #$0004
	BCC @UNKNOWN75
	LDY #$0000
	STY $19
	TYA
	STA $02
	JMP a:.LOWORD(@UNKNOWN106)
@UNKNOWN77:
	JSL CHECK_DEAD_PLAYERS
	LDA #$0000
	JSL COUNT_CHARS
	CMP #$0000
	BNE @UNKNOWN78
	CREATE_WINDOW_FAR #WINDOW::TEXT_BATTLE
	JMP a:.LOWORD(@UNKNOWN225)
@UNKNOWN78:
	LDX $02
	LDA .LOWORD(GAME_STATE)+122,X
	AND #$00FF
	STA $04
	STA $21
	LDA $04
	BNE @UNKNOWN79
	JMP a:.LOWORD(@UNKNOWN105)
@UNKNOWN79:
	LDA $04
	CMP #$0004
	BEQ @UNKNOWN80
	BCC @UNKNOWN80
	JMP a:.LOWORD(@UNKNOWN105)
@UNKNOWN80:
	LDA $1D
	CMP #$0002
	BEQ @UNKNOWN82
	LDA $1D
	CMP #$0003
	BEQ @UNKNOWN82
	LDA $1D
	CMP #$0004
	BEQ @UNKNOWN82
	LDA $04
	CMP #$0004
	BNE @UNKNOWN81
	LDA .LOWORD(MIRROR_ENEMY)
	BNE @UNKNOWN82
@UNKNOWN81:
	LDA $04
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT)+char_struct::afflictions
	TAX
	LDA a:STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @UNKNOWN82
	CMP #STATUS_0::DIAMONDIZED
	BEQ @UNKNOWN82
	LDA a:STATUS_GROUP::TEMPORARY,X
	AND #$00FF
	TAX
	CPX #STATUS_2::ASLEEP
	BEQ @UNKNOWN82
	CPX #STATUS_2::SOLIDIFIED
	BNE @UNKNOWN83
@UNKNOWN82:
	LDA #BATTLE_ACTIONS::NO_EFFECT
	STA $1F
	SEP #PROC_FLAGS::ACCUM8
	STZ .LOWORD(UNKNOWN_7EA97C)
	JMP a:.LOWORD(@UNKNOWN91)
@UNKNOWN83:
	LDA $02
	JSL REDIRECT_C43573
	LDY $19
	TYX
	LDA $04
	JSL BATTLE_SELECTION_MENU
	.A16
	STA $1F
	JSL REDIRECT_C3E6F8
	JSL REDIRECT_CLOSE_FOCUS_WINDOW
	LDA .LOWORD(BATTLE_DEBUG)
	BEQ @UNKNOWN84
	LDA $1F
	CMP #$FFFF
	BNE @UNKNOWN84
	STZ $17
	JMP a:.LOWORD(@UNKNOWN237)
@UNKNOWN84:
	LDA $1F
	CMP #BATTLE_ACTIONS::RUN_AWAY
	BNE @UNKNOWN87
	LDA #BATTLE_ACTIONS::USE_NO_EFFECT
	STA $1F
	LDA $1D
	CMP #$0001
	BNE @UNKNOWN85
	LDA #$0004
	STA $1D
	BRA @UNKNOWN86
@UNKNOWN85:
	LDA #$0003
	STA $1D
@UNKNOWN86:
	LDA #$0001
	STA $27
@UNKNOWN87:
	LDA $1F
	CMP #$FFFF
	BNE @UNKNOWN88
	JMP a:.LOWORD(@UNKNOWN2)
@UNKNOWN88:
	CMP #$0000
	BNE @UNKNOWN90
	LDY $19
	BNE @UNKNOWN89
	JMP a:.LOWORD(@UNKNOWN77)
@UNKNOWN89:
	DEY
	STY $19
	TYA
	ASL
	TAX
	LDA $AA64,X
	STA $02
	JMP a:.LOWORD(@UNKNOWN77)
@UNKNOWN90:
	LDY $19
	TYA
	ASL
	TAX
	LDA $02
	STA $AA64,X
	INY
	STY $19
	LDA $1F
	CMP #$0001
	BNE @UNKNOWN91
	LDA #$0000
	STA $1F
@UNKNOWN91:
	REP #PROC_FLAGS::ACCUM8
	STZ $1B
	JMP a:.LOWORD(@UNKNOWN104)
@UNKNOWN92:
	LDA $1B
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA .LOWORD(BATTLERS_TABLE)+battler::consciousness,X
	AND #$00FF
	BNE @UNKNOWN93
	JMP a:.LOWORD(@UNKNOWN103)
@UNKNOWN93:
	LDA .LOWORD(BATTLERS_TABLE)+battler::ally_or_enemy,X
	AND #$00FF
	BEQ @UNKNOWN94
	JMP a:.LOWORD(@UNKNOWN103)
@UNKNOWN94:
	LDA $04
	CMP .LOWORD(BATTLERS_TABLE) + battler::id,X
	BEQ @UNKNOWN95
	JMP a:.LOWORD(@UNKNOWN103)
@UNKNOWN95:
	LDA $1F
	STA .LOWORD(BATTLERS_TABLE)+battler::current_action,X
	LDA .LOWORD(UNKNOWN_7EA97C)
	AND #$00FF
	BEQ @UNKNOWN96
	SEP #PROC_FLAGS::ACCUM8
	LDA $A97E
	STA .LOWORD(BATTLERS_TABLE)+7,X
	LDA .LOWORD(UNKNOWN_7EA97C)
	STA .LOWORD(BATTLERS_TABLE)+battler::current_action_argument,X
	BRA @UNKNOWN97
@UNKNOWN96:
	SEP #PROC_FLAGS::ACCUM8
	STZ .LOWORD(BATTLERS_TABLE)+7,X
	LDA $A97E
	STA .LOWORD(BATTLERS_TABLE)+battler::current_action_argument,X
@UNKNOWN97:
	REP #PROC_FLAGS::ACCUM8
	LDA $1B
	LDY #.SIZEOF(battler)
	JSL MULT168
	STA $1F
	LDX #.LOWORD(UNKNOWN_7EA981)
	STX $2F
	PHA
	SEP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM),X
	PLX
	STA .LOWORD(BATTLERS_TABLE)+9,X
	REP #PROC_FLAGS::ACCUM8
	LDA $1F
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA $A982
	STA .LOWORD(BATTLERS_TABLE)+battler::current_target,X
	LDX $2F
	REP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM),X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN101
	LDA #$0000
	STA $2F
	BRA @UNKNOWN100
@UNKNOWN98:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA .LOWORD(BATTLERS_TABLE)+battler::consciousness,X
	AND #$00FF
	BEQ @UNKNOWN99
	LDA .LOWORD(BATTLERS_TABLE)+battler::npc_id,X
	AND #$00FF
	BNE @UNKNOWN99
	LDA $A982
	AND #$00FF
	CMP .LOWORD(BATTLERS_TABLE)+battler::id,X
	BNE @UNKNOWN99
	LDA $1B
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA $2F
	SEP #PROC_FLAGS::ACCUM8
	INC
	STA .LOWORD(BATTLERS_TABLE)+battler::current_target,X
	BRA @UNKNOWN101
@UNKNOWN99:
	LDA $2F
	INC
	STA $2F
@UNKNOWN100:
	.A16
	CMP #$0006
	BCC @UNKNOWN98
@UNKNOWN101:
	REP #PROC_FLAGS::ACCUM8
	LDA $1B
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA .LOWORD(BATTLERS_TABLE)+battler::current_action,X
	CMP #BATTLE_ACTIONS::GUARD
	BNE @UNKNOWN102
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA .LOWORD(BATTLERS_TABLE)+battler::guarding,X
	BRA @UNKNOWN105
@UNKNOWN102:
	SEP #PROC_FLAGS::ACCUM8
	STZ .LOWORD(BATTLERS_TABLE)+battler::guarding,X
	BRA @UNKNOWN105
@UNKNOWN103:
	INC $1B
@UNKNOWN104:
	.A16
	LDA $1B
	CMP #BATTLER_COUNT
	BCS @UNKNOWN105
	BEQ @UNKNOWN105
	JMP a:.LOWORD(@UNKNOWN92)
@UNKNOWN105:
	REP #PROC_FLAGS::ACCUM8
	INC $02
@UNKNOWN106:
	LDA $02
	CMP #$0006
	BCS @UNKNOWN107
	BEQ @UNKNOWN107
	JMP a:.LOWORD(@UNKNOWN77)
@UNKNOWN107:
	LDA #.LOWORD(BATTLERS_TABLE)
	STA $02
	STA $19
	LDY #$0000
	STY $1F
	JMP a:.LOWORD(@UNKNOWN132)
@UNKNOWN108:
	LDX $02
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @UNKNOWN109
	LDX $02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN111
@UNKNOWN109:
	LDX $02
	LDA a:battler::npc_id,X
	AND #$00FF
	BNE @UNKNOWN111
	LDX $02
	LDA a:battler::id,X
	CMP #PARTY_MEMBER::POO
	BEQ @UNKNOWN110
	JMP a:.LOWORD(@UNKNOWN131)
@UNKNOWN110:
	LDA .LOWORD(MIRROR_ENEMY)
	BNE @UNKNOWN111
	JMP a:.LOWORD(@UNKNOWN131)
@UNKNOWN111:
	LDA $1D
	CMP #$0001
	BEQ @UNKNOWN112
	LDA $1D
	CMP #$0004
	BNE @UNKNOWN113
@UNKNOWN112:
	LDX $02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN113
	LDX $02
	STZ a:battler::current_action,X
	JMP a:.LOWORD(@UNKNOWN131)
@UNKNOWN113:
	LDA $1D
	CMP #$0002
	BNE @UNKNOWN114
	LDX $02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @UNKNOWN114
	LDX $02
	STZ a:battler::current_action,X
	JMP a:.LOWORD(@UNKNOWN131)
@UNKNOWN114:
	LDX $02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @UNKNOWN115
	LDX $02
	LDA a:battler::id,X
	CMP #PARTY_MEMBER::POO
	BNE @UNKNOWN115
	LOADPTR ENEMY_CONFIGURATION_TABLE, $06
	LDA .LOWORD(MIRROR_ENEMY)
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC $06
	STA $06
	BRA @UNKNOWN116
@UNKNOWN115:
	LOADPTR ENEMY_CONFIGURATION_TABLE, $06
	LDX $02
	LDA a:battler::id,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC $06
	STA $06
@UNKNOWN116:
	SEP #PROC_FLAGS::ACCUM8
	LDY #$0045
	LDA [$06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @ACTION_PATTERN_1
	CMP #$0001
	BEQ @ACTION_PATTERN_2
	CMP #$0002
	BEQ @ACTION_PATTERN_3
	CMP #$0003
	BEQ @ACTION_PATTERN_4
	JMP a:.LOWORD(@UNKNOWN125)
@ACTION_PATTERN_1:
	JSL RAND
	AND #$0003
	STA $04
	STA $21
	JMP a:.LOWORD(@UNKNOWN125)
@ACTION_PATTERN_2:
	JSL RAND
	AND #$0007
	BEQ @ACTION_PATTERN_2_4TH
	CMP #$0001
	BEQ @ACTION_PATTERN_2_3RD
	CMP #$0002
	BEQ @ACTION_PATTERN_2_2ND
	CMP #$0003
	BEQ @ACTION_PATTERN_2_2ND
	BRA @ACTION_PATTERN_2_1ST
@ACTION_PATTERN_2_4TH:
	LDA #$0003
	STA $04
	STA $21
	BRA @UNKNOWN125
@ACTION_PATTERN_2_3RD:
	LDA #$0002
	STA $04
	STA $21
	BRA @UNKNOWN125
@ACTION_PATTERN_2_2ND:
	LDA #$0001
	STA $04
	STA $21
	BRA @UNKNOWN125
@ACTION_PATTERN_2_1ST:
	LDA #$0000
	STA $04
	STA $21
	BRA @UNKNOWN125
@ACTION_PATTERN_3:
	LDA $02
	CLC
	ADC #$0006
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM),X
	STA $16
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA $04
	STA $21
	SEP #PROC_FLAGS::ACCUM8
	LDA $16
	INC
	AND #$0003
	STA a:.LOWORD(RAM),X
	BRA @UNKNOWN125
@ACTION_PATTERN_4:
	.A16
	LDA $02
	CLC
	ADC #$0006
	TAX
	STX $31
	LDA a:.LOWORD(RAM),X
	AND #$00FF
	ASL
	STA $2F
	JSL RAND
	STA $04
	AND #$0001
	STA $02
	LDA $2F
	CLC
	ADC $02
	STA $04
	STA $21
	LDX $31
	SEP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM),X
	INC
	AND #$0001
	STA a:.LOWORD(RAM),X
@UNKNOWN125:
	REP #PROC_FLAGS::ACCUM8
	LDA $19
	STA $02
	INC
	INC
	INC
	INC
	STA $2F
	TAX
	LDA $21
	STA $04
	ASL
	CLC
	ADC #$0046
	LDY $06
	STY $0A
	LDY $08
	STY $0C
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	STA a:.LOWORD(RAM),X
	LDA $02
	CLC
	ADC #$0008
	TAX
	STX $31
	LDA $04
	CLC
	ADC #$0050
	CLC
	ADC $06
	STA $06
	SEP #PROC_FLAGS::ACCUM8
	LDA [$06]
	STA $00
	STA a:.LOWORD(RAM),X
	REP #PROC_FLAGS::ACCUM8
	LDA $2F
	TAX
	LDA a:.LOWORD(RAM),X
	CMP #BATTLE_ACTIONS::ENEMY_EXTENDER
	BNE @UNKNOWN127
	LDX $02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @UNKNOWN126
	LDX $02
	LDA a:battler::id,X
	CMP #PARTY_MEMBER::POO
	BNE @UNKNOWN126
	LDA $00
	AND #$00FF
	STA .LOWORD(MIRROR_ENEMY)
	JMP a:.LOWORD(@UNKNOWN114)
@UNKNOWN126:
	LDX $02
	LDA a:battler::current_action_argument,X
	AND #$00FF
	LDX $02
	STA a:battler::id,X
	JMP a:.LOWORD(@UNKNOWN114)
@UNKNOWN127:
	CMP #BATTLE_ACTIONS::STEAL
	BNE @UNKNOWN128
	JSL SELECT_STEALABLE_ITEM
	SEP #PROC_FLAGS::ACCUM8
	LDX $31
	STA a:.LOWORD(RAM),X
	LDX $02
	REP #PROC_FLAGS::ACCUM8
	STZ a:.LOWORD(RAM)+70,X
@UNKNOWN128:
	LDX $02
	LDA a:battler::current_action,X
	CMP #$0067
	BNE @NOT_DEFENDING
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	LDX $02
	STA a:battler::guarding,X
	BRA @UNKNOWN130
@NOT_DEFENDING:
	LDX $02
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::guarding,X
@UNKNOWN130:
	REP #PROC_FLAGS::ACCUM8
	LDA $02
	JSL CHOOSE_TARGET
@UNKNOWN131:
	LDA $02
	CLC
	ADC #.SIZEOF(battler)
	STA $02
	STA $19
	LDY $1F
	INY
	STY $1F
@UNKNOWN132:
	CPY #BATTLER_COUNT
	BCS @UNKNOWN133
	BEQ @UNKNOWN133
	JMP a:.LOWORD(@UNKNOWN108)
@UNKNOWN133:
	CREATE_WINDOW_FAR #WINDOW::TEXT_BATTLE
	LDA $1D
	CMP #INITIATIVE::ENEMIES_FIRST
	BNE @UNKNOWN134
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF78F7
@UNKNOWN134:
	LDA $27
	BNE @UNKNOWN135
	JMP a:.LOWORD(@UNKNOWN144)
@UNKNOWN135:
	LDY #.LOWORD(BATTLERS_TABLE)
	STY $2F
	STZ $1B
	LDA #$0000
	STA $04
	STA $21
	STA $02
	JMP a:.LOWORD(@UNKNOWN140)
@UNKNOWN136:
	LDA a:battler::consciousness,Y
	AND #$00FF
	BEQ @UNKNOWN139
	LDA a:battler::npc_id,Y
	AND #$00FF
	BNE @UNKNOWN139
	LDA a:battler::ally_or_enemy,Y
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN138
	LDA a:battler::id,Y
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::boss
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	BEQ @UNKNOWN137
	JMP a:.LOWORD(@UNKNOWN143)
@UNKNOWN137:
	LDY $2F
	LDA a:battler::afflictions,Y
	AND #$00FF
	TAX
	CPX #$0001
	BEQ @UNKNOWN139
	CPX #$0002
	BEQ @UNKNOWN139
	CPX #$0003
	BEQ @UNKNOWN139
	LDA a:battler::afflictions+2,Y
	AND #$00FF
	TAX
	CPX #$0001
	BEQ @UNKNOWN139
	CPX #$0003
	BEQ @UNKNOWN139
	CPX #$0004
	BEQ @UNKNOWN139
	LDA a:battler::speed,Y
	CMP $04
	BCC @UNKNOWN139
	BEQ @UNKNOWN139
	STA $04
	STA $21
	BRA @UNKNOWN139
@UNKNOWN138:
	LDA a:battler::speed,Y
	CMP $1B
	BCC @UNKNOWN139
	BEQ @UNKNOWN139
	STA $1B
@UNKNOWN139:
	TYA
	CLC
	ADC #.SIZEOF(battler)
	TAY
	STY $2F
	INC $02
@UNKNOWN140:
	LDA $02
	CMP #BATTLER_COUNT
	BCS @UNKNOWN141
	BEQ @UNKNOWN141
	JMP a:.LOWORD(@UNKNOWN136)
@UNKNOWN141:
	LDA $04
	BEQ @UNKNOWN142
	LDA $1D
	CMP #$0004
	BEQ @UNKNOWN142
	LDA $25
	STA $04
	ASL
	ASL
	ADC $04
	ASL
	CLC
	ADC $1B
	TAX
	STX $2F
	LDA $21
	STA $04
	TXA
	CMP $04
	BCC @UNKNOWN143
	LDA #$0064
	JSR a:.LOWORD(RAND_LIMIT)
	STA $27
	LDX $2F
	TXA
	SEC
	SBC $04
	STA $02
	LDA $27
	CMP $02
	BCS @UNKNOWN143
@UNKNOWN142:
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF84F3
	STZ $17
	JMP a:.LOWORD(@UNKNOWN237)
@UNKNOWN143:
	STZ $27
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF8511
@UNKNOWN144:
	STZ $1D
	JMP a:.LOWORD(@UNKNOWN234)
@UNKNOWN145:
	JSL CHECK_DEAD_PLAYERS
	LDA #$0000
	JSL COUNT_CHARS
	CMP #$0000
	BNE @UNKNOWN146
	JMP a:.LOWORD(@UNKNOWN225)
@UNKNOWN146:
	LDA #$0001
	JSL COUNT_CHARS
	CMP #$0000
	BNE @UNKNOWN147
	JMP a:.LOWORD(@UNKNOWN225)
@UNKNOWN147:
	LDA #$FFFF
	STA $04
	STA $21
	LDX #$0000
	TXA
	STA $31
	BRA @UNKNOWN150
@UNKNOWN148:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAY
	LDA .LOWORD(BATTLERS_TABLE)+battler::consciousness,Y
	AND #$00FF
	BEQ @UNKNOWN149
	LDA .LOWORD(BATTLERS_TABLE)+13,Y
	AND #$00FF
	BNE @UNKNOWN149
	LDA .LOWORD(BATTLERS_TABLE)+70,Y
	TAY
	STX $02
	TYA
	CMP $02
	BCC @UNKNOWN149
	LDA $31
	STA $04
	STA $21
	TYX
@UNKNOWN149:
	LDA $31
	INC
	STA $31
@UNKNOWN150:
	CMP #BATTLER_COUNT
	BCC @UNKNOWN148
	LDA $04
	CMP #$FFFF
	BNE @UNKNOWN151
	JMP a:.LOWORD(@UNKNOWN235)
@UNKNOWN151:
	JSL REDIRECT_C10FA3
	LDA $04
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
	STX .LOWORD(CURRENT_ATTACKER)
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA a:.LOWORD(RAM)+13,X
	LDX .LOWORD(CURRENT_ATTACKER)
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::afflictions+STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	TAX
	CPX #STATUS_0::UNCONSCIOUS
	BNE @UNKNOWN152
	JMP a:.LOWORD(@UNKNOWN234)
@UNKNOWN152:
	CPX #STATUS_0::DIAMONDIZED
	BNE @UNKNOWN153
	JMP a:.LOWORD(@UNKNOWN234)
@UNKNOWN153:
	CPX #STATUS_0::PARALYZED
	BEQ @UNKNOWN154
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::afflictions+STATUS_GROUP::TEMPORARY,X
	AND #$00FF
	CMP #STATUS_2::IMMOBILIZED
	BEQ @UNKNOWN154
	JMP a:.LOWORD(@UNKNOWN157)
@UNKNOWN154:
	LDX .LOWORD(CURRENT_ATTACKER)
	INX
	INX
	INX
	INX
	STX $2F
	LDA a:.LOWORD(RAM),X
	STA $31
	STA $04
	ASL
	ADC $04
	ASL
	ASL
	TAX
	INX
	INX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	CMP #$0003
	BEQ @UNKNOWN157
	LDA $31
	CMP #BATTLE_ACTIONS::PRAY
	BEQ @UNKNOWN157
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_1
	BEQ @UNKNOWN157
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_2
	BEQ @UNKNOWN157
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_3
	BEQ @UNKNOWN157
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_4
	BEQ @UNKNOWN157
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_5
	BEQ @UNKNOWN157
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_6
	BEQ @UNKNOWN157
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_7
	BEQ @UNKNOWN157
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_8
	BEQ @UNKNOWN157
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_9
	BEQ @UNKNOWN157
	CMP #BATTLE_ACTIONS::SPY
	BEQ @UNKNOWN157
	CMP #BATTLE_ACTIONS::MIRROR
	BEQ @UNKNOWN157
	CMP #BATTLE_ACTIONS::NO_EFFECT
	BEQ @UNKNOWN157
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::afflictions+STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::PARALYZED
	BNE @UNKNOWN155
	LDA #BATTLE_ACTIONS::ACTION_252
	LDX $2F
	STA a:.LOWORD(RAM),X
	BRA @UNKNOWN156
@UNKNOWN155:
	LDA #BATTLE_ACTIONS::ACTION_254
	LDX $2F
	STA a:.LOWORD(RAM),X
@UNKNOWN156:
	LDX .LOWORD(CURRENT_ATTACKER)
	SEP #PROC_FLAGS::ACCUM8
	STZ a:.LOWORD(RAM)+7,X
@UNKNOWN157:
	LDX .LOWORD(CURRENT_ATTACKER)
	REP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM)+31,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN158
	LDX .LOWORD(CURRENT_ATTACKER)
	INX
	INX
	INX
	INX
	LDA a:.LOWORD(RAM),X
	BEQ @UNKNOWN158
	LDA #BATTLE_ACTIONS::ACTION_253
	STA a:.LOWORD(RAM),X
	LDX .LOWORD(CURRENT_ATTACKER)
	SEP #PROC_FLAGS::ACCUM8
	STZ a:.LOWORD(RAM)+7,X
@UNKNOWN158:
	LDX .LOWORD(CURRENT_ATTACKER)
	REP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM)+31,X
	AND #$00FF
	CMP #$0004
	BNE @UNKNOWN159
	LDX .LOWORD(CURRENT_ATTACKER)
	INX
	INX
	INX
	INX
	LDA a:.LOWORD(RAM),X
	BEQ @UNKNOWN159
	LDA #BATTLE_ACTIONS::ACTION_255
	STA a:.LOWORD(RAM),X
	LDX .LOWORD(CURRENT_ATTACKER)
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::afflictions+STATUS_GROUP::TEMPORARY,X
	LDX .LOWORD(CURRENT_ATTACKER)
	STZ a:.LOWORD(RAM)+7,X
@UNKNOWN159:
	LDX .LOWORD(CURRENT_ATTACKER)
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::afflictions+STATUS_GROUP::CONCENTRATION,X
	AND #$00FF
	BEQ @UNKNOWN160
	LDX .LOWORD(CURRENT_ATTACKER)
	INX
	INX
	INX
	INX
	STX $2F
	LDA a:.LOWORD(RAM),X
	STA $31
	STA $04
	ASL
	ADC $04
	ASL
	ASL
	TAX
	INX
	INX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	CMP #$0003
	BNE @UNKNOWN160
	LDA $31
	BEQ @UNKNOWN160
	LDA #BATTLE_ACTIONS::ACTION_256
	LDX $2F
	STA a:.LOWORD(RAM),X
@UNKNOWN160:
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::afflictions+STATUS_GROUP::HOMESICKNESS,X
	AND #$00FF
	CMP #STATUS_5::HOMESICK
	BNE @UNKNOWN161
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::current_action,X
	BEQ @UNKNOWN161
	JSL RAND
	AND #$0007
	BNE @UNKNOWN161
	LDA #BATTLE_ACTIONS::ACTION_251
	LDX .LOWORD(CURRENT_ATTACKER)
	STA a:battler::current_action,X
	LDX .LOWORD(CURRENT_ATTACKER)
	SEP #PROC_FLAGS::ACCUM8
	STZ a:.LOWORD(RAM)+7,X
@UNKNOWN161:
	REP #PROC_FLAGS::ACCUM8
	LOADPTR BATTLE_ACTION_TABLE, $06
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::current_action,X
	STA $04
	ASL
	ADC $04
	ASL
	ASL
	STA $2F
	LDX $06
	STX $0A
	LDX $08
	STX $0C
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN163
	LDA $2F
	INC
	CLC
	ADC $06
	STA $06
	LDA [$06]
	AND #$00FF
	BNE @UNKNOWN163
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @UNKNOWN162
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	LDX .LOWORD(CURRENT_ATTACKER)
	STA a:.LOWORD(RAM)+9,X
	LDY #.SIZEOF(battler)
	REP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(CURRENT_ATTACKER)
	SEC
	SBC #.LOWORD(BATTLERS_TABLE)
	JSL DIVISION16S_DIVISOR_POSITIVE
	SEP #PROC_FLAGS::ACCUM8
	INC
	LDX .LOWORD(CURRENT_ATTACKER)
	STA a:battler::current_target,X
	BRA @UNKNOWN163
@UNKNOWN162:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0011
	LDX .LOWORD(CURRENT_ATTACKER)
	STA a:.LOWORD(RAM)+9,X
	LDY #.SIZEOF(battler)
	REP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(CURRENT_ATTACKER)
	SEC
	SBC #.LOWORD(BATTLERS_TABLE)
	JSL DIVISION16S_DIVISOR_POSITIVE
	TAX
	LDA .LOWORD(CURRENT_ATTACKER)
	JSL UNKNOWN_C4A228
@UNKNOWN163:
	LDX #$0000
	STX $2F
	REP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(CURRENT_ATTACKER)
	STA .LOWORD(CURRENT_TARGET)
	TXA
	JSL FIX_ATTACKER_NAME
	JSL FIX_TARGET_NAME
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::afflictions+STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::NAUSEOUS
	BEQ @UNKNOWN164
	CMP #STATUS_0::POISONED
	BEQ @UNKNOWN165
	CMP #STATUS_0::SUNSTROKE
	BEQ @UNKNOWN166
	CMP #STATUS_0::COLD
	BEQ @UNKNOWN167
	JMP a:.LOWORD(@UNKNOWN168)
@UNKNOWN164:
	LDA #$0014
	JSR a:.LOWORD(TWENTY_FIVE_PERCENT_VARIANCE)
	TAX
	STX $2F
	LOADPTR TEXT_BLOCK_EF7768, $0E
	TXA
	STA $06
	STZ $08
	LDA $06
	STA $12
	LDA $08
	STA $14
	JSL DISPLAY_TEXT_WAIT
	BRA @UNKNOWN168
@UNKNOWN165:
	LDA #$0014
	JSR a:.LOWORD(TWENTY_FIVE_PERCENT_VARIANCE)
	TAX
	STX $2F
	LOADPTR TEXT_BLOCK_EF7787, $0E
	TXA
	STA $06
	STZ $08
	LDA $06
	STA $12
	LDA $08
	STA $14
	JSL DISPLAY_TEXT_WAIT
	BRA @UNKNOWN168
@UNKNOWN166:
	LDA #$0004
	JSR a:.LOWORD(TWENTY_FIVE_PERCENT_VARIANCE)
	TAX
	STX $2F
	LOADPTR TEXT_BLOCK_EF77B1, $0E
	TXA
	STA $06
	STZ $08
	LDA $06
	STA $12
	LDA $08
	STA $14
	JSL DISPLAY_TEXT_WAIT
	BRA @UNKNOWN168
@UNKNOWN167:
	LDA #$0004
	JSR a:.LOWORD(TWENTY_FIVE_PERCENT_VARIANCE)
	TAX
	STX $2F
	LOADPTR TEXT_BLOCK_EF77DB, $0E
	TXA
	STA $06
	STZ $08
	LDA $06
	STA $12
	LDA $08
	STA $14
	JSL DISPLAY_TEXT_WAIT
@UNKNOWN168:
	LDX $2F
	LDA .LOWORD(CURRENT_ATTACKER)
	JSL LOSE_HP_STATUS
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::hp,X
	BNE @UNKNOWN171
	LDA .LOWORD(CURRENT_ATTACKER)
	JSL KO_TARGET
	LDA #$0000
	JSL COUNT_CHARS
	CMP #$0000
	BNE @UNKNOWN169
	JMP a:.LOWORD(@UNKNOWN225)
@UNKNOWN169:
	LDA #$0001
	JSL COUNT_CHARS
	CMP #$0000
	BEQ @UNKNOWN170
	JMP a:.LOWORD(@UNKNOWN234)
@UNKNOWN170:
	JMP a:.LOWORD(@UNKNOWN225)
@UNKNOWN171:
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN172
	LDA .LOWORD(CURRENT_ATTACKER)
	JSL CHOOSE_TARGET
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::current_action,X
	CMP #$0042
	BNE @UNKNOWN172
	JSL SELECT_STEALABLE_ITEM
	SEP #PROC_FLAGS::ACCUM8
	LDX .LOWORD(CURRENT_ATTACKER)
	STA a:battler::current_action_argument,X
@UNKNOWN172:
	REP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(CURRENT_ATTACKER)
	JSL UNKNOWN_C24703
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @UNKNOWN174
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::current_action,X
	STA $04
	ASL
	ADC $04
	ASL
	ASL
	TAX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	BNE @UNKNOWN174
	JSL UNKNOWN_C2416F
	LDA #$0000
	STA $0A
	LDA #$0000
	STA $0C
	LDA .LOWORD(BATTLER_TARGET_FLAGS)
	STA $06
	LDA .LOWORD(BATTLER_TARGET_FLAGS)+2
	STA $08
	CMP $0C
	BNE @UNKNOWN173
	LDA $06
	CMP $0A
@UNKNOWN173:
	BNE @UNKNOWN174
	LDA .LOWORD(CURRENT_ATTACKER)
	JSL CHOOSE_TARGET
	LDA .LOWORD(CURRENT_ATTACKER)
	JSL UNKNOWN_C24703
	JSL UNKNOWN_C2416F
@UNKNOWN174:
	LDY #$0000
	STY $31
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::afflictions+STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::MUSHROOMIZED
	BNE @UNKNOWN175
	LDA #100
	JSR a:.LOWORD(RAND_LIMIT)
	CMP #MUSHROOMIZED_TARGET_CHANGE_CHANCE
	BCC @UNKNOWN176
@UNKNOWN175:
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::afflictions+STATUS_GROUP::STRANGENESS,X
	AND #$00FF
	CMP #STATUS_3::STRANGE
	BNE @UNKNOWN179
@UNKNOWN176:
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::current_action,X
	STA $04
	ASL
	ADC $04
	ASL
	ASL
	TAX
	INX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	BEQ @UNKNOWN179
	LDY #$0001
	STY $31
@UNKNOWN177:
	JSR a:.LOWORD(FEELING_STRANGE_RETARGETTING)
	JSL UNKNOWN_C2416F
	LDA #$0000
	STA $0A
	LDA #$0000
	STA $0C
	LDA .LOWORD(BATTLER_TARGET_FLAGS)
	STA $06
	LDA .LOWORD(BATTLER_TARGET_FLAGS)+2
	STA $08
	CMP $0C
	BNE @UNKNOWN178
	LDA $06
	CMP $0A
@UNKNOWN178:
	BEQ @UNKNOWN177
@UNKNOWN179:
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::current_action,X
	CMP #BATTLE_ACTIONS::STEAL
	BNE @UNKNOWN180
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::current_action_argument,X
	AND #$00FF
	JSL UNKNOWN_C24348
	CMP #$0000
	BNE @UNKNOWN180
	LDX .LOWORD(CURRENT_ATTACKER)
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::current_action_argument,X
@UNKNOWN180:
	REP #PROC_FLAGS::ACCUM8
	LDA #$0000
	JSL FIX_ATTACKER_NAME
	LDX .LOWORD(CURRENT_ATTACKER)
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::current_action_argument,X
	JSL REDIRECT_C1ACF8
	JSL UNKNOWN_C23E32
	.A16
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @UNKNOWN185
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::id,X
	CMP #PLAYER_CHAR_COUNT
	BEQ @UNKNOWN181
	BCS @UNKNOWN185
@UNKNOWN181:
	LDX #$0000
	STX $2F
	BRA @UNKNOWN184
@UNKNOWN182:
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::id,X
	STA $02
	LDX $2F
	LDA .LOWORD(GAME_STATE)+122,X
	AND #$00FF
	CMP $02
	BNE @UNKNOWN183
	TXA
	JSL REDIRECT_C43573
	BRA @UNKNOWN185
@UNKNOWN183:
	INX
	STX $2F
@UNKNOWN184:
	CPX #$0006
	BCC @UNKNOWN182
@UNKNOWN185:
	.A16
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::current_action,X
	STA $04
	ASL
	ADC $04
	ASL
	ASL
	TAX
	INX
	INX
	INX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	BEQ @UNKNOWN187
	AND #$00FF
	LDX .LOWORD(CURRENT_ATTACKER)
	CMP a:battler::pp_target,X
	BCC @UNKNOWN186
	BEQ @UNKNOWN186
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_C8FAB8
	JMP a:.LOWORD(@UNKNOWN215)
@UNKNOWN186:
	TAX
	LDA .LOWORD(CURRENT_ATTACKER)
	JSL UNKNOWN_C2BCB9
@UNKNOWN187:
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN194
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::current_action,X
	BEQ @UNKNOWN194
	STA $04
	ASL
	ADC $04
	ASL
	ASL
	TAX
	INX
	INX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN188
	CMP #$0002
	BEQ @UNKNOWN188
	CMP #$0003
	BEQ @UNKNOWN189
	CMP #$0005
	BEQ @UNKNOWN190
	BRA @UNKNOWN191
@UNKNOWN188:
	LDA #$0001
	JSL UNKNOWN_C2FEF9
	BRA @UNKNOWN191
@UNKNOWN189:
	LDA #$0002
	JSL UNKNOWN_C2FEF9
	BRA @UNKNOWN191
@UNKNOWN190:
	LDA #$0003
	JSL UNKNOWN_C2FEF9
@UNKNOWN191:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$000C
	LDX .LOWORD(CURRENT_ATTACKER)
	STA a:.LOWORD(RAM)+73,X
	LDX #$0000
	STX $1F
	BRA @UNKNOWN193
@UNKNOWN192:
	JSL UNKNOWN_C12DD5
	LDX $1F
	INX
	STX $1F
@UNKNOWN193:
	CPX #$000C
	BCC @UNKNOWN192
@UNKNOWN194:
	LDY $31
	BEQ @UNKNOWN196
	LDX .LOWORD(CURRENT_ATTACKER)
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::afflictions+STATUS_GROUP::STRANGENESS,X
	AND #$00FF
	CMP #STATUS_3::STRANGE
	BNE @UNKNOWN195
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF845D
@UNKNOWN195:
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::afflictions+STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::MUSHROOMIZED
	BNE @UNKNOWN196
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF8477
@UNKNOWN196:
	REP #PROC_FLAGS::ACCUM8
	LOADPTR BATTLE_ACTION_TABLE, $0A
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::current_action,X
	STA $04
	ASL
	ADC $04
	ASL
	ASL
	INC
	INC
	INC
	INC
	CLC
	ADC $0A
	STA $0A
	LDY #$0002
	LDA [$0A],Y
	TAY
	LDA [$0A]
	STA $06
	STY $08
	LDA $06
	STA $0E
	LDA $08
	STA $10
	JSL UNKNOWN_C1DD9F
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::current_action,X
	BNE @UNKNOWN197
	JMP a:.LOWORD(@UNKNOWN215)
@UNKNOWN197:
	BRA @UNKNOWN199
@UNKNOWN198:
	JSL UNKNOWN_C12DD5
@UNKNOWN199:
	JSL UNKNOWN_C2EACF
	CMP #$0000
	BNE @UNKNOWN198
	LDY #$0000
	STY $1B
	JMP a:.LOWORD(@UNKNOWN214)
@UNKNOWN200:
	TYA
	JSL IS_CHAR_TARGETTED
	CMP #$0000
	BNE @UNKNOWN201
	JMP a:.LOWORD(@UNKNOWN213)
@UNKNOWN201:
	LDY $1B
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	STA .LOWORD(CURRENT_TARGET)
	JSL FIX_TARGET_NAME
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::afflictions+STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BNE @UNKNOWN204
	LDA #$0000
	STA $2F
	BRA @UNKNOWN203
@UNKNOWN202:
	TXA
	LDX .LOWORD(CURRENT_ATTACKER)
	CMP a:battler::current_action,X
	BEQ @UNKNOWN204
	LDA $2F
	INC
	STA $2F
@UNKNOWN203:
	ASL
	TAX
	LDA f:DEAD_TARGETTABLE_ACTIONS,X
	TAX
	BNE @UNKNOWN202
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF76FD
	JMP a:.LOWORD(@UNKNOWN213)
@UNKNOWN204:
	LOADPTR BATTLE_ACTION_TABLE, $0A
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::current_action,X
	STA $04
	ASL
	ADC $04
	ASL
	ASL
	CLC
	ADC #$0008
	CLC
	ADC $0A
	STA $0A
	LDY #$0002
	LDA [$0A],Y
	TAY
	LDA [$0A]
	STA $06
	STY $08
	LDA #$0000
	STA $0A
	LDA #$0000
	STA $0C
	LDA $08
	CMP $0C
	BNE @UNKNOWN205
	LDA $06
	CMP $0A
@UNKNOWN205:
	BEQ @UNKNOWN213
	PHA
	LDA $06
	STA a:.LOWORD(UNKNOWN_7E00BC)
	LDA $08
	STA a:.LOWORD(UNKNOWN_7E00BE)
	PLA
	JSL UNKNOWN_C09279
	JSL CHECK_DEAD_PLAYERS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA .LOWORD(UNKNOWN_7E9623)
	REP #PROC_FLAGS::ACCUM8
	LDA #$0000
	JSL COUNT_CHARS
	CMP #$0000
	BEQ @UNKNOWN206
	LDA #$0001
	JSL COUNT_CHARS
	CMP #$0000
	BNE @UNKNOWN207
@UNKNOWN206:
	JSL UNKNOWN_C2437E
	JMP a:.LOWORD(@UNKNOWN225)
@UNKNOWN207:
	LDA .LOWORD(UNKNOWN_7EAA0E)
	CMP #$0003
	BEQ @UNKNOWN208
	CMP #$0002
	BEQ @UNKNOWN209
	CMP #$0001
	BEQ @UNKNOWN210
	BRA @UNKNOWN212
@UNKNOWN208:
	STZ $17
	JMP a:.LOWORD(@UNKNOWN237)
@UNKNOWN209:
	JSL UNKNOWN_C2437E
	JMP a:.LOWORD(@ENEMIES_ARE_DEAD)
@UNKNOWN210:
	LDA #$0002
	STA $17
	JMP a:.LOWORD(@UNKNOWN237)
@UNKNOWN211:
	JSL UNKNOWN_C12DD5
@UNKNOWN212:
	LDA .LOWORD(UNKNOWN_7EAD90)
	BNE @UNKNOWN211
@UNKNOWN213:
	LDY $1B
	INY
	STY $1B
@UNKNOWN214:
	CPY #BATTLER_COUNT
	BCS @UNKNOWN215
	BEQ @UNKNOWN215
	JMP a:.LOWORD(@UNKNOWN200)
@UNKNOWN215:
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @UNKNOWN217
	JSL UNKNOWN_C2437E
	LDA .LOWORD(MIRROR_ENEMY)
	BEQ @UNKNOWN216
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::id,X
	CMP #PARTY_MEMBER::POO
	BNE @UNKNOWN216
	LDX .LOWORD(MIRROR_TURN_TIMER)
	DEX
	STX .LOWORD(MIRROR_TURN_TIMER)
	BNE @UNKNOWN216
	STZ .LOWORD(MIRROR_ENEMY)
	LDA .LOWORD(CURRENT_ATTACKER)
	STA $06
	PHB
	SEP #PROC_FLAGS::ACCUM8
	PLA
	STA $08
	STZ $09
	REP #PROC_FLAGS::ACCUM8
	LDA $06
	STA $0E
	LDA $08
	STA $10
	LDA #$AA14
	STA $06
	PHB
	SEP #PROC_FLAGS::ACCUM8
	PLA
	STA $08
	STZ $09
	REP #PROC_FLAGS::ACCUM8
	LDA $06
	STA $12
	LDA $08
	STA $14
	JSL COPY_MIRROR_DATA
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF7142
@UNKNOWN216:
	JSL REDIRECT_C3E6F8
@UNKNOWN217:
	JSL CHECK_DEAD_PLAYERS
	LDA .LOWORD(CURRENT_ATTACKER)
	STA .LOWORD(CURRENT_TARGET)
	JSL FIX_TARGET_NAME
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:battler::afflictions+STATUS_GROUP::TEMPORARY,X
	AND #$00FF
	CMP #STATUS_2::ASLEEP
	BEQ @UNKNOWN218
	CMP #STATUS_2::IMMOBILIZED
	BEQ @UNKNOWN219
	CMP #STATUS_2::SOLIDIFIED
	BEQ @UNKNOWN220
	BRA @UNKNOWN221
@UNKNOWN218:
	JSL RAND
	AND #$0003
	BNE @UNKNOWN221
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF6F54
	LDX .LOWORD(CURRENT_ATTACKER)
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::afflictions+STATUS_GROUP::TEMPORARY,X
	BRA @UNKNOWN221
@UNKNOWN219:
	.A16
	LDA #100
	JSR a:.LOWORD(RAND_LIMIT)
	CMP #100-CHANCE_OF_BODY_MOVING_AGAIN
	BCS @UNKNOWN221
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF6EED
	LDX .LOWORD(CURRENT_ATTACKER)
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::afflictions+STATUS_GROUP::TEMPORARY,X
	BRA @UNKNOWN221
@UNKNOWN220:
	;.A16
	LDA #$000B
	ADC $A90E85
	SBC $108500
	JSL DISPLAY_IN_BATTLE_TEXT
	LDX .LOWORD(CURRENT_ATTACKER)
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::afflictions+STATUS_GROUP::TEMPORARY,X
@UNKNOWN221:
	REP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(CURRENT_ATTACKER)
	CLC
	ADC #battler::afflictions+STATUS_GROUP::CONCENTRATION
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM),X
	STA $16
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @UNKNOWN222
	SEP #PROC_FLAGS::ACCUM8
	LDA $16
	DEC
	STA a:.LOWORD(RAM),X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @UNKNOWN222
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF6F64
@UNKNOWN222:
	LDA #.LOWORD(BATTLERS_TABLE)
	LDX #$0000
	STX $31
	BRA @UNKNOWN224
@UNKNOWN223:
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::id2,X
	CLC
	REP #PROC_FLAGS::ACCUM8
	ADC #.SIZEOF(battler)
	LDX $31
	INX
	STX $31
@UNKNOWN224:
	CPX #BATTLER_COUNT
	BCC @UNKNOWN223
	JSL CHECK_DEAD_PLAYERS
	JSL REDIRECT_SHOW_HPPP_WINDOWS
@UNKNOWN225:
	LDA #$0000
	JSL COUNT_CHARS
	CMP #$0000
	BNE @ALLIES_ARE_ALIVE
	LDA #$0001
	STA $17
	JSL UNKNOWN_C20F9A
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF7A4D
	LDA #$0001
	STA $23
@ALLIES_ARE_ALIVE:
	LDA #$0001
	JSL COUNT_CHARS
	CMP #$0000
	BEQ @ENEMIES_ARE_DEAD
	JMP a:.LOWORD(@UNKNOWN234)
@ENEMIES_ARE_DEAD:
	STZ $17
	JSL UNKNOWN_C20F9A
	LDA #$0001
	STA .LOWORD(UNKNOWN_7EADB6)
	STA .LOWORD(UNKNOWN_7EADD0)
	LDY #$98B9
	STY $2F
	LDA .LOWORD(BATTLE_MONEY_SCRATCH)
	STA $06
	STZ $08
	LDA $06
	STA $0E
	LDA $08
	STA $10
	JSL DEPOSIT_INTO_ATM
	LDA $06
	STA $0A
	LDA $08
	STA $0C
	LDY $2F
	LDA a:.LOWORD(RAM),Y
	STA $06
	LDA a:.LOWORD(RAM)+2,Y
	STA $08
	CLC
	LDA $06
	ADC $0A
	STA $06
	LDA $08
	ADC $0C
	STA $08
	LDA $06
	STA a:.LOWORD(RAM),Y
	LDA $08
	STA a:.LOWORD(RAM)+2,Y
	LDA #$0000
	JSL COUNT_CHARS
	DEC
	STA $0A
	STZ $0C
	LDA .LOWORD(BATTLE_EXP_SCRATCH)
	STA $06
	LDA .LOWORD(BATTLE_EXP_SCRATCH)+2
	STA $08
	CLC
	LDA $06
	ADC $0A
	STA $06
	LDA $08
	ADC $0C
	STA $08
	LDA $06
	STA .LOWORD(BATTLE_EXP_SCRATCH)
	LDA $08
	STA .LOWORD(BATTLE_EXP_SCRATCH)+2
	LDA #$0000
	JSL COUNT_CHARS
	STA $0A
	STZ $0C
	JSL DIVISION32
	LDA $06
	STA .LOWORD(BATTLE_EXP_SCRATCH)
	LDA $08
	STA .LOWORD(BATTLE_EXP_SCRATCH)+2
	LDA .LOWORD(CURRENT_BATTLE_GROUP)
	CMP #$01C0
	BCC @NOT_BOSS_BATTLE
	LOADPTR TEXT_BLOCK_EF7A14, $0E
	LDA $06
	STA $12
	LDA $08
	STA $14
	JSL DISPLAY_TEXT_WAIT
	BRA @SKIP_NOT_BOSS_BATTLE
@NOT_BOSS_BATTLE:
	LOADPTR TEXT_BLOCK_EF79D7, $0E
	LDA $06
	STA $12
	LDA $08
	STA $14
	JSL DISPLAY_TEXT_WAIT
@SKIP_NOT_BOSS_BATTLE:
	LDA .LOWORD(ITEM_DROPPED)
	BEQ @UNKNOWN230
	SEP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(ITEM_DROPPED)
	JSL REDIRECT_C1ACF8
	.A16
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF7BDF
@UNKNOWN230:
	LDY #.LOWORD(BATTLERS_TABLE)
	STY $31
	LDA #$0000
	STA $02
	BRA @UNKNOWN233
@UNKNOWN231:
	LDA a:battler::consciousness,Y
	AND #$00FF
	BEQ @UNKNOWN232
	LDA a:battler::ally_or_enemy,Y
	AND #$00FF
	BNE @UNKNOWN232
	LDA a:battler::npc_id,Y
	AND #$00FF
	BNE @UNKNOWN232
	LDA a:battler::afflictions,Y
	AND #$00FF
	TAX
	CPX #STATUS_0::UNCONSCIOUS
	BEQ @UNKNOWN232
	CPX #STATUS_0::DIAMONDIZED
	BEQ @UNKNOWN232
	LDA .LOWORD(BATTLE_EXP_SCRATCH)
	STA $06
	LDA .LOWORD(BATTLE_EXP_SCRATCH)+2
	STA $08
	LDA $06
	STA $0E
	LDA $08
	STA $10
	LDX #$0001
	LDA a:battler::id,Y
	JSL GAIN_EXP
@UNKNOWN232:
	LDY $31
	TYA
	CLC
	ADC #.SIZEOF(battler)
	TAY
	STY $31
	INC $02
@UNKNOWN233:
	LDA $02
	CMP #BATTLER_COUNT
	BCC @UNKNOWN231
	LDA #$0001
	STA $23
@UNKNOWN234:
	LDA $23
	BNE @UNKNOWN235
	JMP a:.LOWORD(@UNKNOWN145)
@UNKNOWN235:
	JSL REDIRECT_CLOSE_FOCUS_WINDOW
@UNKNOWN236:
	LDA $23
	BNE @UNKNOWN237
	JMP a:.LOWORD(@UNKNOWN71)
@UNKNOWN237:
	JSL UNKNOWN_C20F9A
@UNKNOWN238:
	JSL UNKNOWN_C12DD5
	JSL UNKNOWN_C2108C
	CMP #$0000
	BEQ @UNKNOWN238
	LDA .LOWORD(MIRROR_ENEMY)
	BNE @UNKNOWN239
	JMP a:.LOWORD(@UNKNOWN243)
@UNKNOWN239:
	LDA #.LOWORD(BATTLERS_TABLE)
	STA $2F
	LDX #$0000
	STX $25
	JMP a:.LOWORD(@UNKNOWN242)
@UNKNOWN240:
	TAX
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @UNKNOWN241
	LDA $2F
	TAX
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @UNKNOWN241
	LDA $2F
	TAX
	LDA a:battler::id,X
	CMP #PARTY_MEMBER::POO
	BNE @UNKNOWN241
	STZ .LOWORD(MIRROR_ENEMY)
	LDA $2F
	CLC
	ADC #battler::afflictions
	TAX
	STX $25
	LDA a:.LOWORD(RAM),X
	AND #$00FF
	STA $04
	STA $21
	LDA $2F
	STA $06
	PHB
	SEP #PROC_FLAGS::ACCUM8
	PLA
	STA $08
	STZ $09
	REP #PROC_FLAGS::ACCUM8
	LDA $06
	STA $0E
	LDA $08
	STA $10
	LDA #$AA14
	STA $06
	PHB
	SEP #PROC_FLAGS::ACCUM8
	PLA
	STA $08
	STZ $09
	REP #PROC_FLAGS::ACCUM8
	LDA $06
	STA $12
	LDA $08
	STA $14
	JSL COPY_MIRROR_DATA
	LDA $04
	SEP #PROC_FLAGS::ACCUM8
	LDX $25
	STA a:.LOWORD(RAM),X
	JSL CHECK_DEAD_PLAYERS
	BRA @UNKNOWN243
@UNKNOWN241:
	.A16
	LDA $2F
	CLC
	ADC #.SIZEOF(battler)
	STA $2F
	LDX $25
	INX
	STX $25
@UNKNOWN242:
	CPX #BATTLER_COUNT
	BCS @UNKNOWN243
	BEQ @UNKNOWN243
	JMP a:.LOWORD(@UNKNOWN240)
@UNKNOWN243:
	JSL RESET_POST_BATTLE_STATS
	SEP #PROC_FLAGS::ACCUM8
	STZ .LOWORD(GAME_STATE)+game_state::auto_fight_enable
	REP #PROC_FLAGS::ACCUM8
	STZ .LOWORD(BATTLE_MODE_FLAG)
	LDA .LOWORD(BATTLE_DEBUG)
	BNE @UNKNOWN244
	JMP a:.LOWORD(@UNKNOWN2)
@UNKNOWN244:
	LDX #$0001
	TXA
	JSL UNKNOWN_C0887A
	BRA @UNKNOWN246
@UNKNOWN245:
	JSL READ_JOYPAD
	JSL UNKNOWN_C2DB3F
@UNKNOWN246:
	LDA a:.LOWORD(UNKNOWN_7E0028)
	AND #$00FF
	BNE @UNKNOWN245
	JSL UNKNOWN_C20293
	JSL UNKNOWN_C08726
	JSL UNKNOWN_C1DD5F
	JSL UNKNOWN_C2E0E7
	LDA $17
	PLD
	RTL
