
MISS_CALC:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16 "MISS_CHANCE"
	STACK_RESERVE_INT16 "MISS_MESSAGE"
	STACK_RESERVE_PARAM_INT16 ;int missMessage
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	TAY
	STY @MISS_MESSAGE
	LDX CURRENT_ATTACKER
	LDA __BSS_START__+14,X
	AND #$00FF
	BNEL @UNKNOWN5
	LDX CURRENT_ATTACKER
	LDA __BSS_START__+15,X
	AND #$00FF
	BNEL @UNKNOWN5
	LDX CURRENT_ATTACKER
	LDA __BSS_START__+16,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	BEQ @UNKNOWN2
	DEC
	STA @VIRTUAL02
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	TAX
	STX @MISS_CHANCE
	BRA @UNKNOWN3
@UNKNOWN2:
	LDX #1
	STX @MISS_CHANCE
@UNKNOWN3:
	LDX CURRENT_ATTACKER
	LDA __BSS_START__ + battler::afflictions + STATUS_GROUP::TEMPORARY,X
	AND #$00FF
	CMP #STATUS_2::CRYING
	BEQ @UNKNOWN4
	LDX CURRENT_ATTACKER
	LDA __BSS_START__ + battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::NAUSEOUS
	BNE @UNKNOWN6
@UNKNOWN4:
	LDX @MISS_CHANCE
	TXA
	CLC
	ADC #8 ;miss chance + 1/2
	TAX
	STX @MISS_CHANCE
	BRA @UNKNOWN6
@UNKNOWN5:
	LDX CURRENT_ATTACKER
	LDA __BSS_START__,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::miss_rate
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	TAX
	STX @MISS_CHANCE
@UNKNOWN6:
	LDX @MISS_CHANCE
	BEQ @UNKNOWN9
	LDA #16
	JSR RAND_LIMIT
	STA @VIRTUAL02
	LDX @MISS_CHANCE
	TXA
	DEC
	CMP @VIRTUAL02
	BCC @UNKNOWN9
	LDY @MISS_MESSAGE
	BEQ @UNKNOWN7
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KARABURI_UTSU
	BRA @UNKNOWN8
@UNKNOWN7:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KARABURI
@UNKNOWN8:
	LDA #1
	BRA @UNKNOWN10
@UNKNOWN9:
	LDA #0
@UNKNOWN10:
	END_C_FUNCTION
