
PICK_TARGET:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @VIRTUAL02
	TXY
	TAX
	BEQ @UNKNOWN0
	TYA
	JSR PICK_TARGET_ROW
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX @VIRTUAL02
	TYA
	JSR PICK_TARGET_SINGLE
@UNKNOWN1:
	END_C_FUNCTION
