
RENDER_BATTLE_SPRITE_ROW:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL04
	LDA #.LOWORD(BATTLERS_TABLE) + .SIZEOF(battler) * 8
	STA @VIRTUAL02
	LDA #8
	STA @VIRTUAL04
	STA @LOCAL03
	JMP @UNKNOWN12
@UNKNOWN0:
	LDX @VIRTUAL02
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQL @UNKNOWN11
	LDX @VIRTUAL02
	LDA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #1
	BEQL @UNKNOWN11
	LDX @VIRTUAL02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNEL @UNKNOWN11
	LDX @VIRTUAL02
	LDA a:battler::row,X
	AND #$00FF
	CMP @LOCAL04
	BNEL @UNKNOWN11
	LDX @VIRTUAL02
	LDA a:battler::sprite,X
	BEQL @UNKNOWN11
	LDA @VIRTUAL02
	CLC
	ADC #battler::unknown72
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @UNKNOWN6
	SEP #PROC_FLAGS::ACCUM8
	DEC
	STA __BSS_START__,X
	LDY #3
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	JSL DIVISION16
	AND #$0001
	BNEL @UNKNOWN11
@UNKNOWN6:
	LDA @VIRTUAL02
	CLC
	ADC #battler::unknown73
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @UNKNOWN7
	SEP #PROC_FLAGS::ACCUM8
	DEC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	AND #$0004
	BNE @UNKNOWN7
	LDX @VIRTUAL02
	LDA a:battler::sprite_y,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_VERTICAL_OFFSET
	TAY
	LDX @VIRTUAL02
	LDA a:battler::sprite_x,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_HORIZONTAL_OFFSET
	TAX
	STX @LOCAL02
	LDX @VIRTUAL02
	LDA a:battler::vram_sprite_index,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 80
	CLC
	ADC #.LOWORD(ALT_BATTLE_SPRITEMAPS)
	LDX @LOCAL02
	JSL UNKNOWN_C08CD5
	JMP @UNKNOWN11
@UNKNOWN7:
	LDX @VIRTUAL02
	LDA a:battler::use_alt_spritemap,X
	AND #$00FF
	BEQ @UNKNOWN8
	LDX @VIRTUAL02
	LDA a:battler::sprite_y,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_VERTICAL_OFFSET
	TAY
	LDX @VIRTUAL02
	LDA a:battler::sprite_x,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_HORIZONTAL_OFFSET
	TAX
	STX @LOCAL01
	LDX @VIRTUAL02
	LDA a:battler::vram_sprite_index,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 80
	CLC
	ADC #.LOWORD(ALT_BATTLE_SPRITEMAPS)
	LDX @LOCAL01
	JSL UNKNOWN_C08CD5
	JMP @UNKNOWN11
@UNKNOWN8:
	LDA ENEMY_TARGETTING_FLASHING
	BEQ @UNKNOWN10
	LDX @VIRTUAL02
	LDA a:battler::unknown74,X
	AND #$00FF
	BEQ @UNKNOWN9
	LDA FRAME_COUNTER
	AND #$00FF
	AND #$0008
	BEQ @UNKNOWN10
@UNKNOWN9:
	LDX @VIRTUAL02
	LDA a:battler::sprite_y,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_VERTICAL_OFFSET
	TAY
	LDX @VIRTUAL02
	LDA a:battler::sprite_x,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_HORIZONTAL_OFFSET
	TAX
	STX @LOCAL02
	LDX @VIRTUAL02
	LDA a:battler::vram_sprite_index,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 80
	CLC
	ADC #.LOWORD(ALT_BATTLE_SPRITEMAPS)
	LDX @LOCAL02
	JSL UNKNOWN_C08CD5
	BRA @UNKNOWN11
@UNKNOWN10:
	LDX @VIRTUAL02
	LDA a:battler::sprite_y,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_VERTICAL_OFFSET
	TAY
	LDX @VIRTUAL02
	LDA a:battler::sprite_x,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_HORIZONTAL_OFFSET
	TAX
	STX @LOCAL00
	LDX @VIRTUAL02
	LDA a:battler::vram_sprite_index,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 80
	CLC
	ADC #.LOWORD(BATTLE_SPRITEMAPS)
	LDX @LOCAL00
	JSL UNKNOWN_C08CD5
@UNKNOWN11:
	LDA @VIRTUAL02
	CLC
	ADC #.SIZEOF(battler)
	STA @VIRTUAL02
	LDA @LOCAL03
	STA @VIRTUAL04
	INC @VIRTUAL04
	LDA @VIRTUAL04
	STA @LOCAL03
@UNKNOWN12:
	LDA @VIRTUAL04
	CMP #BATTLER_COUNT
	BCCL @UNKNOWN0
	END_C_FUNCTION
