
SUCCESS_255: ;$C26BB8
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 14
	SEP #PROC_FLAGS::ACCUM8
	STA $00
	JSR a:.LOWORD(RAND_LONG)
	CMP $00
	BCS @UNKNOWN0
	REP #PROC_FLAGS::ACCUM8
	LDA #$0001
	BRA @UNKNOWN1
@UNKNOWN0:
	REP #PROC_FLAGS::ACCUM8
	LDA #$0000
@UNKNOWN1:
	PLD
	RTS
