
SUCCESS_LUCK80: ;$C27C96
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA #$0050
	JSR RAND_LIMIT
	LDX CURRENT_TARGET
	CMP a:battler::luck,X
	BCS @SUCCESS
	LDA #$0000
	BRA @RETURN
@SUCCESS:
	LDA #$0001
@RETURN:
	RTS
