
SET_LAYER_CONFIG:
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:LAYER_CONFIG,X
	STA TM_MIRROR
	LDA f:LAYER_CONFIG+11,X
	STA TD_MIRROR
	LDA f:LAYER_CONFIG+21,X
	STA f:CGWSEL
	LDA f:LAYER_CONFIG+31,X
	STA f:CGADSUB
	REP #PROC_FLAGS::ACCUM8
	RTL
