
; args - A - direction, X surface flags
ADJUST_POSITION_VERTICAL: ;$C03017
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	TAY
	MOVE_INT $22, $06
	MOVE_INT $06, $10
	TXA
	AND #SURFACE_FLAGS::DEEP_WATER
	CMP #SURFACE_FLAGS::SHALLOW_WATER
	BEQ @IN_SHALLOW_WATER
	CMP #SURFACE_FLAGS::DEEP_WATER
	BNE @NOT_IN_WATER_IF
	JMP @IN_DEEP_WATER
@NOT_IN_WATER_IF:
	JMP @NOT_IN_WATER
@IN_SHALLOW_WATER:
	TYA
	ASL
	ASL
	STA $02
	LDA .LOWORD(GAME_STATE)+game_state::walking_style
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC $02
	CLC
	ADC #.LOWORD(UNKNOWN_7E4F96)
	TAY
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $06
	ASR8_INT $06
	MOVE_INT $06, $0A
	MOVE_INT $0A, $06
	MOVE_INT_CONSTANT SHALLOW_WATER_SPEED, $0A
	JSL MULT32
	MOVE_INT $06, $0A
	MOVE_INT $10, $06
	PHA
	LDA $06
	PHA
	MOVE_INT $0A, $06
	ASR8_INT $06
	PULL32 $0A
	CLC
	ADD_INT_ASSIGN $06, $0A
	MOVE_INT $06, $1A
	JMP @UNKNOWN14
@IN_DEEP_WATER:
	TYA
	ASL
	ASL
	STA $02
	LDA .LOWORD(GAME_STATE)+game_state::walking_style
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC $02
	CLC
	ADC #.LOWORD(UNKNOWN_7E4F96)
	TAY
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $06
	ASR8_INT $06
	MOVE_INT $06, $0A
	MOVE_INT $0A, $06
	MOVE_INT_CONSTANT DEEP_WATER_SPEED, $0A
	JSL MULT32
	MOVE_INT $06, $0A
	MOVE_INT $10, $06
	PHA
	LDA $06
	PHA
	MOVE_INT $0A, $06
	ASR8_INT $06
	PULL32 $0A
	CLC
	ADD_INT_ASSIGN $06, $0A
	MOVE_INT $06, $1A
	JMP @UNKNOWN14
@NOT_IN_WATER:
	LDA a:.LOWORD(UNKNOWN_7E0081)
	BEQ @UNKNOWN8
	TYA
	ASL
	ASL
	STA $02
	LDA .LOWORD(GAME_STATE)+game_state::walking_style
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC $02
	CLC
	ADC #.LOWORD(UNKNOWN_7E4F96)
	TAY
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $0A
	CLC
	ADD_INT_ASSIGN $06, $0A
	MOVE_INT $06, $1A
	JMP @UNKNOWN14
@UNKNOWN8:
	LDA .LOWORD(GAME_STATE) + game_state::party_status
	AND #$00FF
	CMP #$0003
	BEQ @UNKNOWN9
	JMP @UNKNOWN13
@UNKNOWN9:
	LDA .LOWORD(GAME_STATE)+game_state::walking_style
	STA $0E
	BEQ @UNKNOWN10
	JMP @UNKNOWN13
@UNKNOWN10:
	TYA
	ASL
	ASL
	STA $02
	LDA $0E
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC $02
	CLC
	ADC #.LOWORD(UNKNOWN_7E4F96)
	TAY
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $06
	ASR8_INT $06
	MOVE_INT $06, $0A
	MOVE_INT $0A, $06
	MOVE_INT_CONSTANT SKIP_SANDWICH_SPEED, $0A
	JSL MULT32
	MOVE_INT $06, $0A
	MOVE_INT $10, $06
	PHA
	LDA $06
	PHA
	MOVE_INT $0A, $06
	ASR8_INT $06
	PULL32 $0A
	CLC
	ADD_INT_ASSIGN $06, $0A
	MOVE_INT $06, $1A
	BRA @UNKNOWN14
@UNKNOWN13:
	TYA
	ASL
	ASL
	STA $02
	LDA .LOWORD(GAME_STATE)+game_state::walking_style
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC $02
	CLC
	ADC #.LOWORD(UNKNOWN_7E4F96)
	TAY
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $0A
	CLC
	ADD_INT_ASSIGN $06, $0A
	MOVE_INT $06, $1A
@UNKNOWN14:
	PLD
	RTS
