
CHECK:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_RETURN_INT32 ;const char*
	END_STACK_VARS
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	JSL FIND_NEARBY_CHECKABLE_TPT_ENTRY
	LDA INTERACTING_NPC_ID
	BEQL @UNKNOWN9
	LDA INTERACTING_NPC_ID
	CMP #$FFFF
	BEQL @UNKNOWN9
	LDA INTERACTING_NPC_ID
	CMP #$FFFE
	BNE @UNKNOWN2
	MOVE_INT MAP_OBJECT_TEXT, @VIRTUAL0A
	JMP @UNKNOWN9
@UNKNOWN2:
	LOADPTR NPC_CONFIG_TABLE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA INTERACTING_NPC_ID
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
	STA @LOCAL01
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP #NPC_TYPE::PERSON
	BEQL @UNKNOWN9
	CMP #NPC_TYPE::ITEM_BOX
	BEQ @UNKNOWN5
	CMP #NPC_TYPE::OBJECT
	BEQL @UNKNOWN8
	JMP @UNKNOWN9
@UNKNOWN5:
	LDA @LOCAL01
	CLC
	ADC #npc_config::item
	MOVE_INTX @LOCAL02, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	CMP #$100
	BCS @GIFT_MONEY
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	BRA @GIFT_COMMON
@GIFT_MONEY:
.IF .DEFINED(JPN)
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	JSR SET_WORKING_MEMORY
	LDA INTERACTING_NPC_ID
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
	CLC
	ADC #npc_config::item
	MOVE_INTX @LOCAL02, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	SEC
	SBC #$100
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_ARGUMENT_MEMORY
@GIFT_COMMON:
	LOADPTR NPC_CONFIG_TABLE, @VIRTUAL06
	LDA INTERACTING_NPC_ID
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
	STA @LOCAL01
	CLC
	ADC #npc_config::event_flag
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	STA CURRENT_INTERACTING_EVENT_FLAG
	LDA @LOCAL01
	CLC
	ADC #npc_config::text_pointer
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	BRA @UNKNOWN9
@UNKNOWN8:
	LDA @LOCAL01
	CLC
	ADC #npc_config::text_pointer
	MOVE_INTX @LOCAL02, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
@UNKNOWN9:
	MOVE_INT @VIRTUAL0A, @RETURNVAL
	END_C_FUNCTION
