
; index == -1 means create new entity
CREATE_ENTITY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT8
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int sprite
	STACK_RESERVE_PARAM_INT16 ;int script
	STACK_RESERVE_PARAM_INT16 ;int index
	STACK_RESERVE_PARAM_INT16 ;int x
	STACK_RESERVE_PARAM_INT16 ;int y
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STY @VIRTUAL04
	PHA
	LDA @VIRTUAL04
	STA @LOCAL0D
	PLA
	STX @LOCAL0C
	STA @LOCAL0B
	LDY @PARAM04
	STY @LOCAL0A
	LDX @PARAM03
	STX @LOCAL09
	LDA DEBUG
	BEQ @UNKNOWN0
	LDA @LOCAL0B
	CMP #$FFFF
	BNE @UNKNOWN0
	LDA #0
	JMP @UNKNOWN8
@UNKNOWN0:
	LOADPTR SPRITE_GROUPING_PTR_TABLE, @VIRTUAL0A
	LDA @LOCAL0B
	OPTIMIZED_MULT @VIRTUAL04, 4
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	LDA @LOCAL0B
	JSR UNKNOWN_C01DED
	STA @VIRTUAL02
	LDY @VIRTUAL04
	LDX NEW_SPRITE_TILE_HEIGHT
	LDA NEW_SPRITE_TILE_WIDTH
	JSL UNKNOWN_C01C52
	STA @LOCAL07
@UNKNOWN1:
	LDA @LOCAL07
	CMP #$7FFF
	BGT @UNKNOWN1
	LOADPTR UNKNOWN_C42B0D, @VIRTUAL06
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 4
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(spritemap) * 2
	JSL FIND_FREE_7E4682
	STA @LOCAL06
@UNKNOWN3:
	LDA @LOCAL06
	CMP #$7FFF
	BGT @UNKNOWN3
	LDA #1
	STA NEW_ENTITY_PRIORITY
.IF .DEFINED(JPN)
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	MOVE_INT @LOCAL08, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDY #3
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAY
	LDX @LOCAL07
	LDA @LOCAL06
	JSR UNKNOWN_C01D38
	LDA @LOCAL0D
	STA @VIRTUAL04
	CMP #$FFFF
	BEQ @UNKNOWN5
	LDA @VIRTUAL04
	STA ENTITY_ALLOCATION_MIN_SLOT
	LDA @VIRTUAL04
	INC
	STA ENTITY_ALLOCATION_MAX_SLOT
	LDY @LOCAL0A
	LDX @LOCAL09
	LDA @LOCAL0C
	JSL INIT_ENTITY
	STA @VIRTUAL02
	BRA @UNKNOWN6
@UNKNOWN5:
	STZ ENTITY_ALLOCATION_MIN_SLOT
	LDA #22
	STA ENTITY_ALLOCATION_MAX_SLOT
	LDY @LOCAL0A
	LDX @LOCAL09
	LDA @LOCAL0C
	JSL INIT_ENTITY
	STA @VIRTUAL02
	ORA #$0080
	TAX
	LDA #$FFFF
	JSL ALLOC_SPRITE_MEM
@UNKNOWN6:
	LDA @VIRTUAL02
	ASL
	TAY
	STY @LOCAL05
	LDA @LOCAL06
	CLC
	ADC #.LOWORD(OVERWORLD_SPRITEMAPS)
	STA ENTITY_SPRITEMAP_POINTER_LOW,Y
	LDA #.HIWORD(OVERWORLD_SPRITEMAPS)
	STA ENTITY_SPRITEMAP_POINTER_HIGH,Y
	LDA [@VIRTUAL0A]
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(spritemap)
	STA ENTITY_SPRITEMAP_SIZES,Y
	LDA @LOCAL07
	STA ENTITY_SPRITEMAP_BEGINNING_INDICES,Y
	TYA
	CLC
	ADC #.LOWORD(ENTITY_VRAM_ADDRESS)
	TAX
	STX @LOCAL04
	LDA @LOCAL07
	ASL
	TAX
	LDA f:UNKNOWN_C42F8C,X
	CLC
	ADC #$4000
	LDX @LOCAL04
	STA __BSS_START__,X
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_grouping::width
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ASL
	LDY @LOCAL05
	STA ENTITY_BYTE_WIDTHS,Y
	LDA [@VIRTUAL06]
	AND #$00FF
	STA ENTITY_TILE_HEIGHTS,Y
	MOVE_INT @LOCAL08, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_grouping::spritebank
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	LDY @LOCAL05
	STA ENTITY_GRAPHICS_SPRITE_BANK,Y
	LOADPTR SPRITE_GROUPING_PTR_TABLE, @VIRTUAL06
	LDA @LOCAL0B
	OPTIMIZED_MULT @VIRTUAL04, 4
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA @LOCAL0B
	LDY @LOCAL05
	STA ENTITY_SPRITE_IDS,Y
	LDA @LOCAL01+2
	STA ENTITY_GRAPHICS_PTR_HIGH,Y
	LDA @LOCAL01
	CLC
	ADC #sprite_grouping::spritepointerarray
	STA ENTITY_GRAPHICS_PTR_LOW,Y
	LDA NEW_SPRITE_TILE_HEIGHT
	AND #$0001
	BEQ @UNKNOWN7
	LDA __BSS_START__,X
	CLC
	ADC #$0100
	STA __BSS_START__,X
@UNKNOWN7:
	LDA @VIRTUAL02
	ASL
	TAX
	STX @LOCAL04
	MOVE_INT @LOCAL08, @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA [@LOCAL03]
	AND #$00FF
	STA ENTITY_SIZES,X
	MOVE_INT @LOCAL08, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_grouping::hitbox_width_ud
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA ENTITY_HITBOX_UP_DOWN_WIDTHS,X
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_grouping::hitbox_height_ud
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA ENTITY_HITBOX_UP_DOWN_HEIGHTS,X
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_grouping::hitbox_width_lr
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA ENTITY_HITBOX_LEFT_RIGHT_WIDTHS,X
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_grouping::hitbox_height_lr
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA ENTITY_HITBOX_LEFT_RIGHT_HEIGHTS,X
	LDA [@LOCAL03]
	AND #$00FF
	ASL
	TAX
	LDA f:UNKNOWN_C42AEB,X
	LDX @LOCAL04
	STA ENTITY_HITBOX_ENABLED,X
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_grouping::width
	LDA [@VIRTUAL0A],Y
	STA @LOCAL02
	STA @VIRTUAL00
	LDA [@VIRTUAL0A]
	SEC
	SBC @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL04
	LDA @LOCAL02
	AND #$00FF
	XBA
	AND #$FF00
	ORA @VIRTUAL04
	STA ENTITY_UPPER_LOWER_BODY_DIVIDES,X
	LDA #$FFFF
	STA ENTITY_ENEMY_SPAWN_TILES,X
	STA ENTITY_ENEMY_IDS,X
	STA ENTITY_NPC_IDS,X
	STA ENTITY_COLLIDED_OBJECTS,X
	STZ ENTITY_SURFACE_FLAGS,X
	STZ ENTITY_UNKNOWN_2DC6,X
	STZ ENTITY_UNUSED,X
	STZ ENTITY_PATHFINDING_STATES,X
	STZ ENTITY_MOVEMENT_SPEEDS,X
	STZ ENTITY_DIRECTIONS,X
	STZ ENTITY_OBSTACLE_FLAGS,X
	LDA @VIRTUAL02
@UNKNOWN8:
	PLD
	RTL
