
DELETE_ACTIVE_ENTRY:
	JSR SEARCH_NEXT_ENTITY_TABLE
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	CPY #$FFFF
	BEQ @UNKNOWN0
	STA ENTITY_NEXT_ENTITY_TABLE,Y
	BRA @UNKNOWN1
@UNKNOWN0:
	STA FIRST_ENTITY
@UNKNOWN1:
	CPX NEXT_ACTIVE_ENTITY
	BNE @UNKNOWN2
	STA NEXT_ACTIVE_ENTITY
@UNKNOWN2:
	RTS
