
DISABLE_HOTSPOT: ;$C071E5
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAX
	DEX
	STX $0E
	TXA
	OPTIMIZED_MULT $04, .SIZEOF(active_hotspot)
	CLC
	ADC #.LOWORD(ACTIVE_HOTSPOTS)
	TAX
	LDA #$0000
	STA a:active_hotspot::mode,X
	LDX $0E
	.IF .DEFINED(JPN)
		TXA
		CLC
		ADC #.LOWORD(GAME_STATE)
		TAX
		SEP #PROC_FLAGS::ACCUM8
		STZ a:game_state::active_hotspot_modes,X
	.ELSE
		SEP #PROC_FLAGS::ACCUM8
		STZ GAME_STATE + game_state::active_hotspot_modes,X
	.ENDIF
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
