
DOOR_TRANSITION:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL03
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @UNKNOWN1
	MOVE_INT @VIRTUAL06, @LOCAL00 ;door_data::text
	JSL UNKNOWN_C10004
@UNKNOWN1:
	STZ UNKNOWN_7E5DAA
	STZ UNKNOWN_7E5DA8
	LDA #door_data::event_flag
	MOVE_INTX @LOCAL03, @VIRTUAL0A
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	BEQ @UNKNOWN3
	AND #$7FFF
	JSL GET_EVENT_FLAG
	STA @LOCAL02
	LDX #0
	LDA [@VIRTUAL06]
	CMP #EVENT_FLAG_UNSET
	BLTEQ @UNKNOWN2
	LDX #1
@UNKNOWN2:
	STX @VIRTUAL02
	LDA @LOCAL02
	CMP @VIRTUAL02
	BEQ @UNKNOWN3
	STZ UNKNOWN_7E5DC2
	JMP @UNKNOWN15
@UNKNOWN3:
	LDY #1
	STY @LOCAL01
	BRA @UNKNOWN5
@UNKNOWN4:
	LDX #0
	TYA
	JSL SET_EVENT_FLAG
	LDY @LOCAL01
	INY
	STY @LOCAL01
@UNKNOWN5:
	CPY #10
	BLTEQ @UNKNOWN4
	JSL UNKNOWN_C06B3D
	JSL UNKNOWN_C07C5B
	LDA #$FFFF
	STA UNKNOWN_7EB4A8
	STZ UNKNOWN_7E5D58
	LDA #door_data::unknown10
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDX #1
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL GET_SCREEN_TRANSITION_SOUND_EFFECT
	JSL PLAY_SOUND
	LDA UNKNOWN_7EB4B6
	BEQ @UNKNOWN6
	LDX #1
	TXA
	JSL FADE_OUT
	BRA @UNKNOWN7
@UNKNOWN6:
	LDX #1
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL SCREEN_TRANSITION
@UNKNOWN7:
	LDY #door_data::unknown8
	LDA [@VIRTUAL0A],Y
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	LDY #door_data::unknown6
	LDA [@VIRTUAL0A],Y
	STA @LOCAL02
	AND #$3FFF
	ASL
	ASL
	ASL
	STA @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDA #14
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	JSL ASR8_UNKNOWN1
	ASL
	REP #PROC_FLAGS::INDEX8
	TAX
	LDA f:UNKNOWN_C3E1D8,X
	CMP #2
	BEQ @UNKNOWN8
	LDA @VIRTUAL02
	CLC
	ADC #8
	STA @VIRTUAL02
@UNKNOWN8:
	LDA DEBUG
	BEQ @UNKNOWN10
	LDA DEBUG_MODE_NUMBER
	CMP #6
	BEQ @UNKNOWN9
	LDX @VIRTUAL04
	LDA @VIRTUAL02
	JSL UNKNOWN_C068F4
@UNKNOWN9:
	LDA UNKNOWN_7EB567
	BNE @UNKNOWN11
	SEP #PROC_FLAGS::ACCUM8
	LDY #door_data::unknown10
	LDA [@VIRTUAL0A],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	JSL UNKNOWN_EFE895
	BRA @UNKNOWN11
@UNKNOWN10:
	LDX @VIRTUAL04
	LDA @VIRTUAL02
	JSL UNKNOWN_C068F4
@UNKNOWN11:
	LDX @VIRTUAL04
	LDA @VIRTUAL02
	JSL LOAD_MAP_AT_POSITION
	STZ UNKNOWN_7E2890
	STZ GAME_STATE+game_state::walking_style
	SEP #PROC_FLAGS::ACCUM8
	LDA #14
	PHA
	REP #PROC_FLAGS::ACCUM8
	LDY #door_data::unknown6
	LDA [@VIRTUAL0A],Y
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR8_UNKNOWN1
	ASL
	REP #PROC_FLAGS::INDEX8
	TAX
	LDA f:UNKNOWN_C3E1D8,X
	TAY
	LDX @VIRTUAL04
	LDA @VIRTUAL02
	JSL UNKNOWN_C03FA9
	LDA DEBUG
	BEQ @UNKNOWN12
	LDA UNKNOWN_7EB567
	BNE @UNKNOWN12
	JSL SAVE_REPLAY_SAVE_SLOT
@UNKNOWN12:
	JSL UNKNOWN_C069AF
	JSL UNKNOWN_C065A3
	LDA #door_data::unknown10
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDX #0
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL GET_SCREEN_TRANSITION_SOUND_EFFECT
	JSL PLAY_SOUND
	LDA UNKNOWN_7EB4B6
	BEQ @UNKNOWN13
	LDX #1
	TXA
	JSL FADE_IN
	BRA @UNKNOWN14
@UNKNOWN13:
	LDX #0
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL SCREEN_TRANSITION
@UNKNOWN14:
	LDA #$FFFF
	STA UNKNOWN_7E5DC4
	STZ UNKNOWN_7E0A34
	JSL SPAWN_BUZZ_BUZZ
	STZ UNKNOWN_7E5DC2
@UNKNOWN15:
	END_C_FUNCTION
