
ENABLE_YOUR_SANCTUARY_DISPLAY: ;$C4DED0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDY #$6000
	LDX #$3800
	LDA #BG_TILEMAP_SIZE::HORIZONTAL
	JSL SET_BG1_VRAM_LOCATION
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0011
	STA TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	RTL
