
FIND_MAP_OBJECT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
.IF .DEFINED(JPN) ;why were these swapped?
	@TMP1 := @VIRTUAL02
	@TMP2 := @VIRTUAL04
.ELSE
	@TMP1 := @VIRTUAL04
	@TMP2 := @VIRTUAL02
.ENDIF
	STA @TMP2
	ASL
	TAX
	LDA GAME_STATE+game_state::leader_x_coord
	LSR
	LSR
	LSR
	CLC
	ADC INTERACT_X_OFFSETS,X
	STA @LOCAL01
	LDA @TMP2
	CMP #4
	BNE @UNKNOWN0
	LDA GAME_STATE+game_state::leader_y_coord
	INC
	LSR
	LSR
	LSR
	CLC
	ADC INTERACT_Y_OFFSETS,X
	STA @TMP1
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA GAME_STATE+game_state::leader_y_coord
	LSR
	LSR
	LSR
	CLC
	ADC INTERACT_Y_OFFSETS,X
	STA @TMP1
@UNKNOWN1:
	LDA @TMP2
	STA @LOCAL00
	LDY GAME_STATE+game_state::current_party_members
	LDA @TMP1
	ASL
	ASL
	ASL
	TAX
	LDA @LOCAL01
	ASL
	ASL
	ASL
	JSL GET_MOVEMENT_COLLISION_FLAGS
	AND #$0082
	CMP #$0082
	BNE @UNKNOWN2
	LDA @TMP2
	ASL
	TAX
	LDA INTERACT_X_OFFSETS,X
	CLC
	ADC @LOCAL01
	STA @LOCAL01
	LDA @TMP1
	CLC
	ADC INTERACT_Y_OFFSETS,X
	STA @TMP1
@UNKNOWN2:
	LDX @TMP1
	LDA @LOCAL01
	JSL GET_MAP_OBJECT_AT
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	CPX #<-1
	BNE @UNKNOWN3
	LDX @TMP1
	LDA @LOCAL01
	INC
	JSL GET_MAP_OBJECT_AT
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@UNKNOWN3:
	CPX #<-1
	BNE @UNKNOWN4
	LDX @TMP1
	LDA @LOCAL01
	DEC
	JSL GET_MAP_OBJECT_AT
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@UNKNOWN4:
	CPX #<-1
	BEQ @UNKNOWN5
	CPX #5
	BNE @UNKNOWN5
	LOADPTR DOOR_DATA&$FF0000, @VIRTUAL06
	LDA DOOR_FOUND
	AND #$7FFF
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA DOOR_FOUND_TYPE
	STA INTERACTED_OBJECT_TYPE
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, MAP_OBJECT_TEXT
	LDA #.LOWORD(-2)
	STA INTERACTING_NPC_ID
@UNKNOWN5:
	END_C_FUNCTION
