
FIND_NEARBY_CHECKABLE_TPT_ENTRY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	LDA #.LOWORD(-1)
	STA INTERACTING_NPC_ID
	STA INTERACTING_NPC_ENTITY
	JSR UNKNOWN_C041E3
	STA @LOCAL01
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN0
	LDX #.LOWORD(GAME_STATE) + game_state::current_party_members
	STX @LOCAL00
	LDA __BSS_START__,X
	ASL
	TAX
	LDA @LOCAL01
	CMP ENTITY_DIRECTIONS,X
	BEQ @UNKNOWN0
	STA GAME_STATE + game_state::leader_direction
	LDX @LOCAL00
	LDA __BSS_START__,X
	ASL
	TAX
	LDA @LOCAL01
	STA ENTITY_DIRECTIONS,X
	LDX @LOCAL00
	LDA __BSS_START__,X
	JSL UNKNOWN_C0A780
@UNKNOWN0:
	LDA INTERACTING_NPC_ID
	END_C_FUNCTION
