
GET_OFF_BICYCLE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	MOVE_INT_CONSTANT 1, @LOCAL00
	JSR SET_WORKING_MEMORY
	DISPLAY_TEXT_PTR MSG_SYS_BICYCLE_OFF
	JSR CLOSE_FOCUS_WINDOW
	JSL WINDOW_TICK
	JSL UNKNOWN_C03CFD
	END_C_FUNCTION
