
GET_OPPOSITE_DIRECTION_FROM_PLAYER_TO_ENTITY: ;$C0C608
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL GET_DIRECTION_FROM_PLAYER_TO_ENTITY
	ASL
	TAX
	LDA f:OPPOSITE_DIRECTIONS,X
	RTL
