
GET_DISTANCE_TO_MAGIC_TRUFFLE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	LDA #OVERWORLD_SPRITE::UNKNOWN2
	JSL UNKNOWN_C46028
	STA @VIRTUAL04
	CMP #.LOWORD(-1)
	BNE @UNKNOWN0
	LDA #0
	JMP @UNKNOWN15
@UNKNOWN0:
	LDA @VIRTUAL04
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	STA @LOCAL02
	LDY GAME_STATE+game_state::leader_x_coord
	TYA
	SEC
	SBC #64
	STA @VIRTUAL02
	LDA @LOCAL02
	CMP @VIRTUAL02
	BCC @UNKNOWN2
	TYA
	CLC
	ADC #64
	STA @VIRTUAL02
	LDA @LOCAL02
	CMP @VIRTUAL02
	BGT @UNKNOWN2
	LDY ENTITY_ABS_Y_TABLE,X
	LDA GAME_STATE+game_state::leader_y_coord
	STA @LOCAL02
	SEC
	SBC #64
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BCC @UNKNOWN2
	LDA @LOCAL02
	CLC
	ADC #64
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BLTEQ @UNKNOWN3
@UNKNOWN2:
	LDA #1
	JMP @UNKNOWN15
@UNKNOWN3:
	LDA @LOCAL02
	STA @VIRTUAL02
	TYA
	SEC
	SBC @VIRTUAL02
	STA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN6
	LDA @LOCAL02
	EOR #$FFFF
	INC
	STA @VIRTUAL02
	STA @LOCAL01
	BRA @UNKNOWN7
@UNKNOWN6:
	LDA @LOCAL02
	STA @VIRTUAL02
	STA @LOCAL01
@UNKNOWN7:
	LDA @VIRTUAL04
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	SEC
	SBC GAME_STATE+game_state::leader_x_coord
	STA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN10
	LDA @LOCAL02
	EOR #$FFFF
	INC
	BRA @UNKNOWN11
@UNKNOWN10:
	LDA @LOCAL02
@UNKNOWN11:
	LDX @LOCAL01
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL02
	LDA #16
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN14
	LDA #10
	BRA @UNKNOWN15
@UNKNOWN14:
	LDA @VIRTUAL04
	ASL
	TAX
	LDA ENTITY_ABS_Y_TABLE,X
	STA @LOCAL00
	LDY ENTITY_ABS_X_TABLE,X
	LDX GAME_STATE + game_state::leader_y_coord
	LDA GAME_STATE + game_state::leader_x_coord
	JSL UNKNOWN_C41EFF
	LDY #$2000
	CLC
	ADC #$1000
	JSL DIVISION16S_DIVISOR_POSITIVE
	INC
	INC
@UNKNOWN15:
	END_C_FUNCTION
