
GET_ON_BICYCLE: ;$C03C5E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	CMP #$0001
	BNEL @UNKNOWN3
	LDA GAME_STATE + game_state::unknown96
	AND #$00FF
	CMP #$0001
	BNEL @UNKNOWN3
	LDA UNKNOWN_7E5DD8
	BNE @UNKNOWN2
	LDA #MUSIC::BICYCLE
	JSL CHANGE_MUSIC
@UNKNOWN2:
	LDA #$0018
	JSL UNKNOWN_C02140
	LDA #$0006
	STA GAME_STATE + game_state::unknown92
	LDA #WALKING_STYLE::BICYCLE
	STA GAME_STATE+game_state::walking_style
	STZ CHAR_STRUCT+char_struct::position_index
	STZ GAME_STATE + game_state::unknown88
	STZ NEW_ENTITY_VAR0
	STZ NEW_ENTITY_VAR1
	LDA ENTITY_ABS_X_TABLE + (PARTY_LEADER_ENTITY_INDEX * 2)
	STA $0E
	LDA ENTITY_ABS_Y_TABLE + (PARTY_LEADER_ENTITY_INDEX * 2)
	STA $10
	LDY #$0018
	LDX #EVENT_SCRIPT::EVENT_002
	LDA #OVERWORLD_SPRITE::NESS_BICYCLE
	JSL CREATE_ENTITY
	LDX #.LOWORD(ENTITY_TICK_CALLBACK_HIGH) + (24 * 2)
	LDA RAM,X
	ORA #$8000
	STA RAM,X
	LDX #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE) + (24 * 2)
	LDA RAM,X
	ORA #$3000
	STA RAM,X
	STZ ENTITY_ANIMATION_FRAME + (PARTY_LEADER_ENTITY_INDEX * 2)
	LDA GAME_STATE+game_state::leader_direction
	STA ENTITY_DIRECTIONS + (PARTY_LEADER_ENTITY_INDEX * 2)
	LDA #$0000
	JSL SET_BOUNDARY_BEHAVIOR
	LDA #$0001
	STA GAME_STATE + game_state::unknown90
	STA UNKNOWN_7E5DBA
	LDA #$0002
	STA INPUT_DISABLE_FRAME_COUNTER
@UNKNOWN3:
	PLD
	RTL
