
GET_TOWN_MAP_ID:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	XBA
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 3
	STA @VIRTUAL02
	LDY #128
	TXA
	JSL DIVISION16S_DIVISOR_POSITIVE
	OPTIMIZED_MULT @VIRTUAL04, 96
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:MAP_DATA_PER_SECTOR_TOWN_MAP_DATA,X
	AND #$00FF
	END_C_FUNCTION
