
GET_DEFAULT_MUSIC:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_MUSIC
	LDA NEXT_MAP_MUSIC_TRACK
	RTL
