
INTERACT_MAP_OBJECT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL01
	STA @VIRTUAL02
	TYX
	LDA @VIRTUAL02
	JSL GET_MAP_OBJECT_AT
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @UNKNOWN0
	CMP #DOOR_TYPE::TYPE1
	BEQ @UNKNOWN1
	CMP #DOOR_TYPE::TYPE2
	BEQ @UNKNOWN2
	CMP #DOOR_TYPE::TYPE3
	BEQ @UNKNOWN3
	CMP #DOOR_TYPE::TYPE4
	BEQ @UNKNOWN4
	CMP #DOOR_TYPE::TYPE5
	BEQ @UNKNOWN5
	CMP #DOOR_TYPE::TYPE7
	BEQ @UNKNOWN5
	CMP #DOOR_TYPE::TYPE6
	BEQ @UNKNOWN6
	BRA @UNKNOWN7
@UNKNOWN0:
	LDA DOOR_FOUND
	JSR INTERACT_MAP_SWITCH
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL00
	BRA @UNKNOWN7
@UNKNOWN1:
	LDA DOOR_FOUND
	JSR INTERACT_ROPE_LADDER
	LDA #1
	STA @VIRTUAL04
	STA @LOCAL00
	BRA @UNKNOWN7
@UNKNOWN2:
	LDA DOOR_FOUND
	JSR INTERACT_DOOR
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL00
	BRA @UNKNOWN7
@UNKNOWN3:
	LDY @LOCAL01
	LDX @VIRTUAL02
	LDA DOOR_FOUND
	JSR INTERACT_ESCALATOR
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL00
	BRA @UNKNOWN7
@UNKNOWN4:
	LDY @LOCAL01
	LDX @VIRTUAL02
	LDA DOOR_FOUND
	JSR INTERACT_STAIRS
	LDA #1
	STA @VIRTUAL04
	STA @LOCAL00
	BRA @UNKNOWN7
@UNKNOWN5:
	LDA DOOR_FOUND
	JSR INTERACT_OBJECT
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL00
	BRA @UNKNOWN7
@UNKNOWN6:
	LDA DOOR_FOUND
	JSR INTERACT_MAP_NPC
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL00
@UNKNOWN7:
	LDA @LOCAL00
	STA @VIRTUAL04
	END_C_FUNCTION
