
IS_VALID_ITEM_TRANSFORMATION: ;$C48ECE
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDY #$0000
	ASL
	ASL
	TAX
	LDA LOADED_TIMED_ITEM_TRANSFORMATIONS + loaded_timed_item_transformation::transformation_countdown,X
	AND #$00FF
	BNE @UNKNOWN0
	LDA LOADED_TIMED_ITEM_TRANSFORMATIONS + loaded_timed_item_transformation::sfx_frequency,X
	AND #$00FF
	BEQ @UNKNOWN1
@UNKNOWN0:
	LDY #$0001
@UNKNOWN1:
	TYA
	RTL
