
LOAD_COLLISION_COLUMN:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL02
	LSR
	LSR
	AND #$000F
	ASL
	CLC
	ADC #.LOWORD(LOADED_MAP_BLOCKS)
	STA @VIRTUAL02
	LDA @LOCAL02
	AND #$003F
	CLC
	ADC #.LOWORD(LOADED_COLLISION_TILES)
	TAX
	STX @LOCAL01
	LDA @LOCAL02
	AND #$0003
	STA @VIRTUAL04
	LDY #0
	STY @LOCAL00
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	ASL
	TAX
	LDA f:TILE_COLLISION_BUFFER,X
	STA @LOCAL02
	LDA @VIRTUAL02
	CLC
	ADC #32
	STA @VIRTUAL02
	LOADPTR MAP_DATA_TILE_COLLISION_ARRANGEMENT_TABLE, @VIRTUAL06
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @VIRTUAL0A
	LDA @VIRTUAL06+2
	STA @VIRTUAL0A+2
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL0A]
	LDX @LOCAL01
	STA __BSS_START__,X
	LDY #4
	LDA [@VIRTUAL06],Y
	STA __BSS_START__+64,X
	LDY #8
	LDA [@VIRTUAL06],Y
	STA __BSS_START__+128,X
	LDY #12
	LDA [@VIRTUAL06],Y
	STA __BSS_START__+192,X
	REP #PROC_FLAGS::ACCUM8
	TXA
	CLC
	ADC #256
	TAX
	STX @LOCAL01
	LDY @LOCAL00
	INY
	STY @LOCAL00
@UNKNOWN1:
	CPY #16
	BCC @UNKNOWN0
	END_C_FUNCTION
