
LOAD_SECTOR_ATTRS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	XBA
	AND #$00FF
	STA @VIRTUAL02
	TXA
	AND #$FF80
	LSR
	LSR
	CLC
	ADC @VIRTUAL02
	ASL
	TAX
	LDA f:MAP_DATA_PER_SECTOR_ATTRIBUTES_TABLE,X
	STA CURRENT_SECTOR_ATTRIBUTES
	END_C_FUNCTION
