
LOAD_TILE_COLLISION:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	STA @LOCAL00
	LOADPTR MAP_DATA_TILE_COLLISION_PTR_TABLE, @VIRTUAL06
	LDA @LOCAL00
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	LOADPTR TILE_COLLISION_BUFFER, @VIRTUAL06
	LDA #0
	STA @LOCAL00
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA [@VIRTUAL0A]
	STA [@VIRTUAL06]
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	INC @VIRTUAL06
	INC @VIRTUAL06
	LDA @LOCAL00
	INC
	STA @LOCAL00
@UNKNOWN1:
	CMP #960
	BCC @UNKNOWN0
	END_C_FUNCTION
