
LOAD_DAD_PHONE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA WINDOW_HEAD
	CMP #.LOWORD(-1)
	BNE @UNKNOWN0
	LDA BATTLE_MODE_FLAG
	BNE @UNKNOWN0
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN0
	LDA BATTLE_SWIRL_FLAG
	BNE @UNKNOWN0
	LDA UNKNOWN_7E9E56
	BNE @UNKNOWN0
	LDA #EVENT_FLAG::FLG_SYS_DIS_2H_PAPA
	JSL GET_EVENT_FLAG
	CMP #0
	BNE @UNKNOWN0
	LOADPTR MSG_SYS_PAPA_2H, @LOCAL00
	LDA #10
	JSL UNKNOWN_C064E3
	LDA #1
	STA UNKNOWN_7E9E56
@UNKNOWN0:
	END_C_FUNCTION
