
LOAD_YOUR_SANCTUARY_LOCATION_DATA:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	STY @LOCAL06
	STX @VIRTUAL02
	STX @LOCAL05
	STA @VIRTUAL04
	STZ YOUR_SANCTUARY_LOADED_TILESET_TILES
	LDA @VIRTUAL04
	LSR
	LSR
	LSR
	LSR
	LSR
	STA @LOCAL04
	LDA @VIRTUAL02
	LSR
	LSR
	LSR
	LSR
	TAX
	LOADPTR GLOBAL_MAP_TILESETPALETTE_DATA, @VIRTUAL06
	LDA @LOCAL04
	STA @VIRTUAL02
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 32
	CLC
	ADC @VIRTUAL02
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAY
	STY @LOCAL03
	LDA @VIRTUAL04
	LSR
	LSR
	LSR
	LSR
	LSR
	PHA
	LDA @LOCAL05
	STA @VIRTUAL02
	LSR
	LSR
	AND #$FFFC
	OPTIMIZED_MULT @VIRTUAL04, 8
	PLX
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	LSR
	LSR
	LSR
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA LOADED_MAP_TILE_COMBO
	LDX @LOCAL06
	TYA
	JSR PREPARE_YOUR_SANCTUARY_LOCATION_PALETTE_DATA
	LOADPTR TILESET_TABLE, @VIRTUAL0A
	LDY @LOCAL03
	TYA
	LSR
	LSR
	LSR
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LOADPTR BUFFER + $8000, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LOADPTR MAP_DATA_TILE_ARRANGEMENT_PTR_TABLE, @VIRTUAL06
	LDA [@VIRTUAL0A]
	OPTIMIZED_MULT @VIRTUAL04, 4
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DECOMP
	LDY @LOCAL06
	LDA @LOCAL05
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSR PREPARE_YOUR_SANCTUARY_LOCATION_TILE_ARRANGEMENT_DATA
.IF .DEFINED(JPN)
	LOADPTR MAP_DATA_TILESET_PTR_TABLE, @VIRTUAL06
	LDA [@VIRTUAL0A]
	OPTIMIZED_MULT @VIRTUAL04, 4
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	LDA [@VIRTUAL0A]
	OPTIMIZED_MULT @VIRTUAL04, 4
	PHA
	LOADPTR MAP_DATA_TILESET_PTR_TABLE, @VIRTUAL0A
	PLA
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	MOVE_INT @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DECOMP
	LDA @LOCAL06
	JSR PREPARE_YOUR_SANCTUARY_LOCATION_TILESET_DATA
	LDA TOTAL_YOUR_SANCTUARY_LOADED_TILESET_TILES
	CLC
	ADC YOUR_SANCTUARY_LOADED_TILESET_TILES
	STA TOTAL_YOUR_SANCTUARY_LOADED_TILESET_TILES
	PLD
	RTS
