
NPC_COLLISION_CHECK:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL07
	STA @VIRTUAL02
	LDA #ENTITY_COLLISION_NO_OBJECT
	STA @LOCAL06
	TYA
	ASL
	TAX
	LDA ENTITY_HITBOX_ENABLED,X
	BEQL @UNKNOWN16
	LDA PLAYER_MOVEMENT_FLAGS
	AND #$0002
	BNEL @UNKNOWN16
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::ESCALATOR
	BEQL @UNKNOWN16
	LDA DEMO_FRAMES_LEFT
	BNEL @UNKNOWN16
	LDA ENTITY_DIRECTIONS,X
	CMP #DIRECTION::RIGHT
	BEQ @UNKNOWN4
	CMP #DIRECTION::LEFT
	BNE @UNKNOWN5
@UNKNOWN4:
	TYA
	ASL
	TAX
	LDA ENTITY_HITBOX_LEFT_RIGHT_WIDTHS,X
	STA @LOCAL05
	LDA ENTITY_HITBOX_LEFT_RIGHT_HEIGHTS,X
	STA @VIRTUAL04
	BRA @UNKNOWN6
@UNKNOWN5:
	LDA ENTITY_HITBOX_UP_DOWN_WIDTHS,X
	STA @LOCAL05
	LDA ENTITY_HITBOX_UP_DOWN_HEIGHTS,X
	STA @VIRTUAL04
@UNKNOWN6:
	LDA @LOCAL05
	PHA
	LDA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	SEC
	SBC @VIRTUAL02
	STA @LOCAL04
	LDA @LOCAL05
	ASL
	STA @LOCAL03
	LDA @LOCAL07
	SEC
	SBC @VIRTUAL04
	STA @LOCAL07
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL02
	JMP @UNKNOWN15
@UNKNOWN7:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #$FFFF
	BEQL @UNKNOWN14
	LDA ENTITY_COLLIDED_OBJECTS,X
	CMP #ENTITY_COLLISION_DISABLED
	BEQL @UNKNOWN14
	LDA PLAYER_INTANGIBILITY_FRAMES
	BEQ @UNKNOWN10
	LDA ENTITY_NPC_IDS,X
	INC
	CMP #$8001
	BCC @UNKNOWN10
	JMP @UNKNOWN14
@UNKNOWN10:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_HITBOX_ENABLED,X
	BEQ @UNKNOWN14
	LDA ENTITY_DIRECTIONS,X
	CMP #DIRECTION::RIGHT
	BEQ @UNKNOWN11
	CMP #DIRECTION::LEFT
	BNE @UNKNOWN12
@UNKNOWN11:
	LDA @VIRTUAL02
	ASL
	TAX
	LDY ENTITY_HITBOX_LEFT_RIGHT_WIDTHS,X
	LDA ENTITY_HITBOX_LEFT_RIGHT_HEIGHTS,X
	STA @LOCAL01
	BRA @UNKNOWN13
@UNKNOWN12:
	LDY ENTITY_HITBOX_UP_DOWN_WIDTHS,X
	LDA ENTITY_HITBOX_UP_DOWN_HEIGHTS,X
	STA @LOCAL01
@UNKNOWN13:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA @LOCAL01
	STA @VIRTUAL02
	LDA ENTITY_ABS_Y_TABLE,X
	SEC
	SBC @VIRTUAL02
	STA @LOCAL00
	SEC
	SBC @VIRTUAL04
	CMP @LOCAL07
	BCS @UNKNOWN14
	LDA @LOCAL01
	CLC
	ADC @LOCAL00
	CMP @LOCAL07
	BLTEQ @UNKNOWN14
	STY @VIRTUAL02
	LDA ENTITY_ABS_X_TABLE,X
	SEC
	SBC @VIRTUAL02
	STA @LOCAL00
	TYA
	ASL
	TAX
	LDA @LOCAL00
	SEC
	SBC @LOCAL03
	CMP @LOCAL04
	BCS @UNKNOWN14
	STX @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL02
	CMP @LOCAL04
	BLTEQ @UNKNOWN14
	LDA @LOCAL02
	STA @VIRTUAL02
	STA @LOCAL06
	BRA @UNKNOWN16
@UNKNOWN14:
	LDA @LOCAL02
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL02
@UNKNOWN15:
	LDA @VIRTUAL02
	CMP #23
	BNEL @UNKNOWN7
@UNKNOWN16:
	LDA @LOCAL06
	STA ENTITY_COLLIDED_OBJECTS+46
	LDA @LOCAL06
	END_C_FUNCTION
