
PARTY_GET_DISTANCE_ADJUSTMENT_LEFT_RIGHT:
	LDX $88
	LDA ENTITY_SCREEN_Y_TABLE,Y
	EOR ENTITY_SCREEN_Y_TABLE,X
	BNE @UNKNOWN2
	LDA ENTITY_ABS_X_TABLE,Y
	SEC
	SBC ENTITY_ABS_X_TABLE,X
	BPL @UNKNOWN0
	EOR #$FFFF
	INC
@UNKNOWN0:
	LDY ENTITY_SCRIPT_VAR5_TABLE,X
	TYX
	SEC
	SBC f:PARTY_SLOT_DISTANCE_CARDINAL,X
	BPL @UNKNOWN1
	EOR #$FFFF
	INC
@UNKNOWN1:
	BEQ @UNKNOWN2
	DEC
@UNKNOWN2:
	RTS
