
PREPARE_NEW_ENTITY_AT_EXISTING_ENTITY_LOCATION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	BEQ @UNKNOWN0
	CMP #1
	BEQ @UNKNOWN1
	BRA @UNKNOWN2
@UNKNOWN0:
	LDX CURRENT_ENTITY_SLOT
	STX @LOCAL00
	BRA @UNKNOWN2
@UNKNOWN1:
	LDX GAME_STATE+game_state::current_party_members
	STX @LOCAL00
@UNKNOWN2:
	LDX @LOCAL00
	TXA
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	STA ENTITY_PREPARED_X_COORDINATE
	LDA ENTITY_ABS_Y_TABLE,X
	STA ENTITY_PREPARED_Y_COORDINATE
	LDA ENTITY_DIRECTIONS,X
	STA ENTITY_PREPARED_DIRECTION
	END_C_FUNCTION
