
PREPARE_NEW_ENTITY_AT_TELEPORT_DESTINATION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	LOADPTR TELEPORT_DESTINATION_TABLE, @VIRTUAL06
	LDA @LOCAL00
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(teleport_destination)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @VIRTUAL0A
	LDA @VIRTUAL06+2
	STA @VIRTUAL0A+2
	LDA [@VIRTUAL0A] ;teleport_destination::x_coord
	ASL
	ASL
	ASL
	STA ENTITY_PREPARED_X_COORDINATE
	LDY #teleport_destination::y_coord
	LDA [@VIRTUAL06],Y
	ASL
	ASL
	ASL
	STA ENTITY_PREPARED_Y_COORDINATE
	SEP #PROC_FLAGS::ACCUM8
	LDY #teleport_destination::direction
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	DEC
	STA ENTITY_PREPARED_DIRECTION
	END_C_FUNCTION
