
PREPARE_NEW_ENTITY_AT_EXISTING_ENTITY_LOCATION: ;$C46DAD
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	BEQ @UNKNOWN0
	CMP #$0001
	BEQ @UNKNOWN1
	BRA @UNKNOWN2
@UNKNOWN0:
	LDX CURRENT_ENTITY_SLOT
	STX $0E
	BRA @UNKNOWN2
@UNKNOWN1:
	LDX GAME_STATE+game_state::current_party_members
	STX $0E
@UNKNOWN2:
	LDX $0E
	TXA
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	STA ENTITY_PREPARED_X_COORDINATE
	LDA ENTITY_ABS_Y_TABLE,X
	STA ENTITY_PREPARED_Y_COORDINATE
	LDA ENTITY_DIRECTIONS,X
	STA ENTITY_PREPARED_DIRECTION
	PLD
	RTL
