
PROCESS_OVERWORLD_TASKS: ;$C0DC4E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA UNKNOWN_7E0002
	AND #$00FF
	BNE @UNKNOWN0
	LDA DAD_PHONE_TIMER
	BEQ @UNKNOWN0
	DEC DAD_PHONE_TIMER
@UNKNOWN0:
	LDA WINDOW_HEAD
	CMP #$FFFF
	BNE @UNKNOWN4
	LDA BATTLE_MODE_FLAG
	BNE @UNKNOWN4
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN4
	LDA BATTLE_SWIRL_FLAG
	BNE @UNKNOWN4
	LDY #.LOWORD(OVERWORLD_TASKS)
	STY $0E
	LDA #$0000
	STA $02
	BRA @UNKNOWN3
@UNKNOWN1:
	LDA RAM,Y
	BEQ @UNKNOWN2
	TYX
	DEC
	STA RAM,X
	BNE @UNKNOWN2
	INY
	INY
	MOVE_INT_YPTRSRC RAM, $06
	PHA
	MOVE_INT $06, UNKNOWN_7E00BC
	PLA
	JSL UNKNOWN_C09279
@UNKNOWN2:
	LDY $0E
	TYA
	CLC
	ADC #$0006
	TAY
	STY $0E
	INC $02
@UNKNOWN3:
	LDA $02
	CMP #$0004
	BCC @UNKNOWN1
@UNKNOWN4:
	PLD
	RTS
