
PROCESS_OVERWORLD_TASKS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA FRAME_COUNTER
	AND #$00FF
	BNE @UNKNOWN0
	LDA DAD_PHONE_TIMER
	BEQ @UNKNOWN0
	DEC DAD_PHONE_TIMER
@UNKNOWN0:
	LDA WINDOW_HEAD
	CMP #.LOWORD(-1)
	BNE @UNKNOWN4
	LDA BATTLE_MODE_FLAG
	BNE @UNKNOWN4
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN4
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @UNKNOWN4
	LDY #.LOWORD(OVERWORLD_TASKS)
	STY @LOCAL00
	LDA #0
	STA @VIRTUAL02
	BRA @UNKNOWN3
@UNKNOWN1:
	LDA a:overworld_task::frames_left,Y
	BEQ @UNKNOWN2
	TYX
	DEC
	STA a:overworld_task::frames_left,X
	BNE @UNKNOWN2
	INY ;overworld_task::function
	INY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	PHA
	MOVE_INT @VIRTUAL06, TEMP_FUNCTION_POINTER
	PLA
	JSL UNKNOWN_C09279
@UNKNOWN2:
	LDY @LOCAL00
	TYA
	CLC
	ADC #.SIZEOF(overworld_task)
	TAY
	STY @LOCAL00
	INC @VIRTUAL02
@UNKNOWN3:
	LDA @VIRTUAL02
	CMP #4
	BCC @UNKNOWN1
@UNKNOWN4:
	END_C_FUNCTION
