
PROCESS_QUEUED_INTERACTIONS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
.IF .DEFINED(JPN)
	STACK_RESERVE_INT32 "LOCALM2"
.ENDIF
	STACK_RESERVE_INT16 "LOCAL02"
	END_STACK_VARS
	LDA CURRENT_QUEUED_INTERACTION
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(queued_interaction)
	TAX
	LDA QUEUED_INTERACTIONS + queued_interaction::type,X
	STA @LOCAL02
	TXA
	CLC
	ADC #.LOWORD(QUEUED_INTERACTIONS) + queued_interaction::text_ptr
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
.IF .DEFINED(JPN)
	MOVE_INT @VIRTUAL06, @LOCALM2
.ENDIF
	LDA @LOCAL02
	STA CURRENT_QUEUED_INTERACTION_TYPE
	LDA CURRENT_QUEUED_INTERACTION
	INC
	AND #$0003
	STA CURRENT_QUEUED_INTERACTION
	LDA PLAYER_INTANGIBILITY_FRAMES
	AND #$FFFE
	STA PLAYER_INTANGIBILITY_FRAMES
	JSL UNKNOWN_C07C5B
	LDA @LOCAL02
	CMP #2
	BEQ @UNKNOWN0
	CMP #10
	BEQ @UNKNOWN1
	CMP #0
	BEQ @UNKNOWN3
	CMP #8
	BEQ @UNKNOWN3
	CMP #9
	BEQ @UNKNOWN3
	BRA @UNKNOWN4
@UNKNOWN0:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR DOOR_TRANSITION
	BRA @UNKNOWN4
@UNKNOWN1:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL UNKNOWN_C10004
.IF .DEFINED(JPN)
	LOADPTR MSG_SYS_PAPA_2H, @VIRTUAL06
	LDA @VIRTUAL06
	STA @VIRTUAL02
	MOVE_INT @LOCALM2, @VIRTUAL06
	LDA @VIRTUAL06
	CMP @VIRTUAL02
.ELSE
	LOADPTR MSG_SYS_PAPA_2H, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
.ENDIF
	BNE @UNKNOWN4
	LDA #1687
	STA DAD_PHONE_TIMER
	STZ DAD_PHONE_QUEUED
	BRA @UNKNOWN4
@UNKNOWN3:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL UNKNOWN_C10004
@UNKNOWN4:
	LDX #0
	LDA CURRENT_QUEUED_INTERACTION
	CMP NEXT_QUEUED_INTERACTION
	BEQ @UNKNOWN5
	LDX #1
@UNKNOWN5:
	STX PENDING_INTERACTIONS
	LDA #.LOWORD(-1)
	STA CURRENT_QUEUED_INTERACTION_TYPE
	END_C_FUNCTION
