
RED_FLASH:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN0
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @UNKNOWN0
	LDA PALETTES
	STA BACKGROUND_COLOUR_BACKUP
	LDA #RGBVAL 31, 0, 0
	STA PALETTES
	SEP #PROC_FLAGS::ACCUM8
	STZ TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA #8
	JSL PREPARE_PALETTE_UPLOAD
	LOADPTR RED_FLASH, $0E
	LDA #1
	JSL SCHEDULE_OVERWORLD_TASK
@UNKNOWN0:
	END_C_FUNCTION
