
RELOAD_HOTSPOTS: ;$C07213
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 15
	LDA #$0000
	STA $02
	JMP @UNKNOWN3
@UNKNOWN0:
	LDA $02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAY
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__ + game_state::active_hotspot_modes,Y
	STA $0E
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQL @UNKNOWN2
	LDA $02
	OPTIMIZED_MULT $04, .SIZEOF(active_hotspot)
	CLC
	ADC #.LOWORD(ACTIVE_HOTSPOTS)
	TAX
	LOADPTR MAP_HOTSPOTS, $06
	LDA __BSS_START__+game_state::active_hotspot_ids,Y
	AND #$00FF
	ASL
	ASL
	ASL
	CLC
	ADC $06
	STA $06
	LDA $0E
	AND #$00FF
	STA __BSS_START__,X
	MOVE_INT $06, $0A
	LDA [$0A]
	ASL
	ASL
	ASL
	STA a:active_hotspot::x1,X
	LDY #$0004
	LDA [$06],Y
	ASL
	ASL
	ASL
	STA a:active_hotspot::x2,X
	LDY #$0002
	LDA [$06],Y
	ASL
	ASL
	ASL
	STA a:active_hotspot::y1,X
	LDY #$0006
	LDA [$06],Y
	ASL
	ASL
	ASL
	STA a:active_hotspot::y2,X
	LDA $02
	ASL
	ASL
	CLC
	.IF .DEFINED(JPN)
		ADC #.LOWORD(GAME_STATE)
		CLC
		ADC #game_state::active_hotspot_pointers
	.ELSE
		ADC #.LOWORD(GAME_STATE) + game_state::active_hotspot_pointers
	.ENDIF
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, $06
	TXA
	CLC
	ADC #$000A
	TAY
	MOVE_INT_YPTRDEST $06, __BSS_START__
@UNKNOWN2:
	INC $02
@UNKNOWN3:
	LDA $02
	CMP #$0002
	BCCL @UNKNOWN0
	PLD
	RTL
