
DO_SECTOR_MUSIC_UPDATE:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA #$0001
	STA DO_MAP_MUSIC_FADE
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_MUSIC
	LDA NEXT_MAP_MUSIC_TRACK
	CMP CURRENT_MAP_MUSIC_TRACK
	BEQ @UNKNOWN0
	JSL WAIT_UNTIL_NEXT_FRAME
	JSL CHANGE_MAP_MUSIC
@UNKNOWN0:
	STZ DO_MAP_MUSIC_FADE
	RTS
