
SET_TELEPORT_STATE: ;$C0DD53
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 15
	SEP #PROC_FLAGS::ACCUM8
	STA $00
	LDA $1D
	STA $0E
	REP #PROC_FLAGS::ACCUM8
	LDA $00
	AND #$00FF
	STA TELEPORT_DESTINATION
	LDA $0E
	AND #$00FF
	STA TELEPORT_STYLE
	PLD
	RTL
