
SHOW_HP_ALERT: ;$C1DBBB
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	TAY
	STY $12
	JSL UNKNOWN_C0943C
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	LDX #$0004
	LDY $12
	TYA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT)
	JSR a:.LOWORD(UNKNOWN_C1AC4A)
	DISPLAY_TEXT_PTR TEXT_ALERT_CONDITION_CRITICAL
	JSR a:.LOWORD(CLOSE_FOCUS_WINDOW)
	JSL UNKNOWN_C12DD5
	JSL UNKNOWN_C09451
	PLD
	RTL
