
TALK_TO:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_RETURN_INT32
	END_STACK_VARS
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	JSL FIND_NEARBY_TALKABLE_TPT_ENTRY
	LDA INTERACTING_NPC_ID
	BEQL @UNKNOWN4
	LDA INTERACTING_NPC_ID
	CMP #.LOWORD(-1)
	BEQL @UNKNOWN4
	LDA INTERACTING_NPC_ID
	CMP #.LOWORD(-2)
	BNE @UNKNOWN2
	MOVE_INT MAP_OBJECT_TEXT, @VIRTUAL0A
	BRA @UNKNOWN4
@UNKNOWN2:
	LOADPTR NPC_CONFIG_TABLE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA INTERACTING_NPC_ID
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP #NPC_TYPE::PERSON
	BEQ @UNKNOWN3
	CMP #NPC_TYPE::ITEM_BOX
	BEQ @UNKNOWN4
	CMP #NPC_TYPE::OBJECT
	BEQ @UNKNOWN4
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA INTERACTING_NPC_ENTITY
	JSL UNKNOWN_C042C2
	LDA INTERACTING_NPC_ID
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
	CLC
	ADC #npc_config::text_pointer
	MOVE_INTX @LOCAL00, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
@UNKNOWN4:
	MOVE_INT @VIRTUAL0A, @RETURNVAL
	END_C_FUNCTION
