
RAND_LIMIT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int limit
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	TAX
	STX @LOCAL00
	JSR RAND_LONG
	LDX @LOCAL00
	JSR TRUNCATE_16_TO_8
	END_C_FUNCTION
