
UNKNOWN_C200D9:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STZ RENDER_HPPP_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	LDA #$FFFF
	STA CURRENT_FLASHING_ENEMY_ROW
	STA CURRENT_FLASHING_ENEMY
	STA CURRENT_FLASHING_ROW
	STA UNREAD_7E89CC
	STA BATTLE_MENU_CURRENT_CHARACTER_ID
	SEP #PROC_FLAGS::ACCUM8
	STZ INSTANT_PRINTING
	STZ REDRAW_ALL_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	STZ ACTIONSCRIPT_STATE
	SEP #PROC_FLAGS::ACCUM8
	STZ UPLOAD_HPPP_METER_TILES
	REP #PROC_FLAGS::ACCUM8
	LDA #$FFFF
	STA WINDOW_HEAD
	STA WINDOW_TAIL
	LDA #0
	STA @LOCAL01
	BRA @UNKNOWN1
@UNKNOWN0:
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA #$FFFF
	STA WINDOW_STATS+window_stats::id,X
	LDA @LOCAL01
	INC
	STA @LOCAL01
@UNKNOWN1:
	CMP #8
	BNE @UNKNOWN0
	LDA #0
	STA @LOCAL01
	BRA @UNKNOWN3
@UNKNOWN2:
	ASL
	TAX
	LDA #$FFFF
	STA OPEN_WINDOW_TABLE,X
	LDA @LOCAL01
	INC
	STA @LOCAL01
@UNKNOWN3:
.IF .DEFINED(JPN)
	CMP #52
.ELSE
	CMP #53
.ENDIF
	BNE @UNKNOWN2
	LDA #0
	STA @LOCAL01
	BRA @UNKNOWN5
@UNKNOWN4:
	ASL
	TAX
	LDA #$FFFF
	STA TITLED_WINDOWS,X
	LDA @LOCAL01
	INC
	STA @LOCAL01
@UNKNOWN5:
.IF .DEFINED(JPN)
	CMP #4
.ELSE
	CMP #5
.ENDIF
	BNE @UNKNOWN4
	LDA #$FFFF
	STA PAGINATION_WINDOW
	STA PAGINATION_ANIMATION_FRAME
	LDY #.LOWORD(BG2_BUFFER)
	LDX #$0380
	BRA @UNKNOWN7
@UNKNOWN6:
	LDA #0
	STA __BSS_START__,Y
	INY
	INY
	DEX
@UNKNOWN7:
	BNE @UNKNOWN6
	LDA #0
	STA @LOCAL01
	BRA @UNKNOWN9
@UNKNOWN8:
	OPTIMIZED_MULT $04, .SIZEOF(menu_option)
	TAX
	STZ MENU_OPTIONS,X
	LDA @LOCAL01
	INC
	STA @LOCAL01
@UNKNOWN9:
	CMP #70
	BNE @UNKNOWN8
	LDA #0
	STA @LOCAL00
	BRA @UNKNOWN13
@UNKNOWN10:
	LDX #0
	STX @LOCAL01
	BRA @UNKNOWN12
@UNKNOWN11:
	STX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA UNKNOWN_7E9D23,X
	LDX @LOCAL01
	INX
	STX @LOCAL01
@UNKNOWN12:
	CPX #32
	BCC @UNKNOWN11
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	INC
	STA @LOCAL00
@UNKNOWN13:
.IF .DEFINED(JPN)
	CMP #4
.ELSE
	CMP #8
.ENDIF
	BCC @UNKNOWN10
	STZ UNKNOWN_7E9E29
	STZ UNKNOWN_7E9E27
	STZ VWF_TILE
	STZ VWF_X
	STZ BLINKING_TRIANGLE_FLAG
	LDA #1
	STA TEXT_SOUND_MODE
	STZ BATTLE_MODE_FLAG
	STZ TEXT_PROMPT_WAITING_FOR_INPUT
	LDA #$FFFF
	STA CURRENT_FOCUS_WINDOW
.IF .DEFINED(USA)
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA CHARACTER_PADDING
	JSL UNKNOWN_C43F53
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA UNREAD_7E9651
	REP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA ENABLE_WORD_WRAP
	SEP #PROC_FLAGS::ACCUM8
	STZ EXTRA_TICK_ON_WINDOW_CLOSE
	STZ VWF_INDENT_NEW_LINE
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
	LDA a:window_stats::current_option,X
	LDY #.SIZEOF(menu_option)
	JSL MULT168
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ FORCE_LEFT_TEXT_ALIGNMENT
	STZ __BSS_START__+44,X
	STZ NEW_TEXT_PIXEL_OFFSET
	STZ LAST_TEXT_PIXEL_OFFSET_SET
	STZ FORCE_CENTRE_TEXT_ALIGNMENT
	STZ LAST_PRINTED_CHARACTER
	STZ PRINT_TARGET_ARTICLE
	STZ PRINT_ATTACKER_ARTICLE
.IF !.DEFINED(PROTOTYPE19950327)
	STZ FORCE_NORMAL_FONT_FOR_LENGTH_CALCULATIONS
	STZ SKIP_ADDING_COMMAND_TEXT
.ENDIF
	REP #PROC_FLAGS::ACCUM8
.ENDIF
	END_C_FUNCTION
