
UNKNOWN_C2077D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY CURRENTLY_DRAWN_HPPP_WINDOWS
	STY @LOCAL01
	LDX #0
	STX @LOCAL00
	BRA @UNKNOWN2
@UNKNOWN0:
	TYA
	AND #$0001
	BEQ @UNKNOWN1
	TXA
	JSR DRAW_HP_PP_WINDOW
@UNKNOWN1:
	LDY @LOCAL01
	TYA
	LSR
	TAY
	STY @LOCAL01
	LDX @LOCAL00
	INX
	STX @LOCAL00
@UNKNOWN2:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	STA @VIRTUAL02
	TXA
	CMP @VIRTUAL02
	BNE @UNKNOWN0
	END_C_FUNCTION
