
UNKNOWN_C209A0: ;$C209A0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	PHA
	TDC
	ADC #$FFEE
	TCD
	PLA
	ASL
	TAX
	LDA .LOWORD(WINDOW_EXISTENCE_TABLE),X
	CMP #$FFFF
	BNE @UNKNOWN4
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS_TABLE)
	TAX
	STX $10
	LDY a:.LOWORD(RAM)+53,X
	STY $0E
	LDY a:.LOWORD(RAM)+12,X
	LDA a:.LOWORD(RAM)+10,X
	JSL MULT16
	STA $02
	BRA @UNKNOWN2
@UNKNOWN0:
	LDY $0E
	LDA a:.LOWORD(RAM),Y
	BEQ @UNKNOWN1
	JSL UNKNOWN_C44E4D
@UNKNOWN1:
	LDA #$0040
	LDY $0E
	STA a:.LOWORD(RAM),Y
	INY
	INY
	STY $0E
	LDA $02
	DEC
	STA $02
@UNKNOWN2:
	LDA $02
	BNE @UNKNOWN0
	LDX $10
	LDA a:.LOWORD(RAM)+59,X
	AND #$00FF
	BEQ @UNKNOWN3
	AND #$00FF
	DEC
	ASL
	TAX
	LDA #$FFFF
	STA .LOWORD(WINDOW_EXISTENCE_TABLE)+106,X
@UNKNOWN3:
	LDX $10
	SEP #PROC_FLAGS::ACCUM8
	STZ a:.LOWORD(RAM)+60,X
	STZ a:.LOWORD(RAM)+59,X
	LDA #$0001
	STA .LOWORD(UNKNOWN_7E9623)
	JSL UNKNOWN_C07C5B
@UNKNOWN4:
	PLD
	RTL
