
UNKNOWN_C216AD:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL00
	TXA
	JSL CHANGE_MUSIC
	LDX @LOCAL00
	STX UNKNOWN_7E5DD4
	STX UNKNOWN_7E5DD6
	END_C_FUNCTION
