
UNKNOWN_C22351:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	TAX
	DEX
	STX @LOCAL01
	LDA #0
	STA @LOCAL00
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@UNKNOWN1:
	STA @VIRTUAL02
	LDA #14
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN4
	LDA @LOCAL00
	STA @VIRTUAL02
	LDX @LOCAL01
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BNE @UNKNOWN0
@UNKNOWN4:
	LDA @LOCAL00
	END_C_FUNCTION
