
UNKNOWN_C22562: ;$C22562
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAX
	CPX #$FFFF
	BNE @UNKNOWN0
	LDX #$0000
@UNKNOWN0:
	TXA
	SEP #PROC_FLAGS::ACCUM8
	STA .LOWORD(UNKNOWN_7E9CD0)
	REP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(UNKNOWN_7E9CD6)
	AND #$00FF
	STA $0E
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(CHAR_STRUCT)+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	STA .LOWORD(UNKNOWN_7E9CD1)
	LDA .LOWORD(CHAR_STRUCT)+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	STA .LOWORD(UNKNOWN_7E9CD2)
	LDA .LOWORD(CHAR_STRUCT)+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	STA .LOWORD(UNKNOWN_7E9CD3)
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	JSL UNKNOWN_C1A1D8
	PLD
	RTL
