
UNKNOWN_C226C5:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAX
	LDA CURRENT_INTERACTING_EVENT_FLAG
	JSL SET_EVENT_FLAG
	TAX
	STX @LOCAL00
	LDA INTERACTING_NPC_ENTITY
	JSL UNKNOWN_C0C30C
	LDX @LOCAL00
	TXA
	END_C_FUNCTION
