
UNKNOWN_C23E32:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	CMP @VIRTUAL0A+2
	BNE @UNKNOWN0
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
@UNKNOWN0:
	BEQ @UNKNOWN4
	LDX #0
	STX @LOCAL00
	BRA @UNKNOWN2
@UNKNOWN1:
	TXA
	JSL IS_CHAR_TARGETTED
	CMP #0
	BNE @UNKNOWN3
	LDX @LOCAL00
	INX
	STX @LOCAL00
@UNKNOWN2:
	CPX #BATTLER_COUNT
	BCC @UNKNOWN1
@UNKNOWN3:
	LDX @LOCAL00
	TXA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	STA CURRENT_TARGET
	JSL FIX_TARGET_NAME
@UNKNOWN4:
	END_C_FUNCTION
