
UNKNOWN_C2437E: ;$C2437E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 21
	LDX CURRENT_ATTACKER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNEL @UNKNOWN3
	LDX CURRENT_ATTACKER
	LDA a:battler::npc_id,X
	AND #$00FF
	BNEL @UNKNOWN3
	LDX CURRENT_ATTACKER
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__+7,X
	STA $00
	REP #PROC_FLAGS::ACCUM8
	LDA $00
	AND #$00FF
	BEQL @UNKNOWN3
	LDX CURRENT_ATTACKER
	LDA __BSS_START__,X
	TAY
	STY $13
	LDX CURRENT_ATTACKER
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::current_action_argument,X
	STA $12
	PHA
	REP #PROC_FLAGS::ACCUM8
	LDA $00
	AND #$00FF
	DEC
	STA $02
	TYA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT)+char_struct::items
	CLC
	ADC $02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	SEP #PROC_FLAGS::INDEX8
	PLX
	STX $00
	CMP $00
	BNE @UNKNOWN3
	REP #PROC_FLAGS::ACCUM8
	LDA $12
	AND #$00FF
	STA $10
	OPTIMIZED_MULT $04, .SIZEOF(item)
	CLC
	ADC #item::flags
	REP #PROC_FLAGS::INDEX8
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #ITEM_FLAGS::CONSUMED_ON_USE
	BEQ @UNKNOWN3
	LDA $10
	TAX
	LDY $13
	TYA
	JSL UNKNOWN_C3EE14
	CMP #$0000
	BEQ @UNKNOWN3
	LDX CURRENT_ATTACKER
	LDA __BSS_START__+7,X
	AND #$00FF
	TAX
	STX $0E
	LDX CURRENT_ATTACKER
	LDA __BSS_START__,X
	LDX $0E
	JSL REDIRECT_REMOVE_ITEM_FROM_INVENTORY
@UNKNOWN3:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	PLD
	RTL
