
UNKNOWN_C290C6: ;$C290C6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 24
	LDA .LOWORD(MIRROR_ENEMY)
	BEQ @UNKNOWN3
	LDX #.LOWORD(BATTLERS_TABLE)
	STX $16
	LDY #$0000
	BRA @UNKNOWN2
@UNKNOWN0:
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @UNKNOWN1
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @UNKNOWN1
	LDA a:battler::id,X
	CMP #$0004
	BNE @UNKNOWN1
	STZ .LOWORD(MIRROR_ENEMY)
	TXA
	PROMOTENEARPTRA $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	PROMOTENEARPTR .LOWORD(UNKNOWN_7EAA14), $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $12
	JSL COPY_MIRROR_DATA
	LDX $16
	STZ a:battler::current_action,X
	DISPLAY_BATTLE_TEXT_PTR TEXT_BATTLE_RETURNED_ORIGINAL_FORM
	BRA @UNKNOWN3
@UNKNOWN1:
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	STX $16
	INY
@UNKNOWN2:
	CPY #$0020
	BCC @UNKNOWN0
@UNKNOWN3:
	JSL TARGET_ALL
	JSR a:.LOWORD(REMOVE_DEAD_TARGETTING)
	LOADPTR BTLACT_NEUTRALIZE, $0E
	JSL UNKNOWN_C240A4
	MOVE_INT_CONSTANT 0, .LOWORD(BATTLER_TARGET_FLAGS)
	PLD
	RTL
