
UNKNOWN_C2C32C: ;$C2C32C
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STA $12
	LDA #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 8) + battler::sprite_x
	STA $02
	LDX $02
	LDA __BSS_START__,X
	AND #$00FF
	STA $10
	LDY #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 8) + battler::sprite_y
	STY $0E
	LDA __BSS_START__,Y
	AND #$00FF
	STA $04
	LDX #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 8)
	LDA $12
	JSL BATTLE_INIT_ENEMY_STATS
	LDA $10
	SEP #PROC_FLAGS::ACCUM8
	LDX $02
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA $04
	SEP #PROC_FLAGS::ACCUM8
	LDY $0E
	STA __BSS_START__,Y
	LDA #$0001
	STA BATTLERS_TABLE + (.SIZEOF(battler) * 8) + battler::has_taken_turn
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTS
