
UNKNOWN_C2D0AC:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #.LOWORD(LETTERBOX_HDMA_TABLE)
	SEP #PROC_FLAGS::ACCUM8
	LDA LETTERBOX_TOP_END
	STA __BSS_START__,X
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA LETTERBOX_NONVISIBLE_SCREEN_VALUE
	STA __BSS_START__,X
	INX
	INX
	LDA LETTERBOX_BOTTOM_START
	SEC
	SBC LETTERBOX_TOP_END
	STA @LOCAL00
	BRA @UNKNOWN1
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$007F
	STA __BSS_START__,X
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA LETTERBOX_VISIBLE_SCREEN_VALUE
	STA __BSS_START__,X
	INX
	INX
	LDA @LOCAL00
	SEC
	SBC #$007F
	STA @LOCAL00
@UNKNOWN1:
	CMP #$0080
	BCS @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	STA __BSS_START__,X
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA LETTERBOX_VISIBLE_SCREEN_VALUE
	STA __BSS_START__,X
	INX
	INX
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA __BSS_START__,X
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA LETTERBOX_NONVISIBLE_SCREEN_VALUE
	STA __BSS_START__,X
	INX
	INX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
