
UNKNOWN_C2DAE3:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	END_STACK_VARS
	LDX #.LOWORD(LOADED_BG_DATA_LAYER1) + loaded_bg_data::distortion_styles
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	LDY #.LOWORD(LOADED_BG_DATA_LAYER1) + loaded_bg_data::distortion_styles + 3
	LDA __BSS_START__,Y
	STA __BSS_START__,X
	STZ LOADED_BG_DATA_LAYER1 + loaded_bg_data::distortion_styles + 1
	REP #PROC_FLAGS::ACCUM8
	LDA #1
	STA LOADED_BG_DATA_LAYER1 + loaded_bg_data::distortion_duration_left
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
