
UNKNOWN_C2DB14:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA LOADED_BG_DATA_LAYER1 + loaded_bg_data::palette_pointer
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #.SIZEOF(loaded_bg_data::palette)
	LDA #.LOWORD(LOADED_BG_DATA_LAYER1) + loaded_bg_data::palette
	JSL MEMCPY16
	END_C_FUNCTION
