
UNKNOWN_C2DF2E:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;loaded_bg_data* data
	STACK_RESERVE_PARAM_INT16 ;int newColour
	STACK_RESERVE_PARAM_INT16 ;int index
	END_STACK_VARS
	STY @LOCAL06
	STX @VIRTUAL02
	STA @LOCAL05
	LDA @VIRTUAL02
	CMP #$FFFF
	BEQ @UNKNOWN0
	LDA @VIRTUAL02
	BNE @UNKNOWN1
@UNKNOWN0:
	LDA @LOCAL06
	ASL
	STA @LOCAL06
	CLC
	ADC @LOCAL05
	TAX
	LDA @VIRTUAL02
	STA __BSS_START__ + loaded_bg_data::palette,X
	LDY #loaded_bg_data::palette_pointer
	LDA @LOCAL06
	CLC
	ADC (@LOCAL05),Y
	TAX
	LDA @VIRTUAL02
	STA __BSS_START__,X
	JMP @UNKNOWN7
@UNKNOWN1:
	LDA @VIRTUAL02
	CMP #$0100
	BNE @UNKNOWN2
	LDA @LOCAL06
	ASL
	STA @LOCAL04
	CLC
	ADC @LOCAL05
	TAX
	LDY __BSS_START__ + loaded_bg_data::palette2,X
	STY @LOCAL03
	TYA
	STA __BSS_START__ + loaded_bg_data::palette,X
	LDY #loaded_bg_data::palette_pointer
	LDA @LOCAL04
	CLC
	ADC (@LOCAL05),Y
	TAX
	LDY @LOCAL03
	TYA
	STA __BSS_START__,X
	JMP @UNKNOWN7
@UNKNOWN2:
	LDA @LOCAL06
	ASL
	CLC
	ADC @LOCAL05
	STA @VIRTUAL04
	STA @LOCAL03
	LDX @VIRTUAL04
	LDA __BSS_START__ + loaded_bg_data::palette2,X
	STA @LOCAL04
	AND #$001F
	TAX
	STX @LOCAL02
	LDA @LOCAL04
	LSR
	LSR
	LSR
	LSR
	LSR
	AND #$001F
	TAY
	STY @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDA #10
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL04
	JSL ASR8_UNKNOWN1
	AND #$001F
	STA @LOCAL04
	REP #PROC_FLAGS::INDEX8
	LDY @VIRTUAL02
	LDX @LOCAL02
	TXA
	JSL MULT16
	XBA
	AND #$00FF
	TAX
	STX @LOCAL02
	LDY @LOCAL01
	TYA
	LDY @VIRTUAL02
	JSL MULT16
	XBA
	AND #$00FF
	TAY
	STY @LOCAL01
	LDY @VIRTUAL02
	LDA @LOCAL04
	JSL MULT16
	XBA
	AND #$00FF
	STA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDA #10
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	JSL ASL16_ENTRY2
	STA @VIRTUAL02
	REP #PROC_FLAGS::INDEX8
	LDY @LOCAL01
	TYA
	ASL
	ASL
	ASL
	ASL
	ASL
	STA @VIRTUAL04
	LDX @LOCAL02
	TXA
	CLC
	ADC @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	LDX @LOCAL03
	STX @VIRTUAL04
	STA __BSS_START__ + loaded_bg_data::palette,X
	LDY #3
	LDA (@LOCAL05),Y
	AND #$00FF
	CMP #2
	BNE @UNKNOWN4
	LDY #6
	LDA (@LOCAL05),Y
	AND #$00FF
	CMP @LOCAL06
	BGT @UNKNOWN4
	LDY #7
	LDA (@LOCAL05),Y
	AND #$00FF
	CMP @LOCAL06
	BCS @UNKNOWN7
@UNKNOWN4:
	LDY #3
	LDA (@LOCAL05),Y
	AND #$00FF
	BEQ @UNKNOWN6
	LDY #4
	LDA (@LOCAL05),Y
	AND #$00FF
	CMP @LOCAL06
	BGT @UNKNOWN6
	LDY #5
	LDA (@LOCAL05),Y
	AND #$00FF
	CMP @LOCAL06
	BCS @UNKNOWN7
@UNKNOWN6:
	LDA @LOCAL06
	ASL
	STA @LOCAL06
	LDY #loaded_bg_data::palette_pointer
	CLC
	ADC (@LOCAL05),Y
	PHA
	LDA @LOCAL06
	CLC
	ADC @LOCAL05
	TAX
	LDA __BSS_START__ + loaded_bg_data::palette,X
	PLX
	STA __BSS_START__,X
@UNKNOWN7:
	END_C_FUNCTION
