
UNKNOWN_C2E8C4: ;$C2E8C4
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @VIRTUAL02
	TAY
	JSL UNKNOWN_C4A67E
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA UNKNOWN_7EAECA
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
