
UNKNOWN_C2EA74: ;$C2EA74
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDX #$0000
	TXA
	JSL UNKNOWN_C4A67E
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0013
	STA UNKNOWN_7EAEC8
	REP #PROC_FLAGS::ACCUM8
	LDA UNKNOWN_7EAEEF
	AND #$00FF
	BEQ @UNKNOWN0
	MOVE_INT_CONSTANT UNKNOWN_C4A652, UNKNOWN_7EAECC
	BRA @UNKNOWN1
@UNKNOWN0:
	MOVE_INT_CONSTANT UNKNOWN_C4A626, UNKNOWN_7EAECC
@UNKNOWN1:
	RTL
