
UNKNOWN_C2EACF:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	LDA PSI_ANIMATION_STATE + psi_animation_state::time_until_next_frame
	AND #$00FF
	BNE @UNKNOWN0
	LDA FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	AND #$00FF
	BEQ @UNKNOWN1
@UNKNOWN0:
	LDA #1
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA #0
@UNKNOWN2:
	END_C_FUNCTION
