
UNKNOWN_C2EAAA:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STZ FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT_CONSTANT NULL, LOADED_OVAL_WINDOW
	LDA #3
	JSL UNKNOWN_C0AE34
	LDX #0
	TXA
	JSL SET_WINDOW_MASK
	END_C_FUNCTION
