
UNKNOWN_C2EA15:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL00
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA ACTIVE_OVAL_WINDOW
	LDX #0
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL UNKNOWN_C4A67E
	SEP #PROC_FLAGS::ACCUM8
	LDA #19
	STA SWIRL_MASK_SETTINGS
	LDY @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	TYA
	CMP #2
	BEQ @UNKNOWN0
	CMP #1
	BEQ @UNKNOWN1
	BRA @UNKNOWN2
@UNKNOWN0:
	MOVE_INT_CONSTANT UNKNOWN_C3F819, LOADED_OVAL_WINDOW
	BRA @UNKNOWN3
@UNKNOWN1:
	MOVE_INT_CONSTANT UNKNOWN_C4A5FA, LOADED_OVAL_WINDOW
	BRA @UNKNOWN3
@UNKNOWN2:
	MOVE_INT_CONSTANT UNKNOWN_C4A5CE, LOADED_OVAL_WINDOW
@UNKNOWN3:
	END_C_FUNCTION
