
UNKNOWN_C2EA74:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDX #0
	TXA
	JSL UNKNOWN_C4A67E
	SEP #PROC_FLAGS::ACCUM8
	LDA #19
	STA SWIRL_MASK_SETTINGS
	REP #PROC_FLAGS::ACCUM8
	LDA ACTIVE_OVAL_WINDOW
	AND #$00FF
	BEQ @UNKNOWN0
	MOVE_INT_CONSTANT UNKNOWN_C4A652, LOADED_OVAL_WINDOW
	BRA @UNKNOWN1
@UNKNOWN0:
	MOVE_INT_CONSTANT UNKNOWN_C4A626, LOADED_OVAL_WINDOW
@UNKNOWN1:
	END_C_FUNCTION
