
UNKNOWN_C2F8F9:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDA #$007E
	JSL UNKNOWN_C088A5
	JSL OAM_CLEAR
	LDA #0
	JSR RENDER_BATTLE_SPRITE_ROW
	LDA #1
	JSR RENDER_BATTLE_SPRITE_ROW
	JSL UPDATE_SCREEN
	END_C_FUNCTION
