
UNKNOWN_C2F917:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	STZ NUM_BATTLERS_IN_BACK_ROW
	STZ NUM_BATTLERS_IN_FRONT_ROW
	LDA #8
	STA @LOCAL02
	BRA @UNKNOWN3
@UNKNOWN0:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @UNKNOWN2
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	CMP #1
	BEQ @UNKNOWN2
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @UNKNOWN2
	LDA BATTLERS_TABLE+battler::row,X
	AND #$00FF
	BEQ @UNKNOWN1
	INC NUM_BATTLERS_IN_BACK_ROW
	BRA @UNKNOWN2
@UNKNOWN1:
	INC NUM_BATTLERS_IN_FRONT_ROW
@UNKNOWN2:
	LDA @LOCAL02
	INC
	STA @LOCAL02
@UNKNOWN3:
	CMP #32
	BCC @UNKNOWN0
	STZ @LOCAL01
	LDA #0
	STA @VIRTUAL02
	JMP @UNKNOWN9
@UNKNOWN4:
	LDA #$FFFF
	STA @VIRTUAL04
	LDY #8
	STY @LOCAL02
	BRA @UNKNOWN8
@UNKNOWN5:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @UNKNOWN7
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	CMP #1
	BEQ @UNKNOWN7
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @UNKNOWN7
	LDA BATTLERS_TABLE+battler::row,X
	AND #$00FF
	BNE @UNKNOWN7
	LDA BATTLERS_TABLE+battler::sprite_x,X
	AND #$00FF
	CMP @LOCAL01
	BLTEQ @UNKNOWN7
	CMP @VIRTUAL04
	BGT @UNKNOWN7
	LDY @LOCAL02
	STY @LOCAL00
	STA @VIRTUAL04
@UNKNOWN7:
	LDY @LOCAL02
	INY
	STY @LOCAL02
@UNKNOWN8:
	CPY #32
	BCC @UNKNOWN5
	LDA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA FRONT_ROW_BATTLERS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LSR
	LSR
	LSR
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA BATTLER_FRONT_ROW_X_POSITIONS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::sprite,X
	JSR GET_BATTLE_SPRITE_HEIGHT
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDA #18
	SEC
	SBC @VIRTUAL00
	LDX @VIRTUAL02
	STA BATTLER_FRONT_ROW_Y_POSITIONS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	STA @LOCAL01
	INC @VIRTUAL02
@UNKNOWN9:
	LDA @VIRTUAL02
	CMP NUM_BATTLERS_IN_FRONT_ROW
	BCCL @UNKNOWN4
	STZ @LOCAL01
	LDA #0
	STA @VIRTUAL02
	JMP @UNKNOWN16
@UNKNOWN11:
	LDA #$FFFF
	STA @VIRTUAL04
	LDY #8
	STY @LOCAL02
	BRA @UNKNOWN15
@UNKNOWN12:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @UNKNOWN14
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @UNKNOWN14
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @UNKNOWN14
	LDA BATTLERS_TABLE+battler::row,X
	AND #$00FF
	BEQ @UNKNOWN14
	LDA BATTLERS_TABLE+battler::sprite_x,X
	AND #$00FF
	CMP @LOCAL01
	BLTEQ @UNKNOWN14
	CMP @VIRTUAL04
	BGT @UNKNOWN14
	LDY @LOCAL02
	STY @LOCAL00
	STA @VIRTUAL04
@UNKNOWN14:
	LDY @LOCAL02
	INY
	STY @LOCAL02
@UNKNOWN15:
	CPY #32
	BCC @UNKNOWN12
	LDA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA BACK_ROW_BATTLERS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LSR
	LSR
	LSR
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA BATTLER_BACK_ROW_X_POSITIONS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::sprite,X
	JSR GET_BATTLE_SPRITE_HEIGHT
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDA #16
	SEC
	SBC @VIRTUAL00
	LDX @VIRTUAL02
	STA BATTLER_BACK_ROW_Y_POSITIONS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	STA @LOCAL01
	INC @VIRTUAL02
@UNKNOWN16:
	LDA @VIRTUAL02
	CMP NUM_BATTLERS_IN_BACK_ROW
	BCCL @UNKNOWN11
	END_C_FUNCTION
