
UNKNOWN_C2F917: ;$C2F917
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 20
	STZ NUM_BATTLERS_IN_FRONT_ROW
	STZ NUM_BATTLERS_IN_BACK_ROW
	LDA #$0008
	STA $12
	BRA @UNKNOWN3
@UNKNOWN0:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @UNKNOWN2
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN2
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN2
	LDA BATTLERS_TABLE+battler::row,X
	AND #$00FF
	BEQ @UNKNOWN1
	INC NUM_BATTLERS_IN_FRONT_ROW
	BRA @UNKNOWN2
@UNKNOWN1:
	INC NUM_BATTLERS_IN_BACK_ROW
@UNKNOWN2:
	LDA $12
	INC
	STA $12
@UNKNOWN3:
	CMP #$0020
	BCC @UNKNOWN0
	STZ $10
	LDA #$0000
	STA $02
	JMP @UNKNOWN9
@UNKNOWN4:
	LDA #$FFFF
	STA $04
	LDY #$0008
	STY $12
	BRA @UNKNOWN8
@UNKNOWN5:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @UNKNOWN7
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN7
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN7
	LDA BATTLERS_TABLE+battler::row,X
	AND #$00FF
	BNE @UNKNOWN7
	LDA BATTLERS_TABLE+battler::sprite_x,X
	AND #$00FF
	CMP $10
	BLTEQ @UNKNOWN7
	CMP $04
	BGT @UNKNOWN7
	LDY $12
	STY $0E
	STA $04
@UNKNOWN7:
	LDY $12
	INY
	STY $12
@UNKNOWN8:
	CPY #$0020
	BCC @UNKNOWN5
	LDA $0E
	SEP #PROC_FLAGS::ACCUM8
	LDX $02
	STA BACK_ROW_BATTLERS,X
	REP #PROC_FLAGS::ACCUM8
	LDA $04
	LSR
	LSR
	LSR
	SEP #PROC_FLAGS::ACCUM8
	LDX $02
	STA UNKNOWN_7EAD5A,X
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::sprite,X
	JSR GET_BATTLE_SPRITE_HEIGHT
	SEP #PROC_FLAGS::ACCUM8
	STA $00
	LDA #$0012
	SEC
	SBC $00
	LDX $02
	STA UNKNOWN_7EAD62,X
	REP #PROC_FLAGS::ACCUM8
	LDA $04
	STA $10
	INC $02
@UNKNOWN9:
	LDA $02
	CMP NUM_BATTLERS_IN_BACK_ROW
	BCCL @UNKNOWN4
	STZ $10
	LDA #$0000
	STA $02
	JMP @UNKNOWN16
@UNKNOWN11:
	LDA #$FFFF
	STA $04
	LDY #$0008
	STY $12
	BRA @UNKNOWN15
@UNKNOWN12:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @UNKNOWN14
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @UNKNOWN14
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN14
	LDA BATTLERS_TABLE+battler::row,X
	AND #$00FF
	BEQ @UNKNOWN14
	LDA BATTLERS_TABLE+battler::sprite_x,X
	AND #$00FF
	CMP $10
	BLTEQ @UNKNOWN14
	CMP $04
	BGT @UNKNOWN14
	LDY $12
	STY $0E
	STA $04
@UNKNOWN14:
	LDY $12
	INY
	STY $12
@UNKNOWN15:
	CPY #$0020
	BCC @UNKNOWN12
	LDA $0E
	SEP #PROC_FLAGS::ACCUM8
	LDX $02
	STA FRONT_ROW_BATTLERS,X
	REP #PROC_FLAGS::ACCUM8
	LDA $04
	LSR
	LSR
	LSR
	SEP #PROC_FLAGS::ACCUM8
	LDX $02
	STA UNKNOWN_7EAD6A,X
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::sprite,X
	JSR GET_BATTLE_SPRITE_HEIGHT
	SEP #PROC_FLAGS::ACCUM8
	STA $00
	LDA #$0010
	SEC
	SBC $00
	LDX $02
	STA UNKNOWN_7EAD72,X
	REP #PROC_FLAGS::ACCUM8
	LDA $04
	STA $10
	INC $02
@UNKNOWN16:
	LDA $02
	CMP NUM_BATTLERS_IN_FRONT_ROW
	BCCL @UNKNOWN11
	PLD
	RTL
