
UNKNOWN_C2FF9A:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_ATTRS
	AND #$0007
	CMP #3
	BCC @MINISPRITES
	LDA #1
	BRA @RETURN
@MINISPRITES:
	LDA #0
@RETURN:
	END_C_FUNCTION
