
HANDLE_FILE_DELETE_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_DELETE_CONFIRMATION
	JSR SET_INSTANT_PRINTING
	LDA #0
	JSR SET_CURRENT_WINDOW_PADDING
	SEP #PROC_FLAGS::ACCUM8
	MOVE_INT832 CURRENT_SAVE_SLOT, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	LDA #CHAR::COLON
	JSR PRINT_LETTER
	LDA #CHAR::SPACE
	JSR PRINT_LETTER
	LDA #1
	JSR DISPLAY_CHARACTER_NAME
	LOADPTR FILE_SELECT_TEXT_LEVEL, @LOCAL00
	LDA #5
	JSR PRINT_STRING
	LDA #1
	JSR SET_CURRENT_WINDOW_PADDING
	SEP #PROC_FLAGS::ACCUM8
	MOVE_INT832 PARTY_CHARACTERS+char_struct::level, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	LDX #1
	LDA #0
	JSR MOVE_CURRENT_TEXT_CURSOR
	LOADPTR FILE_SELECT_TEXT_ARE_YOU_SURE_DELETE, @LOCAL00
	LDA #13
	JSR PRINT_STRING
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	LOADPTR FILE_SELECT_TEXT_ARE_YOU_SURE_DELETE_NO, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDY #2
	LDX #0
	TXA
	JSR CREATE_NEW_MENU_OPTION_AT_POSITION_WITH_USER_DATA
	LOADPTR FILE_SELECT_TEXT_ARE_YOU_SURE_DELETE_YES, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDY #3
	LDX #0
	LDA #1
	JSR CREATE_NEW_MENU_OPTION_AT_POSITION_WITH_USER_DATA
	JSR PRINT_MENU_ITEMS
	LDA #1
	JSR SELECTION_MENU
	TAX
	STX @LOCAL02
	BEQ @UNKNOWN0
	LDA CURRENT_SAVE_SLOT
	AND #$00FF
	DEC
	JSL ERASE_SAVE
@UNKNOWN0:
	JSR CLOSE_FOCUS_WINDOW
	LDX @LOCAL02
	TXA
	END_C_FUNCTION
