.SEGMENT "BANK22"
.INCLUDE "common.asm"
.INCLUDE "symbols/audiopacks.inc.asm"

INSERT_AUDIO_PACK 108
INSERT_AUDIO_PACK 0
.IF .DEFINED(JPN)
	INSERT_AUDIO_PACK 110
	INSERT_AUDIO_PACK 6
.ELSE
	INSERT_AUDIO_PACK 36
	INSERT_AUDIO_PACK 18
.ENDIF
