.SEGMENT "BANK1E"
.INCLUDE "common.asm"
.INCLUDE "symbols/audiopacks.inc.asm"
.INCLUDE "symbols/map.inc.asm"

MAP_DATA_TILE_SET_GRAPHICS_6:
	BINARY "maps/gfx/6.gfx.lzhal"

MAP_DATA_TILE_SET_GRAPHICS_7:
	BINARY "maps/gfx/7.gfx.lzhal"

MAP_DATA_TILE_SET_GRAPHICS_8:
	BINARY "maps/gfx/8.gfx.lzhal"

MAP_DATA_TILE_SET_GRAPHICS_2:
	LOCALEBINARY "maps/gfx/2.gfx.lzhal"

MAP_DATA_TILE_SET_GRAPHICS_10:
	LOCALEBINARY "maps/gfx/10.gfx.lzhal"

MAP_DATA_TILE_SET_GRAPHICS_11:
	LOCALEBINARY "maps/gfx/11.gfx.lzhal"

MAP_DATA_TILE_ANIMATION_GFX_15:
	BINARY "maps/anim_gfx/15.gfx.lzhal"

MAP_DATA_TILE_ANIMATION_GFX_16:
	BINARY "maps/anim_gfx/16.gfx.lzhal"

MAP_DATA_TILE_ANIMATION_GFX_17:
	BINARY "maps/anim_gfx/17.gfx.lzhal"

MAP_DATA_TILE_ANIMATION_GFX_18:
	BINARY "maps/anim_gfx/18.gfx.lzhal"

MAP_DATA_TILE_ANIMATION_GFX_19:
	BINARY "maps/anim_gfx/19.gfx.lzhal"

.IF .DEFINED(USA)
	.IF .DEFINED(PROTOTYPE19950327)
		INSERT_AUDIO_PACK 152
	.ELSE
		INSERT_AUDIO_PACK 143
	.ENDIF
.ENDIF
