.SEGMENT "BANK24"
.INCLUDE "common.asm"
.INCLUDE "symbols/audiopacks.inc.asm"

INSERT_AUDIO_PACK 64
INSERT_AUDIO_PACK 42
INSERT_AUDIO_PACK 126
.IF .DEFINED(JPN)
	INSERT_AUDIO_PACK 36
	INSERT_AUDIO_PACK 128
.ELSE
	INSERT_AUDIO_PACK 125
	INSERT_AUDIO_PACK 155
.ENDIF
