
CC_0D: ;$C145EF
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	CPX #$0000
	BEQ @UNKNOWN0
	JSR GET_SECONDARY_MEMORY
	STORE_INT1632 $06
	BRA @UNKNOWN1
@UNKNOWN0:
	JSR GET_WORKING_MEMORY
@UNKNOWN1:
	MOVE_INT $06, $0E
	JSR SET_ARGUMENT_MEMORY
	LDA #NULL
	PLD
	RTS
