
CC_1F_52: ;$C144A3
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 22
	TXA
	JSR NUM_SELECT_PROMPT
	MOVE_INT_CONSTANT $FFFFFFFF, $0A
	CMP32 $06, $0A
	BNE @UNKNOWN1
	MOVE_INT_CONSTANT NULL, $06
	MOVE_INT $06, $12
	MOVE_INT $06, $0E
	JSR SET_WORKING_MEMORY
	MOVE_INT $12, $06
	MOVE_INT $06, $0E
	JSR SET_ARGUMENT_MEMORY
	BRA @UNKNOWN2
@UNKNOWN1:
	MOVE_INT $06, $0E
	JSR SET_WORKING_MEMORY
@UNKNOWN2:
	LDA #NULL
	PLD
	RTS
