
CC_1F_1F:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	LDA #2
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @UNKNOWN2
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1F_1F)
	BRA @UNKNOWN3
@UNKNOWN2:
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA CC_ARGUMENT_STORAGE+1
	AND #$00FF
	JSL ASL16_ENTRY2
	STA @VIRTUAL04
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	ORA @VIRTUAL04
	REP #PROC_FLAGS::INDEX8
	TAY
	STY @LOCAL00
	TYA
	JSL UNKNOWN_C46028
	LDX @VIRTUAL02
	JSL UNKNOWN_C4C91A
	LDX @VIRTUAL02
	LDY @LOCAL00
	TYA
	JSL UNKNOWN_C46125
	LDA #NULL
@UNKNOWN3:
	END_C_FUNCTION
