
CC_1F_1D: ;$C166DD
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 14
	TXA
	BEQ @ARG_IS_ZERO
	STORE_INT1632 $06
	BRA @ARG_IS_NONZERO
@ARG_IS_ZERO:
	JSR GET_WORKING_MEMORY
@ARG_IS_NONZERO:
	LDA $06
	JSL UNKNOWN_C4B519
	LDA #NULL
	PLD
	RTS
