
CC_1C_13: ;$C173C0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STX $12
	LDA #$0001
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @UNKNOWN2
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1C_13)
	BRA @UNKNOWN5
@UNKNOWN2:
	JSR GET_BLINKING_PROMPT
	CMP #$0000
	BEQ @UNKNOWN4
	LDX $12
	DEX
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	DEC
	JSL UNKNOWN_C3FAC9
	SIGN_EXTENDA1632 $06
	MOVE_INT $06, $0E
	JSR SET_WORKING_MEMORY
@UNKNOWN4:
	LDA #NULL
@UNKNOWN5:
	PLD
	RTS
