
CC_1D_18: ;$C16124
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 14
	CPX #$0000
	BEQ @ARG_IS_ZERO
	TXA
	BRA @ARG_IS_NONZERO
@ARG_IS_ZERO:
	JSR a:.LOWORD(GET_ARGUMENT_MEMORY)
	LDA $06
@ARG_IS_NONZERO:
	JSR a:.LOWORD(ESCARGO_EXPRESS_STORE)
	LDA #NULL
	PLD
	RTS
