
CC_18_05:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA #$0001
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @UNKNOWN2
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_18_05)
	BRA @UNKNOWN5
@UNKNOWN2:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	JSR UNKNOWN_C438A5
@UNKNOWN4:
	LDA #NULL
@UNKNOWN5:
	RTS
