
CC_19_22: ;$C168A0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	PHA
	TDC
	ADC #$FFEC
	TCD
	PLA
	TXA
	STA $12
	LDA #$0003
	CLC
	SBC .LOWORD(CC_ARGUMENT_GATHERING_LOOP_COUNTER)
	BVC @UNKNOWN0
	BPL @UNKNOWN2
	BRA @UNKNOWN1
@UNKNOWN0:
	BMI @UNKNOWN2
@UNKNOWN1:
	LDA $12
	SEP #PROC_FLAGS::ACCUM8
	LDX .LOWORD(CC_ARGUMENT_GATHERING_LOOP_COUNTER)
	STA .LOWORD(CC_ARGUMENT_STORAGE),X
	REP #PROC_FLAGS::ACCUM8
	INC .LOWORD(CC_ARGUMENT_GATHERING_LOOP_COUNTER)
	LDA #.LOWORD(CC_19_22)
	BRA @UNKNOWN7
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(CC_ARGUMENT_STORAGE)
	STA $00
	REP #PROC_FLAGS::ACCUM8
	LDA $00
	AND #$00FF
	BEQ @ARG_1_IS_ZERO
	SEP #PROC_FLAGS::ACCUM8
	LDA $00
	STA $06
	STZ $07
	STZ $08
	STZ $09
	BRA @ARG_1_IS_NONZERO
@ARG_1_IS_ZERO:
	JSR a:.LOWORD(GET_WORKING_MEMORY)
@ARG_1_IS_NONZERO:
	SEP #PROC_FLAGS::ACCUM8
	LDA $06
	STA $01
	LDA .LOWORD(CC_ARGUMENT_STORAGE)+1
	STA $00
	SEP #PROC_FLAGS::INDEX8
	LDY #$0008
	REP #PROC_FLAGS::ACCUM8
	LDA $12
	JSL ASL16_ENTRY2
	STA $02
	LDA .LOWORD(CC_ARGUMENT_STORAGE)+2
	AND #$00FF
	ORA $02
	BEQ @ARG_2_IS_ZERO
	STA $06
	STZ $08
	BRA @ARG_2_IS_NONZERO
@ARG_2_IS_ZERO:
	JSR a:.LOWORD(GET_ARGUMENT_MEMORY)
@ARG_2_IS_NONZERO:
	LDA $06
	REP #PROC_FLAGS::INDEX8
	TAY
	LDA $00
	AND #$00FF
	TAX
	DEX
	LDA $01
	AND #$00FF
	JSL UNKNOWN_C462E4
	INC
	STA $06
	STZ $08
	LDA $06
	STA $0E
	LDA $08
	STA $10
	JSR a:.LOWORD(SET_ARGUMENT_MEMORY)
	LDA #NULL
@UNKNOWN7:
	PLD
	RTS
