
CC_13_14:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL02
	TAY
	STY @LOCAL01
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA DEBUG
	BEQ @UNKNOWN1
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::R_BUTTON
	CMP #PAD::B_BUTTON | PAD::R_BUTTON
	BNE @UNKNOWN1
	STZ TEXT_PROMPT_WAITING_FOR_INPUT
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA TEXT_PROMPT_WAITING_FOR_INPUT
	BNE @UNKNOWN0
@UNKNOWN2:
	JSR CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
	LDX @LOCAL02
	BNE @UNKNOWN3
	LDA BLINKING_TRIANGLE_FLAG
	BEQ @UNKNOWN3
	LDA TEXT_SPEED_BASED_WAIT
	BEQ @UNKNOWN3
	LDA #0
	JSR UNKNOWN_C100FE
	JMP @UNKNOWN14
@UNKNOWN3:
	LDA BLINKING_TRIANGLE_FLAG
	BEQ @UNKNOWN4
	JSL PAUSE_MUSIC
@UNKNOWN4:
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @VIRTUAL02
	LDY @LOCAL01
	BNE @UNKNOWN7
	BRA @UNKNOWN6
@UNKNOWN5:
	JSL UNKNOWN_C12E42
@UNKNOWN6:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON | PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @UNKNOWN5
	JMP @UNKNOWN13
@UNKNOWN7:
	LOADPTR BLINKING_TRIANGLE_TILES + 0 * 2, @LOCAL00
	LDX @VIRTUAL02
	LDA a:window_stats::window_y,X
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::height,X
	OPTIMIZED_MULT @VIRTUAL04, 32
	STA @VIRTUAL04
	LDX @VIRTUAL02
	LDA a:window_stats::window_x,X
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::width,X
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 0, 1
	TAY
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDX #15
	STX @LOCAL01
	BRA @UNKNOWN9
@UNKNOWN8:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON | PAD::A_BUTTON | PAD::L_BUTTON
	BNE @UNKNOWN12
	JSL UNKNOWN_C12E42
	LDX @LOCAL01
	DEX
	STX @LOCAL01
@UNKNOWN9:
	BNE @UNKNOWN8
	LOADPTR BLINKING_TRIANGLE_TILES + 1 * 2, @LOCAL00
	LDX @VIRTUAL02
	LDA a:window_stats::window_y,X
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::height,X
	OPTIMIZED_MULT @VIRTUAL04, 32
	STA @VIRTUAL04
	LDX @VIRTUAL02
	LDA a:window_stats::window_x,X
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::width,X
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 0, 1
	TAY
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDX #10
	STX @LOCAL01
	BRA @UNKNOWN11
@UNKNOWN10:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON | PAD::A_BUTTON | PAD::L_BUTTON
	BNE @UNKNOWN13
	JSL UNKNOWN_C12E42
	LDX @LOCAL01
	DEX
	STX @LOCAL01
@UNKNOWN11:
	BNE @UNKNOWN10
	JMP @UNKNOWN7
@UNKNOWN12:
	LOADPTR BLINKING_TRIANGLE_TILES + 2 * 2, @LOCAL00
	LDX @VIRTUAL02
	LDA a:window_stats::window_y,X
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::height,X
	OPTIMIZED_MULT @VIRTUAL04, 32
	PHA
	LDX @VIRTUAL02
	LDA a:window_stats::window_x,X
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::width,X
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 0, 1
	TAY
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
@UNKNOWN13:
	JSL RESUME_MUSIC
@UNKNOWN14:
	END_C_FUNCTION
