
CC_1F_C0:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL01
	TAY
	STY @LOCAL00
	JSR GET_WORKING_MEMORY
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @UNKNOWN1
	JSR GET_WORKING_MEMORY
	LDX @LOCAL01
	TXA
	STORE_INT1632 @VIRTUAL0A
	CLC
	LDA @VIRTUAL06
	SBC @VIRTUAL0A
	LDA @VIRTUAL06+2
	SBC @VIRTUAL0A+2
	BCS @UNKNOWN1
	JSR GET_WORKING_MEMORY
	LDA @VIRTUAL06
	STA @VIRTUAL02
	LDX @LOCAL01
	TXA
	SEC
	SBC @VIRTUAL02
	STA ONGOSUB_OFFSET
	LDY @LOCAL00
	STY @LOCAL01
	JSR GET_WORKING_MEMORY
	LDA @VIRTUAL06
	DEC
	ASL
	ASL
	PHA
	LDY @LOCAL01
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	PLA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA __BSS_START__,Y
	LDA @VIRTUAL06+2
	STA __BSS_START__+2,Y
	STZ CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(UNKNOWN_C1621F)
	BRA @UNKNOWN2
@UNKNOWN1:
	LDY @LOCAL00
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDX @LOCAL01
	TXA
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA __BSS_START__,Y
	LDA @VIRTUAL06+2
	STA __BSS_START__+2,Y
	LDA #NULL
@UNKNOWN2:
	END_C_FUNCTION
