
CC_1A_00: ;$C1463B
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	LDA CC_ARGUMENT_GATHERING_LOOP_COUNTER
	CMP #$0010
	BCS @UNKNOWN0
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1A_00)
	BRA @UNKNOWN1
@UNKNOWN0:
	LDY #$0000
	LDA #.LOWORD(CC_ARGUMENT_STORAGE)
	JSR UNKNOWN_C1244C
	STORE_INT1632 $06
	MOVE_INT $06, $0E
	JSR SET_WORKING_MEMORY
	LDA #NULL
@UNKNOWN1:
	PLD
	RTS
