
CC_1C_02: ;$C14FD7
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 14
	CPX #$00FF
	BNE @UNKNOWN0
	JSR a:.LOWORD(GET_ACTIVE_WINDOW_ADDRESS)
	TAX
	LDA a:window_stats::working_memory_storage,X
	JSR a:.LOWORD(UNKNOWN_C1931B)
	BRA @UNKNOWN3
@UNKNOWN0:
	CPX #$0000
	BEQ @UNKNOWN1
	TXA
	BRA @UNKNOWN2
@UNKNOWN1:
	JSR a:.LOWORD(GET_ARGUMENT_MEMORY)
	LDA $06
@UNKNOWN2:
	JSR a:.LOWORD(UNKNOWN_C1931B)
@UNKNOWN3:
	LDA #NULL
	PLD
	RTS
