
CC_1C_06:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	CPX #0
	BEQ @UNKNOWN0
	TXA
	STA @LOCAL01
	BRA @UNKNOWN1
@UNKNOWN0:
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
	STA @LOCAL01
@UNKNOWN1:
	LOADPTR PSI_TELEPORT_DEST_TABLE, @VIRTUAL06
	LDA @LOCAL01
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(psi_teleport_destination)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #.SIZEOF(psi_teleport_destination::name)
.IF .DEFINED(JPN)
	JSR PRINT_STRING
.ELSE
	JSL UNKNOWN_C447FB
.ENDIF
	LDA #NULL
	END_C_FUNCTION
