
CC_1C_06: ;$C146DE
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	CPX #$0000
	BEQ @UNKNOWN0
	TXA
	STA $12
	BRA @UNKNOWN1
@UNKNOWN0:
	JSR GET_ARGUMENT_MEMORY
	LDA $06
	STA $12
@UNKNOWN1:
	LOADPTR PSI_TELEPORT_DEST_TABLE, $06
	LDA $12
	OPTIMIZED_MULT $04, .SIZEOF(psi_teleport_destination)
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDA #.SIZEOF(psi_teleport_destination::name)
	JSR PRINT_STRING
	LDA #NULL
	PLD
	RTS
