
CC_0E: ;$C1461A
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 14
	CPX #$0000
	BNE @UNKNOWN0
	JSR a:.LOWORD(GET_ARGUMENT_MEMORY)
	LDA $06
	AND #$00FF
	TAX
@UNKNOWN0:
	TXA
	JSR a:.LOWORD(SET_SECONDARY_MEMORY)
	LDA #NULL
	PLD
	RTS
