
CC_1F_EC: ;$C16D14
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STX $10
	LDA #$0001
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @UNKNOWN2
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1F_EC)
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	TAY
	STY $0E
	TYA
	JSL UNKNOWN_C4608C
	LDX $10
	JSL UNKNOWN_C4C91A
	LDY $0E
	TYA
	JSL UNKNOWN_C4645A
	LDA #NULL
@UNKNOWN3:
	PLD
	RTS
