
CC_1F_16:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL01
	LDA #2
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @UNKNOWN2
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1F_16)
	BRA @UNKNOWN7
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	LDA #8
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA CC_ARGUMENT_STORAGE+1
	AND #$00FF
	JSL ASL16_ENTRY2
	STA @VIRTUAL02
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	ORA @VIRTUAL02
	BEQ @ARG_1_IS_ZERO
	STORE_INT1632 @VIRTUAL06
	BRA @ARG_1_IS_NONZERO
@ARG_1_IS_ZERO:
	JSR GET_WORKING_MEMORY
@ARG_1_IS_NONZERO:
	LDA @VIRTUAL06
	STA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL01
	BEQ @ARG_2_IS_ZERO
	TXA
	STORE_INT1632 @VIRTUAL06
	BRA @ARG_2_IS_NONZERO
@ARG_2_IS_ZERO:
	JSR GET_ARGUMENT_MEMORY
@ARG_2_IS_NONZERO:
	LDA @VIRTUAL06
	TAX
	DEX
	LDA @LOCAL00
	JSL UNKNOWN_C462FF
	LDA #NULL
@UNKNOWN7:
	END_C_FUNCTION
