
CC_1A_05: ;$C1549E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STX $10
	TAY
	STY $0E
	LDA #$0001
	CLC
	SBC .LOWORD(CC_ARGUMENT_GATHERING_LOOP_COUNTER)
	BRANCHLTEQS @UNKNOWN2
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX .LOWORD(CC_ARGUMENT_GATHERING_LOOP_COUNTER)
	STA .LOWORD(CC_ARGUMENT_STORAGE),X
	REP #PROC_FLAGS::ACCUM8
	INC .LOWORD(CC_ARGUMENT_GATHERING_LOOP_COUNTER)
	LDA #.LOWORD(CC_1A_05)
	BRA @UNKNOWN6
@UNKNOWN2:
	LDA .LOWORD(CC_ARGUMENT_STORAGE)
	AND #$00FF
	STA $02
	LDA .LOWORD(CURRENT_FOCUS_WINDOW)
	CMP #$0001
	BNE @UNKNOWN3
	LDA #$0001
	JSL UNKNOWN_EF0115
	LDA .LOWORD(CURRENT_FOCUS_WINDOW)
	ASL
	TAX
	LDA .LOWORD(WINDOW_EXISTENCE_TABLE),X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS_TABLE)
	TAX
	STZ a:window_stats::text_y,X
	TAX
	STZ a:window_stats::text_x,X
	LDY $0E
	TYA
	CLC
	ADC #$0006
	JSL UNKNOWN_C20A20
	SEP #PROC_FLAGS::ACCUM8
	STZ .LOWORD(UNKNOWN_7E5E71)
@UNKNOWN3:
	LDX $10
	BEQ @UNKNOWN4
	REP #PROC_FLAGS::ACCUM8
	TXA
	BRA @UNKNOWN5
@UNKNOWN4:
	JSR a:.LOWORD(GET_ARGUMENT_MEMORY)
	LDA $06
@UNKNOWN5:
	LDX $02
	JSR a:.LOWORD(INVENTORY_GET_ITEM_NAME)
	LDA #NULL
@UNKNOWN6:
	PLD
	RTS
