
CC_1D_0F: ;$C156DB
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STX $12
	LDA #$0001
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @UNKNOWN2
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1D_0F)
	BRA @UNKNOWN7
@UNKNOWN2:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	TAY
	BEQ @UNKNOWN3
	TYA
	BRA @UNKNOWN4
@UNKNOWN3:
	JSR GET_WORKING_MEMORY
	LDA $06
@UNKNOWN4:
	STA $02
	LDX $12
	BEQ @UNKNOWN5
	TXA
	BRA @UNKNOWN6
@UNKNOWN5:
	JSR GET_ARGUMENT_MEMORY
	LDA $06
@UNKNOWN6:
	TAY
	STY $12
	TYX
	LDA $02
	JSL GET_CHARACTER_ITEM
	STORE_INT1632 $06
	MOVE_INT $06, $0E
	JSR SET_ARGUMENT_MEMORY
	LDY $12
	TYX
	LDA $02
	JSR REMOVE_ITEM_FROM_INVENTORY
	STORE_INT1632 $06
	MOVE_INT $06, $0E
	JSR SET_WORKING_MEMORY
	LDA #NULL
@UNKNOWN7:
	PLD
	RTS
