
CC_18_07:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL01
	LDA CC_ARGUMENT_GATHERING_LOOP_COUNTER
	CMP #4
	BCS @UNKNOWN0
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_18_07)
	JMP @UNKNOWN10
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA #8
	SEP #PROC_FLAGS::INDEX8
	TAY
	MOVE_INT832 CC_ARGUMENT_STORAGE+1, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	JSL ASL32_ENTRY2
	SEP #PROC_FLAGS::ACCUM8
	MOVE_INT832 CC_ARGUMENT_STORAGE, @VIRTUAL0A
	REP #PROC_FLAGS::ACCUM8
	OR_INT_ASSIGN @VIRTUAL0A, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #16
	TAY
	MOVE_INT832 CC_ARGUMENT_STORAGE+2, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	JSL ASL32_ENTRY2
	OR_INT_ASSIGN @VIRTUAL0A, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #24
	TAY
	MOVE_INT832 CC_ARGUMENT_STORAGE+3, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	JSL ASL32_ENTRY2
	OR_INT_ASSIGN @VIRTUAL0A, @VIRTUAL06
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL01
	BNE @UNKNOWN1
	JSR GET_WORKING_MEMORY
	BRA @UNKNOWN3
@UNKNOWN1:
	CPX #1
	BNE @UNKNOWN2
	JSR GET_ARGUMENT_MEMORY
	BRA @UNKNOWN3
@UNKNOWN2:
	JSR GET_SECONDARY_MEMORY
	STORE_INT1632 @VIRTUAL06
@UNKNOWN3:
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
	LDA @VIRTUAL06+2
	SBC @VIRTUAL0A+2
	BCS @UNKNOWN4
	LDA #0
	BRA @UNKNOWN8
@UNKNOWN4:
	CMP32 @VIRTUAL0A, @VIRTUAL06
	BNE @UNKNOWN6
	LDX #1
	BRA @UNKNOWN7
@UNKNOWN6:
	LDX #2
@UNKNOWN7:
	TXA
@UNKNOWN8:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDA #NULL
@UNKNOWN10:
	END_C_FUNCTION
