
CC_1F_D2: ;$C17304
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 14
	TXA
	BEQ @UNKNOWN0
	STA $06
	STZ $08
	BRA @UNKNOWN1
@UNKNOWN0:
	JSR a:.LOWORD(GET_ARGUMENT_MEMORY)
@UNKNOWN1:
	LDA $06
	JSL UNKNOWN_C466C1
	LDA #NULL
	PLD
	RTS
