
CC_19_27: ;$C1776A
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	TXA
	BEQ @ARG_IS_ZERO
	STORE_INT1632 $06
	BRA @ARG_IS_NONZERO
@ARG_IS_ZERO:
	JSR GET_ARGUMENT_MEMORY
@ARG_IS_NONZERO:
	LDA $06
	JSL UNKNOWN_C3EE7A
	MOVE_INT $06, $0E
	JSR SET_WORKING_MEMORY
	LDA #NULL
	PLD
	RTS
