
CC_19_1A: ;$C15B0E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	CPX #$0000
	BEQ CC_19_1A_UNKNOWN0
	TXA
	BRA CC_19_1A_UNKNOWN1
CC_19_1A_UNKNOWN0:
	JSR GET_ARGUMENT_MEMORY
	LDA $06
CC_19_1A_UNKNOWN1:
	TAX
	DEX
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE+game_state::escargo_express_items,X
	STORE_INT832 $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	JSR SET_WORKING_MEMORY
	LDA #NULL
	PLD
	RTS
