
CC_19_1D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @UNKNOWN2
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_19_1D)
	BRA @UNKNOWN6
@UNKNOWN2:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	TAX
	BEQ @ARG_IS_ZERO
	TXA
	BRA @ARG_IS_NONZERO
@ARG_IS_ZERO:
	JSR GET_WORKING_MEMORY
	LDA @VIRTUAL06
@ARG_IS_NONZERO:
	DEC
	CLC
	ADC #.LOWORD(GAME_STATE)
	STA @LOCAL02
	CLC
	ADC #game_state::unknownB8
	TAY
	STY @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	STORE_INT832 @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDA @LOCAL02
	CLC
	ADC #game_state::unknownB6
	TAX
	STX @LOCAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STORE_INT832 @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_ARGUMENT_MEMORY
	LDA @VIRTUAL02
	BEQ @UNKNOWN5
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	LDX @LOCAL02
	STA __BSS_START__,X
	LDY @LOCAL01
	STA __BSS_START__,Y
@UNKNOWN5:
	REP #PROC_FLAGS::ACCUM8
	LDA #NULL
@UNKNOWN6:
	END_C_FUNCTION
