
CC_18_0D: ;$C15B46
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TXY
	STY $0E
	LDA #$0001
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @UNKNOWN2
	TYA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_18_0D)
	BRA @UNKNOWN8
@UNKNOWN2:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	TAX
	BEQ @ARG_IS_ZERO
	TXA
	BRA @ARG_IS_NONZERO
@ARG_IS_ZERO:
	JSR GET_WORKING_MEMORY
	LDA $06
@ARG_IS_NONZERO:
	TAX
	LDY $0E
	TYA
	CMP #$0001
	BEQ @UNKNOWN5
	CMP #$0002
	BEQ @UNKNOWN6
	BRA @UNKNOWN7
@UNKNOWN5:
	TXA
	JSL UNKNOWN_C1952F
	BRA @UNKNOWN7
@UNKNOWN6:
	TXA
	JSL NULL_C3EF23
@UNKNOWN7:
	LDA #NULL
@UNKNOWN8:
	PLD
	RTS
