
CC_1D_08:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	STA @LOCAL01
	LDA CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BNE @UNKNOWN0
	LDA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1D_08)
	BRA @UNKNOWN3
@UNKNOWN0:
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA @LOCAL01
	JSL ASL16_ENTRY2
	STA @VIRTUAL02
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	ORA @VIRTUAL02
	BEQ @UNKNOWN1
	STORE_INT1632 @VIRTUAL06
	BRA @UNKNOWN2
@UNKNOWN1:
	JSR GET_ARGUMENT_MEMORY
@UNKNOWN2:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL INCREASE_WALLET_BALANCE
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDA #NULL
@UNKNOWN3:
	END_C_FUNCTION
