
CC_1D_08: ;$C148E9
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	TXA
	STA $12
	LDA CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BNE @UNKNOWN0
	LDA $12
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1D_08)
	BRA @UNKNOWN3
@UNKNOWN0:
	SEP #PROC_FLAGS::INDEX8
	LDY #$0008
	LDA $12
	JSL ASL16_ENTRY2
	STA $02
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	ORA $02
	BEQ @UNKNOWN1
	STORE_INT1632 $06
	BRA @UNKNOWN2
@UNKNOWN1:
	JSR GET_ARGUMENT_MEMORY
@UNKNOWN2:
	MOVE_INT $06, $0E
	JSL INCREASE_WALLET_BALANCE
	MOVE_INT $06, $0E
	JSR SET_WORKING_MEMORY
	LDA #NULL
@UNKNOWN3:
	PLD
	RTS
