
UNKNOWN_C100FE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	LDA DEBUG
	BEQ @UNKNOWN3
	LDA BATTLE_MODE
	BNE @UNKNOWN3
	BRA @UNKNOWN1
@UNKNOWN0:
	JSL UNKNOWN_C12E42
@UNKNOWN1:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON | PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @UNKNOWN0
	BRA @UNKNOWN9
@UNKNOWN2:
	LDA DEBUG
	BEQ @UNKNOWN3
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::R_BUTTON
	CMP #PAD::B_BUTTON | PAD::R_BUTTON
	BNE @UNKNOWN3
	STZ TEXT_PROMPT_WAITING_FOR_INPUT
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA TEXT_PROMPT_WAITING_FOR_INPUT
	BNE @UNKNOWN2
@UNKNOWN4:
	CPX #0
	BEQ @UNKNOWN5
	TXA
	BRA @UNKNOWN6
@UNKNOWN5:
	LDA TEXT_SPEED_BASED_WAIT
@UNKNOWN6:
	TAX
	STX @LOCAL00
	BRA @UNKNOWN8
@UNKNOWN7:
	JSL UNKNOWN_C12E42
@UNKNOWN8:
	LDX @LOCAL00
	TXA
	DEX
	STX @LOCAL00
	CMP #0
	BEQ @UNKNOWN9
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON | PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @UNKNOWN7
@UNKNOWN9:
	END_C_FUNCTION
