
UNKNOWN_C102D0: ;$C102D0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STZ .LOWORD(UNKNOWN_7E9641)
	JSL CLEAR_9622
	JSL UNKNOWN_C12DD5
	BRA @UNKNOWN2
@UNKNOWN0:
	LDA .LOWORD(DEBUG)
	BEQ @UNKNOWN1
	LDA a:.LOWORD(PAD_STATE)
	AND #PAD::START_BUTTON
	BEQ @UNKNOWN1
	LDA a:.LOWORD(PAD_STATE)
	AND #PAD::SELECT_BUTTON
	BNE @UNKNOWN3
@UNKNOWN1:
	JSL UNKNOWN_C1004E
@UNKNOWN2:
	LDA .LOWORD(UNKNOWN_7E9641)
	BEQ @UNKNOWN0
	STZ .LOWORD(UNKNOWN_7E9641)
@UNKNOWN3:
	RTS
