
UNKNOWN_C10BA1: ;$C10BA1
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAX
	STX $0E
	LDA CURRENT_FOCUS_WINDOW
	CMP #$FFFF
	BEQ @UNKNOWN0
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA WINDOW_EXISTENCE_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDY WINDOW_STATS_TABLE+window_stats::curr_tile_attributes,X
	LDX $0E
	LDA CURRENT_FOCUS_WINDOW
	JSR UNKNOWN_C10A85
@UNKNOWN0:
	PLD
	RTS
