
UNKNOWN_C10D7C:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDX #.LOWORD(NUMBER_TEXT_BUFFER) + 6
	LDA #1
	STA @LOCAL01
	BRA @UNKNOWN1
@UNKNOWN0:
	JSL MODULUS32
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL06
	STA __BSS_START__,X
	DEX
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @LOCAL00, @VIRTUAL0A
	MOVE_INT @LOCAL02, @VIRTUAL06
	JSL DIVISION32S_DIVISOR_POSITIVE
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA @LOCAL01
	INC
	STA @LOCAL01
@UNKNOWN1:
	MOVE_INT_CONSTANT 10, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL00
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
	LDA @VIRTUAL06+2
	SBC @VIRTUAL0A+2
	BCS @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL06
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	END_C_FUNCTION
