
UNKNOWN_C10D60: ;$C10D60
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSR UNKNOWN_C10BA1
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA WINDOW_EXISTENCE_TABLE,X
	CMP WINDOW_TAIL
	BEQ @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA UNKNOWN_7E9623
@UNKNOWN0:
	REP #PROC_FLAGS::ACCUM8
	RTS
