
UNKNOWN_C10D60:
	BEGIN_C_FUNCTION
	END_STACK_VARS
	JSR UNKNOWN_C10BA1
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP WINDOW_TAIL
	BEQ @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
@UNKNOWN0:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
