
UNKNOWN_C10F40: ;$C10F40
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	CMP #$FFFF
	BEQ @UNKNOWN3
	ASL
	TAX
	LDA .LOWORD(WINDOW_EXISTENCE_TABLE),X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS_TABLE)
	TAX
	STX $10
	LDY a:window_stats::tilemap_address,X
	STY $0E
	LDY a:window_stats::height,X
	LDA a:window_stats::width,X
	JSL MULT16
	STA $02
	BRA @UNKNOWN2
@UNKNOWN0:
	LDY $0E
	LDA a:.LOWORD(RAM),Y
	BEQ @UNKNOWN1
	JSL FREE_TILE_SAFE
@UNKNOWN1:
	LDA #$0040
	LDY $0E
	STA a:.LOWORD(RAM),Y
	INY
	INY
	STY $0E
	LDA $02
	DEC
	STA $02
@UNKNOWN2:
	LDA $02
	BNE @UNKNOWN0
	JSL UNKNOWN_C45E96
	LDX $10
	STZ a:window_stats::text_y,X
	STZ a:window_stats::text_x,X
@UNKNOWN3:
	PLD
	RTS
