
UNKNOWN_C10FEA:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 "PALETTE"
	END_STACK_VARS
	STA @LOCAL00
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN0
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDY #1024
	LDA @LOCAL00
	JSL MULT16
	STA WINDOW_STATS + window_stats::curr_tile_attributes,X
@UNKNOWN0:
	END_C_FUNCTION
