
UNKNOWN_C1138D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	CMP #.LOWORD(-1)
	BNE @UNKNOWN0
	LDA #0
	BRA @UNKNOWN3
@UNKNOWN0:
	LDX #1
	STX @LOCAL00
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	BRA @UNKNOWN2
@UNKNOWN1:
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	LDX @LOCAL00
	INX
	STX @LOCAL00
@UNKNOWN2:
	TAX
	LDA a:menu_option::next,X
	CMP #.LOWORD(-1)
	BNE @UNKNOWN1
	LDX @LOCAL00
	TXA
@UNKNOWN3:
	END_C_FUNCTION
