
UNKNOWN_C114B1:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	TAY
	STY @LOCAL02
	MOVE_INT @PARAM03, @VIRTUAL06
	MOVE_INT @PARAM02, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSR UNKNOWN_C113D1
	TAX
	LDY @LOCAL02
	TYA
	STA a:menu_option::text_x,X
	LDA @VIRTUAL02
	STA a:menu_option::text_y,X
	TXA
	END_C_FUNCTION
