
UNKNOWN_C11596:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
.IF .DEFINED(USA)
	STACK_RESERVE_INT32
.ENDIF
	STACK_RESERVE_INT16 "LOCAL03"
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_PARAM_INT8
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @LOCAL03
	SEP #PROC_FLAGS::ACCUM8
	LDA @PARAM03
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
.IF .DEFINED(JPN)
	MOVE_INT @PARAM02, @VIRTUAL06
	MOVE_INT @PARAM01, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
.ELSE
	MOVE_INT @PARAM02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	MOVE_INT @PARAM01, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
.ENDIF
	LDA @LOCAL03
	JSR UNKNOWN_C1153B
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	STA a:menu_option::sound_effect,X
	REP #PROC_FLAGS::ACCUM8
	TXA
	END_C_FUNCTION
