
UNKNOWN_C11887: ;$C11887
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STA $10
	CMP #$FFFF
	BEQ @UNKNOWN2
	LDA .LOWORD(CURRENT_FOCUS_WINDOW)
	ASL
	TAX
	LDA .LOWORD(WINDOW_EXISTENCE_TABLE),X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS_TABLE)
	TAY
	STY $0E
	LDA $10
	STA a:.LOWORD(RAM)+47,Y
	LDA a:.LOWORD(RAM)+43,Y
	LDY #.SIZEOF(u89D4_entry)
	JSL MULT168
	CLC
	ADC #.LOWORD(UNKNOWN_7E89D4)
	TAX
	BRA @UNKNOWN1
@UNKNOWN0:
	DEC
	STA $10
	LDA a:.LOWORD(RAM)+2,X
	LDY #.SIZEOF(u89D4_entry)
	JSL MULT168
	CLC
	ADC #.LOWORD(UNKNOWN_7E89D4)
	TAX
@UNKNOWN1:
	LDA $10
	BNE @UNKNOWN0
	LDA a:.LOWORD(RAM)+6,X
	LDY $0E
	STA a:.LOWORD(RAM)+51,Y
@UNKNOWN2:
	JSR a:.LOWORD(PRINT_MENU_ITEMS)
	PLD
	RTS
