
UNKNOWN_C11F8A:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	END_STACK_VARS
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS) + window_stats::cursor_move_callback
	TAY
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	END_C_FUNCTION
