
UNKNOWN_C11F8A: ;$C11F8A
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 14
	MOVE_INT_CONSTANT NULL, $06
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA WINDOW_EXISTENCE_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS_TABLE) + window_stats::cursor_move_callback
	TAY
	MOVE_INT_YPTRDEST $06, __BSS_START__
	PLD
	RTS
