
UNKNOWN_C11FBC:
	BEGIN_C_FUNCTION
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXY
	TAX
	BNE @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	LDA BATTLER_FRONT_ROW_X_POSITIONS,Y
	BRA @UNKNOWN1
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA BATTLER_BACK_ROW_X_POSITIONS,Y
@UNKNOWN1:
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	END_C_FUNCTION
