
UNKNOWN_C11FD4:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	TAX
	CPX #1
	BNE @UNKNOWN0
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battle_action)
	TAX
	INX
	INX
	LDA f:BATTLE_ACTION_TABLE + battle_action::direction,X
	AND #$00FF
	CMP #1
	BNE @UNKNOWN0
	LDA @VIRTUAL02
	JSL UNKNOWN_C2FAD2
	CMP #0
	BNE @UNKNOWN0
	LDA #0
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #1
@UNKNOWN1:
	END_C_FUNCTION
