
UNKNOWN_C12362: ;$C12362
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STA $02
	LDA NUM_BATTLERS_IN_BACK_ROW
	BEQ @UNKNOWN0
	LDX #$0000
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX #$0001
@UNKNOWN1:
	TXY
	STY $12
@UNKNOWN2:
	LDY $12
	TYA
	JSR UNKNOWN_C43657
	JSR CLEAR_INSTANT_PRINTING
	LDX #$FFFF
	LDY $12
	TYA
	JSR UNKNOWN_C120D6
	JSL WINDOW_TICK
@UNKNOWN3:
	JSL UNKNOWN_C12E42
	LDA PAD_PRESS
	AND #PAD::UP
	BEQ @UNKNOWN4
	LDX #$0001
	STX $10
	LDA #SFX::CURSOR3
	STA $0E
	BRA @UNKNOWN7
@UNKNOWN4:
	LDA PAD_PRESS
	AND #PAD::DOWN
	BEQ @UNKNOWN5
	LDX #$0000
	STX $10
	LDA #SFX::CURSOR3
	STA $0E
	BRA @UNKNOWN7
@UNKNOWN5:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @UNKNOWN6
	JSR UNKNOWN_C435E4
	LDY $12
	TYX
	INX
	STX $10
	LDA #SFX::CURSOR1
	JSL PLAY_SOUND
	BRA @UNKNOWN11
@UNKNOWN6:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @UNKNOWN3
	LDA $02
	CMP #$0001
	BNE @UNKNOWN3
	JSR UNKNOWN_C435E4
	LDX #$0000
	STX $10
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	BRA @UNKNOWN11
@UNKNOWN7:
	CPX #$0000
	BNE @UNKNOWN8
	LDA NUM_BATTLERS_IN_BACK_ROW
	BNE @UNKNOWN10
@UNKNOWN8:
	CPX #$0000
	BEQL @UNKNOWN2
	LDA NUM_BATTLERS_IN_FRONT_ROW
	BEQL @UNKNOWN2
@UNKNOWN10:
	LDA $0E
	JSL PLAY_SOUND
	LDX $10
	TXY
	STY $12
	JMP @UNKNOWN2
@UNKNOWN11:
	JSR CLOSE_FOCUS_WINDOW
	LDX $10
	TXA
	PLD
	RTS
