
UNKNOWN_C12BD5: ;$C12BD5
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	CMP #$0000
	BNE @UNKNOWN0
	LDA .LOWORD(CURRENT_FOCUS_WINDOW)
@UNKNOWN0:
	ASL
	TAX
	LDA .LOWORD(WINDOW_EXISTENCE_TABLE),X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA .LOWORD(WINDOW_STATS_TABLE)+43,X
	JSR a:.LOWORD(UNKNOWN_C1138D)
	RTS
