
UNKNOWN_C14070: ;$C14070
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 15
	TXY
	TAX
	BRA @UNKNOWN1
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	STA $00
	LDA $0E
	CMP $00
	BNE @UNKNOWN2
	INX
	INY
@UNKNOWN1:
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA $0E
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @UNKNOWN0
@UNKNOWN2:
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	STA $02
	LDA __BSS_START__,Y
	AND #$00FF
	SEC
	SBC $02
	PLD
	RTS
