
UNKNOWN_C15FB1: ;$C15FB1
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STX $04
	STA $02
	LDY #$0000
	BRA @UNKNOWN2
@UNKNOWN0:
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	STA $0E
	CLC
	ADC #game_state::unknownB6
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BNE @UNKNOWN1
	LDA $04
	SEP #PROC_FLAGS::ACCUM8
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	TAX
	LDA $02
	SEP #PROC_FLAGS::ACCUM8
	STA __BSS_START__+game_state::unknownB8,X
	BRA @UNKNOWN3
@UNKNOWN1:
	INY
@UNKNOWN2:
	CPY #$0003
	BCC @UNKNOWN0
@UNKNOWN3:
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTS
