
UNKNOWN_C1931B: ;$C1931B
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	STA $12
	CMP #PLAYER_CHAR_COUNT
	BLTEQ @UNKNOWN2
	CMP #PARTY_MEMBER::KING
	BNE @UNKNOWN1
	PROMOTENEARPTR .LOWORD(GAME_STATE) + game_state::pet_name, $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDA #$0006
	JSR a:.LOWORD(PRINT_STRING)
	BRA @UNKNOWN4
@UNKNOWN1:
	LOADPTR ENEMY_CONFIGURATION_TABLE, $06
	LDA $12
	OPTIMIZED_MULT $04, 2
	TAX
	INX
	LDA f:NPC_AI_TABLE,X
	AND #$00FF
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC $06
	STA $06
	STA $0E
	LDA $08
	STA $10
	LDA #$000A
	JSR PRINT_STRING
	BRA @UNKNOWN4
@UNKNOWN2:
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT) + char_struct::name
	PROMOTENEARPTRA $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDA #$0004
	JSR a:.LOWORD(PRINT_STRING)
@UNKNOWN4:
	PLD
	RTS
