
UNKNOWN_C1A1D8:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	TXY
	DEY
	STY @LOCAL03
	JSR SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::UNKNOWN2D
	LDA #2
	JSR UNKNOWN_C10EB4
	LDX #0
	LDA #1
	JSR UNKNOWN_C438A5
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_8, @LOCAL00
	LDA #6
	JSR PRINT_STRING
	LDY @LOCAL03
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_offense,X
	AND #$00FF
	STA @LOCAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	BEQ @UNKNOWN1
	LDA #0
	STA @VIRTUAL02
	LDY @LOCAL03
	CPY #3
	BNE @UNKNOWN0
	LDA #1
	STA @VIRTUAL02
@UNKNOWN0:
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@UNKNOWN1:
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN4
	LDA #0
	BRA @UNKNOWN9
@UNKNOWN4:
	LDA @LOCAL02
	CLC
	SBC #$00FF
	BRANCHLTEQS @UNKNOWN7
	LDX #$00FF
	BRA @UNKNOWN8
@UNKNOWN7:
	LDA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@UNKNOWN8:
	TXA
@UNKNOWN9:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	LDX #1
	LDA #0
	JSR UNKNOWN_C438A5
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_9, @LOCAL00
	LDA #7
	JSR PRINT_STRING
	LDY @LOCAL03
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_defense,X
	AND #$00FF
	STA @LOCAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	BEQ @UNKNOWN12
	LDA #0
	STA @VIRTUAL02
	LDY @LOCAL03
	CPY #3
	BNE @UNKNOWN11
	LDA #1
	STA @VIRTUAL02
@UNKNOWN11:
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@UNKNOWN12:
	LDY @LOCAL03
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	BEQ @UNKNOWN14
	LDA #0
	STA @VIRTUAL02
	LDY @LOCAL03
	CPY #3
	BNE @UNKNOWN13
	LDA #1
	STA @VIRTUAL02
@UNKNOWN13:
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@UNKNOWN14:
	LDY @LOCAL03
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	BEQ @UNKNOWN16
	LDA #0
	STA @VIRTUAL02
	LDY @LOCAL03
	CPY #3
	BNE @UNKNOWN15
	LDA #1
	STA @VIRTUAL02
@UNKNOWN15:
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@UNKNOWN16:
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN19
	LDA #0
	BRA @UNKNOWN24
@UNKNOWN19:
	LDA @LOCAL02
	CLC
	SBC #$00FF
	BRANCHLTEQS @UNKNOWN22
	LDX #$00FF
	BRA @UNKNOWN23
@UNKNOWN22:
	LDA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@UNKNOWN23:
	TXA
@UNKNOWN24:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	LDA COMPARE_EQUIPMENT_MODE
	BEQL @UNKNOWN53
	LDX #0
	LDA #10
	JSR UNKNOWN_C438A5
	LDA #1
	JSR UNKNOWN_C10FEA
	LDA #$014E
	JSR PRINT_LETTER
	LDA #0
	JSR UNKNOWN_C10FEA
	LDY @LOCAL03
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_offense,X
	AND #$00FF
	STA @LOCAL02
	LDA TEMPORARY_WEAPON
	AND #$00FF
	BEQ @UNKNOWN28
	LDX #0
	STX @LOCAL01
	LDY @LOCAL03
	CPY #3
	BNE @UNKNOWN27
	LDX #1
	STX @LOCAL01
@UNKNOWN27:
	LDA TEMPORARY_WEAPON
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	LDX @LOCAL01
	STX @VIRTUAL04
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@UNKNOWN28:
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN31
	LDA #0
	BRA @UNKNOWN36
@UNKNOWN31:
	LDA @LOCAL02
	CLC
	SBC #$00FF
	BRANCHLTEQS @UNKNOWN34
	LDX #$00FF
	BRA @UNKNOWN35
@UNKNOWN34:
	LDA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@UNKNOWN35:
	TXA
@UNKNOWN36:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	LDX #1
	LDA #10
	JSR UNKNOWN_C438A5
	LDA #1
	JSR UNKNOWN_C10FEA
	LDA #$014E
	JSR PRINT_LETTER
	LDA #0
	JSR UNKNOWN_C10FEA
	LDY @LOCAL03
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_defense,X
	AND #$00FF
	STA @LOCAL02
	LDA TEMPORARY_BODY_GEAR
	AND #$00FF
	BEQ @UNKNOWN39
	LDX #0
	STX @LOCAL01
	LDY @LOCAL03
	CPY #3
	BNE @UNKNOWN38
	LDX #1
	STX @LOCAL01
@UNKNOWN38:
	LDA TEMPORARY_BODY_GEAR
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	LDX @LOCAL01
	STX @VIRTUAL04
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@UNKNOWN39:
	LDA TEMPORARY_ARMS_GEAR
	AND #$00FF
	BEQ @UNKNOWN41
	LDX #0
	STX @LOCAL01
	LDY @LOCAL03
	CPY #3
	BNE @UNKNOWN40
	LDX #1
	STX @LOCAL01
@UNKNOWN40:
	LDA TEMPORARY_ARMS_GEAR
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	LDX @LOCAL01
	STX @VIRTUAL04
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@UNKNOWN41:
	LDA TEMPORARY_OTHER_GEAR
	AND #$00FF
	BEQ @UNKNOWN43
	LDX #0
	STX @LOCAL01
	LDY @LOCAL03
	CPY #3
	BNE @UNKNOWN42
	LDX #1
	STX @LOCAL01
@UNKNOWN42:
	LDA TEMPORARY_OTHER_GEAR
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	LDX @LOCAL01
	STX @VIRTUAL04
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@UNKNOWN43:
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN46
	LDA #0
	BRA @UNKNOWN51
@UNKNOWN46:
	LDA @LOCAL02
	CLC
	SBC #$00FF
	BRANCHLTEQS @UNKNOWN49
	LDX #$00FF
	BRA @UNKNOWN50
@UNKNOWN49:
	LDA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@UNKNOWN50:
	TXA
@UNKNOWN51:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
@UNKNOWN53:
	JSR CLEAR_INSTANT_PRINTING
	END_C_FUNCTION
