
UNKNOWN_C1A1D8:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	DEC
	STA @VIRTUAL02
	STA @LOCAL04
	CREATE_WINDOW_NEAR #WINDOW::UNKNOWN2D
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
	LDA #2
	JSR UNKNOWN_C10EB4
	LDX #0
	TXA
	JSL UNKNOWN_C438A5
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_8, @LOCAL00
	LDA #8
	JSR PRINT_STRING
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_offense,X
	AND #$00FF
	TAY
	STY @LOCAL03
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	BEQ @UNKNOWN1
	LDX #0
	STX @LOCAL02
	LDA @VIRTUAL02
	CMP #3
	BNE @UNKNOWN0
	LDX #1
	STX @LOCAL02
@UNKNOWN0:
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL01
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	DEC
	STA @VIRTUAL02
	LDA @LOCAL01
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	LDY #.SIZEOF(item)
	JSL MULT168
	LDX @LOCAL02
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL04
	LDY @LOCAL03
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL03
@UNKNOWN1:
	LDA #1
	STA FORCE_LEFT_TEXT_ALIGNMENT
	LDX #0
	LDA #55
	JSL UNKNOWN_C43D75
	LDY @LOCAL03
	STY @VIRTUAL04
	LDA #0
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @UNKNOWN4
	LDA #0
	BRA @UNKNOWN9
@UNKNOWN4:
	TYA
	CLC
	SBC #$00FF
	BRANCHLTEQS @UNKNOWN7
	LDX #$00FF
	BRA @UNKNOWN8
@UNKNOWN7:
	TYA
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@UNKNOWN8:
	TXA
@UNKNOWN9:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	STZ FORCE_LEFT_TEXT_ALIGNMENT
	LDX #1
	LDA #0
	JSL UNKNOWN_C438A5
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_9, @LOCAL00
	LDA #8
	JSR PRINT_STRING
	LDA @LOCAL04
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_defense,X
	AND #$00FF
	TAY
	STY @LOCAL03
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	BEQ @UNKNOWN12
	LDX #0
	STX @LOCAL02
	LDA @VIRTUAL02
	CMP #3
	BNE @UNKNOWN11
	LDX #1
	STX @LOCAL02
@UNKNOWN11:
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL01
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	DEC
	STA @VIRTUAL02
	LDA @LOCAL01
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	LDY #.SIZEOF(item)
	JSL MULT168
	LDX @LOCAL02
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL04
	LDY @LOCAL03
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL03
@UNKNOWN12:
	LDA @LOCAL04
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	BEQ @UNKNOWN14
	LDX #0
	STX @LOCAL02
	LDA @VIRTUAL02
	CMP #3
	BNE @UNKNOWN13
	LDX #1
	STX @LOCAL02
@UNKNOWN13:
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL01
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	DEC
	STA @VIRTUAL02
	LDA @LOCAL01
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	LDY #.SIZEOF(item)
	JSL MULT168
	LDX @LOCAL02
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL04
	LDY @LOCAL03
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL03
@UNKNOWN14:
	LDA @LOCAL04
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	BEQ @UNKNOWN16
	LDX #0
	STX @LOCAL02
	LDA @VIRTUAL02
	CMP #3
	BNE @UNKNOWN15
	LDX #1
	STX @LOCAL02
@UNKNOWN15:
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL01
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	DEC
	STA @VIRTUAL02
	LDA @LOCAL01
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	LDY #.SIZEOF(item)
	JSL MULT168
	LDX @LOCAL02
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL04
	LDY @LOCAL03
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL03
@UNKNOWN16:
	LDA #1
	STA FORCE_LEFT_TEXT_ALIGNMENT
	TAX
	LDA #55
	JSL UNKNOWN_C43D75
	LDY @LOCAL03
	STY @VIRTUAL04
	LDA #0
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @UNKNOWN19
	LDA #0
	BRA @UNKNOWN24
@UNKNOWN19:
	TYA
	CLC
	SBC #$00FF
	BRANCHLTEQS @UNKNOWN22
	LDX #$00FF
	BRA @UNKNOWN23
@UNKNOWN22:
	TYA
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@UNKNOWN23:
	TXA
@UNKNOWN24:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	STZ FORCE_LEFT_TEXT_ALIGNMENT
	LDA COMPARE_EQUIPMENT_MODE
	BEQL @UNKNOWN53
	LDX #0
	LDA #76
	JSL UNKNOWN_C43D75
	LDA #1
	JSR UNKNOWN_C10FEA
	LDA #$014E
	JSL UNKNOWN_C43F77
	LDA #0
	JSR UNKNOWN_C10FEA
	LDA @LOCAL04
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_offense,X
	AND #$00FF
	STA @LOCAL02
	LDA TEMPORARY_WEAPON
	AND #$00FF
	BEQ @UNKNOWN28
	LDX #0
	STX @LOCAL03
	LDA @VIRTUAL02
	CMP #3
	BNE @UNKNOWN27
	LDX #1
	STX @LOCAL03
@UNKNOWN27:
	LDA TEMPORARY_WEAPON
	AND #$00FF
	DEC
	PHA
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	LDY #.SIZEOF(item)
	JSL MULT168
	LDX @LOCAL03
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL04
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL04
	STA @LOCAL02
@UNKNOWN28:
	LDA #1
	STA FORCE_LEFT_TEXT_ALIGNMENT
	LDA @LOCAL02
	STA @VIRTUAL04
	LDA #0
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @UNKNOWN31
	LDA #0
	BRA @UNKNOWN36
@UNKNOWN31:
	LDA @LOCAL02
	CLC
	SBC #$00FF
	BRANCHLTEQS @UNKNOWN34
	LDX #$00FF
	BRA @UNKNOWN35
@UNKNOWN34:
	LDA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@UNKNOWN35:
	TXA
@UNKNOWN36:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	STZ FORCE_LEFT_TEXT_ALIGNMENT
	LDX #1
	LDA #76
	JSL UNKNOWN_C43D75
	LDA #1
	JSR UNKNOWN_C10FEA
	LDA #$014E
	JSL UNKNOWN_C43F77
	LDA @LOCAL04
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_defense,X
	AND #$00FF
	STA @LOCAL03
	LDA TEMPORARY_BODY_GEAR
	AND #$00FF
	BEQ @UNKNOWN39
	LDX #0
	STX @LOCAL02
	LDA @VIRTUAL02
	CMP #3
	BNE @UNKNOWN38
	LDX #1
	STX @LOCAL02
@UNKNOWN38:
	LDA TEMPORARY_BODY_GEAR
	AND #$00FF
	DEC
	PHA
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	LDY #.SIZEOF(item)
	JSL MULT168
	LDX @LOCAL02
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL04
	LDA @LOCAL03
	CLC
	ADC @VIRTUAL04
	STA @LOCAL03
@UNKNOWN39:
	LDA TEMPORARY_ARMS_GEAR
	AND #$00FF
	BEQ @UNKNOWN41
	LDX #0
	STX @LOCAL02
	LDA @LOCAL04
	STA @VIRTUAL02
	CMP #3
	BNE @UNKNOWN40
	LDX #1
	STX @LOCAL02
@UNKNOWN40:
	LDA TEMPORARY_ARMS_GEAR
	AND #$00FF
	DEC
	PHA
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	LDY #.SIZEOF(item)
	JSL MULT168
	LDX @LOCAL02
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL04
	LDA @LOCAL03
	CLC
	ADC @VIRTUAL04
	STA @LOCAL03
@UNKNOWN41:
	LDA TEMPORARY_OTHER_GEAR
	AND #$00FF
	BEQ @UNKNOWN43
	LDX #0
	LDA @LOCAL04
	STA @VIRTUAL02
	CMP #3
	BNE @UNKNOWN42
	LDX #1
@UNKNOWN42:
	STX @VIRTUAL04
	LDA TEMPORARY_OTHER_GEAR
	AND #$00FF
	DEC
	PHA
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	LDY #.SIZEOF(item)
	JSL MULT168
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL03
	CLC
	ADC @VIRTUAL02
	STA @LOCAL03
@UNKNOWN43:
	LDA #1
	STA FORCE_LEFT_TEXT_ALIGNMENT
	LDA @LOCAL03
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN46
	LDA #0
	BRA @UNKNOWN51
@UNKNOWN46:
	LDA @LOCAL03
	CLC
	SBC #$00FF
	BRANCHLTEQS @UNKNOWN49
	LDX #$00FF
	BRA @UNKNOWN50
@UNKNOWN49:
	LDA @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@UNKNOWN50:
	TXA
@UNKNOWN51:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	STZ FORCE_LEFT_TEXT_ALIGNMENT
@UNKNOWN53:
	JSL CLEAR_INSTANT_PRINTING
	END_C_FUNCTION
