
UNKNOWN_C1AA5D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL BACKUP_CURRENT_WINDOW_TEXT_ATTRIBUTES
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	TAX
	STX @LOCAL02
@UNKNOWN0:
	LDX @LOCAL02
	TXA
	JSL PRINT_EQUIPMENT_AND_STATS
	LDA GAME_STATE + game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BEQ @UNKNOWN2
	LDA #0
	JSR OPEN_EQUIP_SELECT_MENU
	LOADPTR PRINT_EQUIPMENT_AND_STATS, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDX #1
	LDA #0
	JSR CHAR_SELECT_PROMPT
	TAX
	STX @LOCAL02
	JSR CLOSE_EQUIP_SELECT_MENU
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	TAX
	STX @LOCAL02
	LDA #0
	JSR SWAP_RAISED_HP_PP_WINDOW
@UNKNOWN3:
	LDX @LOCAL02
	BEQ @UNKNOWN4
	TXA
	JSR HANDLE_EQUIP_MENU
	LDA GAME_STATE + game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BNE @UNKNOWN0
@UNKNOWN4:
	LDA #WINDOW::EQUIP_MENU_STATS
	JSR CLOSE_WINDOW
	LDA #WINDOW::EQUIP_MENU
	JSR CLOSE_WINDOW
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL RESTORE_CURRENT_WINDOW_TEXT_ATTRIBUTES
	LDX @LOCAL02
	TXA
	END_C_FUNCTION
