
UNKNOWN_C1AA5D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL UNKNOWN_C20A20
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	TAX
	STX @LOCAL02
@UNKNOWN0:
	LDX @LOCAL02
	TXA
	JSL UNKNOWN_C1A778
	LDA GAME_STATE + game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BEQ @UNKNOWN2
	LDA #0
	JSR UNKNOWN_C193E7
	LOADPTR UNKNOWN_C1A778, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDX #1
	LDA #0
	JSR CHAR_SELECT_PROMPT
	TAX
	STX @LOCAL02
	JSR UNKNOWN_C19437
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	TAX
	STX @LOCAL02
	LDA #0
	JSR UNKNOWN_C43573
@UNKNOWN3:
	LDX @LOCAL02
	BEQ @UNKNOWN4
	TXA
	JSR UNKNOWN_C1A795
	LDA GAME_STATE + game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BNE @UNKNOWN0
@UNKNOWN4:
	LDA #WINDOW::UNKNOWN2D
	JSR CLOSE_WINDOW
	LDA #WINDOW::EQUIP_MENU
	JSR CLOSE_WINDOW
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL UNKNOWN_C20ABC
	LDX @LOCAL02
	TXA
	END_C_FUNCTION
