
UNKNOWN_C1ACA1: ;$C1ACA1
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 26
	STX $18
	STA $16
	PROMOTENEARPTR UNKNOWN_7E9CF5, $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $0E
	LDA $16
	PROMOTENEARPTRA $06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT $06, $12
	TXA
	JSL MEMCPY24
	LDX $18
	SEP #PROC_FLAGS::ACCUM8
	STZ UNKNOWN_7E9CF5,X
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTS
