
UNKNOWN_C1AD7D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_ATTRS
	TAX
	STX @LOCAL00
	LDA #EVENT_FLAG::FLG_WIN_GIEGU
	JSL GET_EVENT_FLAG
	CMP #0
	BEQ @UNKNOWN0
	LDX @LOCAL00
	TXA
	AND #$0007
	BNE @UNKNOWN0
	LDA #ITEM::BICYCLE
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX @LOCAL00
	TXA
	XBA
	AND #$00FF
@UNKNOWN1:
	END_C_FUNCTION
