
UNKNOWN_C1AD7D: ;$C1AD7D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_ATTRS
	TAX
	STX $0E
	LDA #EVENT_FLAG::FLG_WIN_GIEGU
	JSL GET_EVENT_FLAG
	CMP #$0000
	BEQ @UNKNOWN0
	LDX $0E
	TXA
	AND #$0007
	BNE @UNKNOWN0
	LDA #$00B0
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX $0E
	TXA
	XBA
	AND #$00FF
@UNKNOWN1:
	PLD
	RTS
