
UNKNOWN_C1BB71:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
@UNKNOWN0:
@UNKNOWN1:
	LOADPTR UNKNOWN_C1952F, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDX #1
	LDA #0
	JSR CHAR_SELECT_PROMPT
	TAX
	BEQL @UNKNOWN9
	CPX #3
	BEQ @UNKNOWN0
	CREATE_WINDOW_NEAR #WINDOW::UNKNOWN2E
	LDA #0
	STA @LOCAL03
	BRA @UNKNOWN4
@UNKNOWN3:
	TAX
	INX
	STX @LOCAL02
	LOADPTR PSI_CATEGORIES, @VIRTUAL06
	LDA @LOCAL03
	OPTIMIZED_MULT @VIRTUAL04, 5
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT_CONSTANT NULL, @LOCAL01
	TXA
	JSR UNKNOWN_C115F4
	LDX @LOCAL02
	TXA
	STA @LOCAL03
@UNKNOWN4:
	CMP #4
	BCC @UNKNOWN3
	LDY #0
	TYX
	LDA #1
	JSR UNKNOWN_C1180D
@UNKNOWN5:
	LDA #WINDOW::UNKNOWN2E
	JSR SET_WINDOW_FOCUS
	JSR PRINT_MENU_ITEMS
	LOADPTR UNKNOWN_C1CAF5, @LOCAL00
	JSR UNKNOWN_C11F5A
	LDA #1
	JSR SELECTION_MENU
	TAX
	STX @LOCAL02
	JSR UNKNOWN_C11F8A
	LDX @LOCAL02
	BEQ @UNKNOWN8
	LDA #1
	JSR UNKNOWN_C12BD5
	CMP #0
	BEQ @UNKNOWN5
	LDA #1
	JSR SET_WINDOW_FOCUS
	LOADPTR UNKNOWN_C1BB06, @LOCAL00
	JSR UNKNOWN_C11F5A
@UNKNOWN7:
	LDA #1
	JSR SELECTION_MENU
	CMP #0
	BNE @UNKNOWN7
	JSR UNKNOWN_C11F8A
	LDA #WINDOW::UNKNOWN04
	JSR CLOSE_WINDOW
	LDA #WINDOW::UNKNOWN2F
	JSR CLOSE_WINDOW
	BRA @UNKNOWN5
@UNKNOWN8:
	LDA #WINDOW::UNKNOWN2E
	JSR CLOSE_WINDOW
	LDA #WINDOW::TEXT_STANDARD
	JSR CLOSE_WINDOW
	LDX @LOCAL02
	BEQL @UNKNOWN1
@UNKNOWN9:
	LDA #WINDOW::STATUS_MENU
	JSR CLOSE_WINDOW
	END_C_FUNCTION
