
UNKNOWN_C1BB06: ;$C1BB06
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	TAX
	STX $12
	TXA
	JSL UNKNOWN_C1C8BC
	CREATE_WINDOW_NEAR #WINDOW::UNKNOWN2F
	JSR SET_INSTANT_PRINTING
	LOADPTR PSI_ABILITY_TABLE, $0A
	LDX $12
	TXA
	OPTIMIZED_MULT $04, 15
	CLC
	ADC #$000B
	CLC
	ADC $0A
	STA $0A
	DEREFERENCE_PTR_TO $0A, $06
	MOVE_INT $06, $0E
	JSL DISPLAY_TEXT
	JSR CLEAR_INSTANT_PRINTING
@UNKNOWN1:
	PLD
	RTL
