
UNKNOWN_C1C373:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #0
	STA @VIRTUAL02
	BRA @UNKNOWN2
@UNKNOWN0:
	LDY #15
	LDX #1
	STX @LOCAL00
.IF .DEFINED(JPN)
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDX @VIRTUAL02
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	LDX @LOCAL00
	JSR UNKNOWN_C1C32A
	CMP #0
	BEQ @UNKNOWN1
	LDA @VIRTUAL02
	INC
	BRA @UNKNOWN3
@UNKNOWN1:
	INC @VIRTUAL02
@UNKNOWN2:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CMP @VIRTUAL04
	BCC @UNKNOWN0
	LDA #0
@UNKNOWN3:
	END_C_FUNCTION
