
UNKNOWN_C1C32A:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL01
	STX @LOCAL00
	STA @VIRTUAL02
	LDA #0
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CMP #3
	BEQ @UNKNOWN0
	LDA @VIRTUAL02
	JSR UNKNOWN_C1C165
	CMP #0
	BEQ @UNKNOWN0
	LDY @LOCAL01
	LDX @LOCAL00
	LDA @VIRTUAL02
	JSR UNKNOWN_C1C1BA
	CMP #0
	BEQ @UNKNOWN0
	LDA #1
	STA @VIRTUAL04
@UNKNOWN0:
	LDA @VIRTUAL04
	END_C_FUNCTION
