
UNKNOWN_C1CAF5:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL03
.IF .DEFINED(JPN)
	JSR SET_INSTANT_PRINTING
	LDA BATTLE_MENU_CURRENT_CHARACTER_ID
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDX BATTLE_MENU_CURRENT_CHARACTER_ID
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	TAY
	STY @LOCAL02
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
.IF .DEFINED(USA)
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
.ENDIF
	LDX @LOCAL03
	TXA
	CMP #1
	BEQ @UNKNOWN0
	CMP #2
	BEQ @UNKNOWN1
	CMP #3
	BEQ @UNKNOWN2
	CMP #4
	BEQ @UNKNOWN3
	BRA @UNKNOWN4
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA #2
	STA @LOCAL00
	LDA #1
	STA @LOCAL01
	LDY @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSR GENERATE_PSI_LIST
	BRA @UNKNOWN4
@UNKNOWN1:
	SEP #PROC_FLAGS::ACCUM8
	LDA #2
	STA @LOCAL00
	STA @LOCAL01
	LDY @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSR GENERATE_PSI_LIST
	BRA @UNKNOWN4
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	LDA #2
	STA @LOCAL00
	LDA #4
	STA @LOCAL01
	LDY @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSR GENERATE_PSI_LIST
	BRA @UNKNOWN4
@UNKNOWN3:
	SEP #PROC_FLAGS::ACCUM8
	LDA #3
	STA @LOCAL00
	LDA #8
	STA @LOCAL01
	LDY @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSR GENERATE_PSI_LIST
@UNKNOWN4:
	END_C_FUNCTION
