
UNKNOWN_C1CAF5: ;$C1CAF5
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	TAX
	STX $12
	LDX BATTLE_MENU_CURRENT_CHARACTER_ID
	LDA GAME_STATE + game_state::party_members,X
	AND #$00FF
	TAY
	STY $10
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
	LDX $12
	TXA
	CMP #$0001
	BEQ @UNKNOWN0
	CMP #$0002
	BEQ @UNKNOWN1
	CMP #$0003
	BEQ @UNKNOWN2
	CMP #$0004
	BEQ @UNKNOWN3
	BRA @UNKNOWN4
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0002
	STA $0E
	LDA #$0001
	STA $0F
	LDY $10
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSR GENERATE_PSI_LIST
	BRA @UNKNOWN4
@UNKNOWN1:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0002
	STA $0E
	STA $0F
	LDY $10
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSR GENERATE_PSI_LIST
	BRA @UNKNOWN4
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0002
	STA $0E
	LDA #$0004
	STA $0F
	LDY $10
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSR GENERATE_PSI_LIST
	BRA @UNKNOWN4
@UNKNOWN3:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0003
	STA $0E
	LDA #$0008
	STA $0F
	LDY $10
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSR GENERATE_PSI_LIST
@UNKNOWN4:
	PLD
	RTL
