
UNKNOWN_C1CA72:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	STA @VIRTUAL04
	JSL SET_INSTANT_PRINTING
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	CLC
	ADC #window_stats::text_y
	TAX
	STX @LOCAL01
	LDA __BSS_START__,X
	TAY
	STY @LOCAL00
	LDA CURRENT_FOCUS_WINDOW
	JSL REMOVE_WINDOW_FROM_SCREEN
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
	LDA OVERWORLD_SELECTED_PSI_USER
	JSL CREATE_OVERWORLD_PSI_MENU_WINDOW
	JSR PRINT_MENU_ITEMS
	LDY @LOCAL00
	TYA
	LDX @LOCAL01
	STA __BSS_START__,X
	JSR GET_TEXT_Y
	TAX
	LDA #0
	JSL MOVE_CURRENT_TEXT_CURSOR
	LDA @VIRTUAL02
	JSR WINDOW_SET_TEXT_COLOR
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(psi_ability)
	TAX
	LDA f:PSI_ABILITY_TABLE + psi_ability::name,X
	AND #$00FF
	JSR GET_PSI_NAME
	LDA #0
	JSR WINDOW_SET_TEXT_COLOR
	JSL CLEAR_INSTANT_PRINTING
	END_C_FUNCTION
