
UNKNOWN_C1CA06:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	STACK_RESERVE_INT32
.ENDIF
	STACK_RESERVE_INT16 "LOCAL01"
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL06
	LDA @LOCAL01
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(psi_ability)
	TAX
	STX @LOCAL01
	TXA
	OPTIMIZED_ADD psi_ability::name
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	JSR GET_PSI_NAME
	LDX @LOCAL01
	TXA
	OPTIMIZED_ADD psi_ability::level
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	DEC
	ASL
.IF .DEFINED(PROTOTYPE19950327) || .DEFINED(JPN)
	TAX
	LDA f:PSI_SUFFIXES,X
	AND #$00FF
	JSR PRINT_LETTER
.ELSE
	PHA
	LOADPTR PSI_SUFFIXES, @VIRTUAL06
	PLA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #.LOWORD(-1)
	JSL UNKNOWN_C447FB
.ENDIF
	END_C_FUNCTION
