
UNKNOWN_C1CE85:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL03
	LDA #$00FF
	STA @VIRTUAL02
	LDA __BSS_START__+1,Y
	AND #$00FF
	TAX
	LDA __BSS_START__,Y
	AND #$00FF
	JSL GET_CHARACTER_ITEM
	STA @LOCAL02
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDY @LOCAL03
	STY @VIRTUAL04
	INC @VIRTUAL04
	INC @VIRTUAL04
	LDA #2
	LDX @VIRTUAL04
	STA __BSS_START__,X
	TYA
	INC
	INC
	INC
	INC
	STA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA (@LOCAL01)
	REP #PROC_FLAGS::ACCUM8
	TYA
	CLC
	ADC #5
	STA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	STA (@LOCAL00)
	LDY #item::type
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @LOCAL02
	AND #$0030
	CMP #1 << 4
	BEQ @UNKNOWN0
	CMP #2 << 4
	BEQ @UNKNOWN0
	CMP #3 << 4
	BEQ @UNKNOWN2
	JMP @UNKNOWN6
@UNKNOWN0:
	LDA #item::effect
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDY @LOCAL03
	LDA __BSS_START__,Y
	AND #$00FF
	TAX
	LDA [@VIRTUAL06]
	JSR DETERMINE_TARGETTING
	STA @VIRTUAL02
	AND #$00FF
	BNE @UNKNOWN1
	LDA #0
	JMP @UNKNOWN7
@UNKNOWN1:
	LDA [@VIRTUAL06]
	LDX @VIRTUAL04
	STA __BSS_START__,X
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA @VIRTUAL02
	JSL ASR8_UNKNOWN1
	SEP #PROC_FLAGS::ACCUM8
	STA (@LOCAL01)
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA (@LOCAL00)
	BRA @UNKNOWN6
@UNKNOWN2:
	.A16
	.I16
	LDA @LOCAL02
	AND #$000C
	BEQ @UNKNOWN3
	CMP #4
	BNE @UNKNOWN6
@UNKNOWN3:
	LDY @LOCAL03
	LDA __BSS_START__,Y
	AND #$00FF
	TAX
	STX @LOCAL02
	DEX
	SEP #PROC_FLAGS::ACCUM8
	LDY #item::flags
	LDA [@VIRTUAL06],Y
	AND f:ITEM_USABLE_FLAGS,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @UNKNOWN5
	LDA #item::effect
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDX @LOCAL02
	LDA [@VIRTUAL06]
	JSR DETERMINE_TARGETTING
	STA @VIRTUAL02
	AND #$00FF
	BNE @UNKNOWN4
	LDA #0
	BRA @UNKNOWN7
@UNKNOWN4:
	LDA [@VIRTUAL06]
	LDX @VIRTUAL04
	STA __BSS_START__,X
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA @VIRTUAL02
	JSL ASR8_UNKNOWN1
	SEP #PROC_FLAGS::ACCUM8
	STA (@LOCAL01)
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA (@LOCAL00)
	BRA @UNKNOWN6
@UNKNOWN5:
	.A16
	.I16
	LDA #3
	LDX @VIRTUAL04
	STA __BSS_START__,X
@UNKNOWN6:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
@UNKNOWN7:
	REP #PROC_FLAGS::INDEX8
	END_C_FUNCTION
