
UNKNOWN_C1CFC6:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;NEAR battle_menu_selection*
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LDY #0
	STY @LOCAL01
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::items,X
	AND #$00FF
	BEQ @UNKNOWN1
@UNKNOWN0:
	CREATE_WINDOW_NEAR #WINDOW::INVENTORY
	LDX #2
	STX @LOCAL00
	LDX @VIRTUAL02
	LDA a:battle_menu_selection::user,X
	AND #$00FF
	LDX @LOCAL00
	JSR INVENTORY_GET_ITEM_NAME
	LDA #1
	JSR SELECTION_MENU
	TAY
	STY @LOCAL01
	JSR SET_INSTANT_PRINTING
	JSR CLOSE_FOCUS_WINDOW
	LDY @LOCAL01
	BEQ @UNKNOWN1
	CREATE_WINDOW_NEAR #WINDOW::UNKNOWN26
	LDA #6
	JSR UNKNOWN_C10FEA
	LDY @LOCAL01
	TYX
	STX @LOCAL00
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	LDX @LOCAL00
	JSL GET_CHARACTER_ITEM
	JSR UNKNOWN_C19216
	LDA #0
	JSR UNKNOWN_C10FEA
	JSR CLEAR_INSTANT_PRINTING
	LDY @LOCAL01
	TYA
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA __BSS_START__ + 1,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	JSR UNKNOWN_C1CE85
	TAY
	STY @LOCAL01
	LDA #WINDOW::UNKNOWN26
	JSR CLOSE_WINDOW
	LDY @LOCAL01
	BEQ @UNKNOWN0
@UNKNOWN1:
	LDY @LOCAL01
	TYA
	END_C_FUNCTION
