
UNKNOWN_C1CFC6:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;NEAR battle_menu_selection*
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL01
	LDX #0
	STX @LOCAL00
	LDA __BSS_START__,Y
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::items,X
	AND #$00FF
	BEQ @UNKNOWN1
@UNKNOWN0:
	CREATE_WINDOW_NEAR #WINDOW::INVENTORY
	LDX #2
	LDY @LOCAL01
	LDA a:battle_menu_selection::user,Y
	AND #$00FF
	JSR INVENTORY_GET_ITEM_NAME
	LDA #1
	JSR SELECTION_MENU
	TAX
	STX @LOCAL00
	JSL SET_INSTANT_PRINTING
	JSR CLOSE_FOCUS_WINDOW
	LDX @LOCAL00
	BEQ @UNKNOWN1
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDY @LOCAL01
	STA a:battle_menu_selection::param1,Y
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSR UNKNOWN_C1CE85
	TAX
	STX @LOCAL00
	LDA #WINDOW::UNKNOWN26
	JSL CLOSE_WINDOW
	LDX @LOCAL00
	BEQ @UNKNOWN0
@UNKNOWN1:
	LDX @LOCAL00
	TXA
	END_C_FUNCTION
