
UNKNOWN_C1D038:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL00
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @LOCAL00
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	STA @LOCAL00
	CLC
	ADC #item::type
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	CMP #8
	BNE @UNKNOWN0
	LDA @LOCAL00
	CLC
	ADC #item::params + item_parameters::ep
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #0
@UNKNOWN1:
	END_C_FUNCTION
