
UNKNOWN_C1DD9F: ;$C1DD9F
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	MOVE_INT $20, $06
	LDA #$0001
	JSR ENABLE_BLINKING_TRIANGLE
	MOVE_INT $06, $0E
	JSL DISPLAY_TEXT
	JSR CLEAR_BLINKING_PROMPT
	PLD
	RTL
