
UNKNOWN_C1E48D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL03
	STX @VIRTUAL04
	TAX
	STX @LOCAL02
	JSR SET_INSTANT_PRINTING
	LDX @LOCAL02
	TXA
	JSR SET_WINDOW_FOCUS
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(window_stats)
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @VIRTUAL02
	LDY @LOCAL03
	TYA
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN1
	CMP #WINDOW::FILE_SELECT_NAMING_NAME_BOX
	BEQ @UNKNOWN4
	CMP #WINDOW::FILE_SELECT_NAMING_MESSAGE
	BEQL @UNKNOWN7_
	JMP @UNKNOWN7_2
@UNKNOWN1:
	LDA @VIRTUAL02
	CLC
	ADC #window_stats::text_x
	TAX
	STX @LOCAL03
	LDA __BSS_START__,X
	BNE @UNKNOWN2
	LDX #1
	STX @LOCAL01
	JMP @UNKNOWN8_
@UNKNOWN2:
	CMP @VIRTUAL04
	BCS @UNKNOWN3
	LDA #CHAR::PLACEHOLDER
	JSR PRINT_LETTER
	LDX @LOCAL03
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
@UNKNOWN3:
	LDA @VIRTUAL02
	CLC
	ADC #window_stats::text_x
	TAX
	STX @LOCAL00
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	LDA #CHAR::BULLET
	JSR PRINT_LETTER
	LDX @LOCAL00
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	JMP @UNKNOWN8
@UNKNOWN4:
	LDX @VIRTUAL02
	LDA a:window_stats::text_x,X
	STA @LOCAL00
	BEQL @UNKNOWN8
	LDX @VIRTUAL02
	LDA a:window_stats::text_y,X
	TAX
	LDA @LOCAL00
	DEC
	JSL UNKNOWN_C208B8
	STA @LOCAL00
	CMP #96
	BCS @UNKNOWN6
	JMP @UNKNOWN8
@UNKNOWN6:
	AND #$000F
	TAX
	CPX #2
	BEQ @UNKNOWN7
	CPX #4
	BEQ @UNKNOWN7
	CPX #6
	BEQ @UNKNOWN7
	CPX #9
	BEQ @UNKNOWN7
	JMP @UNKNOWN8
@UNKNOWN7:
	LDA @VIRTUAL02
	CLC
	ADC #window_stats::text_x
	TAX
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	LDA @LOCAL00
	INC
	JSR PRINT_LETTER
	BRA @UNKNOWN8
@UNKNOWN7_:
	LDA @VIRTUAL02
	CLC
	ADC #window_stats::text_x
	TAY
	STY @LOCAL03
	LDA __BSS_START__,Y
	STA @LOCAL01
	BEQ @UNKNOWN8
	LDX @VIRTUAL02
	LDA a:window_stats::text_y,X
	TAX
	LDA @LOCAL01
	DEC
	JSL UNKNOWN_C208B8
	STA @LOCAL02
	CMP #96
	BLTEQ @UNKNOWN8
	AND #$000F
	CMP #9
	BNE @UNKNOWN8
	LDY @LOCAL03
	LDA __BSS_START__,Y
	DEC
	STA __BSS_START__,Y
	LDA @LOCAL02
	INC
	INC
	JSR PRINT_LETTER
	BRA @UNKNOWN8
@UNKNOWN7_2:
	LDA @VIRTUAL02
	CLC
	ADC #window_stats::text_x
	TAX
	STX @LOCAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL04
	BCS @UNKNOWN8
	TYA
	JSR PRINT_LETTER
	LDX @LOCAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL04
	BCS @UNKNOWN8
	LDA #CHAR::BULLET
	JSR PRINT_LETTER
	LDX @LOCAL02
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
@UNKNOWN8:
	LDX #0
	STX @LOCAL01
@UNKNOWN8_:
	LDA #WINDOW::FILE_SELECT_NAMING_KEYBOARD
	JSR SET_WINDOW_FOCUS
	LDX @LOCAL01
	TXA
	PLD
	RTS
