
UNKNOWN_C1E48D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL01
	STX @LOCAL00
	STA @VIRTUAL02
	JSL SET_INSTANT_PRINTING
	LDA @VIRTUAL02
	JSR SET_WINDOW_FOCUS
	LDY @LOCAL01
	LDX @LOCAL00
	LDA @VIRTUAL02
	JSL UNKNOWN_C442AC
	TAX
	STX @LOCAL00
	LDA #WINDOW::FILE_SELECT_NAMING_KEYBOARD
	JSR SET_WINDOW_FOCUS
	LDX @LOCAL00
	TXA
	END_C_FUNCTION
