
PLAY_CREDITS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #1
	STA DISABLED_TRANSITIONS
	JSL UNKNOWN_C4F07D
	JSL OAM_CLEAR
	LDX #2
	LDA #1
	JSL FADE_IN
	JSL COUNT_PHOTO_FLAGS
	CMP #0
	BEQ @UNKNOWN0
	JSL COUNT_PHOTO_FLAGS
	TAY
	LDA #CREDITS_LENGTH
	JSL DIVISION16S_DIVISOR_POSITIVE
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #CREDITS_LENGTH
@UNKNOWN1:
	STA @VIRTUAL04
	STA @VIRTUAL02
	LDA #.LOWORD(UNKNOWN_C0F41E)
	JSL SET_IRQ_CALLBACK
	LDY #0
	STY @LOCAL02
	JMP @UNKNOWN12
@UNKNOWN2:
	TYA
	JSL UNKNOWN_C4F264
	CMP #0
	BEQL @UNKNOWN11
	LDX #$FFFF
	LDA #64
	JSL UNKNOWN_C496E7
	.A16
	LDX #64
	STX @LOCAL01
	BRA @UNKNOWN5
@UNKNOWN4:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL UNKNOWN_C4F01D
	JSL UNKNOWN_C1004E
	LDX @LOCAL01
	DEX
	STX @LOCAL01
@UNKNOWN5:
	BNE @UNKNOWN4
	JSL UNKNOWN_C49740
	LDY @LOCAL02
	TYA
	JSL UNKNOWN_C4F46F
	BRA @UNKNOWN7
@UNKNOWN6:
	JSL UNKNOWN_C4F01D
	JSL UNKNOWN_C1004E
@UNKNOWN7:
	LDA @VIRTUAL02
	CMP BG3_Y_POS
	BGT @UNKNOWN6
	LOADPTR BUFFER+32, @LOCAL00
	LDX #480
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL MEMSET24
	.A16
	LDX #$FFFF
	LDA #64
	JSL UNKNOWN_C496E7
	LDX #0
	STX @LOCAL01
	BRA @UNKNOWN10
@UNKNOWN9:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL UNKNOWN_C4F01D
	JSL UNKNOWN_C1004E
	LDX @LOCAL01
	INX
	STX @LOCAL01
@UNKNOWN10:
	CPX #64
	BCC @UNKNOWN9
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #480
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 1
	JSL MEMSET16
	LDA #24
	JSL UNKNOWN_C0856B
	JSL UNKNOWN_C4F01D
	JSL UNKNOWN_C1004E
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL04
	STA @VIRTUAL02
@UNKNOWN11:
	LDY @LOCAL02
	INY
	STY @LOCAL02
@UNKNOWN12:
	CPY #NUM_PHOTOS
	BCCL @UNKNOWN2
	BRA @UNKNOWN15
@UNKNOWN14:
	JSL UNKNOWN_C4F01D
	JSL UNKNOWN_C1004E
@UNKNOWN15:
	LDA BG3_Y_POS
	CMP #CREDITS_LENGTH
	BCC @UNKNOWN14
	JSL RESET_IRQ_CALLBACK
	LDX #0
	STX @LOCAL01
	BRA @UNKNOWN17
@UNKNOWN16:
	JSL UNKNOWN_C1004E
	LDX @LOCAL01
	INX
	STX @LOCAL01
@UNKNOWN17:
	CPX #2000
	BCC @UNKNOWN16
	LDY #0
	LDX #2
	LDA #1
	JSL FADE_OUT_WITH_MOSAIC
	LDX #0
	LDA #$B3
	JSL UNKNOWN_C4249A
	JSL UNKNOWN_C08726
	JSL OVERWORLD_SETUP_VRAM
	JSL UNKNOWN_C021E6
	LDA #23
	STA ENTITY_ALLOCATION_MIN_SLOT
	LDA #24
	STA ENTITY_ALLOCATION_MAX_SLOT
	LDY #0
	TYX
	LDA #EVENT_SCRIPT::EVENT_001
	JSL INIT_ENTITY
	JSL UNKNOWN_C02D29
	JSL UNKNOWN_C03A24
	PROMOTENEARPTR BG2_BUFFER, @VIRTUAL06
	LDX #0
	BRA @UNKNOWN19
@UNKNOWN18:
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	INX
@UNKNOWN19:
	CPX #512
	BCC @UNKNOWN18
	JSL UNDRAW_FLYOVER_TEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0017
	STA TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PROCESS_OVERWORLD_TASKS)
	JSL SET_IRQ_CALLBACK
	STZ DISABLED_TRANSITIONS
	END_C_FUNCTION
