
PRINT_CAST_NAME_PARTY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
.IF .DEFINED(JPN)
	STACK_RESERVE_INT32
.ELSE
	STACK_RESERVE_INT16
.ENDIF
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
.IF .DEFINED(JPN)
	STY @VIRTUAL04
	STX @VIRTUAL02
	TAX
	CPX #7
	BEQ @UNKNOWN0
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::name
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #.SIZEOF(char_struct::name)
	LDA @VIRTUAL02
	JSL PREPARE_CAST_NAME_TILEMAP
	TAX
	BRA @UNKNOWN1
@UNKNOWN0:
	PROMOTENEARPTR GAME_STATE + game_state::pet_name, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #.SIZEOF(game_state::pet_name)
	LDA @VIRTUAL02
	JSL PREPARE_CAST_NAME_TILEMAP
	TAX
@UNKNOWN1:
	TXY
	LDX @VIRTUAL04
	LDA @VIRTUAL02
	JSL COPY_CAST_NAME_TILEMAP
.ELSE
	STY @VIRTUAL04
	STX @VIRTUAL02
	CMP #7
	BEQ @UNKNOWN0
	LDY @VIRTUAL02
	LDX #UNK_SIZE
	STX @LOCAL00
	DEC
	ASL
	TAX
	LDA UNKNOWN_C3FDB5,X
	LDX @LOCAL00
	JSL PREPARE_CAST_NAME_TILEMAP
	LDY #UNK_SIZE
	LDX @VIRTUAL04
	LDA @VIRTUAL02
	JSL COPY_CAST_NAME_TILEMAP
	BRA @UNKNOWN1
@UNKNOWN0:
	LDY @VIRTUAL02
	LDX #6
	LDA #448
	JSL PREPARE_CAST_NAME_TILEMAP
	LDY #6
	LDX @VIRTUAL04
	LDA @VIRTUAL02
	JSL COPY_CAST_NAME_TILEMAP
@UNKNOWN1:
.ENDIF
	END_C_FUNCTION
