
RESUME_MUSIC: ;$EF026E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA .LOWORD(UNKNOWN_7E9695)
	STA .LOWORD(UNKNOWN_7E9697)
	REP #PROC_FLAGS::ACCUM8
	RTL
