
STOP_MUSIC:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA f:APUIO0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
@UNKNOWN0:
	JSL UNKNOWN_C0AC20
	CMP #$0000
	BNE @UNKNOWN0
	LDA #$FFFF
	STA CURRENT_MUSIC_TRACK
	RTL
