
DEBUG_Y_BUTTON_GOODS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #0
	STX @VIRTUAL04
@UNKNOWN0:
	JSR SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_MENU
	LDA #2
	JSR UNKNOWN_C10EB4
.IF .DEFINED(USA)
	LDA #130
	JSR UNKNOWN_C10EB4
	LDX #0
	TXA
	JSL UNKNOWN_C438A5
.ENDIF
	MOVE_INT1632 @VIRTUAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
.IF .DEFINED(USA)
	LDX #0
	LDA #3
	JSL UNKNOWN_C438A5
.ENDIF
	LDA @VIRTUAL04
	JSR UNKNOWN_C19216
	JSR CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
	LDA @VIRTUAL04
	STA @VIRTUAL02
@UNKNOWN1:
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA PAD_HELD
	AND #PAD::UP
	BEQ @UNKNOWN2
	INC @VIRTUAL02
	JMP @UNKNOWN7
@UNKNOWN2:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQ @UNKNOWN3
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
	JMP @UNKNOWN7
@UNKNOWN3:
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @UNKNOWN4
	LDA @VIRTUAL02
	CLC
	ADC #10
	STA @VIRTUAL02
	JMP @UNKNOWN7
@UNKNOWN4:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @UNKNOWN5
	LDA @VIRTUAL02
	SEC
	SBC #10
	STA @VIRTUAL02
	BRA @UNKNOWN7
@UNKNOWN5:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @UNKNOWN6
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDX #1
	TXA
	JSR CHAR_SELECT_PROMPT
	TAY
	STY @LOCAL02
	BEQ @UNKNOWN7
	TYA
	JSL FIND_INVENTORY_SPACE2
	CMP #0
	BEQ @UNKNOWN7
	LDX @VIRTUAL04
	LDY @LOCAL02
	TYA
	JSL GIVE_ITEM_TO_CHARACTER
	LDX @VIRTUAL04
	LDY @LOCAL02
	TYA
	JSL UNKNOWN_C3EE14
	CMP #0
	BEQ @UNKNOWN9
	LDA @VIRTUAL04
	JSR GET_ITEM_TYPE
	CMP #2
	BNE @UNKNOWN9
	LDY @LOCAL02
	TYA
	JSL UNKNOWN_C22351
	TAX
	LDY @LOCAL02
	TYA
	JSR EQUIP_ITEM
	BRA @UNKNOWN9
@UNKNOWN6:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BNE @UNKNOWN9
	JMP @UNKNOWN1
@UNKNOWN7:
	LDA @VIRTUAL02
	CMP #$0100
	BCC @UNKNOWN8
	JMP @UNKNOWN0
@UNKNOWN8:
	LDA @VIRTUAL02
	STA @VIRTUAL04
	JMP @UNKNOWN0
@UNKNOWN9:
	LDA #WINDOW::FILE_SELECT_MENU
	JSR CLOSE_WINDOW
	END_C_FUNCTION
