
MOVEMENT_CODE_07:
	STY $94
	JSR UNKNOWN_C09D03
	BCS @UNKNOWN0
	STY ACTIONSCRIPT_CURRENT_SCRIPT
	LDX $8A
	LDA ENTITY_SCRIPT_NEXT_SCRIPTS,X
	STA ENTITY_SCRIPT_NEXT_SCRIPTS,Y
	TYA
	STA ENTITY_SCRIPT_NEXT_SCRIPTS,X
	TYX
	STZ ENTITY_SCRIPT_STACK_OFFSETS,X
	STZ ENTITY_SCRIPT_SLEEP_FRAMES,X
	LDY $94
	LDA [$80],Y
	STA ENTITY_SCRIPT_PROGRAM_COUNTERS,X
	LDA $82
	STA ENTITY_SCRIPT_PROGRAM_COUNTER_BANKS,X
	INY
	INY
	RTS
@UNKNOWN0:
	LDY $94
	INY
	INY
	RTS
