
MOVEMENT_CODE_0C:
	STY $94
	LDY $8A
MOVEMENT_CODE_0C_UNK1:
	LDX $88
	JSR UNKNOWN_C09D12
	LDA #$FFFF
	STA ENTITY_SCRIPT_SLEEP_FRAMES,Y
	LDA ENTITY_SCRIPT_INDEX_TABLE,X
	BPL @UNKNOWN0
	JMP MOVEMENT_CODE_00
@UNKNOWN0:
	LDY $94
	RTS
