
MOVEMENT_CODE_16:
	LDX $8A
	LDA ENTITY_SCRIPT_TEMPVARS,X
	BNE MOVEMENT_CODE_16_UNKNOWN0
MOVEMENT_CODE_16_ENTRY2:
	LDA [$80],Y
	TAY
	LDA ENTITY_SCRIPT_STACK_OFFSETS,X
	SEC
	SBC #$0003
	STA ENTITY_SCRIPT_STACK_OFFSETS,X
	RTS
MOVEMENT_CODE_16_UNKNOWN0:
	INY
	INY
	RTS
