
DISPLAY_CHECK_POSITION_DEBUG_OVERLAY: ;$EFDCBC
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA #.LOWORD(GAME_STATE)+game_state::leader_x_coord
	STA $04
	LDX $04
	LDA __BSS_START__,X
	XBA
	AND #$00FF
	JSR INTEGER_TO_HEX_DEBUG_TILES
	TAX
	LDA #$007E
	STA $0E
	LDA #$7F44
	STA $10
	TXY
	LDX #$0008
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	JSL PREPARE_VRAM_COPY_ENTRY_B
	.A16
	LDA #.LOWORD(GAME_STATE)+game_state::leader_y_coord
	STA $02
	LDX $02
	LDA __BSS_START__,X
	XBA
	AND #$00FF
	JSR INTEGER_TO_HEX_DEBUG_TILES
	.A16
	TAX
	LDA #$007E
	STA $0E
	LDA #$7F4A
	STA $10
	TXY
	LDX #$0008
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	JSL PREPARE_VRAM_COPY_ENTRY_B
	LDX $04
	LDA __BSS_START__,X
	LSR
	LSR
	LSR
	JSR INTEGER_TO_HEX_DEBUG_TILES
	.A16
	TAX
	LDA #$007E
	STA $0E
	LDA #$7F24
	STA $10
	TXY
	LDX #$0008
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	JSL PREPARE_VRAM_COPY_ENTRY_B
	LDX $02
	LDA __BSS_START__,X
	LSR
	LSR
	LSR
	JSR INTEGER_TO_HEX_DEBUG_TILES
	.A16
	TAX
	LDA #$007E
	STA $0E
	LDA #$7F2A
	STA $10
	TXY
	LDX #$0008
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	JSL PREPARE_VRAM_COPY_ENTRY_B
	LDX $04
	LDA __BSS_START__,X
	JSR INTEGER_TO_HEX_DEBUG_TILES
	.A16
	TAX
	LDA #$007E
	STA $0E
	LDA #$7F04
	STA $10
	TXY
	LDX #$0008
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	JSL PREPARE_VRAM_COPY_ENTRY_B
	LDX $02
	LDA __BSS_START__,X
	JSR INTEGER_TO_HEX_DEBUG_TILES
	.A16
	TAX
	LDA #$007E
	STA $0E
	LDA #$7F0A
	STA $10
	TXY
	LDX #$0008
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	JSL PREPARE_VRAM_COPY_ENTRY_B
	.A16
	LDX $04
	LDA __BSS_START__,X
	XBA
	AND #$00FF
	PHA
	LDY #MAP_WIDTH_TILES
	LDX $02
	LDA __BSS_START__,X
	JSL DIVISION16S_DIVISOR_POSITIVE
	ASL
	ASL
	ASL
	ASL
	ASL
	PLY
	STY $02
	CLC
	ADC $02
	TAX
	LDA MAP_DATA_PER_SECTOR_MUSIC,X
	AND #$00FF
	TAX
	JSR INTEGER_TO_HEX_DEBUG_TILES
	TAX
	LDA #$007E
	STA $0E
	LDA #$7C42
	STA $10
	TXY
	INY
	INY
	INY
	INY
	LDX #$0004
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	JSL PREPARE_VRAM_COPY_ENTRY_B
	LDA CURRENT_SECTOR_ATTRIBUTES
	JSR INTEGER_TO_BINARY_DEBUG_TILES
	.A16
	TAX
	LDA #$007E
	STA $0E
	LDA #$7C62
	STA $10
	TXY
	LDX #$0010
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	JSL PREPARE_VRAM_COPY_ENTRY_B
	LDA GAME_STATE+game_state::trodden_tile_type
	JSR INTEGER_TO_BINARY_DEBUG_TILES
	.A16
	TAX
	LDA #$007E
	STA $0E
	LDA #$7C82
	STA $10
	TXY
	LDX #$0010
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	JSL PREPARE_VRAM_COPY_ENTRY_B
	PLD
	RTS
