
DEBUG_DISPLAY_MENU_OPTIONS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LOADPTR DEBUG_MENU_TEXT_2_LINE_1, @LOCAL00
	LDX #0
	TXA
	JSR RENDER_DEBUG_MENU_STRING
	LOADPTR DEBUG_MENU_TEXT_2_LINE_2, @LOCAL00
	LDX #3
	LDA #11
	JSR RENDER_DEBUG_MENU_STRING
	LDA #6
	STA @VIRTUAL02
	LDY #0
	STY @LOCAL01
	BRA @UNKNOWN1
@UNKNOWN0:
	LOADPTR DEBUG_MENU_TEXT_2_LINE_2, @VIRTUAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 17
	CLC
	ADC #17
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX @VIRTUAL02
	LDA #8
	JSR RENDER_DEBUG_MENU_STRING
	INC @VIRTUAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDY @LOCAL01
	INY
	STY @LOCAL01
@UNKNOWN1:
	CPY #7
	BCC @UNKNOWN0
	END_C_FUNCTION
