
DISPLAY_VIEW_CHARACTER_DEBUG_OVERLAY:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY #64
	LDA GAME_STATE+game_state::leader_x_coord
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @VIRTUAL04
	JSR INTEGER_TO_HEX_DEBUG_TILES
	.A16
	TAX
	LDA #^__BSS_START__
	STA @LOCAL00
	LDA #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 4, 25
	STA @LOCAL01
	TXY
	LDX #8
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY_ENTRY_B
	LDY #64
	LDA GAME_STATE+game_state::leader_y_coord
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @VIRTUAL02
	JSR INTEGER_TO_HEX_DEBUG_TILES
	.A16
	TAX
	LDA #^__BSS_START__
	STA @LOCAL00
	LDA #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 10, 25
	STA @LOCAL01
	TXY
	LDX #8
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY_ENTRY_B
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSL UNKNOWN_C0263D
	JSR INTEGER_TO_DECIMAL_DEBUG_TILES
	.A16
	TAX
	LDA #^__BSS_START__
	STA @LOCAL00
	LDA #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 21, 25
	STA @LOCAL01
	TXY
	LDX #8
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY_ENTRY_B
	LDA ENEMY_SPAWN_TOO_MANY_ENEMIES_FAILURE_COUNT
	JSR INTEGER_TO_DECIMAL_DEBUG_TILES
	.A16
	TAX
	LDA #^__BSS_START__
	STA @LOCAL00
	LDA #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 26, 25
	STA @LOCAL01
	TXY
	LDX #8
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY_ENTRY_B
	.A16
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @UNKNOWN2
	LDA #0
	STA @VIRTUAL02
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
	JSR INTEGER_TO_DECIMAL_DEBUG_TILES
	.A16
	TAX
	LDA #^__BSS_START__
	STA @LOCAL00
	LDA @VIRTUAL02
	STA @VIRTUAL04
	ASL
	ASL
	ADC @VIRTUAL04
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 6, 26
	STA @LOCAL01
	TXY
	LDX #8
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY_ENTRY_B
	.A16
	INC @VIRTUAL02
@UNKNOWN1:
	LDA @VIRTUAL02
	CMP #5
	BNE @UNKNOWN0
	LDA CURRENT_BATTLE_GROUP
	JSR INTEGER_TO_DECIMAL_DEBUG_TILES
	.A16
	TAX
	LDA #^__BSS_START__
	STA @LOCAL00
	LDA #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 1, 26
	STA @LOCAL01
	TXY
	LDX #8
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY_ENTRY_B
@UNKNOWN2:
	END_C_FUNCTION
