
DEBUG_HANDLE_CURSOR_MOVEMENT: ;$EFE578
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA PAD_HELD
	STA $0E
	AND #PAD::UP
	BEQ @UNKNOWN1
	LDA DEBUG_MENU_CURSOR_POSITION
	BEQ @UNKNOWN0
	DEC DEBUG_MENU_CURSOR_POSITION
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #$0006
	STA DEBUG_MENU_CURSOR_POSITION
@UNKNOWN1:
	LDA $0E
	AND #PAD::DOWN
	BEQ @UNKNOWN3
	LDA DEBUG_MENU_CURSOR_POSITION
	CMP #$0006
	BEQ @UNKNOWN2
	INC DEBUG_MENU_CURSOR_POSITION
	BRA @UNKNOWN3
@UNKNOWN2:
	STZ DEBUG_MENU_CURSOR_POSITION
@UNKNOWN3:
	LDA UNKNOWN_7EB553
	ASL
	TAX
	LDA DEBUG_MENU_CURSOR_POSITION
	STA $04
	ASL
	ADC $04
	ASL
	ASL
	ASL
	CLC
	ADC #$0034
	STA ENTITY_ABS_Y_TABLE,X
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::START_BUTTON | PAD::A_BUTTON | PAD::L_BUTTON
	STA UNKNOWN_7EB557
	PLD
	RTS
