
DEBUG_MENU_LOAD:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA #$0080
	STA DEBUG_START_POSITION_X
	LDA #$0070
	STA DEBUG_START_POSITION_Y
	LDA #$0094
	STA DEBUG_VIEW_CHARACTER_SPRITE
	LDA #$FFFF
	STA DAD_PHONE_TIMER
	JSL UNKNOWN_C0927C
	JSR UNKNOWN_EFDA05
	JSR DEBUG_DISPLAY_MENU_OPTIONS
	LDX #$0001
	LDA #$0004
	JSL FADE_IN
@UNKNOWN0:
	JSL OAM_CLEAR
	JSR DEBUG_HANDLE_CURSOR_MOVEMENT
	JSR DEBUG_PROCESS_COMMAND_SELECTION
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
	BRA @UNKNOWN0
