
DEBUG_PROCESS_COMMAND_SELECTION:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA DEBUG_MENU_BUTTONS_PRESSED
	BEQL @UNKNOWN9
	LDA DEBUG_MENU_CURSOR_POSITION
	BEQ @UNKNOWN1
	CMP #$0001
	BEQ @UNKNOWN2
	CMP #$0002
	BEQ @UNKNOWN3
	CMP #$0003
	BEQ @UNKNOWN4
	CMP #$0004
	BEQ @UNKNOWN5
	CMP #$0005
	BEQ @UNKNOWN6
	CMP #$0006
	BEQ @UNKNOWN7
	BRA @UNKNOWN8
@UNKNOWN1:
	LDY #$0000
	LDX #$0001
	LDA #$0004
	JSL FADE_OUT_WITH_MOSAIC
	JSL MAIN_LOOP
	BRA @UNKNOWN8
@UNKNOWN2:
	LDA #$0001
	STA DEBUG_MODE_NUMBER
	LDA #$FFFF
	STA NPC_SPAWNS_ENABLED
	JSR UNKNOWN_EFE175
	BRA @UNKNOWN8
@UNKNOWN3:
	LDA #$0002
	STA DEBUG_MODE_NUMBER
	LDA #$000A
	STA OVERWORLD_ENEMY_MAXIMUM
	LDA #$FFFF
	STA ENEMY_SPAWNS_ENABLED
	JSR UNKNOWN_EFE175
	BRA @UNKNOWN8
@UNKNOWN4:
	LDA #$0003
	STA DEBUG_MODE_NUMBER
	JSR UNKNOWN_EFE175
	BRA @UNKNOWN8
@UNKNOWN5:
	LDA #$0004
	STA DEBUG_MODE_NUMBER
	JSL BATTLE_ROUTINE
	BRA @UNKNOWN8
@UNKNOWN6:
	LDA #$0005
	STA DEBUG_MODE_NUMBER
	JSR UNKNOWN_EFE175
	BRA @UNKNOWN8
@UNKNOWN7:
	LDA #$0006
	STA DEBUG_MODE_NUMBER
	LDA DEBUG_CURSOR_ENTITY
	JSL UNKNOWN_EFD6D4
@UNKNOWN8:
	JSL UNKNOWN_EFEB2A
	STZ DEBUG_MENU_BUTTONS_PRESSED
	STZ DEBUG_MODE_NUMBER
	JSL UNKNOWN_C0927C
	JSR UNKNOWN_EFDA05
	JSR DEBUG_DISPLAY_MENU_OPTIONS
	LDX #$0001
	TXA
	JSL FADE_IN
@UNKNOWN9:
	RTS
