
RESET_DEBUG_SOUND_MODE_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LDY #0
	LDX #1
	LDA #4
	JSL FADE_OUT_WITH_MOSAIC
	JSL INIT_ENTITY_SUBSYSTEM
	JSR INIT_DEBUG_MENU_STRING
	LOADPTR DEBUG_SOUND_MODE_MENU_TEXT, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL00
	LDX #5
	LDA #10
	JSR RENDER_DEBUG_MENU_STRING
	LDA #14
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	STA @LOCAL00
	LDA @VIRTUAL0A+2
	STA @LOCAL00+2
	LDX #10
	TXA
	JSR RENDER_DEBUG_MENU_STRING
	LDA #28
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	STA @LOCAL00
	LDA @VIRTUAL0A+2
	STA @LOCAL00+2
	LDX #12
	LDA #10
	JSR RENDER_DEBUG_MENU_STRING
	LDA #42
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	STA @LOCAL00
	LDA @VIRTUAL0A+2
	STA @LOCAL00+2
	LDX #14
	LDA #10
	JSR RENDER_DEBUG_MENU_STRING
	LDA #56
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	STA @LOCAL00
	LDA @VIRTUAL0A+2
	STA @LOCAL00+2
	LDX #20
	LDA #9
	JSR RENDER_DEBUG_MENU_STRING
	LDA #70
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #22
	LDA #10
	JSR RENDER_DEBUG_MENU_STRING
	LDA @VIRTUAL02
	ASL
	TAX
	LDA #64
	STA ENTITY_ABS_X_TABLE,X
	LDA #80
	STA ENTITY_ABS_Y_TABLE,X
	LDY #0
	LDX #1
	LDA #4
	JSL FADE_IN_WITH_MOSAIC
	END_C_FUNCTION
