
UNKNOWN_C00480:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 2
	JSR GET_COLOUR_AVERAGE
	LDY SAVED_COLOUR_AVERAGE_RED
	LDA COLOUR_AVERAGE_RED
	XBA
	AND #$FF00
	JSL DIVISION16S_DIVISOR_POSITIVE ; COLOUR_AVERAGE_RED / SAVED_COLOUR_AVERAGE_RED
	STA @LOCAL09
	LDY SAVED_COLOUR_AVERAGE_GREEN
	LDA COLOUR_AVERAGE_GREEN
	XBA
	AND #$FF00
	JSL DIVISION16S_DIVISOR_POSITIVE ; COLOUR_AVERAGE_GREEN / SAVED_COLOUR_AVERAGE_GREEN
	STA @LOCAL08
	LDY SAVED_COLOUR_AVERAGE_BLUE
	LDA COLOUR_AVERAGE_BLUE
	XBA
	AND #$FF00
	JSL DIVISION16S_DIVISOR_POSITIVE ; COLOUR_AVERAGE_BLUE / SAVED_COLOUR_AVERAGE_BLUE
	STA @LOCAL07
	LDY #3
	LDA @LOCAL09
	CLC
	ADC @LOCAL08
	CLC
	ADC @LOCAL07
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @LOCAL06
	LDA @LOCAL09
	CMP #256
	BGTL @UNKNOWN7
	LDA @LOCAL08
	CMP #256
	BGTL @UNKNOWN7
	LDA @LOCAL07
	CMP #256
	BGTL @UNKNOWN7
	LDA #128
	STA @LOCAL05
	JMP @UNKNOWN6
@UNKNOWN3:
	LDA @LOCAL05
	ASL
	TAX
	LDA PALETTES,X
	TAX
	;Extract red
	AND #BGR555::RED
	STA @LOCAL04
	TAY
	STY @LOCAL03
	;Extract green
	TXA
	AND #BGR555::GREEN
	; >> 5
	LSR
	LSR
	LSR
	LSR
	LSR
	STA @VIRTUAL02
	STA @LOCAL02
	LDA @VIRTUAL02
	STA @LOCAL01
	;Extract blue
	TXA
	AND #BGR555::BLUE
	; >>10
	XBA
	AND #$00FF
	LSR
	LSR
	STA @VIRTUAL04
	STA @LOCAL00
	LDA @LOCAL04
	CMP @VIRTUAL02
	BNE @UNKNOWN4 ;red != green
	LDA @VIRTUAL02
	CMP @VIRTUAL04
	BNE @UNKNOWN4 ;green != blue
	LDA @LOCAL04
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BNE @UNKNOWN4 ;blue != red
	LDY @LOCAL06
	LDA @LOCAL04
	JSL MULT16 ; red *= ???
	STA @LOCAL04
	LDY @LOCAL06
	LDA @LOCAL02
	STA @VIRTUAL02
	JSL MULT16 ; blue *= ???
	STA @VIRTUAL02
	LDY @LOCAL06
	LDA @VIRTUAL04
	JSL MULT16 ; green *= ???
	STA @VIRTUAL04
	BRA @UNKNOWN5
@UNKNOWN4:
	LDY @LOCAL09
	LDA @LOCAL04
	JSL MULT16 ; red *= ???
	STA @LOCAL04
	LDY @LOCAL08
	LDA @LOCAL02
	STA @VIRTUAL02
	JSL MULT16 ; blue *= ???
	STA @VIRTUAL02
	LDY @LOCAL07
	LDA @VIRTUAL04
	JSL MULT16 ; green *= ???
	STA @VIRTUAL04
@UNKNOWN5:
	LDA @LOCAL04
	XBA
	AND #$00FF
	AND #$001F
	TAX
	LDY @LOCAL03
	TYA
	JSR UNKNOWN_C00434 ;red & new red
	TAY
	STY @LOCAL03
	LDA @VIRTUAL02
	XBA
	AND #$00FF
	AND #$001F
	TAX
	LDA @LOCAL01
	JSR UNKNOWN_C00434 ;green & new green
	STA @VIRTUAL02
	LDA @VIRTUAL04
	XBA
	AND #$00FF
	AND #$001F
	TAX
	LDA @LOCAL00
	JSR UNKNOWN_C00434 ;blue & new blue
	STA @LOCAL00
	LDA @LOCAL05
	ASL
	TAX
	LDY @LOCAL03 ;final red
	LDA @VIRTUAL02 ;final green
	ASL
	ASL
	ASL
	ASL
	ASL
	STA @VIRTUAL04
	LDA @LOCAL00 ;final blue
	XBA
	AND #$FF00
	ASL
	ASL
	ORA @VIRTUAL04
	STY @VIRTUAL02
	ORA @VIRTUAL02
	STA PALETTES,X
	INC @LOCAL05
@UNKNOWN6:
	LDA @LOCAL05
	CMP #256
	BCCL @UNKNOWN3
@UNKNOWN7:
	END_C_FUNCTION
