
UNKNOWN_C005E7:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	MOVE_INT f:MAP_PALETTE_PTR_TABLE+4, @VIRTUAL06
	LDY #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 2
	STY @LOCAL01
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 6
	TYA
	JSL MEMCPY16
	LDY @LOCAL01
	TYA
	JSR GET_COLOUR_AVERAGE
	LDA COLOUR_AVERAGE_RED
	STA SAVED_COLOUR_AVERAGE_RED
	LDA COLOUR_AVERAGE_GREEN
	STA SAVED_COLOUR_AVERAGE_GREEN
	LDA COLOUR_AVERAGE_BLUE
	STA SAVED_COLOUR_AVERAGE_BLUE
	END_C_FUNCTION
