
UNKNOWN_C0122A:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LDA #64
	JSL SBRK
	TAY
	STY @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #64
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSL MEMSET16
	LDA @VIRTUAL02
	AND #$003F
	STA @VIRTUAL02
	CMP #31
	BGT @UNKNOWN1
	LDY @LOCAL01
	TYA
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	COPY_TO_VRAM1OFFSET @VIRTUAL06, @VIRTUAL02, 64, VRAM::OVERWORLD_LAYER_1_TILEMAP, 27
	COPY_TO_VRAM1OFFSET @VIRTUAL06, @VIRTUAL02, 64, VRAM::OVERWORLD_LAYER_2_TILEMAP, 27
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA @VIRTUAL02
	AND #$001F
	STA @VIRTUAL02
	LDY @LOCAL01
	TYA
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	COPY_TO_VRAM1OFFSET @VIRTUAL06, @VIRTUAL02, 64, VRAM::OVERWORLD_LAYER_1_TILEMAP + TILEMAP_SIZE, 27
	COPY_TO_VRAM1OFFSET @VIRTUAL06, @VIRTUAL02, 64, VRAM::OVERWORLD_LAYER_2_TILEMAP + TILEMAP_SIZE, 27
@UNKNOWN2:
	END_C_FUNCTION
