
UNKNOWN_C01A86:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDX #$0000
	BRA @UNKNOWN1
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA OVERWORLD_SPRITEMAPS,X
	INX
@UNKNOWN1:
	CPX #$0380
	BCC @UNKNOWN0
	REP #PROC_FLAGS::ACCUM8
	RTL
