
UNKNOWN_C01B15:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	CMP #.LOWORD(SPRITE_TABLE_7E467E)
	BCC @UNKNOWN3
	CMP #.LOWORD(SPRITE_TABLE_7E467E) + 179 * .SIZEOF(spritemap) + 1
	BGT @UNKNOWN3
	SEC
	SBC #.LOWORD(SPRITE_TABLE_7E467E)
	STA @LOCAL01
	LDA #0
	STA @VIRTUAL02
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA @LOCAL01
	CLC
	ADC #.LOWORD(SPRITE_TABLE_7E467E + spritemap::special_flags)
	TAX
	STX @LOCAL00
	LDA __BSS_START__,X
	AND #$00FF
	TAY
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #>-1
	STA SPRITE_TABLE_7E467E + spritemap::y_offset,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #>-1
	STA SPRITE_TABLE_7E467E + spritemap::tile,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #>-1
	STA SPRITE_TABLE_7E467E + spritemap::flags,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #>-1
	STA SPRITE_TABLE_7E467E + spritemap::x_offset,X
	LDX @LOCAL00 ;address was precalculated because it was also being read from
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	CLC
	ADC #.SIZEOF(spritemap)
	STA @LOCAL01
	TYA
	AND #128
	BEQ @UNKNOWN1
	INC @VIRTUAL02
@UNKNOWN2:
	LDA @VIRTUAL02
	CMP #2
	BCC @UNKNOWN1
@UNKNOWN3:
	END_C_FUNCTION
