
UNKNOWN_C02194:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	STZ MAGIC_BUTTERFLY_SPAWNED
	STZ ENEMY_SPAWN_TOO_MANY_ENEMIES_FAILURE_COUNT
	STZ OVERWORLD_ENEMY_COUNT
	LDX #0
	STX @LOCAL01
	BRA @UNKNOWN2
@UNKNOWN0:
	TXA
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	INC
	CMP #6
	BLTEQ @UNKNOWN1
	LDX @LOCAL01
	TXA
	JSL UNKNOWN_C02140
@UNKNOWN1:
	LDX @LOCAL01
	INX
	STX @LOCAL01
@UNKNOWN2:
	CPX #MAX_ENTITIES
	BNE @UNKNOWN0
	LDA #0
	STA @LOCAL00
	BRA @UNKNOWN4
@UNKNOWN3:
	ASL
	TAX
	LDA #ENTITY_COLLISION_NO_OBJECT
	STA ENTITY_COLLIDED_OBJECTS,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@UNKNOWN4:
	CMP #MAX_ENTITIES
	BCC @UNKNOWN3
	END_C_FUNCTION
