
UNKNOWN_C0369B: ;$C0369B
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	PHA
	TDC
	ADC #$FFE4
	TCD
	PLA
	TAY
	STY $1A
	LDX #$0000
	STX $18
	CPY #$0005
	BCC @UNKNOWN1
@UNKNOWN0:
	LDA .LOWORD(GAME_STATE)+150,X
	AND #$00FF
	BEQ @UNKNOWN5
	AND #$00FF
	STA $02
	TYA
	CMP $02
	BCC @UNKNOWN5
	BEQ @UNKNOWN5
	INX
	STX $18
	BRA @UNKNOWN0
@UNKNOWN1:
	LDA .LOWORD(GAME_STATE)+150,X
	AND #$00FF
	BEQ @UNKNOWN5
	AND #$00FF
	STA $16
	STA $02
	LDA #$0005
	CLC
	SBC $02
	BVC @UNKNOWN2
	BPL @UNKNOWN5
	BRA @UNKNOWN3
@UNKNOWN2:
	BMI @UNKNOWN5
@UNKNOWN3:
	LDY $1A
	STY $02
	LDA $16
	CMP $02
	BEQ @UNKNOWN4
	BCS @UNKNOWN5
@UNKNOWN4:
	ASL
	TAX
	LDA .LOWORD(UNKNOWN_30X2_TABLE_4),X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA .LOWORD(CHAR_STRUCT)+char_struct::afflictions,X
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN5
	LDX $18
	INX
	STX $18
	BRA @UNKNOWN1
@UNKNOWN5:
	LDX $18
	LDA .LOWORD(GAME_STATE)+150,X
	AND #$00FF
	BEQ @UNKNOWN8
	LDA #$0005
	STA $14
	BRA @UNKNOWN7
@UNKNOWN6:
	CLC
	ADC #$97F5
	STA $12
	LDA $14
	DEC
	STA $04
	CLC
	ADC #$97F5
	STA $02
	LDX $02
	SEP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM)+150,X
	LDY #$0096
	STA ($12),Y
	REP #PROC_FLAGS::ACCUM8
	LDA $14
	ASL
	PHA
	LDA $04
	ASL
	TAX
	LDA .LOWORD(GAME_STATE)+162,X
	PLX
	STA .LOWORD(GAME_STATE)+162,X
	LDX $02
	SEP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM)+game_state::player_controlled_party_members,X
	LDY #$009C
	STA ($12),Y
	REP #PROC_FLAGS::ACCUM8
	LDA $04
	STA $14
@UNKNOWN7:
	LDX $18
	TXA
	DEC
	STA $02
	LDA $14
	CMP $02
	BNE @UNKNOWN6
@UNKNOWN8:
	LDY $1A
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA .LOWORD(GAME_STATE)+150,X
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(GAME_STATE) + game_state::party_count
	PHA
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM),X
	INC
	PLX
	STA a:.LOWORD(RAM),X
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA $12
	STA .LOWORD(UNKNOWN_7E0A38)
	LDA $12
	ASL
	ASL
	ASL
	CLC
	ADC #$0006
	TAX
	LDA f:UNKNOWN_C3DFE8+42,X
	STA $1A
	ASL
	TAX
	LDA .LOWORD(LOADED_SPRITE_MOVEMENT_CODES_TABLE),X
	CMP #$FFFF
	BEQ @UNKNOWN9
	INC $1A
@UNKNOWN9:
	LDX $18
	TXA
	ASL
	TAX
	LDA $1A
	STA .LOWORD(GAME_STATE)+162,X
	LDA $1A
	STA .LOWORD(UNKNOWN_7E0A3A)
	SEC
	SBC #$0018
	STA .LOWORD(UNKNOWN_7E0A3A)
	SEP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(UNKNOWN_7E0A3A)
	LDX $18
	STA .LOWORD(GAME_STATE)+game_state::player_controlled_party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(GAME_STATE)+game_state::party_count
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN10
	LDA .LOWORD(UNKNOWN_7E0A3A)
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA .LOWORD(GAME_STATE)+136
	STA .LOWORD(CHAR_STRUCT)+char_struct::position_index,X
	BRA @UNKNOWN13
@UNKNOWN10:
	CPX #$0000
	BNE @UNKNOWN11
	LDA .LOWORD(GAME_STATE)+136
	STA $16
	BRA @UNKNOWN12
@UNKNOWN11:
	TXA
	DEC
	ASL
	TAX
	LDA .LOWORD(GAME_STATE)+162,X
	ASL
	TAX
	LDA .LOWORD(UNKNOWN_30X2_TABLE_4),X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA .LOWORD(CHAR_STRUCT)+char_struct::position_index,X
	STA $16
@UNKNOWN12:
	LDA .LOWORD(UNKNOWN_7E0A3A)
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA $16
	STA .LOWORD(CHAR_STRUCT)+char_struct::position_index,X
@UNKNOWN13:
	LDA .LOWORD(UNKNOWN_7E0A3A)
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA .LOWORD(CHAR_STRUCT)+char_struct::position_index,X
	BEQ @UNKNOWN14
	TAX
	DEX
	BRA @UNKNOWN15
@UNKNOWN14:
	LDX #$00FF
@UNKNOWN15:
	TXA
	STA $04
	ASL
	ADC $04
	ASL
	ASL
	TAX
	LDA .LOWORD(PLAYER_POSITION_BUFFER),X
	STA $04
	LDA .LOWORD(PLAYER_POSITION_BUFFER)+2,X
	STA $02
	LDA .LOWORD(GAME_STATE)+146
	CMP #$0003
	BEQ @UNKNOWN16
	LDA $12
	ASL
	ASL
	ASL
	TAX
	LDA f:UNKNOWN_C3DFE8+42,X
	STA $18
	BRA @UNKNOWN17
@UNKNOWN16:
	LDA $12
	ASL
	ASL
	ASL
	TAX
	INX
	INX
	LDA f:UNKNOWN_C3DFE8+42,X
	STA $18
@UNKNOWN17:
	LOADPTR UNKNOWN_C3DFE8+42, $06
	LDA $04
	STA $0E
	LDA $02
	STA $10
	LDY $1A
	LDA $12
	ASL
	ASL
	ASL
	INC
	INC
	INC
	INC
	LDX $06
	STX $0A
	LDX $08
	STX $0C
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	TAX
	LDA $18
	JSL PARSE_C3FC49_DATA
	LDA $1A
	ASL
	TAX
	STX $14
	LDA $04
	SEC
	SBC a:.LOWORD(BG1_X_POS)
	STA .LOWORD(SPRITE_SCREEN_X_TABLE),X
	LDA $02
	SEC
	SBC a:.LOWORD(BG1_Y_POS)
	STA .LOWORD(SPRITE_SCREEN_Y_TABLE),X
	LDY #.LOWORD(GAME_STATE) + game_state::current_party_members
	STY $18
	LDA .LOWORD(GAME_STATE)+150
	AND #$00FF
	DEC
	ASL
	ASL
	ASL
	CLC
	ADC #$0006
	CLC
	ADC $06
	STA $06
	LDA [$06]
	STA a:.LOWORD(RAM),Y
	JSL UNKNOWN_C09CD7
	JSL UNKNOWN_C032EC
	LDA .LOWORD(GAME_STATE)+162
	LDY $18
	STA a:.LOWORD(RAM),Y
	JSL UNKNOWN_C034D6
	LDA $04
	STA $9E2D
	LDA $02
	STA $9E2F
	LDX $14
	LDA .LOWORD(UNKNOWN_30X2_TABLE_34),X
	STA $9E31
	LDA $1A
	PLD
	RTL
