
UNKNOWN_C0369B:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL06
	LDX #0
	STX @LOCAL05
	CPY #5
	BCC @UNKNOWN1
@UNKNOWN0:
	TXA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknown96,X
	AND #$00FF
	BEQ @UNKNOWN5
	AND #$00FF
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BLTEQ @UNKNOWN5
	LDX @LOCAL05
	INX
	STX @LOCAL05
	BRA @UNKNOWN0
@UNKNOWN1:
	TXA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknown96,X
	AND #$00FF
	BEQ @UNKNOWN5
	AND #$00FF
	STA @LOCAL04
	STA @VIRTUAL02
	LDA #5
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN5
	LDY @LOCAL06
	STY @VIRTUAL02
	LDA @LOCAL04
	CMP @VIRTUAL02
	BGT @UNKNOWN5
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::afflictions,X
	AND #$00FF
	CMP #1
	BEQ @UNKNOWN5
	LDX @LOCAL05
	INX
	STX @LOCAL05
	BRA @UNKNOWN1
@UNKNOWN5:
	LDX @LOCAL05
	TXA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknown96,X
	AND #$00FF
	BEQ @UNKNOWN8
	LDA #5
	STA @LOCAL03
	BRA @UNKNOWN7
@UNKNOWN6:
	CLC
	ADC #.LOWORD(GAME_STATE)
	STA @LOCAL02
	LDA @LOCAL03
	DEC
	STA @VIRTUAL04
	CLC
	ADC #.LOWORD(GAME_STATE)
	STA @VIRTUAL02
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__ + game_state::unknown96,X
	LDY #game_state::unknown96
	STA (@LOCAL02),Y
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	ASL
	CLC
	ADC #.LOWORD(GAME_STATE)
	PHA
	LDA @VIRTUAL04
	ASL
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknownA2,X
	PLX
	STA a:game_state::unknownA2,X
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__+game_state::player_controlled_party_members,X
	LDY #game_state::player_controlled_party_members
	STA (@LOCAL02),Y
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	STA @LOCAL03
@UNKNOWN7:
	LDX @LOCAL05
	TXA
	DEC
	STA @VIRTUAL02
	LDA @LOCAL03
	CMP @VIRTUAL02
	BNE @UNKNOWN6
@UNKNOWN8:
	LDX @LOCAL05
	TXA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDY @LOCAL06
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA a:game_state::unknown96,X
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(GAME_STATE) + game_state::party_count
	PHA
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	INC
	PLX
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @LOCAL02
	STA NEW_ENTITY_VAR0
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	CLC
	ADC #character_initial_entity_entry::unknown6
	TAX
	LDA f:CHARACTER_INITIAL_ENTITY_DATA,X
	STA @LOCAL06
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN9
	INC @LOCAL06
@UNKNOWN9:
	LDX @LOCAL05
	TXA
	ASL
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA @LOCAL06
	STA a:game_state::unknownA2,X
	LDA @LOCAL06
	STA NEW_ENTITY_VAR1
	SEC
	SBC #24
	STA NEW_ENTITY_VAR1
	LDX @LOCAL05
	TXA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA NEW_ENTITY_VAR1
	STA a:game_state::player_controlled_party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	CMP #1
	BNE @UNKNOWN10
	LDA NEW_ENTITY_VAR1
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA GAME_STATE + game_state::unknown88
	STA PARTY_CHARACTERS+char_struct::position_index,X
	BRA @UNKNOWN13
@UNKNOWN10:
	LDX @LOCAL05
	BNE @UNKNOWN11
	LDA GAME_STATE + game_state::unknown88
	STA @LOCAL04
	BRA @UNKNOWN12
@UNKNOWN11:
	TXA
	DEC
	ASL
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknownA2,X
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::position_index,X
	STA @LOCAL04
@UNKNOWN12:
	LDA NEW_ENTITY_VAR1
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA @LOCAL04
	STA PARTY_CHARACTERS+char_struct::position_index,X
@UNKNOWN13:
	LDA NEW_ENTITY_VAR1
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::position_index,X
	BEQ @UNKNOWN14
	TAX
	DEX
	BRA @UNKNOWN15
@UNKNOWN14:
	LDX #$00FF
@UNKNOWN15:
	TXA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(player_position_buffer_entry)
	TAX
	LDA PLAYER_POSITION_BUFFER + player_position_buffer_entry::x_coord,X
	STA @VIRTUAL04
	LDA PLAYER_POSITION_BUFFER + player_position_buffer_entry::y_coord,X
	STA @VIRTUAL02
	LDA GAME_STATE + game_state::unknown92
	CMP #3
	BEQ @UNKNOWN16
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	TAX
	LDA f:CHARACTER_INITIAL_ENTITY_DATA,X ;character_initial_entity_entry::overworld_sprite
	STA @LOCAL05
	BRA @UNKNOWN17
@UNKNOWN16:
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	TAX
	INX
	INX
	LDA f:CHARACTER_INITIAL_ENTITY_DATA,X ;character_initial_entity_entry::lost_underworld_sprite
	STA @LOCAL05
@UNKNOWN17:
	LOADPTR CHARACTER_INITIAL_ENTITY_DATA, @VIRTUAL06
	LDA @VIRTUAL04
	STA @LOCAL00
	LDA @VIRTUAL02
	STA @LOCAL01
	LDY @LOCAL06
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	INC
	INC
	INC
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A] ;character_initial_entity_entry::actionscript_id
	TAX
	LDA @LOCAL05
	JSL CREATE_ENTITY
	LDA @LOCAL06
	ASL
	TAX
	STX @LOCAL03
	LDA @VIRTUAL04
	SEC
	SBC BG1_X_POS
	STA ENTITY_SCREEN_X_TABLE,X
	LDA @VIRTUAL02
	SEC
	SBC BG1_Y_POS
	STA ENTITY_SCREEN_Y_TABLE,X
	LDY #.LOWORD(GAME_STATE) + game_state::current_party_members
	STY @LOCAL05
	LDA GAME_STATE + game_state::unknown96
	AND #$00FF
	DEC
	ASL
	ASL
	ASL
	CLC
	ADC #character_initial_entity_entry::unknown6
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA __BSS_START__,Y
	JSL UNKNOWN_C09CD7
	JSL UNKNOWN_C032EC
	LDA GAME_STATE + game_state::unknownA2
	LDY @LOCAL05
	STA __BSS_START__,Y
	JSL UPDATE_PARTY
	LDA @VIRTUAL04
	STA ENTITY_PREPARED_X_COORDINATE
	LDA @VIRTUAL02
	STA ENTITY_PREPARED_Y_COORDINATE
	LDX @LOCAL03
	LDA ENTITY_DIRECTIONS,X
	STA ENTITY_PREPARED_DIRECTION
	LDA @LOCAL06
	END_C_FUNCTION
