
UNKNOWN_C03A94:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
.IF .DEFINED(JPN)
	STACK_RESERVE_INT16 "LOCALM2"
.ENDIF
	STACK_RESERVE_INT16 "LOCAL05"
	STACK_RESERVE_INT16 "LOCAL06"
	STACK_RESERVE_INT16 "LOCAL07"
	STACK_RESERVE_INT16 "LOCAL08"
	STACK_RESERVE_INT16 "LOCAL09"
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
.IF .DEFINED(JPN)
	@LOCAL07ALT := @LOCALM2
	@LOCAL08ALT := @LOCAL07
.ELSE
	@LOCAL07ALT := @LOCAL07
	@LOCAL08ALT := @LOCAL08
.ENDIF
	STA @LOCAL09
	LDA CURRENT_TELEPORT_DESTINATION_X
	ORA CURRENT_TELEPORT_DESTINATION_Y
	BEQ @UNKNOWN0
	LDA CURRENT_TELEPORT_DESTINATION_X
	OPTIMIZED_MULT @VIRTUAL04, 8
	STA @LOCAL08
	LDA CURRENT_TELEPORT_DESTINATION_Y
	OPTIMIZED_MULT @VIRTUAL04, 8
	TAX
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA GAME_STATE+game_state::leader_x_coord
	STA @LOCAL08
	LDX GAME_STATE+game_state::leader_y_coord
@UNKNOWN1:
	LDA @LOCAL08
	JSL LOAD_SECTOR_ATTRS
	AND #$0007
	STA @LOCAL07
	STA GAME_STATE+game_state::unknown92
	ASL
	STA FOOTSTEP_SOUND_ID
	STZ FOOTSTEP_SOUND_ID_OVERRIDE
	LDA @LOCAL07
	CMP #3
	BEQ @UNKNOWN2
	STZ GAME_STATE+game_state::walking_style
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA #WALKING_STYLE::SLOWEST
	STA GAME_STATE+game_state::walking_style
@UNKNOWN3:
	LDA CURRENT_ENTITY_SLOT
	STA @LOCAL06
	LDA #.LOWORD(-1)
	STA CURRENT_ENTITY_SLOT
	STZ @LOCAL05
	JMP @UNKNOWN9
@UNKNOWN4:
.IF .DEFINED(JPN)
	LDA @LOCAL05
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknown96,X
.ELSE
	LDY #.LOWORD(GAME_STATE) + game_state::unknown96
	LDA (@LOCAL05),Y
.ENDIF
	AND #$00FF
	TAX
	BEQL @UNKNOWN8
	TXA
	DEC
	STA @VIRTUAL04
	LDA @LOCAL05
	ASL
.IF .DEFINED(JPN)
	STA @LOCALM2
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknownA2,X
.ELSE
	TAY
	LDA GAME_STATE + game_state::unknownA2,Y
.ENDIF
	STA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	STA NEW_ENTITY_VAR0
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	STA NEW_ENTITY_VAR1
.IF .DEFINED(JPN)
	LDA @LOCALM2
	STA NEW_ENTITY_VAR5
.ELSE
	STY NEW_ENTITY_VAR5
.ENDIF
	LDA ENTITY_SPRITEMAP_POINTER_HIGH,X
	STA @LOCAL03
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	STA @LOCAL07ALT
	LDA @VIRTUAL02
	JSL UNKNOWN_C02140
	LDA @VIRTUAL02
	STA MOVING_PARTY_MEMBER_ENTITY_ID
	LDA GAME_STATE+game_state::unknown92
	CMP #3
	BEQ @UNKNOWN6
	LDA @LOCAL05
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAY
	LDX #0
	LDA @VIRTUAL04
	JSL UNKNOWN_C0780F
	STA @LOCAL08ALT
	LDA GAME_STATE+game_state::leader_x_coord
	STA @LOCAL00
	LDA GAME_STATE+game_state::leader_y_coord
	STA @LOCAL01
	LDY @VIRTUAL02
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	TAX
	INX
	INX
	INX
	INX
	LDA f:CHARACTER_INITIAL_ENTITY_DATA,X ;character_initial_entity_entry::actionscript_id
	TAX
	LDA @LOCAL08ALT
	JSL CREATE_ENTITY
	STA @LOCAL02
	BRA @UNKNOWN7
@UNKNOWN6:
	LDA @LOCAL05
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAY
	LDX #10
	LDA @VIRTUAL04
	JSL UNKNOWN_C0780F
	STA @LOCAL08ALT
	LDA GAME_STATE+game_state::leader_x_coord
	STA @LOCAL00
	LDA GAME_STATE+game_state::leader_y_coord
	STA @LOCAL01
	LDY @VIRTUAL02
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	TAX
	INX
	INX
	INX
	INX
	LDA f:CHARACTER_INITIAL_ENTITY_DATA,X ;character_initial_entity_entry::actionscript_id
	TAX
	LDA @LOCAL08ALT
	JSL CREATE_ENTITY
	STA @LOCAL02
@UNKNOWN7:
	ASL
	TAX
	LDA @LOCAL03
	STA ENTITY_SPRITEMAP_POINTER_HIGH,X
	LDA @LOCAL07ALT
	STA ENTITY_TICK_CALLBACK_HIGH,X
	LDA @LOCAL09
	STA ENTITY_DIRECTIONS,X
	STZ ENTITY_ANIMATION_FRAME,X
	LDA @LOCAL02
	JSL UNKNOWN_C0A780
@UNKNOWN8:
	INC @LOCAL05
@UNKNOWN9:
	LDA @LOCAL05
	CMP #6
	BCCL @UNKNOWN4
	LDA @LOCAL06
	STA CURRENT_ENTITY_SLOT
	JSL UNKNOWN_C039E5
	LDA #.LOWORD(-1)
	STA LADDER_STAIRS_TILE_X
	LDA PENDING_INTERACTIONS
	STA @VIRTUAL02
	STZ PENDING_INTERACTIONS
	LDA #4
	STA @LOCAL00
	LDY GAME_STATE+game_state::current_party_members
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL UNKNOWN_C05B7B
	LDA @VIRTUAL02
	STA PENDING_INTERACTIONS
	LDA LADDER_STAIRS_TILE_X
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN11
	LDX LADDER_STAIRS_TILE_Y
	LDA LADDER_STAIRS_TILE_X
	JSL UNKNOWN_C07526
@UNKNOWN11:
	PLD
	RTL
