
UNKNOWN_C03C25:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA #$0001
	STA DO_MAP_MUSIC_FADE
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL UNKNOWN_C068F4
	LDA NEXT_MAP_MUSIC_TRACK
	CMP CURRENT_MAP_MUSIC_TRACK
	BEQ @UNKNOWN0
	JSL WAIT_UNTIL_NEXT_FRAME
	JSL UNKNOWN_C069AF
@UNKNOWN0:
	STZ DO_MAP_MUSIC_FADE
	RTS
