
UNKNOWN_C03DAA: ;$C03DAA
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA .LOWORD(UNKNOWN_7E1A42)
	STA $02
	ASL
	TAY
	STY $0E
	LDA #$FFFF
	STA $3456,Y
	TYA
	CLC
	ADC #$0F12
	STA $04
	LDA #$0008
	LDX $04
	STA a:.LOWORD(RAM),X
	JSL RAND
	AND #$000F
	LDY $0E
	STA .LOWORD(UNKNOWN_30X2_TABLE_5),Y
	LDA $02
	JSL UNKNOWN_C0A780
	LDY $0E
	LDA .LOWORD(UNKNOWN_30X2_TABLE_4),Y
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT)
	TAX
	LDA $02
	STA a:.LOWORD(RAM)+59,X
	LDY $0E
	LDA .LOWORD(UNKNOWN_30X2_TABLE_3),Y
	STA a:.LOWORD(RAM)+53,X
	STZ a:.LOWORD(RAM)+57,X
	LDA #$FFFF
	STA a:.LOWORD(RAM)+92,X
	LDA a:.LOWORD(RAM)+14,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN0
	LDA #$0010
	LDX $04
	STA a:.LOWORD(RAM),X
@UNKNOWN0:
	LDA .LOWORD(GAME_STATE)+game_state::current_party_members
	ASL
	STA .LOWORD(UNKNOWN_7E2898)
	PLD
	RTL
