
UNKNOWN_C03E25:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL00
	LDX #0
	BRA @UNKNOWN1
@UNKNOWN0:
	INX
@UNKNOWN1:
	LDA @LOCAL00
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA GAME_STATE + game_state::unknown96,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @UNKNOWN0
	CPX #0
	BNE @UNKNOWN2
	LDA #.LOWORD(-1)
	BRA @UNKNOWN3
@UNKNOWN2:
	DEX
	LDA GAME_STATE + game_state::unknown96,X
	AND #$00FF
@UNKNOWN3:
	END_C_FUNCTION
