
UNKNOWN_C03EC3:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL00
	STX @VIRTUAL02
	TAX
	LDA @PARAM03
	STA @VIRTUAL04
	TXA
	JSL UNKNOWN_C03E9D
	CMP @VIRTUAL02
	BNE @UNKNOWN0
	LDY @LOCAL00
	INY
	STY @LOCAL00
	LDA CURRENT_ENTITY_SLOT
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ SPRITE_TABLE_10_FLAGS::UNKNOWN12
	STA __BSS_START__,X
	BRA @UNKNOWN1
@UNKNOWN0:
	CMP @VIRTUAL02
	BLTEQ @UNKNOWN1
	LDY @LOCAL00
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL00
	LDA CURRENT_ENTITY_SLOT
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	ORA #SPRITE_TABLE_10_FLAGS::UNKNOWN12
	STA __BSS_START__,X
@UNKNOWN1:
	LDY @LOCAL00
	TYA
	END_C_FUNCTION
