
UNKNOWN_C042C2: ;$C042C2
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAX
	STX $0E
	TXA
	ASL
	PHA
	LDA GAME_STATE+game_state::leader_direction
	ASL
	TAX
	LDA f:UNKNOWN_C3E168,X
	PLX
	STA ENTITY_DIRECTIONS,X
	LDX $0E
	TXA
	JSL UNKNOWN_C09907
	LDX $0E
	TXA
	JSL UNKNOWN_C0A443_ENTRY2
	PLD
	RTL
