
UNKNOWN_C048D3: ;$C048D3
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 32
	TAX
	STX $1E
	LDA .LOWORD(GAME_STATE)+game_state::walking_style
	JSL MAP_INPUT_TO_DIRECTION
	TAY
	STY $1C
	STY $02
	LDA .LOWORD(BATTLE_SWIRL_COUNTDOWN)
	BEQ @UNKNOWN1
	LDX .LOWORD(BATTLE_SWIRL_COUNTDOWN)
	DEX
	STX .LOWORD(BATTLE_SWIRL_COUNTDOWN)
	BEQ @UNKNOWN0
	LDY .LOWORD(GAME_STATE)+game_state::current_party_members
	LDX .LOWORD(GAME_STATE)+game_state::leader_y_coord
	LDA .LOWORD(GAME_STATE)+game_state::leader_x_coord
	JSL NPC_COLLISION_CHECK
	JMP @UNKNOWN9
@UNKNOWN0:
	LDA #$FFFF
	STA .LOWORD(BATTLE_DEBUG)
	JMP @UNKNOWN9
@UNKNOWN1:
	LDA a:.LOWORD(PAD_1_PRESS)
	AND #PAD::R_BUTTON
	BEQ @UNKNOWN2
	LDA #SFX::BICYCLE_BELL
	JSL PLAY_SOUND
@UNKNOWN2:
	LDY $1C
	CPY #$FFFF
	BNE @UNKNOWN4
	LDX $1E
	BEQ @UNKNOWN3
	LDY .LOWORD(GAME_STATE)+game_state::leader_direction
	STY $1C
	BRA @UNKNOWN4
@UNKNOWN3:
	LDY .LOWORD(GAME_STATE)+game_state::current_party_members
	LDX .LOWORD(GAME_STATE)+game_state::leader_y_coord
	LDA .LOWORD(GAME_STATE)+game_state::leader_x_coord
	JSL NPC_COLLISION_CHECK
	JMP @UNKNOWN9
@UNKNOWN4:
	TYA
	AND #$0001
	BEQ @UNKNOWN5
	LDA #$0004
	STA .LOWORD(UNKNOWN_7E5D5A)
	BRA @UNKNOWN7
@UNKNOWN5:
	LDA .LOWORD(UNKNOWN_7E5D5A)
	BEQ @UNKNOWN7
	LDX .LOWORD(UNKNOWN_7E5D5A)
	DEX
	STX .LOWORD(UNKNOWN_7E5D5A)
	BEQ @UNKNOWN6
	LDY .LOWORD(GAME_STATE)+game_state::leader_direction
	STY $1C
	BRA @UNKNOWN7
@UNKNOWN6:
	LDA $02
	CMP #$FFFF
	BNE @UNKNOWN7
	LDY .LOWORD(GAME_STATE)+game_state::leader_direction
	STY $1C
@UNKNOWN7:
	STY .LOWORD(GAME_STATE)+game_state::leader_direction
	LDA #.LOWORD(GAME_STATE) + game_state::unknown80
	STA $1A
	TYA
	ASL
	ASL
	STA $18
	CLC
	ADC #.LOWORD(UNKNOWN_7E4DD6)
	CLC
	ADC #96
	TAY
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $0A
	LDY $1A
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $06
	CLC
	ADD_INT_ASSIGN $06, $0A
	MOVE_INT $06, $10
	LDA #.LOWORD(GAME_STATE) + game_state::unknown84
	STA $04
	LDA $18
	CLC
	ADC #.LOWORD(UNKNOWN_7E4F96)
	CLC
	ADC #96
	TAY
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $0A
	LDY $04
	MOVE_INT_YPTRSRC a:.LOWORD(RAM), $06
	CLC
	ADD_INT_ASSIGN $06, $0A
	MOVE_INT $06, $14
	LDA #$FFFF
	STA .LOWORD(UNKNOWN_7E5DA8)
	LDY $1C
	STY $0E
	LDY #$0018
	LDX $16
	LDA $12
	JSL UNKNOWN_C05CD7
	STA $02
	LDY .LOWORD(GAME_STATE) + game_state::current_party_members
	LDX $16
	LDA $12
	JSL NPC_COLLISION_CHECK
	LDA .LOWORD(UNKNOWN_30X2_TABLE_24) + 46
	CMP #$FFFF
	BNE @UNKNOWN9
	LDX #.LOWORD(GAME_STATE) + game_state::unknown90
	LDA a:.LOWORD(RAM),X
	INC
	STA a:.LOWORD(RAM),X
	INC .LOWORD(UNKNOWN_7E2890)
	LDA $02
	AND #$00C0
	BEQ @UNKNOWN8
	LDA #$0000
	STA a:.LOWORD(RAM),X
	BRA @UNKNOWN9
@UNKNOWN8:
	MOVE_INT $10, $06
	LDY $1A
	MOVE_INT_YPTRDEST $06, a:.LOWORD(RAM)
	MOVE_INT $14, $06
	LDY $04
	MOVE_INT_YPTRDEST $06, a:.LOWORD(RAM)
@UNKNOWN9:
	PLD
	RTS
