
UNKNOWN_C04EF0: ;$C04EF0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAY
	LDA ENTITY_SCRIPT_VAR1_TABLE,Y
	ASL
	TAX
	LDA CHOSEN_FOUR_PTRS,X
	TAX
	STX UNKNOWN_7E4DC6
	LDA RAM+61,X
	OPTIMIZED_MULT $04, .SIZEOF(player_position_buffer_entry)
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	TAX
	STX $0E
	LDA a:player_position_buffer_entry::direction,X
	STA ENTITY_DIRECTIONS,Y
	LDA CURRENT_ENTITY_SLOT
	ASL
	PHA
	LDA a:player_position_buffer_entry::tile_flags,X
	PLX
	STA ENTITY_SURFACE_FLAGS,X
	LDY CURRENT_ENTITY_SLOT
	LDX $0E
	LDA a:player_position_buffer_entry::walking_style,X
	TAX
	STX $0E
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	LDX $0E
	JSL UNKNOWN_C07A56
	PLD
	RTL
