
UNKNOWN_C04EF0: ;$C04EF0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA .LOWORD(CURRENT_ENTITY_SLOT)
	ASL
	TAY
	LDA .LOWORD(ENTITY_SCRIPT_VAR1_TABLE),Y
	ASL
	TAX
	LDA .LOWORD(CHOSEN_FOUR_PTRS),X
	TAX
	STX .LOWORD(UNKNOWN_7E4DC6)
	LDA a:.LOWORD(RAM)+61,X
	STA $04
	ASL
	ADC $04
	ASL
	ASL
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	TAX
	STX $0E
	LDA a:.LOWORD(RAM)+8,X
	STA .LOWORD(ENTITY_DIRECTIONS),Y
	LDA .LOWORD(CURRENT_ENTITY_SLOT)
	ASL
	PHA
	LDA a:.LOWORD(RAM)+4,X
	PLX
	STA .LOWORD(ENTITY_SURFACE_FLAGS),X
	LDY .LOWORD(CURRENT_ENTITY_SLOT)
	LDX $0E
	LDA a:.LOWORD(RAM)+6,X
	TAX
	STX $0E
	LDA .LOWORD(CURRENT_ENTITY_SLOT)
	ASL
	TAX
	LDA .LOWORD(ENTITY_SCRIPT_VAR0_TABLE),X
	LDX $0E
	JSL UNKNOWN_C07A56
	PLD
	RTL
