
UNKNOWN_C04EF0:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAY
	LDA ENTITY_SCRIPT_VAR1_TABLE,Y
	ASL
	TAX
	LDA CHOSEN_FOUR_PTRS,X
	TAX
	STX CURRENT_PARTY_MEMBER_TICK
	LDA __BSS_START__ + char_struct::position_index,X
	OPTIMIZED_MULT $04, .SIZEOF(player_position_buffer_entry)
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	TAX
	STX @LOCAL00
	LDA a:player_position_buffer_entry::direction,X
	STA ENTITY_DIRECTIONS,Y
	LDA CURRENT_ENTITY_SLOT
	ASL
	PHA
	LDA a:player_position_buffer_entry::tile_flags,X
	PLX
	STA ENTITY_SURFACE_FLAGS,X
	LDY CURRENT_ENTITY_SLOT
	LDX @LOCAL00
	LDA a:player_position_buffer_entry::walking_style,X
	TAX
	STX @LOCAL00
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	LDX @LOCAL00
	JSL UNKNOWN_C07A56
	END_C_FUNCTION
