
UNKNOWN_C04F47:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA BACKGROUND_COLOUR_BACKUP
	STA PALETTES
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0017
	STA TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA #$0008
	JSL UNKNOWN_C0856B
	RTL
