
UNKNOWN_C04F60:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN0
	LDA BATTLE_SWIRL_FLAG
	BNE @UNKNOWN0
	LDA CUR_TEXT_PAL
	STA UNKNOWN_7E5D72
	LDA #RGBVAL 31, 0, 0
	STA CUR_TEXT_PAL
	SEP #PROC_FLAGS::ACCUM8
	STZ TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA #8
	JSL UNKNOWN_C0856B
	LOADPTR UNKNOWN_C04F47, $0E
	LDA #1
	JSL SCHEDULE_OVERWORLD_TASK
@UNKNOWN0:
	END_C_FUNCTION
