
UNKNOWN_C04FFE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA GAME_STATE + game_state::unknownB0
	CMP #2
	BNE @UNKNOWN0
	LDA #1
	JMP @UNKNOWN28
@UNKNOWN0:
	LDA OVERWORLD_STATUS_SUPPRESSION
	BEQ @UNKNOWN1
	LDA #1
	JMP @UNKNOWN28
@UNKNOWN1:
	STZ @LOCAL04
	STZ @LOCAL03
	LDA #0
	STA @VIRTUAL04
	STA @VIRTUAL02
	STA @LOCAL02
	JMP @UNKNOWN23
@UNKNOWN2:
	LDA __BSS_START__+game_state::player_controlled_party_members,X
	AND #$00FF
	ASL
	TAX
	LDA CHOSEN_FOUR_PTRS,X
	STA CURRENT_PARTY_MEMBER_TICK
	TAX
	LDA __BSS_START__+char_struct::afflictions,X
	AND #$00FF
	TAY
	STY @LOCAL01
	CPY #1
	BEQL @UNKNOWN22
	CPY #2
	BEQL @UNKNOWN22
	CPY #5
	BNE @UNKNOWN7
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(OVERWORLD_DAMAGE_COUNTDOWN_FRAMES)
	TAX
	LDA __BSS_START__,X
	BEQ @UNKNOWN6
	DEC
	STA __BSS_START__,X
	BNEL @UNKNOWN14
	INC @VIRTUAL04
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #char_struct::current_hp
	TAX
	LDA __BSS_START__,X
	SEC
	SBC #10
	STA __BSS_START__,X
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #char_struct::current_hp_target
	TAX
	LDA __BSS_START__,X
	SEC
	SBC #10
	STA __BSS_START__,X
	LDA @VIRTUAL02
	JSR UNKNOWN_C04F9F
	JMP @UNKNOWN14
@UNKNOWN6:
	LDA #120
	STA __BSS_START__,X
	JMP @UNKNOWN14
@UNKNOWN7:
	CPY #4
	BCC @UNKNOWN8
	CPY #7
	BLTEQ @UNKNOWN9
@UNKNOWN8:
	LDA GAME_STATE+game_state::trodden_tile_type
	AND #$000C
	CMP #12
	BNEL @UNKNOWN14
@UNKNOWN9:
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(OVERWORLD_DAMAGE_COUNTDOWN_FRAMES)
	TAX
	LDA __BSS_START__,X
	BEQ @UNKNOWN12
	DEC
	STA __BSS_START__,X
	BNE @UNKNOWN14
	INC @VIRTUAL04
	CPY #4
	BNE @UNKNOWN10
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #char_struct::current_hp
	TAX
	LDA __BSS_START__,X
	SEC
	SBC #10
	STA __BSS_START__,X
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #char_struct::current_hp_target
	TAX
	LDA __BSS_START__,X
	SEC
	SBC #10
	STA __BSS_START__,X
	BRA @UNKNOWN11
@UNKNOWN10:
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #char_struct::current_hp
	TAX
	LDA __BSS_START__,X
	DEC
	DEC
	STA __BSS_START__,X
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #char_struct::current_hp_target
	TAX
	LDA __BSS_START__,X
	DEC
	DEC
	STA __BSS_START__,X
@UNKNOWN11:
	LDA @VIRTUAL02
	JSR UNKNOWN_C04F9F
	BRA @UNKNOWN14
@UNKNOWN12:
	CPY #4
	BNE @UNKNOWN13
	LDA #120
	STA __BSS_START__,X
	BRA @UNKNOWN14
@UNKNOWN13:
	LDA #240
	STA __BSS_START__,X
@UNKNOWN14:
	LDX CURRENT_PARTY_MEMBER_TICK
	LDA __BSS_START__+char_struct::current_hp,X
	CMP #$8000
	BGT @UNKNOWN16
	CMP #0
	BNE @UNKNOWN21
@UNKNOWN16:
	LDY @LOCAL01
	CPY #1
	BEQ @UNKNOWN22
	LDA #0
	STA @LOCAL00
	BRA @UNKNOWN18
@UNKNOWN17:
	LDA @LOCAL00
	CLC
	ADC CURRENT_PARTY_MEMBER_TICK
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ __BSS_START__+char_struct::afflictions,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	INC
	STA @LOCAL00
@UNKNOWN18:
	STA @VIRTUAL02
	LDA #6
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @UNKNOWN17
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	LDX CURRENT_PARTY_MEMBER_TICK
	STA a:char_struct::afflictions,X
	LDX CURRENT_PARTY_MEMBER_TICK
	REP #PROC_FLAGS::ACCUM8
	STZ a:char_struct::current_hp_target,X
	LDX CURRENT_PARTY_MEMBER_TICK
	STZ a:char_struct::current_hp,X
	LDX CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::unknown59,X
	ASL
	TAX
	LDA #16
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	INC @LOCAL04
	BRA @UNKNOWN22
@UNKNOWN21:
	LDY @LOCAL01
	CPY #2
	BEQ @UNKNOWN22
	CLC
	ADC @LOCAL03
	STA @LOCAL03
@UNKNOWN22:
	LDA @LOCAL02
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL02
@UNKNOWN23:
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA __BSS_START__+game_state::unknown96,X
	AND #$00FF
	BEQ @UNKNOWN25
	AND #$00FF
	CLC
	SBC #4
	JUMPLTEQS @UNKNOWN2
@UNKNOWN25:
	LDA @VIRTUAL04
	BEQ @UNKNOWN26
	JSR UNKNOWN_C04F60
@UNKNOWN26:
	LDA @LOCAL04
	BEQ @UNKNOWN27
	STZ PARTY_MEMBERS_ALIVE_OVERWORLD
	JSL UPDATE_PARTY
	JSL UNKNOWN_C07B52
	JSL UNKNOWN_C09451
@UNKNOWN27:
	LDA @LOCAL03
@UNKNOWN28:
	END_C_FUNCTION
