
UNKNOWN_C05200: ;$C05200
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA BATTLE_DEBUG
	BNEL @UNKNOWN9
	LDA UNKNOWN_7E9F6F
	BEQ @UNKNOWN1
	LDA UNKNOWN_7E9F6B
	CMP #$FFFF
	BNE @UNKNOWN2
	JSL UNKNOWN_C07716
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA UNKNOWN_7E9F6B
	CMP #$FFFF
	BEQ @UNKNOWN2
	JSL UNKNOWN_C0777A
@UNKNOWN2:
	LDA LOADED_ANIMATED_TILE_COUNT
	BEQ @UNKNOWN3
	JSL ANIMATE_TILESET
@UNKNOWN3:
	LDA UNKNOWN_7E4474
	BEQ @UNKNOWN4
	JSL ANIMATE_PALETTE
@UNKNOWN4:
	LDA UNKNOWN_7E9F2A
	BEQ @UNKNOWN5
	JSL PROCESS_ITEM_TRANSFORMATIONS
@UNKNOWN5:
	JSL UNKNOWN_C04C45
	LDA GAME_STATE+game_state::leader_x_coord
	XBA
	AND #$00FF
	STA $0E
	LDA GAME_STATE+game_state::leader_y_coord
	XBA
	AND #$00FF
	TAX
	LDA $0E
	EOR UNKNOWN_7E5D5C
	BNE @UNKNOWN6
	TXA
	EOR UNKNOWN_7E5D5E
	BEQ @UNKNOWN7
@UNKNOWN6:
	LDA $0E
	STA UNKNOWN_7E5D5C
	STX UNKNOWN_7E5D5E
	LDA SECTOR_BOUNDARY_BEHAVIOUR_FLAG
	BEQ @UNKNOWN7
	JSR UNKNOWN_C03C25
@UNKNOWN7:
	LDA DAD_PHONE_TIMER
	BNE @UNKNOWN8
	LDA GAME_STATE + game_state::unknownB0
	CMP #$0002
	BEQ @UNKNOWN8
	JSL LOAD_DAD_PHONE
@UNKNOWN8:
	STZ UNKNOWN_7E9F6F
	LDA GAME_STATE+game_state::leader_direction
	STA UNKNOWN_7E5D76
	LDA GAME_STATE+game_state::current_party_members
	ASL
	STA UNKNOWN_7E5D78
	LDA GAME_STATE + game_state::unknown90
	BEQ @UNKNOWN9
	LDA #$0001
	STA UNKNOWN_7E0A34
@UNKNOWN9:
	PLD
	RTL
