
UNKNOWN_C05F33:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int x
	STACK_RESERVE_PARAM_INT16 ;int y
	STACK_RESERVE_PARAM_INT16 ;int entityID
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STX @LOCAL02
	STA @LOCAL01
	TYA
	ASL
	TAX
	LDY ENTITY_SIZES,X
	STY @LOCAL00
	STZ UNKNOWN_7E5DA4
	TYA
	ASL
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA @LOCAL01
	SEC
	SBC f:UNKNOWN_C42A1F,X
	STA UNKNOWN_7E5DAC
	LDX @LOCAL02
	TXA
	LDX @VIRTUAL02
	SEC
	SBC f:UNKNOWN_C42A41,X
	LDX @VIRTUAL02
	CLC
	ADC f:UNKNOWN_C42AEB,X
	STA UNKNOWN_7E5DAE
	TYX
	JSR UNKNOWN_C05639
	LDY @LOCAL00
	TYX
	LDA UNKNOWN_7E5DAE
	JSR UNKNOWN_C056D0
	LDA UNKNOWN_7E5DA4
	END_C_FUNCTION
