
UNKNOWN_C06267:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL08
	TXY
	TAX
	STX @LOCAL07
	LDA #ENTITY_COLLISION_NO_OBJECT
	STA @LOCAL06
	LDA @LOCAL08
	ASL
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA ENTITY_HITBOX_ENABLED,X
	BEQL @UNKNOWN26
	LDX @VIRTUAL04
	LDA ENTITY_DIRECTIONS,X
	CMP #DIRECTION::RIGHT
	BEQ @UNKNOWN1
	CMP #DIRECTION::LEFT
	BNE @UNKNOWN2
@UNKNOWN1:
	LDA @LOCAL08
	ASL
	STA @LOCAL05
	TAX
	LDA ENTITY_HITBOX_LEFT_RIGHT_WIDTHS,X
	STA @VIRTUAL02
	LDA @LOCAL05
	TAX
	LDA ENTITY_HITBOX_LEFT_RIGHT_HEIGHTS,X
	STA @LOCAL04
	BRA @UNKNOWN3
@UNKNOWN2:
	LDX @VIRTUAL04
	LDA ENTITY_HITBOX_UP_DOWN_WIDTHS,X
	STA @VIRTUAL02
	LDX @VIRTUAL04
	LDA ENTITY_HITBOX_UP_DOWN_HEIGHTS,X
	STA @LOCAL04
@UNKNOWN3:
	LDX @LOCAL07
	TXA
	SEC
	SBC @VIRTUAL02
	STA @VIRTUAL04
	LDA @VIRTUAL02
	ASL
	STA @LOCAL05
	TYA
	SEC
	SBC @LOCAL04
	STA @VIRTUAL02
	STA @LOCAL03
	LDA PLAYER_INTANGIBILITY_FRAMES
	BNEL @UNKNOWN14
	LDX #24
	JMP @UNKNOWN13
@UNKNOWN5:
	TXA
	ASL
	TAY
	LDA ENTITY_SCRIPT_TABLE,Y
	CMP #.LOWORD(-1)
	BEQL @UNKNOWN12
	LDA ENTITY_COLLIDED_OBJECTS,Y
	CMP #ENTITY_COLLISION_DISABLED
	BEQL @UNKNOWN12
	LDA ENTITY_HITBOX_ENABLED,Y
	BEQL @UNKNOWN12
	LDA ENTITY_DIRECTIONS,Y
	CMP #DIRECTION::RIGHT
	BEQ @UNKNOWN9
	CMP #DIRECTION::LEFT
	BNE @UNKNOWN10
@UNKNOWN9:
	TXA
	ASL
	TAY
	LDA ENTITY_HITBOX_LEFT_RIGHT_WIDTHS,Y
	STA @LOCAL02
	LDA ENTITY_HITBOX_LEFT_RIGHT_HEIGHTS,Y
	STA @LOCAL01
	BRA @UNKNOWN11
@UNKNOWN10:
	LDA ENTITY_HITBOX_UP_DOWN_WIDTHS,Y
	STA @LOCAL02
	LDA ENTITY_HITBOX_UP_DOWN_HEIGHTS,Y
	STA @LOCAL01
@UNKNOWN11:
	TXA
	ASL
	STA @LOCAL00
	LDY #.LOWORD(ENTITY_ABS_Y_TABLE)
	LDA (@LOCAL00),Y
	SEC
	SBC @LOCAL01
	TAY
	SEC
	SBC @LOCAL04
	PHA
	LDA @LOCAL03
	STA @VIRTUAL02
	STA TEMP_REGISTER
	PLA
	STA @VIRTUAL02
	LDA TEMP_REGISTER
	CMP @VIRTUAL02
	BLTEQ @UNKNOWN12
	TYA
	CLC
	ADC @LOCAL01
	PHA
	LDA @LOCAL03
	STA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BCS @UNKNOWN12
	LDA @LOCAL02
	STA @VIRTUAL02
	LDY #.LOWORD(ENTITY_ABS_X_TABLE)
	LDA (@LOCAL00),Y
	SEC
	SBC @VIRTUAL02
	TAY
	LDA @LOCAL02
	ASL
	STA @LOCAL02
	TYA
	SEC
	SBC @LOCAL05
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BLTEQ @UNKNOWN12
	LDA @LOCAL02
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BCS @UNKNOWN12
	STX @LOCAL06
	JMP @UNKNOWN26
@UNKNOWN12:
	INX
@UNKNOWN13:
	CPX #MAX_ENTITIES
	BNEL @UNKNOWN5
@UNKNOWN14:
	LDX #0
	JMP @UNKNOWN25
@UNKNOWN15:
	CPX @LOCAL08
	BEQL @UNKNOWN24
	TXA
	ASL
	TAY
	LDA ENTITY_SCRIPT_TABLE,Y
	CMP #.LOWORD(-1)
	BEQL @UNKNOWN24
	LDA ENTITY_NPC_IDS,Y
	CMP #$1000
	BCC @UNKNOWN18
	JMP @UNKNOWN24
@UNKNOWN18:
	LDA ENTITY_COLLIDED_OBJECTS,Y
	CMP #ENTITY_COLLISION_DISABLED
	BEQL @UNKNOWN24
	LDA ENTITY_HITBOX_ENABLED,Y
	BEQL @UNKNOWN24
	LDA ENTITY_DIRECTIONS,Y
	CMP #DIRECTION::RIGHT
	BEQ @UNKNOWN21
	CMP #DIRECTION::LEFT
	BNE @UNKNOWN22
@UNKNOWN21:
	TXA
	ASL
	TAY
	LDA ENTITY_HITBOX_LEFT_RIGHT_WIDTHS,Y
	STA @LOCAL02
	LDA ENTITY_HITBOX_LEFT_RIGHT_HEIGHTS,Y
	STA @LOCAL01
	BRA @UNKNOWN23
@UNKNOWN22:
	LDA ENTITY_HITBOX_UP_DOWN_WIDTHS,Y
	STA @LOCAL02
	LDA ENTITY_HITBOX_UP_DOWN_HEIGHTS,Y
	STA @LOCAL01
@UNKNOWN23:
	TXA
	ASL
	STA @LOCAL00
	LDY #.LOWORD(ENTITY_ABS_Y_TABLE)
	LDA (@LOCAL00),Y
	SEC
	SBC @LOCAL01
	TAY
	SEC
	SBC @LOCAL04
	PHA
	LDA @LOCAL03
	STA @VIRTUAL02
	STA TEMP_REGISTER
	PLA
	STA @VIRTUAL02
	LDA TEMP_REGISTER
	CMP @VIRTUAL02
	BLTEQ @UNKNOWN24
	TYA
	CLC
	ADC @LOCAL01
	DEC
	PHA
	LDA @LOCAL03
	STA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BCS @UNKNOWN24
	LDA @LOCAL02
	STA @VIRTUAL02
	LDY #.LOWORD(ENTITY_ABS_X_TABLE)
	LDA (@LOCAL00),Y
	SEC
	SBC @VIRTUAL02
	TAY
	LDA @LOCAL02
	ASL
	STA @LOCAL02
	TYA
	SEC
	SBC @LOCAL05
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BLTEQ @UNKNOWN24
	LDA @LOCAL02
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	DEC
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BCS @UNKNOWN24
	STX @LOCAL06
	BRA @UNKNOWN26
@UNKNOWN24:
	INX
@UNKNOWN25:
	CPX #23
	BNEL @UNKNOWN15
@UNKNOWN26:
	LDA @LOCAL08
	ASL
	TAX
	LDA @LOCAL06
	STA ENTITY_COLLIDED_OBJECTS,X
	LDA @LOCAL06
	END_C_FUNCTION
