
UNKNOWN_C06478:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX CURRENT_ENTITY_SLOT
	STX @LOCAL00
	TXA
	ASL
	TAX
	LDA ENTITY_COLLIDED_OBJECTS,X
	CMP #ENTITY_COLLISION_DISABLED
	BEQ @UNKNOWN0
	LDX @LOCAL00
	TXA
	JSL UNKNOWN_C09EFF_ENTRY2
	LDX @LOCAL00
	TXY
	LDX ENTITY_MOVEMENT_PROSPECTIVE_Y
	LDA ENTITY_MOVEMENT_PROSPECTIVE_X
	JSL UNKNOWN_C06267
@UNKNOWN0:
	END_C_FUNCTION
