
UNKNOWN_C064D4: ;$C064D4
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STZ NEXT_QUEUED_INTERACTION
	STZ CURRENT_QUEUED_INTERACTION
	LDA #$FFFF
	STA CURRENT_QUEUED_INTERACTION_TYPE
	RTL
