
UNKNOWN_C065C2:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	ASL
	TAX
	LDA GAME_STATE+game_state::leader_x_coord
	LSR
	LSR
	LSR
	CLC
	ADC f:UNKNOWN_C3E230,X
	TAY
	STY @LOCAL00
	LDA GAME_STATE+game_state::leader_y_coord
	LSR
	LSR
	LSR
	CLC
	ADC f:UNKNOWN_C3E240,X
	STA @VIRTUAL02
	LDA @LOCAL01
	CMP #6
	BNE @UNKNOWN0
	DEY
	STY @LOCAL00
@UNKNOWN0:
	LDX @VIRTUAL02
	TYA
	JSL UNKNOWN_C07477
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	CPX #$00FF
	BNE @UNKNOWN1
	LDX @VIRTUAL02
	LDY @LOCAL00
	TYA
	INC
	JSL UNKNOWN_C07477
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@UNKNOWN1:
	CPX #$00FF
	BEQ @UNKNOWN2
	CPX #6
	BNE @UNKNOWN2
	LOADPTR DOOR_DATA & $FF0000, @VIRTUAL06
	LDA DOOR_FOUND
	AND #$7FFF
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA DOOR_FOUND_TYPE
	STA UNREAD_7E5DDC
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, MAP_OBJECT_TEXT
	LDA #.LOWORD(-2)
	STA INTERACTING_NPC_ID
@UNKNOWN2:
	END_C_FUNCTION
