
UNKNOWN_C06578:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL01
	STA @LOCAL00
	LDA ENTITY_CREATION_QUEUE_LENGTH
	ASL
	ASL
	TAX
	LDA @LOCAL00
	STA ENTITY_CREATION_QUEUE + queued_entity_creation::sprite,X
	LDX @LOCAL01
	PHX
	LDA ENTITY_CREATION_QUEUE_LENGTH
	ASL
	ASL
	TAX
	PLA
	STA ENTITY_CREATION_QUEUE + queued_entity_creation::script,X
	INC ENTITY_CREATION_QUEUE_LENGTH
	END_C_FUNCTION
