
UNKNOWN_C06A91:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	TAY
	LDX #.LOWORD(GAME_STATE) + game_state::walking_style
	LDA __BSS_START__,X
	CMP #$0007
	BEQ @UNKNOWN2
	CMP #$0008
	BEQ @UNKNOWN2
	CPY #$0000
	BNE @UNKNOWN0
	LDA #$0007
	STA __BSS_START__,X
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #$0008
	STA __BSS_START__,X
@UNKNOWN1:
	LDX #.LOWORD(GAME_STATE) + game_state::leader_direction
	LDA __BSS_START__,X
	AND #$FFFE
	STA __BSS_START__,X
	LDA #$FFFF
	STA STAIRS_DIRECTION
@UNKNOWN2:
	RTS
