
UNKNOWN_C06A91: ;$C06A91
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	TAY
	LDX #.LOWORD(GAME_STATE) + game_state::walking_style
	LDA RAM,X
	CMP #$0007
	BEQ @UNKNOWN2
	CMP #$0008
	BEQ @UNKNOWN2
	CPY #$0000
	BNE @UNKNOWN0
	LDA #$0007
	STA RAM,X
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #$0008
	STA RAM,X
@UNKNOWN1:
	LDX #.LOWORD(GAME_STATE) + game_state::leader_direction
	LDA RAM,X
	AND #$FFFE
	STA RAM,X
	LDA #$FFFF
	STA UNKNOWN_7E5DC4
@UNKNOWN2:
	RTS
