
UNKNOWN_C06A1B:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	AND #$7FFF
	STA @LOCAL02
	LOADPTR DOOR_DATA & $FF0000, @VIRTUAL0A
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	STA @VIRTUAL06
	LDA @VIRTUAL0A+2
	STA @VIRTUAL06+2
	LDA [@VIRTUAL06]
	AND #$7FFF
	JSL GET_EVENT_FLAG
	TAX
	LDA #0
	STA @LOCAL01
	LDA [@VIRTUAL06]
	CMP #EVENT_FLAG_UNSET
	BLTEQ @UNKNOWN0
	LDA #1
	STA @LOCAL01
@UNKNOWN0:
	LDA @LOCAL01
	STA @VIRTUAL02
	TXA
	CMP @VIRTUAL02
	BNE @UNKNOWN1
	LDY #2
	LDA [@VIRTUAL0A],Y
	PHA
	INY
	INY
	LDA [@VIRTUAL0A],Y
	STA @VIRTUAL06+2
	PLA
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #0
	JSL UNKNOWN_C064E3
	STZ LADDER_STAIRS_TILE_Y
	STZ LADDER_STAIRS_TILE_X
@UNKNOWN1:
	END_C_FUNCTION
