
UNKNOWN_C06B3D:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #0
	STX @LOCAL02
	TXY
	STY @LOCAL01
	BRA @UNKNOWN2
@UNKNOWN0:
	JSL UNKNOWN_C06537
	CMP #10
	BNE @UNKNOWN1
	JSL UNKNOWN_C0654E
	LDY @LOCAL01
	TYA
	ASL
	ASL
	CLC
	ADC #.LOWORD(DOOR_INTERACTIONS)
	TAY
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDY @LOCAL01
	INY
	STY @LOCAL01
@UNKNOWN1:
	LDA CURRENT_QUEUED_INTERACTION
	INC
	AND #$0003
	STA CURRENT_QUEUED_INTERACTION
	LDX @LOCAL02
	INX
	STX @LOCAL02
@UNKNOWN2:
	STX @VIRTUAL02
	LDA #4
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN5
	LDA CURRENT_QUEUED_INTERACTION
	CMP NEXT_QUEUED_INTERACTION
	BNE @UNKNOWN0
@UNKNOWN5:
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	LDY @LOCAL01
	TYA
	ASL
	ASL
	CLC
	ADC #.LOWORD(DOOR_INTERACTIONS)
	TAY
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDX #0
	STX @LOCAL02
	BRA @UNKNOWN7
@UNKNOWN6:
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #10
	JSL UNKNOWN_C064E3
	LDX @LOCAL02
	INX
	STX @LOCAL02
@UNKNOWN7:
	TXA
	ASL
	ASL
	CLC
	ADC #.LOWORD(DOOR_INTERACTIONS)
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BNE @UNKNOWN6
	END_C_FUNCTION
