
UNKNOWN_C06E6E:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL05
	STX @LOCAL04
	STA @LOCAL03
	LDA DEMO_FRAMES_LEFT
	BNEL @UNKNOWN4
	JSL UNKNOWN_C48C69
	LDX @LOCAL04
	TXA
	ASL
	ASL
	ASL
	TAX
	STX @LOCAL02
	LDY @LOCAL05
	TYA
	ASL
	ASL
	ASL
	STA @LOCAL01
	LDA @LOCAL03
	AND #$8000
	BEQ @UNKNOWN2
	LDY #.LOWORD(GAME_STATE) + game_state::walking_style
	LDA __BSS_START__,Y
	CMP #12
	BNEL @UNKNOWN4
	LDA #0
	STA __BSS_START__,Y
	LDA #3
	STA PLAYER_MOVEMENT_FLAGS
	LDA ESCALATOR_ENTRANCE_DIRECTION
	XBA
	AND #$00FF
	ASL
	STA @VIRTUAL02
	TXA
	LDX @VIRTUAL02
	CLC
	ADC f:UNKNOWN_C06E02+8,X
	STA @VIRTUAL04
	LDA @LOCAL01
	STA @LOCAL00
	LDY @VIRTUAL04
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL UNKNOWN_C48D58
	TAY
	STY @LOCAL05
	LDX #16
	STX @LOCAL04
	LDX @VIRTUAL02
	LDA f:UNKNOWN_C06E02+16,X
	LDX @LOCAL04
	JSL UNKNOWN_C48E6B
	LOADPTR UNKNOWN_C06E4A, @LOCAL00
	LDY @LOCAL05
	TYA
	INC
	JSL SCHEDULE_OVERWORLD_TASK
	JSL UNKNOWN_C48E95
	STZ ESCALATOR_ENTRANCE_DIRECTION
	LDA #1
	STA UNREAD_7E5DBA
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::ESCALATOR
	BEQ @UNKNOWN4
	LDA #1
	STA UNREAD_7E5DBA
	LDA @LOCAL03
	STA ESCALATOR_ENTRANCE_DIRECTION
	XBA
	AND #$00FF
	ASL
	STA @LOCAL03
	TAX
	LDA f:UNKNOWN_C06E02+16,X
	STA GAME_STATE+game_state::leader_direction
	LDA #3
	STA PLAYER_MOVEMENT_FLAGS
	LDA @LOCAL03
	PHA
	LDX @LOCAL02
	TXA
	PLX
	CLC
	ADC f:UNKNOWN_C06E02,X
	STA @VIRTUAL04
	LDA @LOCAL01
	STA @LOCAL00
	LDY @VIRTUAL04
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL UNKNOWN_C48D58
	TAX
	LOADPTR UNKNOWN_C06E2C, @LOCAL00
	TXA
	INC
	JSL SCHEDULE_OVERWORLD_TASK
	JSL UNKNOWN_C48E95
@UNKNOWN3:
	LDA @VIRTUAL04
	STA ESCALATOR_NEW_X
	LDA @LOCAL01
	STA ESCALATOR_NEW_Y
	LDA #.LOWORD(-1)
	STA STAIRS_DIRECTION
@UNKNOWN4:
	END_C_FUNCTION
