
UNKNOWN_C06E6E: ;$C06E6E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	PHA
	TDC
	ADC #$FFE4
	TCD
	PLA
	STY $1A
	STX $18
	STA $16
	LDA a:.LOWORD(UNKNOWN_7E0081)
	BEQ @UNKNOWN0
	JMP a:.LOWORD(@UNKNOWN4)
@UNKNOWN0:
	JSL UNKNOWN_C48C69
	LDX $18
	TXA
	ASL
	ASL
	ASL
	TAX
	STX $14
	LDY $1A
	TYA
	ASL
	ASL
	ASL
	STA $12
	LDA $16
	AND #$8000
	BEQ @UNKNOWN2
	LDY #.LOWORD(GAME_STATE) + game_state::walking_style
	LDA a:.LOWORD(RAM),Y
	CMP #$000C
	BEQ @UNKNOWN1
	JMP a:.LOWORD(@UNKNOWN4)
@UNKNOWN1:
	LDA #$0000
	STA a:.LOWORD(RAM),Y
	LDA #$0003
	STA .LOWORD(MISC_DEBUG_FLAGS)
	LDA .LOWORD(UNKNOWN_7E5DC6)
	XBA
	AND #$00FF
	ASL
	STA $02
	TXA
	LDX $02
	CLC
	ADC f:UNKNOWN_C06E02+8,X
	STA $04
	LDA $12
	STA $0E
	LDY $04
	LDX .LOWORD(GAME_STATE)+game_state::leader_y_coord
	LDA .LOWORD(GAME_STATE)+game_state::leader_x_coord
	JSL UNKNOWN_C48D58
	TAY
	STY $1A
	LDX #$0010
	STX $18
	LDX $02
	LDA f:UNKNOWN_C06E02+16,X
	LDX $18
	JSL UNKNOWN_C48E6B
	LOADPTR UNKNOWN_C06E4A, $0E
	LDY $1A
	TYA
	INC
	JSL UNKNOWN_C0DBE6
	JSL UNKNOWN_C48E95
	STZ .LOWORD(UNKNOWN_7E5DC6)
	LDA #$0001
	STA .LOWORD(UNKNOWN_7E5DBA)
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA .LOWORD(GAME_STATE)+game_state::walking_style
	CMP #WALKING_STYLE::ESCALATOR
	BEQ @UNKNOWN4
	LDA #$0001
	STA .LOWORD(UNKNOWN_7E5DBA)
	LDA $16
	STA .LOWORD(UNKNOWN_7E5DC6)
	XBA
	AND #$00FF
	ASL
	STA $16
	TAX
	LDA f:UNKNOWN_C06E02+16,X
	STA .LOWORD(GAME_STATE)+game_state::leader_direction
	LDA #$0003
	STA .LOWORD(MISC_DEBUG_FLAGS)
	LDA $16
	PHA
	LDX $14
	TXA
	PLX
	CLC
	ADC f:UNKNOWN_C06E02,X
	STA $04
	LDA $12
	STA $0E
	LDY $04
	LDX .LOWORD(GAME_STATE)+game_state::leader_y_coord
	LDA .LOWORD(GAME_STATE)+game_state::leader_x_coord
	JSL UNKNOWN_C48D58
	TAX
	LOADPTR UNKNOWN_C06E2C, $0E
	TXA
	INC
	JSL UNKNOWN_C0DBE6
	JSL UNKNOWN_C48E95
@UNKNOWN3:
	LDA $04
	STA.LOWORD(UNKNOWN_7E5DD0)
	LDA $12
	STA .LOWORD(UNKNOWN_7E5DD2)
	LDA #$FFFF
	STA .LOWORD(UNKNOWN_7E5DC4)
@UNKNOWN4:
	PLD
	RTS
