
UNKNOWN_C06E1A:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA #$FFFF
	STA UNKNOWN_7E5DC4
	STZ GAME_STATE+game_state::walking_style
	STZ MISC_DEBUG_FLAGS
	STZ UNKNOWN_7E5DBA
	RTL
