
UNKNOWN_C06FED: ;$C06FED
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 20
	LDA #$0000
	STA $12
	LDA .LOWORD(UNKNOWN_7E5DC4)
	BEQ @UNKNOWN0
	LDA .LOWORD(UNKNOWN_7E5DC4)
	CMP #$0100
	BNE @UNKNOWN1
@UNKNOWN0:
	LDA .LOWORD(GAME_STATE)+game_state::leader_y_coord
	CMP .LOWORD(UNKNOWN_7E5DCE)
	BCS @UNKNOWN2
	LDA #$0001
	STA $12
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA .LOWORD(GAME_STATE)+game_state::leader_y_coord
	CMP .LOWORD(UNKNOWN_7E5DCE)
	BCC @UNKNOWN2
	BEQ @UNKNOWN2
	LDA #$0001
	STA $12
@UNKNOWN2:
	LDA $12
	BEQ @UNKNOWN3
	LDA #$FFFF
	STA .LOWORD(UNKNOWN_7E5DC4)
	STZ .LOWORD(GAME_STATE)+game_state::walking_style
	STZ .LOWORD(MISC_DEBUG_FLAGS)
	LDA .LOWORD(UNKNOWN_7E5DCC)
	STA .LOWORD(GAME_STATE)+game_state::leader_x_coord
	LDA .LOWORD(UNKNOWN_7E5DCE)
	STA .LOWORD(GAME_STATE)+game_state::leader_y_coord
	STZ .LOWORD(GAME_STATE)+132
	STZ .LOWORD(GAME_STATE)+128
	STZ .LOWORD(UNKNOWN_7E5DBA)
	BRA @UNKNOWN4
@UNKNOWN3:
	LOADPTR UNKNOWN_C06FED, $0E
	LDA #$0001
	JSL UNKNOWN_C0DBE6
@UNKNOWN4:
	PLD
	RTL
