
UNKNOWN_C070CB:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
.IF .DEFINED(USA)
	STACK_RESERVE_INT16
.ELSE
	@LOCAL01 := @LOCAL04
.ENDIF
	STACK_RESERVE_INT16 "LOCAL02"
	STACK_RESERVE_INT16 "LOCAL03"
	STACK_RESERVE_INT16 "LOCAL04"
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @VIRTUAL02
	TXY
	STY @LOCAL04
	STA @LOCAL03
	LDA DEMO_FRAMES_LEFT
	BNEL @UNKNOWN7
	JSL UNKNOWN_C48C69
	LDA @LOCAL03
	TAX
	XBA
	AND #$00FF
	STA @VIRTUAL04
	LDY @LOCAL04
	TYA
	ASL
	ASL
	ASL
	TAY
	STY @LOCAL04
	LDA @VIRTUAL02
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	LDA GAME_STATE+game_state::walking_style
	BNEL @UNKNOWN4
	TXA
	JSR UNKNOWN_C0705F
	CMP #0
	BNEL @UNKNOWN7
	LDA AUTO_MOVEMENT_DIRECTION
	STA GAME_STATE+game_state::leader_direction
	STZ NOT_MOVING_IN_SAME_DIRECTION_FACED
	LDA #3
	STA PLAYER_MOVEMENT_FLAGS
	LDA #1
	STA UNREAD_7E5DBA
	LDA @VIRTUAL04
	XBA
	AND #$FF00
	STA STAIRS_DIRECTION
	LDA @VIRTUAL04
	ASL
	TAX
	LDY @LOCAL04
	TYA
	CLC
	ADC f:UNKNOWN_C3E210,X
	STA @LOCAL03
	LDA @VIRTUAL02
	CLC
	ADC f:UNKNOWN_C3E218,X
	STA @VIRTUAL02
	STA @LOCAL00
	LDY @LOCAL03
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL UNKNOWN_C48D58
	TAY
	STY @LOCAL02
	BNE @UNKNOWN3
	INY
	STY @LOCAL02
@UNKNOWN3:
	LDX #6
	STX @LOCAL01
	LDA @VIRTUAL04
	ASL
	TAX
	LDA f:UNKNOWN_C3E200,X
	LDX @LOCAL01
	JSL UNKNOWN_C48E6B
	LOADPTR UNKNOWN_C06F82, @LOCAL00
	LDY @LOCAL02
	TYA
	JSL SCHEDULE_OVERWORLD_TASK
	BRA @UNKNOWN6
@UNKNOWN4:
	LDA @VIRTUAL04
	ASL
	TAX
	TYA
	CLC
	ADC f:UNKNOWN_C3E220,X
	STA @LOCAL03
	LDA @VIRTUAL02
	CLC
	ADC f:UNKNOWN_C3E228,X
	STA @VIRTUAL02
	STA @LOCAL00
	LDY @LOCAL03
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL UNKNOWN_C48D58
	TAY
	STY @LOCAL02
	BNE @UNKNOWN5
	INY
	STY @LOCAL02
@UNKNOWN5:
	LDX #12
	STX @LOCAL04
	LDA @VIRTUAL04
	ASL
	TAX
	LDA f:UNKNOWN_C3E208,X
	LDX @LOCAL04
	JSL UNKNOWN_C48E6B
	LOADPTR UNKNOWN_C06FED, @LOCAL00
	LDY @LOCAL02
	TYA
	JSL SCHEDULE_OVERWORLD_TASK
@UNKNOWN6:
	LDA @LOCAL03
	STA STAIRS_NEW_X
	LDA @VIRTUAL02
	STA STAIRS_NEW_Y
	JSL UNKNOWN_C48E95
@UNKNOWN7:
	END_C_FUNCTION
