
UNKNOWN_C0769C: ;$C0769C
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	SEP #PROC_FLAGS::ACCUM8
	STZ .LOWORD(GAME_STATE) + game_state::unknown4B
	REP #PROC_FLAGS::ACCUM8
	LDA #$0018
	STA $0E
	BRA @UNKNOWN1
@UNKNOWN0:
	ASL
	TAX
	LDA #$0008
	STA .LOWORD(UNKNOWN_30X2_TABLE_6),X
	LDA $0E
	INC
	STA $0E
@UNKNOWN1:
	CMP #$001D
	BCC @UNKNOWN0
	BEQ @UNKNOWN0
	PLD
	RTL
