
UNKNOWN_C07716: ;$C07716
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA .LOWORD(GAME_STATE)+game_state::current_party_members
	ASL
	TAX
	LDA .LOWORD(ENTITY_TICK_CALLBACK_HIGH),X
	AND #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	BNE @RETURN
	LDA .LOWORD(UNKNOWN_30X2_TABLE_16),X
	AND #$8000
	BNE @RETURN
	LDA .LOWORD(GAME_STATE) + game_state::unknownB0
	CMP #$0002
	BEQ @RETURN
	STZ $0E
	STZ $10
	LDY #$FFFF
	LDX #EVENT_SCRIPT::EVENT_786
	LDA #OVERWORLD_SPRITE::MINI_GHOST
	JSL PARSE_C3FC49_DATA
	STA .LOWORD(UNKNOWN_7E9F6B)
	ASL
	TAX
	LDA #$FFFF
	STA .LOWORD(UNKNOWN_30X2_TABLE_14),X
	LDA .LOWORD(UNKNOWN_7E9F6B)
	ASL
	TAX
	LDA #$FF00
	STA .LOWORD(ENTITY_SCREEN_Y_TABLE),X
	LDA .LOWORD(UNKNOWN_7E9F6B)
	ASL
	TAX
	LDA #$FF00
	STA .LOWORD(ENTITY_ABS_Y_TABLE),X
	LDA .LOWORD(UNKNOWN_7E9F6B)
	ASL
	TAX
	LDA #$FF00
	STA .LOWORD(ENTITY_ABS_X_TABLE),X
@RETURN:
	PLD
	RTL
