
UNKNOWN_C0778A: ;$C0778A
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA GAME_STATE+game_state::current_party_members
	ASL
	TAX
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	AND #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	BEQ @UNKNOWN0
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA #$FFFF
	STA ENTITY_ANIMATION_FRAME,X
	BRA @UNKNOWN2
@UNKNOWN0:
	LDX #$3000
	LDA UNKNOWN_7E9F6D
	JSL UNKNOWN_C41FFF
	MOVE_INT $06, $0E
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA $10
	AND #$FF00
	XBA
	BPL @UNKNOWN1
	ORA #$FF00
@UNKNOWN1:
	CLC
	ADC GAME_STATE+game_state::leader_x_coord
	STA ENTITY_ABS_X_TABLE,X
	LDA CURRENT_ENTITY_SLOT
	ASL
	PHA
	SEP #PROC_FLAGS::ACCUM8
	LDA #$000A
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	JSL ASR16
	STA $02
	LDA GAME_STATE+game_state::leader_y_coord
	SEC
	SBC #$0008
	CLC
	ADC $02
	REP #PROC_FLAGS::INDEX8
	PLX
	STA ENTITY_ABS_Y_TABLE,X
	LDA UNKNOWN_7E9F6D
	CLC
	ADC #$0300
	STA UNKNOWN_7E9F6D
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	STZ ENTITY_ANIMATION_FRAME,X
@UNKNOWN2:
	PLD
	RTL
