
UNKNOWN_C07B52: ;$C07B52
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	LDA .LOWORD(CHAR_STRUCT)+char_struct::position_index
	STA $14
	LDA #$0018
	STA $12
	JMP @UNKNOWN6
@UNKNOWN0:
	LDA $12
	ASL
	STA $04
	STA $10
	LDX $04
	LDA .LOWORD(ENTITY_SCRIPT_TABLE),X
	CMP #$FFFF
	BNE @UNKNOWN1
	JMP @UNKNOWN5
@UNKNOWN1:
	LDA $04
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA a:.LOWORD(RAM),X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA a:.LOWORD(RAM),X
	LDX $04
	LDA .LOWORD(ENTITY_SCRIPT_VAR1_TABLE),X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT)
	TAX
	STX .LOWORD(UNKNOWN_7E4DC6)
	LDA .LOWORD(GAME_STATE)+game_state::current_party_members
	CMP $12
	BEQ @UNKNOWN2
	LDA a:char_struct::position_index,X
	CMP $14
	BNE @UNKNOWN3
@UNKNOWN2:
	LDA $12
	ASL
	STA $02
	LDY $12
	LDX .LOWORD(GAME_STATE)+game_state::walking_style
	STX $0E
	LDX $02
	LDA .LOWORD(ENTITY_SCRIPT_VAR0_TABLE),X
	LDX $0E
	JSL UNKNOWN_C07A56
	LDA .LOWORD(GAME_STATE)+game_state::leader_x_coord
	LDX $02
	STA .LOWORD(ENTITY_ABS_X_TABLE),X
	LDA .LOWORD(GAME_STATE)+game_state::leader_y_coord
	LDX $02
	STA .LOWORD(ENTITY_ABS_Y_TABLE),X
	LDA .LOWORD(GAME_STATE)+game_state::party_count
	AND #$00FF
	CMP #$0001
	BEQ @UNKNOWN4
	LDA .LOWORD(GAME_STATE)+game_state::leader_direction
	LDX $02
	STA .LOWORD(ENTITY_DIRECTIONS),X
	BRA @UNKNOWN4
@UNKNOWN3:
	OPTIMIZED_MULT $04, .SIZEOF(player_position_buffer_entry)
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	STA $02
	LDY $12
	LDX $02
	LDA a:player_position_buffer_entry::walking_style,X
	TAX
	STX $0E
	LDA $10
	STA $04
	LDX $04
	LDA .LOWORD(ENTITY_SCRIPT_VAR0_TABLE),X
	LDX $0E
	JSL UNKNOWN_C07A56
	LDX $02
	LDA a:player_position_buffer_entry::x_coord,X
	LDX $04
	STA .LOWORD(ENTITY_ABS_X_TABLE),X
	LDX $02
	LDA a:player_position_buffer_entry::y_coord,X
	LDX $04
	STA .LOWORD(ENTITY_ABS_Y_TABLE),X
	LDX $02
	LDA a:player_position_buffer_entry::direction,X
	LDX $04
	STA .LOWORD(ENTITY_DIRECTIONS),X
@UNKNOWN4:
	LDA $12
	ASL
	TAX
	LDA .LOWORD(ENTITY_ABS_X_TABLE),X
	SEC
	SBC a:.LOWORD(RAM)+49
	STA .LOWORD(ENTITY_SCREEN_X_TABLE),X
	LDA .LOWORD(ENTITY_ABS_Y_TABLE),X
	SEC
	SBC a:.LOWORD(RAM)+51
	STA .LOWORD(ENTITY_SCREEN_Y_TABLE),X
	LDA $12
	JSL UNKNOWN_C0A780
@UNKNOWN5:
	INC $12
@UNKNOWN6:
	LDA $12
	CMP #$001E
	BCS @UNKNOWN7
	BEQ @UNKNOWN7
	JMP @UNKNOWN0
@UNKNOWN7:
	PLD
	RTL
