
UNKNOWN_C083C1:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	MOVE_INT $0E, DEMO_WRITE_DESTINATION
	LDA PAD_STATE
	STA DEMO_LAST_INPUT
	LDA #1
	STA DEMO_SAME_INPUT_FRAMES
	LDA #DEMO_RECORDING_FLAG::RECORDING
	ORA DEMO_RECORDING_FLAGS
	STA DEMO_RECORDING_FLAGS
	RTL
