
UNKNOWN_C08C6D:
	LDX PRIORITY_0_SPRITE_OFFSET
	STA PRIORITY_0_SPRITEMAPS,X
	PLA
	STA PRIORITY_0_SPRITE_X,X
	TYA
	STA PRIORITY_0_SPRITE_Y,X
	LDA SPRITEMAP_BANK
	STA PRIORITY_0_SPRITEMAP_BANKS,X
	INX
	INX
	STX PRIORITY_0_SPRITE_OFFSET
	RTS
