
UNKNOWN_C092F5: ;$C092F5
	PHA
	STZ .LOWORD(UNKNOWN_7E0A48)
	STZ .LOWORD(UNKNOWN_7E0A38)
	STZ .LOWORD(UNKNOWN_7E0A3A)
	STZ .LOWORD(UNKNOWN_7E0A3C)
	STZ .LOWORD(UNKNOWN_7E0A3E)
	STZ .LOWORD(UNKNOWN_7E0A40)
	STZ .LOWORD(UNKNOWN_7E0A42)
	STZ .LOWORD(UNKNOWN_7E0A44)
	STZ .LOWORD(UNKNOWN_7E0A46)
	STZ .LOWORD(UNKNOWN_7E0A4A)
	LDA #$0000
	STA .LOWORD(UNKNOWN_7E0A4C)
	LDA #$001E
	STA .LOWORD(UNKNOWN_7E0A4E)
	PLA
; Initializes movement...?
;A = movement code, X,Y = coordinates
UNKNOWN_C092F5_ENTRY2: ;$C09321
	PHA
	PHY
	PHX
	LDA .LOWORD(UNKNOWN_7E0A4C)
	ASL
	STA .LOWORD(UNKNOWN_7E0A4C)
	LDA .LOWORD(UNKNOWN_7E0A4E)
	ASL
	STA .LOWORD(UNKNOWN_7E0A4E)
	JSR a:.LOWORD(UNKNOWN_C09C02)
	BCC UNKNOWN_C092F5_UNKNOWN0
	PLA
	PLA
	PLA
	LDA #$0000
	RTL
UNKNOWN_C092F5_UNKNOWN0:
	JSR a:.LOWORD(UNKNOWN_C09D03)
	TYA
	STA .LOWORD(UNKNOWN_30X2_TABLE_2),X
	LDA #$FFFF
	STA .LOWORD(UNKNOWN_7E125A),Y
	LDA #$9FC8
	STA .LOWORD(UNKNOWN_30X2_TABLE_19),X
	LDA #$A023
	STA .LOWORD(UNKNOWN_30X2_TABLE_17),X
	LDA #$A3A4
	STA .LOWORD(UNKNOWN_30X2_TABLE_18),X
	LDA .LOWORD(UNKNOWN_7E0A38)
	STA .LOWORD(UNKNOWN_30X2_TABLE_3),X
	LDA .LOWORD(UNKNOWN_7E0A3A)
	STA .LOWORD(UNKNOWN_30X2_TABLE_4),X
	LDA .LOWORD(UNKNOWN_7E0A3C)
	STA .LOWORD(UNKNOWN_30X2_TABLE_5),X
	LDA .LOWORD(UNKNOWN_7E0A3E)
	STA .LOWORD(UNKNOWN_30X2_TABLE_6),X
	LDA .LOWORD(UNKNOWN_7E0A40)
	STA .LOWORD(UNKNOWN_30X2_TABLE_7),X
	LDA .LOWORD(UNKNOWN_7E0A42)
	STA .LOWORD(UNKNOWN_30X2_TABLE_8),X
	LDA .LOWORD(UNKNOWN_7E0A44)
	STA .LOWORD(UNKNOWN_30X2_TABLE_9),X
	LDA .LOWORD(UNKNOWN_7E0A46)
	STA .LOWORD(UNKNOWN_30X2_TABLE_10),X
	LDA .LOWORD(UNKNOWN_7E0A4A)
	STA .LOWORD(UNKNOWN_30X2_TABLE_11),X
	LDA #$8000
	STA .LOWORD(SPRITE_ABS_X_FRACTION_TABLE),X
	STA .LOWORD(SPRITE_ABS_Y_FRACTION_TABLE),X
	STA .LOWORD(SPRITE_ABS_Z_FRACTION_TABLE),X
	PLA
	STA .LOWORD(SPRITE_ABS_X_TABLE),X
	STA .LOWORD(SPRITE_SCREEN_X_TABLE),X
	PLA
	STA .LOWORD(SPRITE_ABS_Y_TABLE),X
	STA .LOWORD(SPRITE_SCREEN_Y_TABLE),X
	LDA .LOWORD(UNKNOWN_7E0A48)
	STA .LOWORD(SPRITE_ABS_Z_TABLE),X
	JSR a:.LOWORD(UNKNOWN_C09C57)
	PLA
	BRA UNKNOWN_C092F5_UNKNOWN1
	PHA
	JSR a:.LOWORD(UNKNOWN_C09C99)
	JSR a:.LOWORD(UNKNOWN_C09D03)
	TYA
	STA .LOWORD(UNKNOWN_30X2_TABLE_2),X
	LDA #$FFFF
	STA .LOWORD(UNKNOWN_7E125A),Y
	PLA
UNKNOWN_C092F5_UNKNOWN1:
	STA .LOWORD(LOADED_SPRITE_MOVEMENT_CODES_TABLE),X
	PHX
	ASL
	ADC .LOWORD(LOADED_SPRITE_MOVEMENT_CODES_TABLE),X
	TXY
	TAX
	LDA f:MOVEMENT_PATTERN_POINTERS+2,X
	TAY
	LDA f:MOVEMENT_PATTERN_POINTERS,X
	PLX
	STZ .LOWORD(UNKNOWN_30X2_TABLE_14),X
	DEC .LOWORD(UNKNOWN_30X2_TABLE_14),X
	STZ .LOWORD(SPRITE_DELTA_X_FRACTION_TABLE),X
	STZ .LOWORD(SPRITE_DELTA_X_TABLE),X
	STZ .LOWORD(SPRITE_DELTA_Y_FRACTION_TABLE),X
	STZ .LOWORD(SPRITE_DELTA_Y_TABLE),X
	STZ .LOWORD(SPRITE_DELTA_Z_FRACTION_TABLE),X
	STZ .LOWORD(SPRITE_DELTA_Z_TABLE),X
	BRA UNKNOWN_C092F5_UNKNOWN4
UNKNOWN_C092F5_ENTRY3:
	PHA
	TXA
	ASL
	TAX
	PLA
	JSL UNKNOWN_C092F5_X
	RTL
UNKNOWN_C092F5_X:
	PHY
	PHA
	LDA .LOWORD(LOADED_SPRITE_MOVEMENT_CODES_TABLE),X
	BPL UNKNOWN_C092F5_UNKNOWN3
UNKNOWN_C092F5_UNKNOWN2:
	BRA UNKNOWN_C092F5_UNKNOWN2
UNKNOWN_C092F5_UNKNOWN3:
	JSR a:.LOWORD(UNKNOWN_C09C99)
	JSR a:.LOWORD(UNKNOWN_C09D03)
	TYA
	STA .LOWORD(UNKNOWN_30X2_TABLE_2),X
	LDA #$FFFF
	STA .LOWORD(UNKNOWN_7E125A),Y
	PLA
	PLY
UNKNOWN_C092F5_UNKNOWN4:
	PHY
	PHA
	JSR a:.LOWORD(CLEAR_SPRITE_TICK_CALLBACK)
	TXY
	LDX .LOWORD(UNKNOWN_30X2_TABLE_2),Y
	PLA
	STA .LOWORD(UNKNOWN_30X2_TABLE_21),X
	PLA
	AND #$00FF
	STA .LOWORD(UNKNOWN_30X2_TABLE_22),X
	STZ .LOWORD(MAP_ENTITY_SLEEP_FRAMES),X
	STZ .LOWORD(UNKNOWN_7E12E6),X
	TYA
	LSR
	CLC
MOVEMENT_NOP: ;$C0943B
	RTL
