
UNKNOWN_C0943C: ;$C0943C
	LDX FIRST_ENTITY
	BMI @UNKNOWN1
@UNKNOWN0:
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA ENTITY_TICK_CALLBACK_HIGH,X
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	TAX
	BPL @UNKNOWN0
@UNKNOWN1:
	RTL
