
UNKNOWN_C094D0: ;$C094D0
	BIT ENTITY_TICK_CALLBACK_HIGH,X
	BVS @UNKNOWN1
	LDY ENTITY_SCRIPT_INDEX_TABLE,X
@UNKNOWN0:
	STY $8A
	STY CURRENT_SCRIPT_OFFSET
	STY CURRENT_SCRIPT_SLOT
	LSR CURRENT_SCRIPT_SLOT
	LDA UNKNOWN_7E125A,Y
	STA UNKNOWN_7E0A58
	JSR UNKNOWN_C09506
	LDY UNKNOWN_7E0A58
	BPL @UNKNOWN0
	LDX $88
@UNKNOWN1:
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	BMI @UNKNOWN2
	STA MOVEMENT_42_LOADED_PTR+2
	LDA ENTITY_TICK_CALLBACK_LOW,X
	STA MOVEMENT_42_LOADED_PTR
	JSL JUMP_TO_LOADED_MOVEMENT_PTR
@UNKNOWN2:
	RTS
