
UNKNOWN_C09403:
	PHY
	PHA
	LDA ENTITY_SCRIPT_TABLE,X
	BPL @DONT_LOOP
@LOOP:
	BRA @LOOP
@DONT_LOOP:
	JSR UNKNOWN_C09C99
	JSR ALLOCATE_SCRIPT
	TYA
	STA ENTITY_SCRIPT_INDEX_TABLE,X
	LDA #$FFFF
	STA ENTITY_SCRIPT_NEXT_SCRIPTS,Y
	PLA
	PLY
UNKNOWN_C09403_ENTRY2:
	PHY
	PHA
	JSR CLEAR_SPRITE_TICK_CALLBACK
	TXY
	LDX ENTITY_SCRIPT_INDEX_TABLE,Y
	PLA
	STA ENTITY_SCRIPT_PROGRAM_COUNTERS,X
	PLA
	AND #$00FF
	STA ENTITY_SCRIPT_PROGRAM_COUNTER_BANKS,X
	STZ ENTITY_SCRIPT_SLEEP_FRAMES,X
	STZ ENTITY_SCRIPT_STACK_OFFSETS,X
	TYA
	LSR
	CLC
MOVEMENT_NOP:
	RTL
