
UNKNOWN_C09506:
	LDX $8A
	LDA ENTITY_SLEEP_FRAMES,X
	BNE @RETURN
	LDY ENTITY_PROGRAM_COUNTER,X
	LDA ENTITY_PROGRAM_COUNTER_BANK,X
	STA $82
	TXA
	ASL
	ASL
	ASL
	ADC #.LOWORD(UNKNOWN_7E15A2)
	STA $84
@UNKNOWN0:
	LDA [$80],Y
	INY
	AND #$00FF
	CMP #$0070
	BCS @UNKNOWN1
	ASL
	TAX
	JSR (.LOWORD(MOVEMENT_CTRL_CODES_PTR_TABLE),X)
	BRA @UNKNOWN2
@UNKNOWN1:
	STA $90
	AND #$000F
	STA ENTITY_SLEEP_FRAMES,X
	LDA $90
	AND #$0070
	LSR
	LSR
	LSR
	TAX
	JSR (.LOWORD(MOVEMENT_CTRL_CODES_PTR_TABLE)+138,X)
@UNKNOWN2:
	LDX $8A
	LDA ENTITY_SLEEP_FRAMES,X
	BEQ @UNKNOWN0
	TYA
	STA ENTITY_PROGRAM_COUNTER,X
	LDA $82
	STA ENTITY_PROGRAM_COUNTER_BANK,X
@RETURN:
	DEC ENTITY_SLEEP_FRAMES,X
	RTS
