
UNKNOWN_C09C73:
	JSR UNKNOWN_C09CB5
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	CPY #$FFFF
	BEQ @UNKNOWN0
	STA ENTITY_NEXT_ENTITY_TABLE,Y
	BRA @UNKNOWN1
@UNKNOWN0:
	STA FIRST_ENTITY
@UNKNOWN1:
	CPX NEXT_ACTIVE_ENTITY
	BNE @UNKNOWN2
	STA NEXT_ACTIVE_ENTITY
@UNKNOWN2:
	RTS
