
UNKNOWN_C09C57: ;$C09C57
	LDA #$FFFF
	STA .LOWORD(ENTITY_NEXT_ENTITY_TABLE),X
	TXA
	LDX .LOWORD(FIRST_ENTITY)
	BPL @UNKNOWN0
	STA .LOWORD(FIRST_ENTITY)
	BRA @UNKNOWN1
@UNKNOWN0:
	TXY
	LDX .LOWORD(ENTITY_NEXT_ENTITY_TABLE),Y
	BPL @UNKNOWN0
	STA .LOWORD(ENTITY_NEXT_ENTITY_TABLE),Y
@UNKNOWN1:
	TAX
	RTS
