
UNKNOWN_C09C3B: ;$C09C3B
	PHA
	LDA .LOWORD(ENTITY_SCRIPT_TABLE),X
	BMI @UNKNOWN0
	PHY
	LDA #$FFFF
	STA .LOWORD(ENTITY_SCRIPT_TABLE),X
	JSR a:.LOWORD(CLEAR_SPRITE_TICK_CALLBACK)
	JSR a:.LOWORD(UNKNOWN_C09C99)
	JSR a:.LOWORD(UNKNOWN_C09C73)
	JSR a:.LOWORD(UNKNOWN_C09C8F)
	PLY
@UNKNOWN0:
	PLA
	RTS
