
UNKNOWN_C09C02: ;$C09C02
	LDA .LOWORD(UNKNOWN_7E0A54)
	BMI @UNKNOWN2
	LDY #$FFFF
	LDA .LOWORD(UNKNOWN_7E0A52)
	BMI @UNKNOWN2
@UNKNOWN0:
	TAX
	CPX .LOWORD(ENTITY_ALLOCATION_MIN_SLOT)
	BCC @UNKNOWN1
	CPX .LOWORD(ENTITY_ALLOCATION_MAX_SLOT)
	BCC @UNKNOWN3
@UNKNOWN1:
	TXY
	LDA .LOWORD(ENTITY_NEXT_ENTITY_TABLE),X
	BPL @UNKNOWN0
@UNKNOWN2:
	SEC
	RTS
@UNKNOWN3:
	TYA
	BPL @UNKNOWN4
	LDA .LOWORD(ENTITY_NEXT_ENTITY_TABLE),X
	STA .LOWORD(UNKNOWN_7E0A52)
	CLC
	RTS
@UNKNOWN4:
	LDA .LOWORD(ENTITY_NEXT_ENTITY_TABLE),X
	STA .LOWORD(ENTITY_NEXT_ENTITY_TABLE),Y
	CLC
	RTS
