
UNKNOWN_C09F3B:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	LDA #$FFFF
	STA CURRENT_ENTITY_OFFSET
UNKNOWN_C09F3B_ENTRY2:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	PHA
	LDX #$0000
@UNKNOWN0:
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	STA ENTITY_CALLBACK_FLAGS_BACKUP,X
	INX
	INX
	CPX #$003C
	BNE @UNKNOWN0
	PLA
	LDX FIRST_ENTITY
	BMI @UNKNOWN3
@UNKNOWN1:
	CPX CURRENT_ENTITY_OFFSET
	BEQ @UNKNOWN2
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA ENTITY_TICK_CALLBACK_HIGH,X
@UNKNOWN2:
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	TAX
	BPL @UNKNOWN1
@UNKNOWN3:
	RTL
