
UNKNOWN_C0A0E3:
	LDA ENTITY_SPRITEMAP_POINTER_HIGH,X
	BMI @RETURN
	BVS @RETURN
	STA $8E
	LDA ENTITY_SPRITEMAP_POINTER_LOW,X
	STA $8C
	LDA ENTITY_ANIMATION_FRAME,X
	BMI @RETURN
	JMP (.LOWORD(ENTITY_DRAW_CALLBACK),X)
@RETURN:
	RTS
