
UNKNOWN_C0A0FA: ;$C0A0FA
	ASL
	TAY
	SEP #PROC_FLAGS::ACCUM8
	LDA $8E
	STA a:.LOWORD(UNKNOWN_7E000B)
	REP #PROC_FLAGS::ACCUM8
	LDA [$8C],Y
	STA $96
	LDA .LOWORD(UNKNOWN_30X2_TABLE_11),X
	STA .LOWORD(UNKNOWN_7E2400)
	LDY .LOWORD(SPRITE_ABS_Y_TABLE),X
	LDA .LOWORD(SPRITE_ABS_X_TABLE),X
	TAX
	LDA $96
	JMP a:.LOWORD(UNKNOWN_C08C58)
	RTS
