
UNKNOWN_C0A00C: ;$C0A00C
	JSR UNKNOWN_C09FAE_ENTRY2
	LDA ENTITY_ABS_Z_FRACTION_TABLE,X
	CLC
	ADC ENTITY_DELTA_Z_FRACTION_TABLE,X
	STA ENTITY_ABS_Z_FRACTION_TABLE,X
	LDA ENTITY_ABS_Z_TABLE,X
	ADC ENTITY_DELTA_Z_TABLE,X
	STA ENTITY_ABS_Z_TABLE,X
	RTS
