
UNKNOWN_C0A0A0: ;$C0A0A0
	LDX $88
	LDA ENTITY_ABS_X_TABLE,X
	SEC
	SBC BG3_X_POS
	STA ENTITY_SCREEN_X_TABLE,X
	LDA ENTITY_ABS_Y_TABLE,X
	SEC
	SBC BG3_Y_POS
	SEC
	SBC ENTITY_ABS_Z_TABLE,X
	STA ENTITY_SCREEN_Y_TABLE,X
	RTS
