
UNKNOWN_C0A26B:
	.A8
	LDX $88
	CPX CURRENT_LEADING_PARTY_MEMBER_ENTITY
	BEQ @UNKNOWN0
	LDA ENTITY_SCRIPT_VAR7_TABLE,X
	AND #$0000
	CLC
	BNE @UNKNOWN0
	LDA NOT_MOVING_IN_SAME_DIRECTION_FACED
	BNE @UNKNOWN0
	LDA ENTITY_DIRECTIONS,X
	CMP CURRENT_LEADER_DIRECTION
	BNE @UNKNOWN0
	ASL
	TAX
	LDY CURRENT_LEADING_PARTY_MEMBER_ENTITY
	JSR (.LOWORD(UNKNOWN_C0A350),X)
	ASL
	BEQ @UNKNOWN1
@UNKNOWN0:
	LDX $88
	LDA ENTITY_ABS_X_TABLE,X
	SEC
	SBC BG1_X_POS
	STA ENTITY_SCREEN_X_TABLE,X
	LDA ENTITY_ABS_Y_TABLE,X
	SEC
	SBC BG1_Y_POS
	STA ENTITY_SCREEN_Y_TABLE,X
@UNKNOWN1:
	LDX $88
	RTS
