
UNKNOWN_C0A254: ;$C0A254
	ASL
	TAX
	LDA .LOWORD(ENTITY_ABS_X_TABLE),X
	SEC
	SBC a:.LOWORD(BG1_X_POS)
	STA .LOWORD(ENTITY_SCREEN_X_TABLE),X
	LDA .LOWORD(ENTITY_ABS_Y_TABLE),X
	SEC
	SBC a:.LOWORD(BG1_Y_POS)
	STA .LOWORD(ENTITY_SCREEN_Y_TABLE),X
	RTL
