
UNKNOWN_C0A794:
	LDY SPRITE_UPDATE_ENTITY_OFFSET
	LDA ENTITY_TILE_HEIGHTS,Y
	STA $00
	LDA ENTITY_BYTE_WIDTHS,Y
	STA DMA_COPY_SIZE
	LDA ENTITY_VRAM_ADDRESS,Y
	STA DMA_COPY_VRAM_DEST
	LDA ENTITY_GRAPHICS_PTR_HIGH,Y
	STA $04
	LDA ENTITY_DIRECTIONS,Y
	ASL
	TAX
	LDA f:SPRITE_DIRECTION_MAPPING_8_DIRECTION,X
	ASL
	ASL
	CLC
	ADC ENTITY_GRAPHICS_PTR_LOW,Y
	ADC ENTITY_ANIMATION_FRAME,Y
	STA $02
	LDA [$02]
	AND #$0002
	BNE @UNKNOWN0
	LDA ENTITY_SURFACE_FLAGS,Y
	STA $06
	AND #$0008
	BEQ @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0003
	STA DMA_COPY_MODE
	LDA #.BANKBYTE(UNKNOWN_C40BE8)
	STA DMA_COPY_RAM_SRC + 2
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(UNKNOWN_C40BE8)
	STA DMA_COPY_RAM_SRC
	JSL UNKNOWN_C0A56E
	DEC $00
	BEQ @UNKNOWN2
	LDA $06
	AND #$0004
	BEQ @UNKNOWN0
	JSL UNKNOWN_C0A56E
	DEC $00
	BEQ @UNKNOWN2
@UNKNOWN0:
	LDY SPRITE_UPDATE_ENTITY_OFFSET
	LDA [$02]
	STA ENTITY_CURRENT_DISPLAYED_SPRITES,Y
	AND #$FFFE
	STA DMA_COPY_RAM_SRC
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA DMA_COPY_MODE
	LDA ENTITY_GRAPHICS_SPRITE_BANK,Y
	STA DMA_COPY_RAM_SRC + 2
	REP #PROC_FLAGS::ACCUM8
@UNKNOWN1:
	JSL UNKNOWN_C0A56E
	DEC $00
	BEQ @UNKNOWN2
	LDA DMA_COPY_RAM_SRC
	CLC
	ADC DMA_COPY_SIZE
	STA DMA_COPY_RAM_SRC
	BRA @UNKNOWN1
@UNKNOWN2:
	RTS
