
UNKNOWN_C0B67F:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
.IF .DEFINED(JPN)
	STACK_RESERVE_INT32
.ELSE
	STACK_RESERVE_INT8
.ENDIF
	END_STACK_VARS
	JSL UNKNOWN_C0927C
	JSL UNKNOWN_C01A86
	LDX #0
	LDA #$8000
	JSL ALLOC_SPRITE_MEM
	JSL INITIALIZE_MISC_OBJECT_DATA
	STZ BATTLE_MODE
	STZ INPUT_DISABLE_FRAME_COUNTER
	LDA #1
	STA NPC_SPAWNS_ENABLED
	LDA #.LOWORD(-1)
	STA ENEMY_SPAWNS_ENABLED
	LDA #10
	STA OVERWORLD_ENEMY_MAXIMUM
	STZ BATTLE_SWIRL_COUNTDOWN
	STZ PENDING_INTERACTIONS
	LDA #1
	JSL SET_BOUNDARY_BEHAVIOR
	LDA #1687
	STA DAD_PHONE_TIMER
	LDA #.LOWORD(PROCESS_OVERWORLD_TASKS)
	JSL SET_IRQ_CALLBACK
	STZ PSI_TELEPORT_STYLE
	STZ PSI_TELEPORT_DESTINATION
	LDA #.LOWORD(-1)
	STA ENTITY_FADE_ENTITY
	LDA #23
	STA ENTITY_ALLOCATION_MIN_SLOT
	LDA #24
	STA ENTITY_ALLOCATION_MAX_SLOT
	LDY #0
	TYX
	LDA #EVENT_SCRIPT::EVENT_001
	JSL INIT_ENTITY
	JSL UNKNOWN_C02D29
	JSL UNKNOWN_C03A24
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #BPP4PALETTE_SIZE * 16
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PALETTES)
	JSL MEMSET16
	JSL UNKNOWN_C47F87
	JSL OVERWORLD_INITIALIZE
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_MAP_AT_POSITION
	JSL SPAWN_BUZZ_BUZZ
	JSL LOAD_WINDOW_GFX
.IF .DEFINED(JPN)
	COPY_TO_VRAM1 BUFFER, VRAM::TEXT_LAYER_TILES, $3800, 0
.ELSE
	LDA #1
	JSL UNKNOWN_C44963
.ENDIF
	JSL UNKNOWN_C039E5
	END_C_FUNCTION
