
UNKNOWN_C0BA35:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL13
	STX @LOCAL12
	STA @VIRTUAL04
	STA @LOCAL11
	LDA @PARAM06
	STA @LOCAL10
	LDA @PARAM05
	STA @LOCAL0F
	LDX @PARAM04
	STX @LOCAL0E
	LDY @PARAM03
	STY @LOCAL0D
	LOADPTR BUFFER + $3000, @VIRTUAL06
	LDA @LOCAL12
	LDX @VIRTUAL04
	STA a:pathfinding::target_count,X
	LDX #0
	STX @LOCAL0C
	BRA @UNKNOWN5
@UNKNOWN0:
	LDA #0
	STA @LOCAL0B
	BRA @UNKNOWN4
@UNKNOWN1:
	CLC
	ADC @LOCAL13
	AND #$003F
	PHA
	LDX @LOCAL0C
	STX @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	AND #$003F
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	PLX
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA LOADED_COLLISION_TILES,X
	AND #$00FF
	AND #$00C0
	BEQ @UNKNOWN2
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-3
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	BRA @UNKNOWN3
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
@UNKNOWN3:
	LDA @LOCAL0B
	INC
	STA @LOCAL0B
@UNKNOWN4:
	LDX @VIRTUAL04
	CMP a:pathfinding::radius,X
	BNE @UNKNOWN1
	LDX @LOCAL0C
	INX
	STX @LOCAL0C
@UNKNOWN5:
	TXA
	LDX @VIRTUAL04
	CMP a:pathfinding::radius + 2,X
	BNE @UNKNOWN0
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL0A
	STA @LOCAL0B
	JMP @UNKNOWN10
@UNKNOWN6:
	ASL
	STA @LOCAL09
	LDY #.LOWORD(ENTITY_SCRIPT_TABLE)
	LDA (@LOCAL09),Y
	CMP #.LOWORD(-1)
	BEQL @UNKNOWN9
	LDY #.LOWORD(ENTITY_PATHFINDING_STATES)
	LDA (@LOCAL09),Y
	CMP #.LOWORD(-1)
	BNEL @UNKNOWN9
	LDY #.LOWORD(ENTITY_SIZES)
	LDA (@LOCAL09),Y
	STA @LOCAL08
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 18
	STA @VIRTUAL02
	LDA @LOCAL11
	STA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	TAX
	STX @LOCAL0C
	LDA @LOCAL0B
	STA a:pathfinding::pathfinders + pathfinder::object_index,X
	LDA @LOCAL0E
	STA a:pathfinding::pathfinders + pathfinder::from_offscreen,X
	LDA @LOCAL08
	ASL
	STA @LOCAL08
	LDX @LOCAL08
	LDA f:UNKNOWN_C42AA7,X
	LDX @LOCAL0C
	STA a:pathfinding::pathfinders + pathfinder::unknown_hitbox + 2,X
	LDX @LOCAL08
	LDA f:UNKNOWN_C42AC9,X
	LDX @LOCAL0C
	STA a:pathfinding::pathfinders + pathfinder::unknown_hitbox,X
	LDX @LOCAL08
	LDY #.LOWORD(ENTITY_ABS_X_TABLE)
	LDA (@LOCAL09),Y
	SEC
	SBC f:UNKNOWN_C42A1F,X
	LSR
	LSR
	LSR
	SEC
	SBC @LOCAL13
	AND #$003F
	LDX @LOCAL0C
	STA a:pathfinding::pathfinders + pathfinder::origin + 2,X
	LDY @LOCAL0D
	STY @VIRTUAL02
	LDX @LOCAL08
	LDY #.LOWORD(ENTITY_ABS_Y_TABLE)
	LDA (@LOCAL09),Y
	SEC
	SBC f:UNKNOWN_C42A41,X
	LDX @LOCAL08
	CLC
	ADC f:UNKNOWN_C42AEB,X
	LSR
	LSR
	LSR
	SEC
	SBC @VIRTUAL02
	AND #$003F
	LDX @LOCAL0C
	STA a:pathfinding::pathfinders + pathfinder::origin,X
	LDA @LOCAL0A
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL0A
@UNKNOWN9:
	LDA @LOCAL0B
	INC
	STA @LOCAL0B
@UNKNOWN10:
	CMP #MAX_ENTITIES
	BNEL @UNKNOWN6
	LDA @VIRTUAL02
	LDX @VIRTUAL04
	STA a:pathfinding::pathfinder_count,X
	LOADPTR BUFFER + $3000, @LOCAL00
	LDA #4
	STA @LOCAL01
	LDA @LOCAL12
	STA @LOCAL02
	LDA @VIRTUAL04
	CLC
	ADC #pathfinding::targets
	STA @LOCAL03
	LDA @VIRTUAL02
	STA @LOCAL04
	LDA @VIRTUAL04
	CLC
	ADC #pathfinding::pathfinders
	STA @LOCAL05
	LDA #.LOWORD(-1)
	STA @LOCAL06
	MOVE_INT @LOCAL0F, @LOCAL07
	LDA @VIRTUAL04
	CLC
	ADC #pathfinding::radius
	TAY
	LDX #.LOWORD(PATHFINDING_BUFFER)
	LDA #$0C00
	JSL UNKNOWN_C4B59F
	TAX
	STX @LOCAL0B
@UNKNOWN12:
	JSL UNKNOWN_C4B595
	CMP #$0C00
	BGT @UNKNOWN12
	LDX @LOCAL0B
	BNE @UNKNOWN17
	LDA #0
	STA @LOCAL0B
	BRA @UNKNOWN16
@UNKNOWN14:
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN15
	LDA #1
	STA ENTITY_PATHFINDING_STATES,X
@UNKNOWN15:
	LDA @LOCAL0B
	INC
	STA @LOCAL0B
@UNKNOWN16:
	CMP #MAX_ENTITIES
	BNE @UNKNOWN14
	LDA #.LOWORD(-1)
	BRA @UNKNOWN22
@UNKNOWN17:
	LDA #0
	STA @LOCAL0B
	BRA @UNKNOWN21
@UNKNOWN18:
	OPTIMIZED_MULT @VIRTUAL04, 18
	STA @VIRTUAL02
	LDA @LOCAL11
	STA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	TAX
	LDA a:pathfinding::pathfinders + pathfinder::object_index,X
	STA @LOCAL08
	TXA
	CLC
	ADC #pathfinding::pathfinders + pathfinder::unknown10;
	TAY
	STY @LOCAL0F
	LDA __BSS_START__,Y
	BEQ @UNKNOWN19
	LDA @LOCAL08
	ASL
	STA @LOCAL08
	LDA a:pathfinding::pathfinders + pathfinder::unknown12,X
	LDY #.LOWORD(ENTITY_PATH_POINTS)
	STA (@LOCAL08),Y
	LDY @LOCAL0F
	LDA __BSS_START__,Y
	LDY #.LOWORD(ENTITY_PATH_POINT_COUNTS)
	STA (@LOCAL08),Y
	BRA @UNKNOWN20
@UNKNOWN19:
	LDA @LOCAL08
	ASL
	TAX
	LDA #1
	STA ENTITY_PATHFINDING_STATES,X
@UNKNOWN20:
	LDA @LOCAL0B
	INC
	STA @LOCAL0B
@UNKNOWN21:
	LDX @LOCAL0A
	STX @VIRTUAL02
	CMP @VIRTUAL02
	BCC @UNKNOWN18
	LDA #0
@UNKNOWN22:
	END_C_FUNCTION
