
UNKNOWN_C0C19B:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	LDY CURRENT_ENTITY_SLOT
	STY @LOCAL02
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_ATTRS
	AND #$0007
	TAX
	LDA f:UNKNOWN_C3DFE8,X
	AND #$00FF
	BEQL @UNKNOWN4
	LDY @LOCAL02
	TYA
	ASL
	STA @LOCAL01
	CLC
	ADC #.LOWORD(ENTITY_PATHFINDING_STATES)
	TAX
	STX @LOCAL00
	LDA #.LOWORD(-1)
	STA __BSS_START__,X
	JSL UNKNOWN_C0BD96
	TAY
	BNE @UNKNOWN4
	LDA #0
	LDX @LOCAL00
	STA __BSS_START__,X
	LDA @LOCAL01
	CLC
	ADC #.LOWORD(ENTITY_PATH_POINTS)
	TAX
	LDA __BSS_START__,X
	STA @VIRTUAL02
	LDA @VIRTUAL04
	STA @VIRTUAL04
	ASL
	ASL
	ADC @VIRTUAL04
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(DELIVERY_PATHS)
	TAY
	STA __BSS_START__,X
	LDA @LOCAL01
	TAX
	LDA ENTITY_PATH_POINT_COUNTS,X
	STA @LOCAL01
	LDX #0
	STX @LOCAL00
	BRA @UNKNOWN2
@UNKNOWN1:
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	STA __BSS_START__,Y
	LDX @VIRTUAL02
	LDA __BSS_START__+2,X
	STA __BSS_START__+2,Y
	INC @VIRTUAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
	INY
	INY
	INY
	INY
	LDA @LOCAL01
	DEC
	STA @LOCAL01
	LDX @LOCAL00
	INX
	STX @LOCAL00
@UNKNOWN2:
	CMP #0
	BEQ @UNKNOWN3
	CPX #20
	BCC @UNKNOWN1
@UNKNOWN3:
	LDA #0
	BRA @UNKNOWN5
@UNKNOWN4:
	LDA #1
@UNKNOWN5:
	END_C_FUNCTION
