
UNKNOWN_C0C6B6: ;$C0C6B6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA .LOWORD(UNKNOWN_7E9F47)
	CMP #$0004
	BCC @UNKNOWN0
	LDA #$FFFF
	BRA @UNKNOWN4
@UNKNOWN0:
	LDA .LOWORD(CURRENT_ENTITY_SLOT)
	ASL
	TAX
	LDA .LOWORD(GAME_STATE)+game_state::leader_x_coord
	SEC
	SBC #$0080
	STA $02
	LDA .LOWORD(ENTITY_ABS_X_TABLE),X
	SEC
	SBC $02
	STA $0E
	LDA .LOWORD(GAME_STATE)+game_state::leader_y_coord
	SEC
	SBC #$0070
	STA $02
	LDA .LOWORD(ENTITY_ABS_Y_TABLE),X
	SEC
	SBC $02
	TAX
	LDA $0E
	CMP #$FFC0
	BCS @UNKNOWN1
	CMP #$0140
	BCS @UNKNOWN3
@UNKNOWN1:
	CPX #$FFC0
	BCS @UNKNOWN2
	CPX #$0140
	BCS @UNKNOWN3
@UNKNOWN2:
	LDA #$FFFF
	BRA @UNKNOWN4
@UNKNOWN3:
	LDA #$0000
@UNKNOWN4:
	PLD
	RTL
