
UNKNOWN_C0C615:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL UNKNOWN_C0C524
	CMP #$0000
	BEQ @UNKNOWN0
	JSL GET_OPPOSITE_DIRECTION_FROM_PLAYER_TO_ENTITY
	BRA @UNKNOWN1
@UNKNOWN0:
	JSL GET_DIRECTION_FROM_PLAYER_TO_ENTITY
@UNKNOWN1:
	RTL
