
UNKNOWN_C0C7AC:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL02
	JSL UNKNOWN_C09EFF
	CMP #0
	BEQ @UNKNOWN0
	LDY @VIRTUAL02
	LDX ENTITY_MOVEMENT_PROSPECTIVE_Y
	LDA ENTITY_MOVEMENT_PROSPECTIVE_X
	JSL UNKNOWN_C05F33
	STA @LOCAL00
	LDA @VIRTUAL02
	ASL
	TAX
	LDA @LOCAL00
	STA ENTITY_SURFACE_FLAGS,X
@UNKNOWN0:
	END_C_FUNCTION
