
UNKNOWN_C0C7DB:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @LOCAL01
	ASL
	STA @VIRTUAL02
	LDA @LOCAL01
	TAY
	LDX @VIRTUAL02
	LDA ENTITY_ABS_Y_TABLE,X
	TAX
	STX @LOCAL00
	LDX @VIRTUAL02
	LDA ENTITY_ABS_X_TABLE,X
	LDX @LOCAL00
	JSL UNKNOWN_C05F33
	LDX @VIRTUAL02
	STA ENTITY_SURFACE_FLAGS,X
	END_C_FUNCTION
