
UNKNOWN_C0C808: ;$C0C808
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA .LOWORD(UNKNOWN_7E1A42)
	STA $10
	ASL
	STA $02
	LDA $10
	TAY
	LDX $02
	LDA .LOWORD(ENTITY_ABS_Y_TABLE),X
	LDX $02
	SEC
	SBC .LOWORD(ENTITY_ABS_Z_TABLE),X
	TAX
	STX $0E
	LDX $02
	LDA .LOWORD(ENTITY_ABS_X_TABLE),X
	LDX $0E
	JSL UNKNOWN_C05F33
	LDX $02
	STA .LOWORD(UNKNOWN_30X2_TABLE_37),X
	PLD
	RTL
