
UNKNOWN_C0CBD3: ;$C0CBD3
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	PHA
	TDC
	ADC #$FFF0
	TCD
	PLA
	STA $0E
	LDA .LOWORD(UNKNOWN_7E1A46)
	ASL
	PHA
	LDA .LOWORD(UNKNOWN_7E1A42)
	ASL
	TAX
	LDA .LOWORD(UNKNOWN_30X2_TABLE_35),X
	STA $0A
	STZ $0C
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0008
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	STA $06
	STZ $08
	JSL ASL32_ENTRY2
	REP #PROC_FLAGS::INDEX8
	JSL DIVISION32
	LDA $06
	PLX
	STA .LOWORD(MAP_ENTITY_SLEEP_FRAMES),X
	PLD
	RTL
