
UNKNOWN_C0CC11:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL04
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR6_TABLE,X
	SEC
	SBC ENTITY_ABS_X_TABLE,X
	STA @LOCAL01
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN2
	LDA @LOCAL01
	EOR #.LOWORD(-1)
	INC
	BRA @UNKNOWN3
@UNKNOWN2:
	LDA @LOCAL01
@UNKNOWN3:
	TAY
	LDA @VIRTUAL04
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR7_TABLE,X
	SEC
	SBC ENTITY_ABS_Y_TABLE,X
	STA @LOCAL01
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UNKNOWN6
	LDA @LOCAL01
	EOR #.LOWORD(-1)
	INC
	BRA @UNKNOWN7
@UNKNOWN6:
	LDA @LOCAL01
@UNKNOWN7:
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BLTEQ @UNKNOWN8
	TYA
	STA @LOCAL01
	LDA @VIRTUAL04
	ASL
	TAX
	LDA ENTITY_DELTA_X_TABLE,X
	STA @LOCAL00 + fixed_point::integer
	LDA ENTITY_DELTA_X_FRACTION_TABLE,X
	STA @LOCAL00 + fixed_point::fraction
	BRA @UNKNOWN9
@UNKNOWN8:
	LDA @VIRTUAL02
	STA @LOCAL01
	LDA @VIRTUAL04
	ASL
	TAX
	LDA ENTITY_DELTA_Y_TABLE,X
	STA @LOCAL00 + fixed_point::integer
	LDA ENTITY_DELTA_Y_FRACTION_TABLE,X
	STA @LOCAL00 + fixed_point::fraction
@UNKNOWN9:
	MOVE_INT @LOCAL00, @VIRTUAL0A
	SEP #PROC_FLAGS::INDEX8
	LDY #16
	LDA @LOCAL01
	JSL ASL16_ENTRY2
	STORE_INT1632 @VIRTUAL06
	REP #PROC_FLAGS::INDEX8
	JSL DIVISION32
	LDA @VIRTUAL06
	STA @LOCAL01
	BNE @UNKNOWN10
	LDA #1
	STA @LOCAL01
@UNKNOWN10:
	LDA CURRENT_SCRIPT_SLOT
	ASL
	TAX
	LDA @LOCAL01
	STA ENTITY_SCRIPT_SLEEP_FRAMES,X
	END_C_FUNCTION
