
UNKNOWN_C0D0E6: ;$C0D0E6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDA .LOWORD(UNKNOWN_7E1A42)
	STA $02
	JSL UNKNOWN_C0C363
	CMP #$0000
	BNE @UNKNOWN0
	LDA $02
	ASL
	TAX
	LDA .LOWORD(UNKNOWN_30X2_TABLE_41),X
	BEQ @UNKNOWN0
	LDA .LOWORD(GAME_STATE)+game_state::leader_x_coord
	STA .LOWORD(SPRITE_ABS_X_TABLE),X
	LDA .LOWORD(GAME_STATE)+game_state::leader_y_coord
	STA .LOWORD(SPRITE_ABS_Y_TABLE),X
	LDA #$FFFF
	BRA @UNKNOWN2
@UNKNOWN0:
	JSL UNKNOWN_C09EFF
	LDA #$0004
	STA $0E
	LDY $02
	LDX .LOWORD(UNKNOWN_7E284A)
	LDA .LOWORD(UNKNOWN_7E2848)
	JSL UNKNOWN_C05CD7
	AND #$00C0
	BEQ @UNKNOWN1
	LDA $02
	ASL
	CLC
	ADC #$2B32
	TAX
	LDA a:.LOWORD(RAM),X
	SEC
	SBC #$1000
	STA a:.LOWORD(RAM),X
	LDA #$0000
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA $02
	ASL
	TAX
	LDA .LOWORD(UNKNOWN_7E2848)
	STA .LOWORD(SPRITE_ABS_X_TABLE),X
	LDA .LOWORD(UNKNOWN_7E284A)
	STA .LOWORD(SPRITE_ABS_Y_TABLE),X
	LDA #$FFFF
@UNKNOWN2:
	PLD
	RTL
