
UNKNOWN_C0D5B0:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA BATTLE_MODE
	BEQ @UNKNOWN0
	LDA #0
	JMP @UNKNOWN25
@UNKNOWN0:
	LDA USING_DOOR
	BEQ @UNKNOWN1
	LDA #0
	JMP @UNKNOWN25
@UNKNOWN1:
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL02
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @UNKNOWN2
	LDA @VIRTUAL02
	CMP TOUCHED_ENEMY
	BEQ @UNKNOWN8
@UNKNOWN2:
	LDA GAME_STATE + game_state::unknownB0
	CMP #2
	BNE @UNKNOWN3
	LDA #0
	JMP @UNKNOWN25
@UNKNOWN3:
	LDA PLAYER_MOVEMENT_FLAGS
	AND #02
	BEQ @UNKNOWN4
	LDA #0
	JMP @UNKNOWN25
@UNKNOWN4:
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::ESCALATOR
	BNE @UNKNOWN5
	LDA #0
	JMP @UNKNOWN25
@UNKNOWN5:
	LDA PLAYER_INTANGIBILITY_FRAMES
	BEQ @UNKNOWN6
	LDA #0
	JMP @UNKNOWN25
@UNKNOWN6:
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @UNKNOWN7
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_PATH_POINT_COUNTS,X
	BEQ @UNKNOWN8
@UNKNOWN7:
	JSL UNKNOWN_C0D15C
	CMP #0
	BNE @UNKNOWN8
	LDA #0
	JMP @UNKNOWN25
@UNKNOWN8:
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN9
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @UNKNOWN9
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_ENEMY_IDS,X
	CMP #ENEMY::MAGIC_BUTTERFLY
	BNE @UNKNOWN9
	LDA #1
	JMP @UNKNOWN25
@UNKNOWN9:
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @UNKNOWN15
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @UNKNOWN15
	LDA #1
	STA ENEMY_HAS_BEEN_TOUCHED
	JSL UNKNOWN_C0D4DE
	LDA @VIRTUAL02
	CMP ENTITY_COLLIDED_OBJECTS+46
	BNE @UNKNOWN10
	LDA #24
	STA ENEMY_PATHFINDING_TARGET_ENTITY
	BRA @UNKNOWN11
@UNKNOWN10:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_COLLIDED_OBJECTS,X
	STA ENEMY_PATHFINDING_TARGET_ENTITY
@UNKNOWN11:
	LDA @VIRTUAL02
	STA TOUCHED_ENEMY
	LDA #0
	STA @LOCAL03
	BRA @UNKNOWN14
@UNKNOWN12:
	CMP #23
	BEQ @UNKNOWN13
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
@UNKNOWN13:
	LDA @LOCAL03
	INC
	STA @LOCAL03
@UNKNOWN14:
	CMP #MAX_ENTITIES
	BCC @UNKNOWN12
	JSL UNKNOWN_C04A88
	LDA #1
	JMP @UNKNOWN25
@UNKNOWN15:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA #ENTITY_COLLISION_DISABLED
	STA ENTITY_COLLIDED_OBJECTS,X
	STZ @LOCAL02
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQL @UNKNOWN24
	LDA @VIRTUAL02
	CMP TOUCHED_ENEMY
	BNE @UNKNOWN17
	TXA
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
	LDA #1
	STA @LOCAL02
	JMP @UNKNOWN24
@UNKNOWN17:
	LDA ENTITY_ENEMY_IDS,X
	STA @VIRTUAL04
	LDY #0
	STZ @LOCAL02
	TYA
	STA @LOCAL01
	BRA @UNKNOWN20
@UNKNOWN18:
	ASL
	TAX
	LDA @VIRTUAL04
	CMP PATHFINDING_ENEMY_IDS,X
	BNE @UNKNOWN19
	TXA
	CLC
	ADC #.LOWORD(PATHFINDING_ENEMY_COUNTS)
	TAX
	LDA __BSS_START__,X
	STA @LOCAL00
	BEQ @UNKNOWN19
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
	LDA #1
	STA @LOCAL02
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
	LDA ENEMIES_IN_BATTLE
	ASL
	TAX
	LDA @VIRTUAL04
	STA ENEMIES_IN_BATTLE_IDS,X
	INC ENEMIES_IN_BATTLE
@UNKNOWN19:
	LDA @LOCAL01
	ASL
	TAX
	TYA
	CLC
	ADC PATHFINDING_ENEMY_COUNTS,X
	TAY
	LDA @LOCAL01
	INC
	STA @LOCAL01
@UNKNOWN20:
	CMP #4
	BNE @UNKNOWN18
	CPY #0
	BNE @UNKNOWN24
	JSL UNKNOWN_C2E9C8
	CMP #0
	BNE @UNKNOWN24
	LDA #0
	STA @LOCAL03
	BRA @UNKNOWN23
@UNKNOWN21:
	CMP #23
	BEQ @UNKNOWN22
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
@UNKNOWN22:
	LDA @LOCAL03
	INC
	STA @LOCAL03
@UNKNOWN23:
	CMP #MAX_ENTITIES
	BCC @UNKNOWN21
	LDA #1
	STA BATTLE_SWIRL_COUNTDOWN
@UNKNOWN24:
	LDA @LOCAL02
@UNKNOWN25:
	END_C_FUNCTION
