
UNKNOWN_C0D7E0: ;$C0D7E0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA .LOWORD(UNKNOWN_7E1A42)
	ASL
	CLC
	ADC #.LOWORD(UNKNOWN_30X2_TABLE_41)
	TAX
	LDA a:.LOWORD(RAM),X
	BEQ @UNKNOWN0
	LDA #$0001
	STA a:.LOWORD(RAM),X
@UNKNOWN0:
	RTL
