
UNKNOWN_C0D7B3: ;$C0D7B3
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA .LOWORD(UNKNOWN_7E1A42)
	ASL
	TAX
	LDA .LOWORD(ENTITY_ABS_X_TABLE),X
	STA .LOWORD(UNKNOWN_7E4DBE)
	LDA .LOWORD(ENTITY_ABS_Y_TABLE),X
	STA .LOWORD(UNKNOWN_7E4DC0)
	RTL
