
UNKNOWN_C0D98F:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAY
	CLC
	ADC #.LOWORD(ENTITY_PATH_POINT_COUNTS)
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	BNE @UNKNOWN0
	LDA #0
	JMP @UNKNOWN1
@UNKNOWN0:
	LDA ENTITY_SIZES,Y
	STA @LOCAL02
	TYA
	CLC
	ADC #.LOWORD(ENTITY_PATH_POINTS)
	STA @VIRTUAL02
	STA @LOCAL01
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAX
	STX @LOCAL00
	LDA @LOCAL02
	ASL
	STA @LOCAL02
	PHA
	LDA __BSS_START__+2,X
	OPTIMIZED_MULT @VIRTUAL04, 8
	PLX
	CLC
	ADC f:UNKNOWN_C42A1F,X
	STA @VIRTUAL02
	LDA PATHFINDING_TARGET_CENTRE_X
	SEC
	SBC PATHFINDING_TARGET_WIDTH
	OPTIMIZED_MULT @VIRTUAL04, 8
	CLC
	ADC @VIRTUAL02
	STA ENTITY_SCRIPT_VAR6_TABLE,Y
	LDA @LOCAL02
	PHA
	PHA
	LDX @LOCAL00
	LDA __BSS_START__,X
	OPTIMIZED_MULT @VIRTUAL04, 8
	PLX
	SEC
	SBC f:UNKNOWN_C42AEB,X
	PLX
	CLC
	ADC f:UNKNOWN_C42A41,X
	STA @VIRTUAL02
	LDA PATHFINDING_TARGET_CENTRE_Y
	SEC
	SBC PATHFINDING_TARGET_HEIGHT
	OPTIMIZED_MULT @VIRTUAL04, 8
	CLC
	ADC @VIRTUAL02
	STA ENTITY_SCRIPT_VAR7_TABLE,Y
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	DEC
	LDX @VIRTUAL04
	STA __BSS_START__,X
	LDX @LOCAL00
	TXA
	INC
	INC
	INC
	INC
	LDX @LOCAL01
	STX @VIRTUAL02
	STA __BSS_START__,X
	LDA #1
@UNKNOWN1:
	END_C_FUNCTION
