
UNKNOWN_C0DD0F: ;$C0DD0F
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	BRA @UNKNOWN1
@UNKNOWN0:
	JSL OAM_CLEAR
	JSL UNKNOWN_C09466
	JSL UNKNOWN_C08B19_ENTRY_POINT_2
	JSL WAIT_UNTIL_NEXT_FRAME
@UNKNOWN1:
	LDA a:.LOWORD(UNKNOWN_7E0028)
	AND #$00FF
	BNE @UNKNOWN0
	RTS
