
UNKNOWN_C0DD79:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PSI_TELEPORT_DESTINATION
	STA @VIRTUAL02
	LDY #1
	STY @LOCAL01
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX #0
	TYA
	JSL SET_EVENT_FLAG
	LDY @LOCAL01
	INY
	STY @LOCAL01
@UNKNOWN1:
	CPY #10
	BLTEQ @UNKNOWN0
	LOADPTR PSI_TELEPORT_DEST_TABLE, @VIRTUAL06
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(psi_teleport_destination)
	STA @LOCAL01
	CLC
	ADC #psi_teleport_destination::dest_x
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	TAX
	STX CURRENT_TELEPORT_DESTINATION_X
	LDA @LOCAL01
	CLC
	ADC #psi_teleport_destination::dest_y
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA @LOCAL01
	STA CURRENT_TELEPORT_DESTINATION_Y
	TXA
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	LDA @LOCAL01
	ASL
	ASL
	ASL
	STA @LOCAL00
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::INSTANT
	BEQ @UNKNOWN2
	LDA @VIRTUAL02
	CLC
	ADC #316
	STA @VIRTUAL02
@UNKNOWN2:
	LDA #.LOWORD(-1)
	STA CURRENT_MAP_MUSIC_TRACK
	STA LOADED_MAP_PALETTE
	STA LOADED_MAP_TILE_COMBO
	LDY #6
	LDA @LOCAL00
	TAX
	LDA @VIRTUAL02
	JSL INITIALIZE_MAP
	END_C_FUNCTION
