
UNKNOWN_C0DE16:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY #24
	BRA @UNKNOWN1
@UNKNOWN0:
	TYA
	ASL
	STA @LOCAL00
	TAX
	LDA #8
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	ORA #SPRITE_TABLE_10_FLAGS::UNKNOWN11
	STA __BSS_START__,X
	INY
@UNKNOWN1:
	CPY #MAX_ENTITIES
	BCC @UNKNOWN0
	END_C_FUNCTION
