
UNKNOWN_C0DE7C:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #.LOWORD(CHAR_STRUCT)
	STA UNKNOWN_7E4DC6
	LDY #24
	BRA @UNKNOWN1
@UNKNOWN0:
	TYA
	ASL
	STA @LOCAL00
	TAX
	LDA #8
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ SPRITE_TABLE_10_FLAGS::UNKNOWN11
	STA __BSS_START__,X
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(ENTITY_COLLIDED_OBJECTS)
	TAX
	LDA __BSS_START__,X
	AND #$7FFF
	STA __BSS_START__,X
	LDA #.LOWORD(-1)
	LDX UNKNOWN_7E4DC6
	STA a:char_struct::unknown55,X
	LDA UNKNOWN_7E4DC6
	CLC
	ADC #.SIZEOF(char_struct)
	STA UNKNOWN_7E4DC6
	INY
@UNKNOWN1:
	CPY #MAX_ENTITIES
	BCC @UNKNOWN0
	JSL CHANGE_MUSIC_5DD6
	END_C_FUNCTION
