
UNKNOWN_C0DED9:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL02
	STX @VIRTUAL04
	STA @LOCAL01
	LDX @PARAM03
	STX @LOCAL00
	LDA PSI_TELEPORT_STATE
	BEQ @UNKNOWN0
	LDA #0
	BRA @UNKNOWN1
@UNKNOWN0:
	LDA #.LOWORD(GAME_STATE) + game_state::current_party_members
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAY
	LDX @VIRTUAL04
	LDA @LOCAL01
	JSL UNKNOWN_C05F33
	STA @VIRTUAL04
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAY
	LDX @LOCAL00
	LDA @LOCAL02
	JSL UNKNOWN_C05F33
	STA @VIRTUAL02
	LDA @VIRTUAL04
	ORA @VIRTUAL02
@UNKNOWN1:
	END_C_FUNCTION
