
UNKNOWN_C0E28F:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #1
	STA GAME_STATE + game_state::unknown90
	LDA #0
	JSL MAP_INPUT_TO_DIRECTION
	STA @VIRTUAL02
	LDA GAME_STATE+game_state::leader_direction
	STA @LOCAL04
	LDA @VIRTUAL02
	EOR #$0004
	STA @VIRTUAL04
	LDA @LOCAL04
	CMP @VIRTUAL04
	BNE @UNKNOWN0
	STA @VIRTUAL02
@UNKNOWN0:
	LDA @VIRTUAL02
	CMP #.LOWORD(-1)
	BNE @UNKNOWN1
	LDA GAME_STATE+game_state::leader_direction
	STA @VIRTUAL02
@UNKNOWN1:
	LDA @VIRTUAL02
	STA GAME_STATE+game_state::leader_direction
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @UNKNOWN2
	LDA #2
	STA PSI_TELEPORT_STATE
	LDA #1
	STA BATTLE_MODE
@UNKNOWN2:
	LDA @VIRTUAL02
	JSR UNKNOWN_C0DF22
	LDA GAME_STATE + game_state::unknown80
	STA @VIRTUAL0A
	LDA GAME_STATE+game_state::leader_x_coord
	STA @VIRTUAL0A+2
	MOVE_INT PSI_TELEPORT_SPEED_X, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_NEXT_X
	LDA GAME_STATE + game_state::unknown84
	STA @VIRTUAL0A
	LDA GAME_STATE+game_state::leader_y_coord
	STA @VIRTUAL0A+2
	MOVE_INT PSI_TELEPORT_SPEED_Y, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_NEXT_Y
	LDY GAME_STATE+game_state::current_party_members
	LDX PSI_TELEPORT_NEXT_Y + fixed_point::integer
	LDA PSI_TELEPORT_NEXT_X + fixed_point::integer
	JSL NPC_COLLISION_CHECK
	CMP #.LOWORD(-1)
	BEQ @UNKNOWN3
	LDA #2
	STA PSI_TELEPORT_STATE
@UNKNOWN3:
	LDA PSI_TELEPORT_NEXT_Y + fixed_point::integer
	STA @LOCAL00
	LDA @VIRTUAL02
	STA @LOCAL01
	LDY PSI_TELEPORT_NEXT_X + fixed_point::integer
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSR UNKNOWN_C0DED9
	AND #$00C0
	BEQ @UNKNOWN4
	LDA #2
	STA PSI_TELEPORT_STATE
@UNKNOWN4:
	LDA PSI_TELEPORT_STATE
	CMP #2
	BEQ @UNKNOWN5
	MOVE_INT PSI_TELEPORT_NEXT_X, @VIRTUAL06
	LDA @VIRTUAL06
	STA GAME_STATE + game_state::unknown80
	LDA @VIRTUAL06+2
	STA GAME_STATE+game_state::leader_x_coord
	MOVE_INT PSI_TELEPORT_NEXT_Y, @VIRTUAL06
	LDA @VIRTUAL06
	STA GAME_STATE + game_state::unknown84
	LDA @VIRTUAL06+2
	STA GAME_STATE+game_state::leader_y_coord
@UNKNOWN5:
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CENTER_SCREEN
	JSR UNKNOWN_C0E196
	JSR UNKNOWN_C0E254
	LDA PSI_TELEPORT_SPEED + fixed_point::integer
	CMP #9
	BLTEQ @UNKNOWN6
	LDA #1
	STA PSI_TELEPORT_STATE
@UNKNOWN6:
	END_C_FUNCTION
