
UNKNOWN_C0E674:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	END_STACK_VARS
	LDA GAME_STATE+game_state::leader_direction
	JSR UNKNOWN_C0DF22
	LDY #.LOWORD(GAME_STATE) + game_state::unknown80
	MOVE_INT UNKNOWN_7E9F49, @VIRTUAL0A
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDY #.LOWORD(GAME_STATE) + game_state::unknown84
	MOVE_INT UNKNOWN_7E9F4D, @VIRTUAL0A
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDA UNKNOWN_7E9F59 + 2
	CLC
	ADC UNKNOWN_7E9F59
	TAY
	STY UNKNOWN_7E9F5B
	LDA UNKNOWN_7E9F5F
	CLC
	ADC UNKNOWN_7E9F5D
	STA UNKNOWN_7E9F5F
	TAX
	TYA
	JSL CENTER_SCREEN
	JSR UNKNOWN_C0E196
	PLD
	RTL
