
UNKNOWN_C0E6FE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAY
	STY @LOCAL01
	LDA ENTITY_SCRIPT_VAR1_TABLE,Y
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAX
	STX CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::position_index,X
	STA @VIRTUAL04
	STA @LOCAL00
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(player_position_buffer_entry)
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	TAX
	LDY @LOCAL01
	LDA ENTITY_SCRIPT_VAR0_TABLE,Y
	STA @VIRTUAL02
	LDA a:player_position_buffer_entry::x_coord,X
	STA ENTITY_ABS_X_TABLE,Y
	LDA a:player_position_buffer_entry::y_coord,X
	STA ENTITY_ABS_Y_TABLE,Y
	LDA a:player_position_buffer_entry::direction,X
	STA ENTITY_DIRECTIONS,Y
	LDA a:player_position_buffer_entry::tile_flags,X
	STA ENTITY_SURFACE_FLAGS,Y
	LDY CURRENT_ENTITY_SLOT
	LDA a:player_position_buffer_entry::walking_style,X
	TAX
	LDA @VIRTUAL02
	JSL UNKNOWN_C07A56
	LDA @LOCAL00
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA @VIRTUAL02
	JSR UNKNOWN_C0E214
	AND #$00FF
	LDX CURRENT_PARTY_MEMBER_TICK
	STA a:char_struct::position_index,X
	END_C_FUNCTION
