
UNKNOWN_C0E815:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA TELEPORT_STYLE
	CMP #TELEPORT_STYLE::INSTANT
	BEQ @UNKNOWN2
	LDA #24
	STA @LOCAL03
	BRA @UNKNOWN1
@UNKNOWN0:
	ASL
	TAX
	LDA #ENTITY_COLLISION_DISABLED
	STA ENTITY_COLLIDED_OBJECTS,X
	LDA @LOCAL03
	INC
	STA @LOCAL03
@UNKNOWN1:
	CMP #MAX_ENTITIES
	BCC @UNKNOWN0
	LDY #.LOWORD(UNKNOWN_7E9F4D) + 2
	STY @LOCAL02
	LDA #00
	STA __BSS_START__,Y
	LDX #.LOWORD(UNKNOWN_7E9F49) + 2
	STX @LOCAL03
	STA __BSS_START__,X
	LOADPTR UNKNOWN_C0E674, @LOCAL00
	LOADPTR UNKNOWN_C0E3C1, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
	LDX @LOCAL03
	LDA __BSS_START__,X
	STA UNKNOWN_7E9F59
	LDA GAME_STATE+game_state::leader_x_coord
	STA UNKNOWN_7E9F5B
	LDY @LOCAL02
	LDA __BSS_START__,Y
	STA UNKNOWN_7E9F5D
	LDA GAME_STATE+game_state::leader_y_coord
	STA UNKNOWN_7E9F5F
	LDX #4
	LDA #1
	JSL FADE_OUT
	JSR UNKNOWN_C0DD0F
@UNKNOWN2:
	END_C_FUNCTION
