
UNKNOWN_C0E897:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::INSTANT
	BNE @UNKNOWN0
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CENTER_SCREEN
	LDX #1
	TXA
	JSL FADE_IN
	JSR UNKNOWN_C0DD0F
	JMP @UNKNOWN7
@UNKNOWN0:
	LDA #0
	STA @VIRTUAL02
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA #.LOWORD(-1)
	STA PARTY_CHARACTERS + char_struct::unknown55,X
	LDA @VIRTUAL02
	CLC
	ADC #24
	TAY
	LDX #0
	STX @LOCAL03
.IF .DEFINED(JPN)
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknown96,X
.ELSE
	LDX @VIRTUAL02
	LDA GAME_STATE + game_state::unknown96,X
.ENDIF
	AND #$00FF
	DEC
	LDX @LOCAL03
	JSL UNKNOWN_C07A56
	INC @VIRTUAL02
@UNKNOWN2:
	LDA @VIRTUAL02
	CMP #6
	BCC @UNKNOWN1
	MOVE_INT_CONSTANT $00080000, PSI_TELEPORT_SPEED
	LDA #6
	STA GAME_STATE+game_state::leader_direction
	LDA #3
	STA PSI_TELEPORT_STATE
	LOADPTR UNKNOWN_C0E776, @LOCAL00
	LOADPTR UNKNOWN_C0E3C1, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
	JSR UNKNOWN_C0DE16
	LDA #MUSIC::TELEPORT_IN
	JSL CHANGE_MUSIC
	LDX #0
	STX @LOCAL02
	BRA @UNKNOWN4
@UNKNOWN3:
	JSL WAIT_UNTIL_NEXT_FRAME
	LDX @LOCAL02
	INX
	STX @LOCAL02
@UNKNOWN4:
	CPX #30
	BCC @UNKNOWN3
	LDX #4
	LDA #1
	JSL FADE_IN
	BRA @UNKNOWN6
@UNKNOWN5:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
@UNKNOWN6:
	LDA PSI_TELEPORT_SPEED + fixed_point::integer
	BNE @UNKNOWN5
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CENTER_SCREEN
@UNKNOWN7:
	END_C_FUNCTION
