
UNKNOWN_C0E97C:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL04
	ASL
	STA @VIRTUAL02
	LDY @VIRTUAL04
	LDX @VIRTUAL02
	LDA ENTITY_ABS_Y_TABLE,X
	TAX
	STX @LOCAL00
	LDX @VIRTUAL02
	LDA ENTITY_ABS_X_TABLE,X
	LDX @LOCAL00
	JSL UNKNOWN_C05F33
	LDX @VIRTUAL02
	STA ENTITY_SURFACE_FLAGS,X
	LDY @VIRTUAL04
	LDX #.LOWORD(-1)
	STX @LOCAL00
	LDX @VIRTUAL02
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	LDX @LOCAL00
	JSL UNKNOWN_C07A56
	END_C_FUNCTION
