
UNKNOWN_C0ED41:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDY ENTITY_SCRIPT_VAR0_TABLE,X
	STY @LOCAL02
	LOADPTR BUFFER, @VIRTUAL06
	TYA
	LDY #BPP4PALETTE_SIZE * 16
	JSL MULT16
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #BPP4PALETTE_SIZE * 16
	LDA #.LOWORD(PALETTES)
	JSL MEMCPY16
	LDY @LOCAL02
	TYA
	INC
	STA @LOCAL01
	CMP #9
	BNE @UNKNOWN0
	LDA #0
	STA @LOCAL01
@UNKNOWN0:
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA @LOCAL01
	STA ENTITY_SCRIPT_VAR0_TABLE,X
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
