
UNKNOWN_C0ED5C:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STZ PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
	LOADPTR TITLE_SCREEN_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DECOMP
	LDA #0
	JSL UNKNOWN_C0EC77
	LOADPTR BUFFER+$1A0, @LOCAL00
	LDX #BPP4PALETTE_SIZE
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 8
	JSL MEMCPY16
	LDA #1
	JSL UNKNOWN_C0EC77
	LOADPTR BUFFER+$260, @LOCAL00
	LDX #BPP4PALETTE_SIZE
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 7
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
