
UNKNOWN_C0ED14:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA @LOCAL00
	LDX #BPP4PALETTE_SIZE * 8
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(CUR_TEXT_PAL)
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
	LDA #$18
	STA UNKNOWN_7E0030
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
