
CHECK_DIAGONAL_MOVEMENT_COLLISION:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL00
	STZ TEMP_ENTITY_SURFACE_FLAGS
	INC SET_TEMP_ENTITY_SURFACE_FLAGS
	TXA
	LSR
	ASL
	TAX
	LDA f:DIAGONAL_COLLISION_MASKS,X
	JSR PERFORM_COLLISION_CHECKS
	CMP #0
	BEQ @UNKNOWN0
	LDA #$FF00
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX @LOCAL00
	TXA
@UNKNOWN1:
	END_C_FUNCTION
