
GET_MOVEMENT_COLLISION_FLAGS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL04
	STA @LOCAL02
	LDX @PARAM03
	STX @LOCAL01
	STZ TEMP_ENTITY_SURFACE_FLAGS
	TYA
	ASL
	TAX
	LDA ENTITY_SIZES,X
	STA @VIRTUAL02
	ASL
	STA @LOCAL00
	LDX @LOCAL00
	LDA @LOCAL02
	SEC
	SBC f:COLLISION_WIDTHS,X
	TAY
	STY CHECKED_COLLISION_LEFT_X
	LDX @LOCAL00
	LDA @VIRTUAL04
	SEC
	SBC f:COLLISION_HEIGHTS,X
	LDX @LOCAL00
	CLC
	ADC f:COLLISION_HEIGHTS2,X
	STA @LOCAL00
	STA CHECKED_COLLISION_TOP_Y
	LDX @LOCAL01
	TXA
	CMP #1
	BEQ @UNKNOWN0
	CMP #0
	BEQ @UNKNOWN1
	CMP #3
	BEQ @UNKNOWN2
	CMP #2
	BEQ @UNKNOWN3
	CMP #5
	BEQ @UNKNOWN4
	CMP #4
	BEQ @UNKNOWN5
	CMP #7
	BEQ @UNKNOWN6
	CMP #6
	BEQ @UNKNOWN7
	BRA @UNKNOWN8
@UNKNOWN0:
	LDX @VIRTUAL02
	LDA @LOCAL00
	JSR CHECK_HORIZONTAL_RIGHT_TILE_COLLISION
@UNKNOWN1:
	LDX @VIRTUAL02
	LDA CHECKED_COLLISION_LEFT_X
	JSR CHECK_VERTICAL_UP_TILE_COLLISION
	BRA @UNKNOWN8
@UNKNOWN2:
	LDX @VIRTUAL02
	TYA
	JSR CHECK_VERTICAL_DOWN_TILE_COLLISION
@UNKNOWN3:
	LDX @VIRTUAL02
	LDA CHECKED_COLLISION_TOP_Y
	JSR CHECK_HORIZONTAL_RIGHT_TILE_COLLISION
	BRA @UNKNOWN8
@UNKNOWN4:
	LDX @VIRTUAL02
	LDA @LOCAL00
	JSR CHECK_HORIZONTAL_LEFT_TILE_COLLISION
@UNKNOWN5:
	LDX @VIRTUAL02
	LDA CHECKED_COLLISION_LEFT_X
	JSR CHECK_VERTICAL_DOWN_TILE_COLLISION
	BRA @UNKNOWN8
@UNKNOWN6:
	LDX @VIRTUAL02
	TYA
	JSR CHECK_VERTICAL_UP_TILE_COLLISION
@UNKNOWN7:
	LDX @VIRTUAL02
	LDA CHECKED_COLLISION_TOP_Y
	JSR CHECK_HORIZONTAL_LEFT_TILE_COLLISION
@UNKNOWN8:
	LDA TEMP_ENTITY_SURFACE_FLAGS
	END_C_FUNCTION
