
UNKNOWN_C0030F: ;$C0030F
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	TDC
	ADC #$FFF0
	TCD
	LDA .LOWORD(UNKNOWN_7E445C)
	DEC
	STA .LOWORD(UNKNOWN_7E445C)
	BNE @UNKNOWN1
	LDX #$445E
	STX $0E
	LDA a:.LOWORD(RAM),X
	ASL
	TAX
	LDA .LOWORD(UNKNOWN_7E4460),X
	BNE @UNKNOWN0
	LDA #$0000
	LDX $0E
	STA a:.LOWORD(RAM),X
@UNKNOWN0:
	LDX #$445E
	STX $0E
	LDA a:.LOWORD(RAM),X
	ASL
	TAX
	LDA .LOWORD(UNKNOWN_7E4460),X
	STA .LOWORD(UNKNOWN_7E445C)
	LDX $0E
	LDA a:.LOWORD(RAM),X
	JSL UNKNOWN_C0A1F2
	LDX $0E
	LDA a:.LOWORD(RAM),X
	INC
	STA a:.LOWORD(RAM),X
@UNKNOWN1:
	PLD
	RTL
