
UNKNOWN_C04452: ;$C04452
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	TDC
	ADC #$FFEE
	TCD
	LDA #$FFFF
	STA .LOWORD(CURRENT_TPT_ENTRY)
	STA .LOWORD(UNKNOWN_7E5D64)
	JSR a:.LOWORD(UNKNOWN_C043BC)
	STA $10
	CMP #$FFFF
	BEQ @UNKNOWN0
	LDX #$9889
	STX $0E
	LDA a:.LOWORD(RAM),X
	ASL
	TAX
	LDA $10
	CMP .LOWORD(UNKNOWN_30X2_TABLE_34),X
	BEQ @UNKNOWN0
	STA .LOWORD(GAME_STATE)+game_state::leader_direction
	LDX $0E
	LDA a:.LOWORD(RAM),X
	ASL
	TAX
	LDA $10
	STA .LOWORD(UNKNOWN_30X2_TABLE_34),X
	LDX $0E
	LDA a:.LOWORD(RAM),X
	JSL UNKNOWN_C0A780
@UNKNOWN0:
	LDA .LOWORD(CURRENT_TPT_ENTRY)
	PLD
	RTL
