
UNKNOWN_C07716: ;$C07716
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	TDC
	ADC #$FFEE
	TCD
	LDA .LOWORD(GAME_STATE)+game_state::current_party_members
	ASL
	TAX
	LDA .LOWORD(UNKNOWN_30X2_TABLE_13),X
	AND #$C000
	BNE @UNKNOWN0
	LDA .LOWORD(UNKNOWN_30X2_TABLE_16),X
	AND #$8000
	BNE @UNKNOWN0
	LDA .LOWORD(GAME_STATE)+176
	CMP #$0002
	BEQ @UNKNOWN0
	STZ $0E
	STZ $10
	LDY #$FFFF
	LDX #$0312
	LDA #$0108
	JSL PARSE_C3FC49_DATA
	STA .LOWORD(UNKNOWN_7E9F6B)
	ASL
	TAX
	LDA #$FFFF
	STA .LOWORD(UNKNOWN_30X2_TABLE_14),X
	LDA .LOWORD(UNKNOWN_7E9F6B)
	ASL
	TAX
	LDA #$FF00
	STA .LOWORD(SPRITE_SCREEN_Y_TABLE),X
	LDA .LOWORD(UNKNOWN_7E9F6B)
	ASL
	TAX
	LDA #$FF00
	STA .LOWORD(SPRITE_ABS_Y_TABLE),X
	LDA .LOWORD(UNKNOWN_7E9F6B)
	ASL
	TAX
	LDA #$FF00
	STA .LOWORD(SPRITE_ABS_X_TABLE),X
@UNKNOWN0:
	PLD
	RTL
