
UNKNOWN_C087CE: ;$C087CE
	PHP
	REP #PROC_FLAGS::ACCUM8
	PHD
	PHA
	TDC
	SEC
	SBC #$0006
	TCD
	PLA
	STZ a:.LOWORD($0028)
	STA $00
	STX $02
	STY $04
	SEP #PROC_FLAGS::ACCUM8
	STZ a:.LOWORD(INIDISP_MIRROR)
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	STZ a:.LOWORD(MOSAIC_MIRROR)
	LDA a:.LOWORD(INIDISP_MIRROR)
	CLC
	ADC $00
	CMP #$000F
	REP #PROC_FLAGS::ACCUM8
	BCS @UNKNOWN2
	JSR a:.LOWORD(UNKNOWN_C0879D)
	LDA $04
	BEQ @UNKNOWN1
	JSR a:.LOWORD(UNKNOWN_C087AB)
@UNKNOWN1:
	LDA $02
	JSL UNKNOWN_C0878B
	BRA @UNKNOWN0
@UNKNOWN2:
	LDA #$000F
	JSR a:.LOWORD(UNKNOWN_C0879D)
	PLD
	PLP
	RTL
