
UNKNOWN_C09EFF: ;$C09EFF
	LDX .LOWORD(UNKNOWN_7E1A44)
	BRA UNKNOWN_C09EFF_UNKNOWN0
	LDX $88
	BRA UNKNOWN_C09EFF_UNKNOWN0
UNKNOWN_C09EFF_ENTRY2:
	ASL
	TAX
UNKNOWN_C09EFF_UNKNOWN0:
	LDY #$0000
	LDA .LOWORD(SPRITE_ABS_X_FRACTION_TABLE),X
	CLC
	ADC .LOWORD(SPRITE_DELTA_X_FRACTION_TABLE),X
	LDA .LOWORD(SPRITE_ABS_X_TABLE),X
	ADC .LOWORD(SPRITE_DELTA_X_TABLE),X
	STA .LOWORD(UNKNOWN_7E2848)
	CMP .LOWORD(SPRITE_ABS_X_TABLE),X
	BEQ UNKNOWN_C09EFF_UNKNOWN1
	INY
UNKNOWN_C09EFF_UNKNOWN1:
	LDA .LOWORD(SPRITE_ABS_Y_FRACTION_TABLE),X
	CLC
	ADC .LOWORD(SPRITE_DELTA_Y_FRACTION_TABLE),X
	LDA .LOWORD(SPRITE_ABS_Y_TABLE),X
	ADC .LOWORD(SPRITE_DELTA_Y_TABLE),X
	STA .LOWORD(UNKNOWN_7E284A)
	CMP .LOWORD(SPRITE_ABS_Y_TABLE),X
	BEQ UNKNOWN_C09EFF_UNKNOWN2
	INY
UNKNOWN_C09EFF_UNKNOWN2:
	TYA
	RTL
