
UNKNOWN_C0A055: ;$C0A055
	LDX $88
	LDA .LOWORD(SPRITE_ABS_X_TABLE),X
	SEC
	SBC a:.LOWORD(BG3_X_POS)
	STA .LOWORD(SPRITE_SCREEN_X_TABLE),X
	LDA .LOWORD(SPRITE_ABS_Y_TABLE),X
	SEC
	SBC a:.LOWORD(BG3_Y_POS)
	STA .LOWORD(SPRITE_SCREEN_Y_TABLE),X
	RTS
