
UNKNOWN_C10BA1: ;$C10BA1
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	PHA
	TDC
	ADC #$FFF0
	TCD
	PLA
	TAX
	STX $0E
	LDA .LOWORD(CURRENT_FOCUS_WINDOW)
	CMP #$FFFF
	BEQ @UNKNOWN0
	LDA .LOWORD(CURRENT_FOCUS_WINDOW)
	ASL
	TAX
	LDA .LOWORD(WINDOW_EXISTENCE_TABLE),X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDY .LOWORD(WINDOW_STATS_TABLE)+19,X
	LDX $0E
	LDA .LOWORD(CURRENT_FOCUS_WINDOW)
	JSR a:.LOWORD(UNKNOWN_C10A85)
@UNKNOWN0:
	PLD
	RTS
