
UNKNOWN_EF0D73: ;$EF0D73
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA .LOWORD(UNKNOWN_7E1A42)
	ASL
	TAX
	LDA .LOWORD(UNKNOWN_30X2_TABLE_3),X
	ASL
	CLC
	ADC #$B525
	TAX
	LDA a:.LOWORD(RAM),X
	BEQ @UNKNOWN0
	DEC
	STA a:.LOWORD(RAM),X
@UNKNOWN0:
	RTL
