
UNKNOWN_EFE873: ;$EFE873
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL TEST_SRAM_SIZE
	CMP #$0000
	BEQ @GOOD_SRAM_SIZE
	LDA .LOWORD(UNKNOWN_7EB56D)
	STA a:.LOWORD(RAND_A)
	LDA .LOWORD(UNKNOWN_7EB56F)
	STA a:.LOWORD(RAND_B)
	SEP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(UNKNOWN_7EB571)
	STA a:.LOWORD(UNKNOWN_7E0002)
@GOOD_SRAM_SIZE:
	REP #PROC_FLAGS::ACCUM8
	RTL
