.SEGMENT "BANK0E"
.INCLUDE "common.asm"

BATTLE_SPRITE_82: ;$CE0000
	.INCBIN"bin/battle_sprites/82.bin"

BATTLE_SPRITE_6: ;$CE0305
	.INCBIN"bin/battle_sprites/6.bin"

BATTLE_SPRITE_31: ;$CE0601
	.INCBIN"bin/battle_sprites/31.bin"

BATTLE_SPRITE_50: ;$CE08F3
	.INCBIN"bin/battle_sprites/50.bin"

BATTLE_SPRITE_109: ;$CE0BD6
	.INCBIN"bin/battle_sprites/109.bin"

BATTLE_SPRITE_53: ;$CE0EB3
	.INCBIN"bin/battle_sprites/53.bin"

BATTLE_SPRITE_103: ;$CE118D
	.INCBIN"bin/battle_sprites/103.bin"

BATTLE_SPRITE_98: ;$CE1461
	.INCBIN"bin/battle_sprites/98.bin"

BATTLE_SPRITE_68: ;$CE170A
	.INCBIN"bin/battle_sprites/68.bin"

BATTLE_SPRITE_52: ;$CE19A9
	.INCBIN"bin/battle_sprites/52.bin"

BATTLE_SPRITE_8: ;$CE1C2E
	.INCBIN"bin/battle_sprites/8.bin"

BATTLE_SPRITE_21: ;$CE1EB1
	.INCBIN"bin/battle_sprites/21.bin"

BATTLE_SPRITE_43: ;$CE2133
	.INCBIN"bin/battle_sprites/43.bin"

BATTLE_SPRITE_7: ;$CE239C
	.INCBIN"bin/battle_sprites/7.bin"

BATTLE_SPRITE_5: ;$CE25E6
	.INCBIN"bin/battle_sprites/5.bin"

BATTLE_SPRITE_26: ;$CE2830
	.INCBIN"bin/battle_sprites/26.bin"

BATTLE_SPRITE_61: ;$CE2A5E
	.INCBIN"bin/battle_sprites/61.bin"

BATTLE_SPRITE_24: ;$CE2C7E
	.INCBIN"bin/battle_sprites/24.bin"

BATTLE_SPRITE_92: ;$CE2E9B
	.INCBIN"bin/battle_sprites/92.bin"

BATTLE_SPRITE_33: ;$CE30B7
	.INCBIN"bin/battle_sprites/33.bin"

BATTLE_SPRITE_29: ;$CE32C9
	.INCBIN"bin/battle_sprites/29.bin"

BATTLE_SPRITE_69: ;$CE34C5
	.INCBIN"bin/battle_sprites/69.bin"

BATTLE_SPRITE_49: ;$CE36B1
	.INCBIN"bin/battle_sprites/49.bin"

BATTLE_SPRITE_80: ;$CE3897
	.INCBIN"bin/battle_sprites/80.bin"

BATTLE_SPRITE_3: ;$CE3A60
	.INCBIN"bin/battle_sprites/3.bin"

BATTLE_SPRITE_45: ;$CE3C0F
	.INCBIN"bin/battle_sprites/45.bin"

BATTLE_SPRITE_20: ;$CE3DB9
	.INCBIN"bin/battle_sprites/20.bin"

BATTLE_SPRITE_91: ;$CE3F63
	.INCBIN"bin/battle_sprites/91.bin"

BATTLE_SPRITE_19: ;$CE4104
	.INCBIN"bin/battle_sprites/19.bin"

BATTLE_SPRITE_2: ;$CE429C
	.INCBIN"bin/battle_sprites/2.bin"

BATTLE_SPRITE_25: ;$CE4432
	.INCBIN"bin/battle_sprites/25.bin"

BATTLE_SPRITE_17: ;$CE45BF
	.INCBIN"bin/battle_sprites/17.bin"

BATTLE_SPRITE_76: ;$CE4745
	.INCBIN"bin/battle_sprites/76.bin"

BATTLE_SPRITE_15: ;$CE48C8
	.INCBIN"bin/battle_sprites/15.bin"

BATTLE_SPRITE_48: ;$CE4A4A
	.INCBIN"bin/battle_sprites/48.bin"

BATTLE_SPRITE_70: ;$CE4BAE
	.INCBIN"bin/battle_sprites/70.bin"

BATTLE_SPRITE_57: ;$CE4D0E
	.INCBIN"bin/battle_sprites/57.bin"

BATTLE_SPRITE_1: ;$CE4E6D
	.INCBIN"bin/battle_sprites/1.bin"

BATTLE_SPRITE_47: ;$CE4FCC
	.INCBIN"bin/battle_sprites/47.bin"

BATTLE_SPRITE_46: ;$CE5128
	.INCBIN"bin/battle_sprites/46.bin"

BATTLE_SPRITE_4: ;$CE5283
	.INCBIN"bin/battle_sprites/4.bin"

BATTLE_SPRITE_77: ;$CE53DB
	.INCBIN"bin/battle_sprites/77.bin"

BATTLE_SPRITE_65: ;$CE5527
	.INCBIN"bin/battle_sprites/65.bin"

BATTLE_SPRITE_85: ;$CE5673
	.INCBIN"bin/battle_sprites/85.bin"

BATTLE_SPRITE_44: ;$CE57BD
	.INCBIN"bin/battle_sprites/44.bin"

BATTLE_SPRITE_58: ;$CE58FD
	.INCBIN"bin/battle_sprites/58.bin"

BATTLE_SPRITE_18: ;$CE5A3B
	.INCBIN"bin/battle_sprites/18.bin"

BATTLE_SPRITE_59: ;$CE5B5F
	.INCBIN"bin/battle_sprites/59.bin"

BATTLE_SPRITE_16: ;$CE5C78
	.INCBIN"bin/battle_sprites/16.bin"

BATTLE_SPRITE_66: ;$CE5D8A
	.INCBIN"bin/battle_sprites/66.bin"

BATTLE_SPRITE_90: ;$CE5E8A
	.INCBIN"bin/battle_sprites/90.bin"

BATTLE_SPRITE_88: ;$CE5F82
	.INCBIN"bin/battle_sprites/88.bin"

BATTLE_SPRITE_0: ;$CE606D
	.INCBIN"bin/battle_sprites/0.bin"

BATTLE_SPRITE_42: ;$CE6158
	.INCBIN"bin/battle_sprites/42.bin"

BATTLE_SPRITE_89: ;$CE6230
	.INCBIN"bin/battle_sprites/89.bin"

BATTLE_SPRITES_POINTERS: ;$CE62EE
	.DWORD BATTLE_SPRITE_0
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_1
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_2
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_3
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_4
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_5
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_6
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_7
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_8
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_9
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_10
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_11
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_12
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_13
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_14
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_15
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_16
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_17
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_18
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_19
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_20
	.BYTE BATTLE_SPRITE_SIZE::_64X32
	.DWORD BATTLE_SPRITE_21
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_22
	.BYTE BATTLE_SPRITE_SIZE::_64X32
	.DWORD BATTLE_SPRITE_23
	.BYTE BATTLE_SPRITE_SIZE::_64X32
	.DWORD BATTLE_SPRITE_24
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_25
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_26
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_27
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_28
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_29
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_30
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_31
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_32
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_33
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_34
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_35
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_36
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_37
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_38
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_39
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_40
	.BYTE BATTLE_SPRITE_SIZE::_128X64
	.DWORD BATTLE_SPRITE_41
	.BYTE BATTLE_SPRITE_SIZE::_128X64
	.DWORD BATTLE_SPRITE_42
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_43
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_44
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_45
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_46
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_47
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_48
	.BYTE BATTLE_SPRITE_SIZE::_64X32
	.DWORD BATTLE_SPRITE_49
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_50
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_51
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_52
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_53
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_54
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_55
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_56
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_57
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_58
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_59
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_60
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_61
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_62
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_63
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_64
	.BYTE BATTLE_SPRITE_SIZE::_128X64
	.DWORD BATTLE_SPRITE_65
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_66
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_67
	.BYTE BATTLE_SPRITE_SIZE::_64X32
	.DWORD BATTLE_SPRITE_68
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_69
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_70
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_71
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_72
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_73
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_74
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_75
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_76
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_77
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_78
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_79
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_80
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_81
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_82
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_83
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_84
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_85
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_86
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_87
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_88
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_89
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_90
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_91
	.BYTE BATTLE_SPRITE_SIZE::_32X32
	.DWORD BATTLE_SPRITE_92
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_93
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_94
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_95
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_96
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_97
	.BYTE BATTLE_SPRITE_SIZE::_128X64
	.DWORD BATTLE_SPRITE_98
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_99
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_100
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_101
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_102
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_103
	.BYTE BATTLE_SPRITE_SIZE::_32X64
	.DWORD BATTLE_SPRITE_104
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_105
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_106
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_107
	.BYTE BATTLE_SPRITE_SIZE::_128X128
	.DWORD BATTLE_SPRITE_108
	.BYTE BATTLE_SPRITE_SIZE::_64X64
	.DWORD BATTLE_SPRITE_109
	.BYTE BATTLE_SPRITE_SIZE::_64X64


BATTLE_SPRITE_PALETTES: ;$CE6514
	.INCBIN "bin/battle_sprites/palettes/0.pal"
	.INCBIN "bin/battle_sprites/palettes/1.pal"
	.INCBIN "bin/battle_sprites/palettes/2.pal"
	.INCBIN "bin/battle_sprites/palettes/3.pal"
	.INCBIN "bin/battle_sprites/palettes/4.pal"
	.INCBIN "bin/battle_sprites/palettes/5.pal"
	.INCBIN "bin/battle_sprites/palettes/6.pal"
	.INCBIN "bin/battle_sprites/palettes/7.pal"
	.INCBIN "bin/battle_sprites/palettes/8.pal"
	.INCBIN "bin/battle_sprites/palettes/9.pal"
	.INCBIN "bin/battle_sprites/palettes/10.pal"
	.INCBIN "bin/battle_sprites/palettes/11.pal"
	.INCBIN "bin/battle_sprites/palettes/12.pal"
	.INCBIN "bin/battle_sprites/palettes/13.pal"
	.INCBIN "bin/battle_sprites/palettes/14.pal"
	.INCBIN "bin/battle_sprites/palettes/15.pal"
	.INCBIN "bin/battle_sprites/palettes/16.pal"
	.INCBIN "bin/battle_sprites/palettes/17.pal"
	.INCBIN "bin/battle_sprites/palettes/18.pal"
	.INCBIN "bin/battle_sprites/palettes/19.pal"
	.INCBIN "bin/battle_sprites/palettes/20.pal"
	.INCBIN "bin/battle_sprites/palettes/21.pal"
	.INCBIN "bin/battle_sprites/palettes/22.pal"
	.INCBIN "bin/battle_sprites/palettes/23.pal"
	.INCBIN "bin/battle_sprites/palettes/24.pal"
	.INCBIN "bin/battle_sprites/palettes/25.pal"
	.INCBIN "bin/battle_sprites/palettes/26.pal"
	.INCBIN "bin/battle_sprites/palettes/27.pal"
	.INCBIN "bin/battle_sprites/palettes/28.pal"
	.INCBIN "bin/battle_sprites/palettes/29.pal"
	.INCBIN "bin/battle_sprites/palettes/30.pal"
	.INCBIN "bin/battle_sprites/palettes/31.pal"


SWIRL_DATA: ;$CE6914
SWIRL_DATA_0:
	.INCBIN "bin/swirls/0.swirl"
SWIRL_DATA_1:
	.INCBIN "bin/swirls/1.swirl"
SWIRL_DATA_2:
	.INCBIN "bin/swirls/2.swirl"
SWIRL_DATA_3:
	.INCBIN "bin/swirls/3.swirl"
SWIRL_DATA_4:
	.INCBIN "bin/swirls/4.swirl"
SWIRL_DATA_5:
	.INCBIN "bin/swirls/5.swirl"
SWIRL_DATA_6:
	.INCBIN "bin/swirls/6.swirl"
SWIRL_DATA_7:
	.INCBIN "bin/swirls/7.swirl"
SWIRL_DATA_8:
	.INCBIN "bin/swirls/8.swirl"
SWIRL_DATA_9:
	.INCBIN "bin/swirls/9.swirl"
SWIRL_DATA_10:
	.INCBIN "bin/swirls/10.swirl"
SWIRL_DATA_11:
	.INCBIN "bin/swirls/11.swirl"
SWIRL_DATA_12:
	.INCBIN "bin/swirls/12.swirl"
SWIRL_DATA_13:
	.INCBIN "bin/swirls/13.swirl"
SWIRL_DATA_14:
	.INCBIN "bin/swirls/14.swirl"
SWIRL_DATA_15:
	.INCBIN "bin/swirls/15.swirl"
SWIRL_DATA_16:
	.INCBIN "bin/swirls/16.swirl"
SWIRL_DATA_17:
	.INCBIN "bin/swirls/17.swirl"
SWIRL_DATA_18:
	.INCBIN "bin/swirls/18.swirl"
SWIRL_DATA_19:
	.INCBIN "bin/swirls/19.swirl"
SWIRL_DATA_20:
	.INCBIN "bin/swirls/20.swirl"
SWIRL_DATA_21:
	.INCBIN "bin/swirls/21.swirl"
SWIRL_DATA_22:
	.INCBIN "bin/swirls/22.swirl"
SWIRL_DATA_23:
	.INCBIN "bin/swirls/23.swirl"
SWIRL_DATA_24:
	.INCBIN "bin/swirls/24.swirl"
SWIRL_DATA_25:
	.INCBIN "bin/swirls/25.swirl"
SWIRL_DATA_26:
	.INCBIN "bin/swirls/26.swirl"
SWIRL_DATA_27:
	.INCBIN "bin/swirls/27.swirl"
SWIRL_DATA_28:
	.INCBIN "bin/swirls/28.swirl"
SWIRL_DATA_29:
	.INCBIN "bin/swirls/29.swirl"
SWIRL_DATA_30:
	.INCBIN "bin/swirls/30.swirl"
SWIRL_DATA_31:
	.INCBIN "bin/swirls/31.swirl"
SWIRL_DATA_32:
	.INCBIN "bin/swirls/32.swirl"
SWIRL_DATA_33:
	.INCBIN "bin/swirls/33.swirl"
SWIRL_DATA_34:
	.INCBIN "bin/swirls/34.swirl"
SWIRL_DATA_35:
	.INCBIN "bin/swirls/35.swirl"
SWIRL_DATA_36:
	.INCBIN "bin/swirls/36.swirl"
SWIRL_DATA_37:
	.INCBIN "bin/swirls/37.swirl"
SWIRL_DATA_38:
	.INCBIN "bin/swirls/38.swirl"
SWIRL_DATA_39:
	.INCBIN "bin/swirls/39.swirl"
SWIRL_DATA_40:
	.INCBIN "bin/swirls/40.swirl"
SWIRL_DATA_41:
	.INCBIN "bin/swirls/41.swirl"
SWIRL_DATA_42:
	.INCBIN "bin/swirls/42.swirl"
SWIRL_DATA_43:
	.INCBIN "bin/swirls/43.swirl"
SWIRL_DATA_44:
	.INCBIN "bin/swirls/44.swirl"
SWIRL_DATA_45:
	.INCBIN "bin/swirls/45.swirl"
SWIRL_DATA_46:
	.INCBIN "bin/swirls/46.swirl"
SWIRL_DATA_47:
	.INCBIN "bin/swirls/47.swirl"
SWIRL_DATA_48:
	.INCBIN "bin/swirls/48.swirl"
SWIRL_DATA_49:
	.INCBIN "bin/swirls/49.swirl"
SWIRL_DATA_50:
	.INCBIN "bin/swirls/50.swirl"
SWIRL_DATA_51:
	.INCBIN "bin/swirls/51.swirl"
SWIRL_DATA_52:
	.INCBIN "bin/swirls/52.swirl"
SWIRL_DATA_53:
	.INCBIN "bin/swirls/53.swirl"
SWIRL_DATA_54:
	.INCBIN "bin/swirls/54.swirl"
SWIRL_DATA_55:
	.INCBIN "bin/swirls/55.swirl"
SWIRL_DATA_56:
	.INCBIN "bin/swirls/56.swirl"
SWIRL_DATA_57:
	.INCBIN "bin/swirls/57.swirl"
SWIRL_DATA_58:
	.INCBIN "bin/swirls/58.swirl"
SWIRL_DATA_59:
	.INCBIN "bin/swirls/59.swirl"
SWIRL_DATA_60:
	.INCBIN "bin/swirls/60.swirl"
SWIRL_DATA_61:
	.INCBIN "bin/swirls/61.swirl"
SWIRL_DATA_62:
	.INCBIN "bin/swirls/62.swirl"
SWIRL_DATA_63:
	.INCBIN "bin/swirls/63.swirl"
SWIRL_DATA_64:
	.INCBIN "bin/swirls/64.swirl"
SWIRL_DATA_65:
	.INCBIN "bin/swirls/65.swirl"
SWIRL_DATA_66:
	.INCBIN "bin/swirls/66.swirl"
SWIRL_DATA_67:
	.INCBIN "bin/swirls/67.swirl"
SWIRL_DATA_68:
	.INCBIN "bin/swirls/68.swirl"
SWIRL_DATA_69:
	.INCBIN "bin/swirls/69.swirl"
SWIRL_DATA_70:
	.INCBIN "bin/swirls/70.swirl"
SWIRL_DATA_71:
	.INCBIN "bin/swirls/71.swirl"
SWIRL_DATA_72:
	.INCBIN "bin/swirls/72.swirl"
SWIRL_DATA_73:
	.INCBIN "bin/swirls/73.swirl"
SWIRL_DATA_74:
	.INCBIN "bin/swirls/74.swirl"
SWIRL_DATA_75:
	.INCBIN "bin/swirls/75.swirl"
SWIRL_DATA_76:
	.INCBIN "bin/swirls/76.swirl"
SWIRL_DATA_77:
	.INCBIN "bin/swirls/77.swirl"
SWIRL_DATA_78:
	.INCBIN "bin/swirls/78.swirl"
SWIRL_DATA_79:
	.INCBIN "bin/swirls/79.swirl"
SWIRL_DATA_80:
	.INCBIN "bin/swirls/80.swirl"
SWIRL_DATA_81:
	.INCBIN "bin/swirls/81.swirl"
SWIRL_DATA_82:
	.INCBIN "bin/swirls/82.swirl"
SWIRL_DATA_83:
	.INCBIN "bin/swirls/83.swirl"
SWIRL_DATA_84:
	.INCBIN "bin/swirls/84.swirl"
SWIRL_DATA_85:
	.INCBIN "bin/swirls/85.swirl"
SWIRL_DATA_86:
	.INCBIN "bin/swirls/86.swirl"
SWIRL_DATA_87:
	.INCBIN "bin/swirls/87.swirl"
SWIRL_DATA_88:
	.INCBIN "bin/swirls/88.swirl"
SWIRL_DATA_89:
	.INCBIN "bin/swirls/89.swirl"
SWIRL_DATA_90:
	.INCBIN "bin/swirls/90.swirl"
SWIRL_DATA_91:
	.INCBIN "bin/swirls/91.swirl"
SWIRL_DATA_92:
	.INCBIN "bin/swirls/92.swirl"
SWIRL_DATA_93:
	.INCBIN "bin/swirls/93.swirl"
SWIRL_DATA_94:
	.INCBIN "bin/swirls/94.swirl"
SWIRL_DATA_95:
	.INCBIN "bin/swirls/95.swirl"
SWIRL_DATA_96:
	.INCBIN "bin/swirls/96.swirl"
SWIRL_DATA_97:
	.INCBIN "bin/swirls/97.swirl"
SWIRL_DATA_98:
	.INCBIN "bin/swirls/98.swirl"
SWIRL_DATA_99:
	.INCBIN "bin/swirls/99.swirl"
SWIRL_DATA_100:
	.INCBIN "bin/swirls/100.swirl"
SWIRL_DATA_101:
	.INCBIN "bin/swirls/101.swirl"
SWIRL_DATA_102:
	.INCBIN "bin/swirls/102.swirl"
SWIRL_DATA_103:
	.INCBIN "bin/swirls/103.swirl"
SWIRL_DATA_104:
	.INCBIN "bin/swirls/104.swirl"
SWIRL_DATA_105:
	.INCBIN "bin/swirls/105.swirl"
SWIRL_DATA_106:
	.INCBIN "bin/swirls/106.swirl"
SWIRL_DATA_107:
	.INCBIN "bin/swirls/107.swirl"
SWIRL_DATA_108:
	.INCBIN "bin/swirls/108.swirl"
SWIRL_DATA_109:
	.INCBIN "bin/swirls/109.swirl"
SWIRL_DATA_110:
	.INCBIN "bin/swirls/110.swirl"
SWIRL_DATA_111:
	.INCBIN "bin/swirls/111.swirl"
SWIRL_DATA_112:
	.INCBIN "bin/swirls/112.swirl"
SWIRL_DATA_113:
	.INCBIN "bin/swirls/113.swirl"
SWIRL_DATA_114:
	.INCBIN "bin/swirls/114.swirl"
SWIRL_DATA_115:
	.INCBIN "bin/swirls/115.swirl"
SWIRL_DATA_116:
	.INCBIN "bin/swirls/116.swirl"
SWIRL_DATA_117:
	.INCBIN "bin/swirls/117.swirl"
SWIRL_DATA_118:
	.INCBIN "bin/swirls/118.swirl"
SWIRL_DATA_119:
	.INCBIN "bin/swirls/119.swirl"
SWIRL_DATA_120:
	.INCBIN "bin/swirls/120.swirl"
SWIRL_DATA_121:
	.INCBIN "bin/swirls/121.swirl"
SWIRL_DATA_122:
	.INCBIN "bin/swirls/122.swirl"
SWIRL_DATA_123:
	.INCBIN "bin/swirls/123.swirl"
SWIRL_DATA_124:
	.INCBIN "bin/swirls/124.swirl"
SWIRL_DATA_125:
	.INCBIN "bin/swirls/125.swirl"

SWIRL_POINTER_TABLE: ;$CEDC45
	.WORD .LOWORD(SWIRL_DATA_0)
	.WORD .LOWORD(SWIRL_DATA_1)
	.WORD .LOWORD(SWIRL_DATA_2)
	.WORD .LOWORD(SWIRL_DATA_3)
	.WORD .LOWORD(SWIRL_DATA_4)
	.WORD .LOWORD(SWIRL_DATA_5)
	.WORD .LOWORD(SWIRL_DATA_6)
	.WORD .LOWORD(SWIRL_DATA_7)
	.WORD .LOWORD(SWIRL_DATA_8)
	.WORD .LOWORD(SWIRL_DATA_9)
	.WORD .LOWORD(SWIRL_DATA_10)
	.WORD .LOWORD(SWIRL_DATA_11)
	.WORD .LOWORD(SWIRL_DATA_12)
	.WORD .LOWORD(SWIRL_DATA_13)
	.WORD .LOWORD(SWIRL_DATA_14)
	.WORD .LOWORD(SWIRL_DATA_15)
	.WORD .LOWORD(SWIRL_DATA_16)
	.WORD .LOWORD(SWIRL_DATA_17)
	.WORD .LOWORD(SWIRL_DATA_18)
	.WORD .LOWORD(SWIRL_DATA_19)
	.WORD .LOWORD(SWIRL_DATA_20)
	.WORD .LOWORD(SWIRL_DATA_21)
	.WORD .LOWORD(SWIRL_DATA_22)
	.WORD .LOWORD(SWIRL_DATA_23)
	.WORD .LOWORD(SWIRL_DATA_24)
	.WORD .LOWORD(SWIRL_DATA_25)
	.WORD .LOWORD(SWIRL_DATA_26)
	.WORD .LOWORD(SWIRL_DATA_27)
	.WORD .LOWORD(SWIRL_DATA_28)
	.WORD .LOWORD(SWIRL_DATA_29)
	.WORD .LOWORD(SWIRL_DATA_30)
	.WORD .LOWORD(SWIRL_DATA_31)
	.WORD .LOWORD(SWIRL_DATA_32)
	.WORD .LOWORD(SWIRL_DATA_33)
	.WORD .LOWORD(SWIRL_DATA_34)
	.WORD .LOWORD(SWIRL_DATA_35)
	.WORD .LOWORD(SWIRL_DATA_36)
	.WORD .LOWORD(SWIRL_DATA_37)
	.WORD .LOWORD(SWIRL_DATA_38)
	.WORD .LOWORD(SWIRL_DATA_39)
	.WORD .LOWORD(SWIRL_DATA_40)
	.WORD .LOWORD(SWIRL_DATA_41)
	.WORD .LOWORD(SWIRL_DATA_42)
	.WORD .LOWORD(SWIRL_DATA_43)
	.WORD .LOWORD(SWIRL_DATA_44)
	.WORD .LOWORD(SWIRL_DATA_45)
	.WORD .LOWORD(SWIRL_DATA_46)
	.WORD .LOWORD(SWIRL_DATA_47)
	.WORD .LOWORD(SWIRL_DATA_48)
	.WORD .LOWORD(SWIRL_DATA_49)
	.WORD .LOWORD(SWIRL_DATA_50)
	.WORD .LOWORD(SWIRL_DATA_51)
	.WORD .LOWORD(SWIRL_DATA_52)
	.WORD .LOWORD(SWIRL_DATA_53)
	.WORD .LOWORD(SWIRL_DATA_54)
	.WORD .LOWORD(SWIRL_DATA_55)
	.WORD .LOWORD(SWIRL_DATA_56)
	.WORD .LOWORD(SWIRL_DATA_57)
	.WORD .LOWORD(SWIRL_DATA_58)
	.WORD .LOWORD(SWIRL_DATA_59)
	.WORD .LOWORD(SWIRL_DATA_60)
	.WORD .LOWORD(SWIRL_DATA_61)
	.WORD .LOWORD(SWIRL_DATA_62)
	.WORD .LOWORD(SWIRL_DATA_63)
	.WORD .LOWORD(SWIRL_DATA_64)
	.WORD .LOWORD(SWIRL_DATA_65)
	.WORD .LOWORD(SWIRL_DATA_66)
	.WORD .LOWORD(SWIRL_DATA_67)
	.WORD .LOWORD(SWIRL_DATA_68)
	.WORD .LOWORD(SWIRL_DATA_69)
	.WORD .LOWORD(SWIRL_DATA_70)
	.WORD .LOWORD(SWIRL_DATA_71)
	.WORD .LOWORD(SWIRL_DATA_72)
	.WORD .LOWORD(SWIRL_DATA_73)
	.WORD .LOWORD(SWIRL_DATA_74)
	.WORD .LOWORD(SWIRL_DATA_75)
	.WORD .LOWORD(SWIRL_DATA_76)
	.WORD .LOWORD(SWIRL_DATA_77)
	.WORD .LOWORD(SWIRL_DATA_78)
	.WORD .LOWORD(SWIRL_DATA_79)
	.WORD .LOWORD(SWIRL_DATA_80)
	.WORD .LOWORD(SWIRL_DATA_81)
	.WORD .LOWORD(SWIRL_DATA_82)
	.WORD .LOWORD(SWIRL_DATA_83)
	.WORD .LOWORD(SWIRL_DATA_84)
	.WORD .LOWORD(SWIRL_DATA_85)
	.WORD .LOWORD(SWIRL_DATA_86)
	.WORD .LOWORD(SWIRL_DATA_87)
	.WORD .LOWORD(SWIRL_DATA_88)
	.WORD .LOWORD(SWIRL_DATA_89)
	.WORD .LOWORD(SWIRL_DATA_90)
	.WORD .LOWORD(SWIRL_DATA_91)
	.WORD .LOWORD(SWIRL_DATA_92)
	.WORD .LOWORD(SWIRL_DATA_93)
	.WORD .LOWORD(SWIRL_DATA_94)
	.WORD .LOWORD(SWIRL_DATA_95)
	.WORD .LOWORD(SWIRL_DATA_96)
	.WORD .LOWORD(SWIRL_DATA_97)
	.WORD .LOWORD(SWIRL_DATA_98)
	.WORD .LOWORD(SWIRL_DATA_99)
	.WORD .LOWORD(SWIRL_DATA_100)
	.WORD .LOWORD(SWIRL_DATA_101)
	.WORD .LOWORD(SWIRL_DATA_102)
	.WORD .LOWORD(SWIRL_DATA_103)
	.WORD .LOWORD(SWIRL_DATA_104)
	.WORD .LOWORD(SWIRL_DATA_105)
	.WORD .LOWORD(SWIRL_DATA_106)
	.WORD .LOWORD(SWIRL_DATA_107)
	.WORD .LOWORD(SWIRL_DATA_108)
	.WORD .LOWORD(SWIRL_DATA_109)
	.WORD .LOWORD(SWIRL_DATA_110)
	.WORD .LOWORD(SWIRL_DATA_111)
	.WORD .LOWORD(SWIRL_DATA_112)
	.WORD .LOWORD(SWIRL_DATA_113)
	.WORD .LOWORD(SWIRL_DATA_114)
	.WORD .LOWORD(SWIRL_DATA_115)
	.WORD .LOWORD(SWIRL_DATA_116)
	.WORD .LOWORD(SWIRL_DATA_117)
	.WORD .LOWORD(SWIRL_DATA_118)
	.WORD .LOWORD(SWIRL_DATA_119)
	.WORD .LOWORD(SWIRL_DATA_120)
	.WORD .LOWORD(SWIRL_DATA_121)
	.WORD .LOWORD(SWIRL_DATA_122)
	.WORD .LOWORD(SWIRL_DATA_123)
	.WORD .LOWORD(SWIRL_DATA_124)
	.WORD .LOWORD(SWIRL_DATA_125)

SWIRL_PRIMARY_TABLE: ;$CEDD41
	.INCBIN "bin/unknowns/CEDD41.bin"

SOUND_STONE_GFX: ;$CEDD5D
	.INCBIN "bin/unknowns/CEDD5D.bin"

SOUND_STONE_PALETTE: ;$CEF806
	.INCBIN "bin/unknowns/CEF806.bin"

AUDIO_PACK_102: ;$CEF8C6
	.INCBIN "bin/audiopacks/102.bin"
