.SEGMENT "BANK0A"
.ORG $CA0000

BATTLEBG_PRIMARY_DATA_GROUP: ;$CA0000
	.INCBIN "bin/unknowns/CA0000.bin"

BATTLEBG_GFX_POINTERS: ;$CAD7A1
	.INCBIN "bin/unknowns/CAD7A1.bin"

BATTLEBG_ARR_POINTERS: ;$CAD93D
	.INCBIN "bin/unknowns/CAD93D.bin"

BATTLEBG_PALETTE_POINTERS: ;$CADAD9
	.INCBIN "bin/unknowns/CADAD9.bin"

BG_DATA_TABLE: ;$CADCA1
	.INCBIN "bin/unknowns/CADCA1.bin"

BG_SCROLLING_TABLE: ;$CAF258
	.INCBIN "bin/unknowns/CAF258.bin"

BG_DISTORTION_TABLE: ;$CAF708
	.INCBIN "bin/unknowns/CAF708.bin"
