.SEGMENT "BANK18"
.ORG $D80000

MAP_DATA_TILE_COLLISION_ARRANGEMENT_TABLE: ;$D80000
	.INCBIN "bin/unknowns/D80000.bin"

MAP_DATA_TILE_COLLISION_ARRANGEMENT_POINTER_TABLE: ;$D88F50
	.INCBIN "bin/unknowns/D88F50.bin"

ANTI_PIRACY_NOTICE_ARRANGEMENT: ;$D8F05E
	.INCBIN "bin/unknowns/D8F05E.bin"

ANTI_PIRACY_NOTICE_GRAPHICS: ;$D8F20D
	.INCBIN "bin/unknowns/D8F20D.bin"

WARNING_PALETTE: ;$D8F3BE
	.INCBIN "bin/unknowns/D8F3BE.bin"

FAULTY_GAME_PAK_ARRANGEMENT: ;$D8F3C6
	.INCBIN "bin/unknowns/D8F3C6.bin"

FAULTY_GAME_PAK_GRAPHICS: ;$D8F5C4
	.INCBIN "bin/unknowns/D8F5C4.bin"

AUDIO_PACK_61: ;$D8F6B7
	.INCBIN "bin/audiopacks/61.bin"
