
CHANGE_EQUIPPED_WEAPON: ;$C4577D
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STX $02
	TAY
	STY $0E
	TYA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT)+char_struct::equipment+EQUIPMENT_SLOT::WEAPON
	TAX
	LDA RAM,X
	AND #$00FF
	STA $04
	LDA $02
	SEP #PROC_FLAGS::ACCUM8
	STA RAM,X
	LDY $0E
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSL RECALC_CHARACTER_POSTMATH_OFFENSE
	LDY $0E
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSL RECALC_CHARACTER_POSTMATH_GUTS
	LDY $0E
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSL RECALC_CHARACTER_MISS_RATE
	REP #PROC_FLAGS::ACCUM8
	LDA $04
	PLD
	RTL
