
DECREASE_WALLET_BALANCE: ;$C22272
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 14
	MOVE_INT $1C, $06
	LDY #.LOWORD(GAME_STATE)+game_state::money_carried
	MOVE_INT $06, $0A
	MOVE_INT_YPTRSRC RAM, $06
	SEC
	SUB_INT_ASSIGN $06, $0A
	MOVE_INT_CONSTANT NULL, $0A
	CLC
	LDA $0A
	SBC $06
	LDA $0C
	SBC $08
	BRANCHLTEQS @UNKNOWN2
	LDA #$0001
	BRA @UNKNOWN3
@UNKNOWN2:
	MOVE_INT_YPTRDEST $06, RAM
	LDA #$0000
@UNKNOWN3:
	PLD
	RTL
