
EQUIP_ITEM: ;$C19066
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STX $10
	STA $0E
	TXA
	DEC
	STA $02
	LDA $0E
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT)+char_struct::items
	CLC
	ADC $02
	TAX
	LDA a:.LOWORD(RAM),X
	AND #$00FF
	LDY #.SIZEOF(item)
	JSL MULT168
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #EQUIPMENT_SLOT::ALL<<2
	BEQ @UNKNOWN0
	CMP #EQUIPMENT_SLOT::BODY<<2
	BEQ @UNKNOWN1
	CMP #EQUIPMENT_SLOT::ARMS<<2
	BEQ @UNKNOWN2
	CMP #EQUIPMENT_SLOT::OTHER<<2
	BEQ @UNKNOWN3
	BRA @UNKNOWN4
@UNKNOWN0:
	LDX $10
	LDA $0E
	JSL CHANGE_EQUIPPED_WEAPON
	BRA @UNKNOWN5
@UNKNOWN1:
	LDX $10
	LDA $0E
	JSL CHANGE_EQUIPPED_BODY
	BRA @UNKNOWN5
@UNKNOWN2:
	LDX $10
	LDA $0E
	JSL CHANGE_EQUIPPED_ARMS
	BRA @UNKNOWN5
@UNKNOWN3:
	LDX $10
	LDA $0E
	JSL CHANGE_EQUIPPED_OTHER
	BRA @UNKNOWN5
@UNKNOWN4:
	LDA #$0000
@UNKNOWN5:
	PLD
	RTS
