
FIND_CONDIMENT: ;$C1DB33
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 20
	AND #$00FF
	OPTIMIZED_MULT $04, .SIZEOF(item)
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #$003C
	CMP #$0020
	BNE @UNKNOWN3
	LDX CURRENT_ATTACKER
	LDA __BSS_START__,X
	TAY
	DEY
	STY $12
	LDX #$0000
	STX $10
	BRA @UNKNOWN2
@UNKNOWN0:
	AND #$00FF
	STA $0E
	OPTIMIZED_MULT $04, .SIZEOF(item)
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #$003C
	CMP #$0028
	BNE @UNKNOWN1
	LDA $0E
	BRA @UNKNOWN4
@UNKNOWN1:
	LDX $10
	INX
	STX $10
@UNKNOWN2:
	CPX #$000E
	BCS @UNKNOWN3
	STX $02
	LDY $12
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(CHAR_STRUCT)+char_struct::items
	CLC
	ADC $02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BNE @UNKNOWN0
@UNKNOWN3:
	LDA #$0000
@UNKNOWN4:
	PLD
	RTL
