
GET_ITEM_TYPE: ;$C19EE6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
.IF .DEFINED(JPN)
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
.ENDIF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #$0030
	BEQ @UNKNOWN0
	CMP #$0010
	BEQ @UNKNOWN1
	CMP #$0020
	BEQ @UNKNOWN2
	CMP #$0030
	BEQ @UNKNOWN3
	BRA @UNKNOWN4
@UNKNOWN0:
	LDA #$0001
	BRA @UNKNOWN5
@UNKNOWN1:
	LDA #$0002
	BRA @UNKNOWN5
@UNKNOWN2:
	LDA #$0003
	BRA @UNKNOWN5
@UNKNOWN3:
	LDA #$0004
	BRA @UNKNOWN5
@UNKNOWN4:
	LDA #$0000
@UNKNOWN5:
.IF .DEFINED(JPN)
	PLD
.ENDIF
	RTS
