
GIVE_ITEM_TO_CHARACTER: ;$C18BC6
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	STX $04
	CMP #$00FF
	BNE @UNKNOWN3
	LDA #$0000
	STA $02
	STA $10
	BRA @UNKNOWN2
@UNKNOWN0:
	LDA $10
	STA $02
	CLC
	ADC #.LOWORD(GAME_STATE)
	CLC
	ADC #game_state::party_members
	TAY
	STY $0E
	LDX $04
	LDA __BSS_START__,Y
	AND #$00FF
	JSR GIVE_ITEM_TO_SPECIFIC_CHARACTER
	CMP #$0000
	BEQ @UNKNOWN1
	LDY $0E
	LDA __BSS_START__,Y
	AND #$00FF
	BRA @UNKNOWN4
@UNKNOWN1:
	INC $02
	LDA $02
	STA $10
@UNKNOWN2:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	PHA
	LDA $02
	PLY
	STY $02
	CMP $02
	BCC @UNKNOWN0
	LDA #$0000
	BRA @UNKNOWN4
@UNKNOWN3:
	LDX $04
	JSR GIVE_ITEM_TO_SPECIFIC_CHARACTER
@UNKNOWN4:
	PLD
	RTL
