
LEARN_SPECIAL_PSI: ;$C227C8
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	CMP #$0001
	BEQ @LEARN_TELEPORT_ALPHA
	CMP #$0002
	BEQ @LEARN_TELEPORT_BETA
	CMP #$0003
	BEQ @LEARN_STARSTORM_ALPHA
	CMP #$0004
	BEQ @LEARN_STARSTORM_BETA
	BRA @RETURN
@LEARN_TELEPORT_ALPHA:
	LDX #.LOWORD(GAME_STATE) + game_state::party_psi
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	ORA #PARTY_PSI_FLAGS::TELEPORT_ALPHA
	STA __BSS_START__,X
	BRA @RETURN
@LEARN_TELEPORT_BETA:
	LDX #.LOWORD(GAME_STATE) + game_state::party_psi
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	ORA #PARTY_PSI_FLAGS::TELEPORT_BETA
	STA __BSS_START__,X
	BRA @RETURN
@LEARN_STARSTORM_ALPHA:
	LDX #.LOWORD(GAME_STATE) + game_state::party_psi
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	ORA #PARTY_PSI_FLAGS::STARSTORM_ALPHA
	STA __BSS_START__,X
	BRA @RETURN
@LEARN_STARSTORM_BETA:
	LDX #.LOWORD(GAME_STATE) + game_state::party_psi
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	ORA #PARTY_PSI_FLAGS::STARSTORM_BETA
	STA __BSS_START__,X
@RETURN:
	REP #PROC_FLAGS::ACCUM8
	RTL
