
LEVEL_UP_CHAR:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL07
	TAX
	TXY
	DEY
	STY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL05
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::level
	STA @VIRTUAL02
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL04
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL03
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL04
	INC
	LDX @VIRTUAL02
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @UNKNOWN0
	LDA #1
	JSR ENABLE_BLINKING_TRIANGLE
	LDX #5
	LDA @LOCAL05
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	JSR UNKNOWN_C1ACA1
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STORE_INT832 @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR UNKNOWN_C1AD0A
	DISPLAY_TEXT_PTR MSG_BTL_LEVEL_UP
	LDA #2
	JSR ENABLE_BLINKING_TRIANGLE
@UNKNOWN0:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_offense
	TAX
	STX @LOCAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	LDX @LOCAL02
	LDA __BSS_START__,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR UNKNOWN_C1D08B
	STA @VIRTUAL02
	CLC
	SBC #0
	BRANCHLTEQS @UNKNOWN4
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDX @LOCAL02
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_OFFENSE
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @UNKNOWN4
	MOVE_INT1632S @VIRTUAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR UNKNOWN_C1AD0A
	DISPLAY_TEXT_PTR MSG_BTL_LV_OFFENSE_UP
@UNKNOWN4:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_defense
	TAX
	STX @LOCAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	INX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	LDX @LOCAL02
	LDA __BSS_START__,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR UNKNOWN_C1D08B
	STA @VIRTUAL02
	CLC
	SBC #0
	BRANCHLTEQS @UNKNOWN8
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDX @LOCAL02
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_DEFENSE
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @UNKNOWN8
	MOVE_INT1632S @VIRTUAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR UNKNOWN_C1AD0A
	DISPLAY_TEXT_PTR MSG_BTL_LV_DEFENSE_UP
@UNKNOWN8:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_speed
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	INX
	INX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR UNKNOWN_C1D08B
	TAX
	STX @LOCAL02
	TXA
	CLC
	SBC #0
	BRANCHLTEQS @UNKNOWN12
	SEP #PROC_FLAGS::INDEX8
	STX @VIRTUAL00
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_SPEED
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @UNKNOWN12
	LDX @LOCAL02
	TXA
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR UNKNOWN_C1AD0A
	DISPLAY_TEXT_PTR MSG_BTL_LV_SPEED_UP
@UNKNOWN12:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_guts
	TAX
	STX @LOCAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	INX
	INX
	INX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	LDX @LOCAL02
	LDA __BSS_START__,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR UNKNOWN_C1D08B
	STA @VIRTUAL02
	CLC
	SBC #0
	BRANCHLTEQS @UNKNOWN16
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDX @LOCAL02
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_GUTS
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @UNKNOWN16
	MOVE_INT1632S @VIRTUAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR UNKNOWN_C1AD0A
	DISPLAY_TEXT_PTR MSG_BTL_LV_GUTS_UP
@UNKNOWN16:
	LDA #10
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @UNKNOWN19
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_vitality,X
	AND #$00FF
	DEC
	DEC
	OPTIMIZED_MULT @VIRTUAL04, 10
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	INX
	INX
	INX
	INX
	LDA f:STATS_GROWTH_VARS,X
	AND #$00FF
	TAY
	LDA @LOCAL03
	STA @VIRTUAL04
	JSL MULT16
	SEC
	SBC @VIRTUAL02
	LDY #10
	JSL DIVISION16
	BRA @UNKNOWN20
@UNKNOWN19:
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	INX
	INX
	INX
	INX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA PARTY_CHARACTERS+char_struct::base_vitality,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR UNKNOWN_C1D08B
@UNKNOWN20:
	STA @VIRTUAL02
	CLC
	SBC #0
	BRANCHLTEQS @UNKNOWN24
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_vitality
	TAX
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_VITALITY
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @UNKNOWN24
	MOVE_INT1632S @VIRTUAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR UNKNOWN_C1AD0A
	DISPLAY_TEXT_PTR MSG_BTL_LV_VITA_UP
@UNKNOWN24:
	LDA #10
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @UNKNOWN27
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_iq,X
	AND #$00FF
	DEC
	DEC
	OPTIMIZED_MULT @VIRTUAL04, 10
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	CLC
	ADC #5
	TAX
	LDA f:STATS_GROWTH_VARS,X
	AND #$00FF
	TAY
	LDA @LOCAL03
	STA @VIRTUAL04
	JSL MULT16
	SEC
	SBC @VIRTUAL02
	LDY #10
	JSL DIVISION16
	BRA @UNKNOWN28
@UNKNOWN27:
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	CLC
	ADC #5
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA PARTY_CHARACTERS+char_struct::base_iq,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR UNKNOWN_C1D08B
@UNKNOWN28:
	STA @VIRTUAL02
	CLC
	SBC #0
	BRANCHLTEQS @UNKNOWN32
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_iq
	TAX
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_IQ
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @UNKNOWN32
	MOVE_INT1632S @VIRTUAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR UNKNOWN_C1AD0A
	DISPLAY_TEXT_PTR MSG_BTL_LV_IQ_UP
@UNKNOWN32:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_luck
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	CLC
	ADC #6
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR UNKNOWN_C1D08B
	TAX
	STX @LOCAL02
	TXA
	CLC
	SBC #0
	BRANCHLTEQS @UNKNOWN36
	SEP #PROC_FLAGS::INDEX8
	STX @VIRTUAL00
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_LUCK
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @UNKNOWN36
	LDX @LOCAL02
	TXA
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR UNKNOWN_C1AD0A
	DISPLAY_TEXT_PTR MSG_BTL_LV_LUCK_UP
@UNKNOWN36:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::vitality,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 15
	SEC
	SBC PARTY_CHARACTERS+char_struct::max_hp,X
	STA @LOCAL02
	CLC
	SBC #1
	BRANCHLTEQS @UNKNOWN39
	LDA @LOCAL02
	TAX
	BRA @UNKNOWN40
@UNKNOWN39:
	LDA #2
	JSL RAND_MOD
	TAX
	INX
@UNKNOWN40:
	STX @VIRTUAL02
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL05
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::max_hp
	TAX
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL05
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::current_hp_target
	TAX
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL07
	BEQ @UNKNOWN42
	MOVE_INT1632S @VIRTUAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR UNKNOWN_C1AD0A
	DISPLAY_TEXT_PTR MSG_BTL_LV_MAXHP_UP
@UNKNOWN42:
	LDY @LOCAL06
	CPY #2
	BEQL @UNKNOWN66
	CPY #0
	BNE @UNKNOWN44
	LDA #EVENT_FLAG::FLG_WIN_OSCAR
	JSL GET_EVENT_FLAG
	CMP #0
	BEQ @UNKNOWN44
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::iq,X
	AND #$00FF
	ASL
	BRA @UNKNOWN45
@UNKNOWN44:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::iq,X
	AND #$00FF
@UNKNOWN45:
	STA @LOCAL01
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA @LOCAL01
	OPTIMIZED_MULT @VIRTUAL04, 5
	SEC
	SBC PARTY_CHARACTERS+char_struct::max_pp,X
	STA @LOCAL02
	CLC
	SBC #1
	BRANCHLTEQS @UNKNOWN48
	LDA @LOCAL02
	TAX
	BRA @UNKNOWN49
@UNKNOWN48:
	LDA #2
	JSL RAND_MOD
	TAX
@UNKNOWN49:
	TXA
	STA @LOCAL02
	BEQ @UNKNOWN51
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @VIRTUAL02
	STA @LOCAL05
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::max_pp
	TAX
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL05
	STA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::current_pp_target
	TAX
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL07
	BEQ @UNKNOWN51
	MOVE_INT1632S @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR UNKNOWN_C1AD0A
	DISPLAY_TEXT_PTR MSG_BTL_LV_MAXPP_UP
@UNKNOWN51:
	LDA @LOCAL07
	BEQL @UNKNOWN66
	LDA @LOCAL03
	STA @VIRTUAL04
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDY @LOCAL06
	TYA
	BEQ @UNKNOWN54
	CMP #1
	BEQ @UNKNOWN58
	CMP #3
	BEQL @UNKNOWN62
	JMP @UNKNOWN66
@UNKNOWN54:
	LDX #1
	STX @LOCAL06
	BRA @UNKNOWN57
@UNKNOWN55:
	LDA @LOCAL03
	CLC
	ADC #6
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP @VIRTUAL02
	BNE @UNKNOWN56
	TXA
	SEP #PROC_FLAGS::ACCUM8
	JSR UNKNOWN_C1ACF8
	.A16
	DISPLAY_TEXT_PTR MSG_BTL_LEARN_PSI
@UNKNOWN56:
	.A8
	LDX @LOCAL06
	INX
	STX @LOCAL06
@UNKNOWN57:
	.A16
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL06
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 15
	STA @LOCAL03
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BNE @UNKNOWN55
	JMP @UNKNOWN66
@UNKNOWN58:
	LDX #1
	STX @LOCAL06
	BRA @UNKNOWN61
@UNKNOWN59:
	LDA @LOCAL03
	CLC
	ADC #7
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP @VIRTUAL02
	BNE @UNKNOWN60
	TXA
	SEP #PROC_FLAGS::ACCUM8
	JSR UNKNOWN_C1ACF8
	.A16
	DISPLAY_TEXT_PTR MSG_BTL_LEARN_PSI
@UNKNOWN60:
	.A8
	LDX @LOCAL06
	INX
	STX @LOCAL06
@UNKNOWN61:
	.A16
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL06
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 15
	STA @LOCAL03
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BNE @UNKNOWN59
	BRA @UNKNOWN66
@UNKNOWN62:
	LDX #1
	STX @LOCAL06
	BRA @UNKNOWN65
@UNKNOWN63:
	LDA @LOCAL03
	CLC
	ADC #8
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP @VIRTUAL02
	BNE @UNKNOWN64
	TXA
	SEP #PROC_FLAGS::ACCUM8
	JSR UNKNOWN_C1ACF8
	.A16
	DISPLAY_TEXT_PTR MSG_BTL_LEARN_PSI
@UNKNOWN64:
	.A8
	LDX @LOCAL06
	INX
	STX @LOCAL06
@UNKNOWN65:
	.A16
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL06
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 15
	STA @LOCAL03
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BNE @UNKNOWN63
@UNKNOWN66:
	LDA @LOCAL07
	BEQ @UNKNOWN67
	JSR CLEAR_BLINKING_PROMPT
@UNKNOWN67:
	END_C_FUNCTION
