
REMOVE_CHAR_FROM_PARTY: ;$C229BB
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 18
	TAX
	STX $10
	LDA #$0000
	STA $0E
	BRA @UNKNOWN7
@UNKNOWN0:
	LDX $10
	STX $02
	LDA $0E
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
	AND #$00FF
	CMP $02
	BNE @UNKNOWN6
	BRA @UNKNOWN2
@UNKNOWN1:
	LDA $0E
	CLC
	ADC #.LOWORD(GAME_STATE)
	PHA
	LDA $0E
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE + game_state::party_members + 1,X
	PLX
	STA a:game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	INC
	STA $0E
@UNKNOWN2:
	LDA $0E
	STA $02
	LDA #$0006
	CLC
	SBC $02
	BRANCHGTS @UNKNOWN1
	LDA $0E
	DEC
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:game_state::party_members,X
	LDX $10
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL UNKNOWN_C03903
	LDX $10
	CPX #$0004
	BGT @UNKNOWN9
	JSL UNKNOWN_C216DB
	JSL UNKNOWN_C3EBCA
	BRA @UNKNOWN9
@UNKNOWN6:
	LDA $0E
	INC
	STA $0E
@UNKNOWN7:
	STA $02
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	CLC
	SBC $02
	JUMPGTS @UNKNOWN0
@UNKNOWN9:
	PLD
	RTL
