
REMOVE_CHAR_FROM_PARTY: ;$C229BB
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	TAY
	STY $0E
	LDX #$0000
	BRA @UNKNOWN7
@UNKNOWN0:
	STY $02
	LDA GAME_STATE + game_state::party_members,X
	AND #$00FF
	CMP $02
	BNE @UNKNOWN6
	BRA @UNKNOWN2
@UNKNOWN1:
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE + game_state::party_members + 1,X
	STA GAME_STATE + game_state::party_members,X
	INX
@UNKNOWN2:
	STX $02
	REP #PROC_FLAGS::ACCUM8
	LDA #$0006
	CLC
	SBC $02
	BRANCHGTS @UNKNOWN1
	DEX
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE + game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSL UNKNOWN_C03903
	LDY $0E
	CPY #$0004
	BGT @UNKNOWN9
	JSL UNKNOWN_C216DB
	JSL UNKNOWN_C3EBCA
	BRA @UNKNOWN9
@UNKNOWN6:
	INX
@UNKNOWN7:
	STX $02
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	CLC
	SBC $02
	BRANCHGTS @UNKNOWN0
@UNKNOWN9:
	PLD
	RTL
