
ADD_CHAR_TO_PARTY: ;$C228F8
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE 16
	STA $04
	LDA #$0000
	STA $02
	STA $0E
	JMP a:.LOWORD(@UNKNOWN14)
@UNKNOWN0:
	LDX $02
	SEP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(GAME_STATE) + game_state::party_members,X
	STA $00
	REP #PROC_FLAGS::ACCUM8
	LDA $00
	AND #$00FF
	CMP $04
	BNE @UNKNOWN1
	JMP a:.LOWORD(@UNKNOWN16)
@UNKNOWN1:
	CMP $04
	BEQ @UNKNOWN2
	BCS @UNKNOWN3
@UNKNOWN2:
	LDA $00
	AND #$00FF
	BNE @UNKNOWN13
@UNKNOWN3:
	LDY $02
	BRA @UNKNOWN7
@UNKNOWN4:
	STY $02
	LDA #$0006
	CLC
	SBC $02
	BVC @UNKNOWN5
	BPL @UNKNOWN16
	BRA @UNKNOWN6
@UNKNOWN5:
	BMI @UNKNOWN16
@UNKNOWN6:
	INY
@UNKNOWN7:
	LDA .LOWORD(GAME_STATE) + game_state::party_members,Y
	AND #$00FF
	BNE @UNKNOWN4
	BRA @UNKNOWN9
@UNKNOWN8:
	TYX
	DEX
	SEP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(GAME_STATE) + game_state::party_members,X
	STA .LOWORD(GAME_STATE) + game_state::party_members,Y
	TXY
@UNKNOWN9:
	REP #PROC_FLAGS::ACCUM8
	LDA $0E
	STA $02
	TYA
	CLC
	SBC $02
	BVS @UNKNOWN10
	BPL @UNKNOWN8
	BRA @UNKNOWN11
@UNKNOWN10:
	BMI @UNKNOWN8
@UNKNOWN11:
	LDA $04
	SEP #PROC_FLAGS::ACCUM8
	LDX $02
	STA .LOWORD(GAME_STATE) + game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA $04
	JSL UNKNOWN_C0369B
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA a:.LOWORD(RAM),X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA a:.LOWORD(RAM),X
	LDA $04
	CMP #$0004
	BEQ @UNKNOWN12
	BCS @UNKNOWN16
@UNKNOWN12:
	JSL UNKNOWN_C216DB
	JSL UNKNOWN_C3EBCA
	BRA @UNKNOWN16
@UNKNOWN13:
	INC $02
	LDA $02
	STA $0E
@UNKNOWN14:
	LDA #$0006
	CLC
	SBC $02
	BVS @UNKNOWN15
	BMI @UNKNOWN16
	JMP a:.LOWORD(@UNKNOWN0)
@UNKNOWN15:
	BPL @UNKNOWN16
	JMP a:.LOWORD(@UNKNOWN0)
@UNKNOWN16:
	PLD
	RTL
