
TRY_ENDING_FAST_HPPP_ROLLING:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	JSL TEST_IF_HPPP_ROLLING_DONE
	CMP #0
	BEQ @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	STZ FASTEST_HPPP_METER_SPEED
@UNKNOWN0:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
