
BTLACT_BASH: ;$C2859F
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA #$0000
	JSR MISS_CALC
	CMP #$0000
	BNE @UNKNOWN1
	JSR SMAAAASH
	CMP #$0000
	BNE @UNKNOWN1
	JSR DETERMINE_DODGE
	CMP #$0000
	BNE @UNKNOWN0
	JSR BTLACT_LEVEL_2_ATK
	JSR HEAL_STRANGENESS
	BRA @UNKNOWN1
@UNKNOWN0:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TATAKU_YOKETA
@UNKNOWN1:
	PLD
	RTL
