
BTLACT_CLUMSYDEATH: ;$C29298
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA f:PSI_TELEPORT_DEST_TABLE+.SIZEOF(psi_teleport_destination) * 13 + psi_teleport_destination::event_flag
	JSL GET_EVENT_FLAG
	CMP #$0000
	BEQ @UNKNOWN0
	DISPLAY_BATTLE_TEXT_PTR TEXT_BATTLE_RUNAWAY_FIVE_DEFEAT_CLUMSYROBOT
	SEP #PROC_FLAGS::ACCUM8
	LDA #TELEPORT_STYLE::INSTANT
	STA $0E
	LDA #$000F
	JSL SET_TELEPORT_STATE
	.A16
	BRA @UNKNOWN1
@UNKNOWN0:
	DISPLAY_BATTLE_TEXT_PTR TEXT_BATTLE_BLACK_SMOKE_POURED_OUT
	SEP #PROC_FLAGS::ACCUM8
	LDA #TELEPORT_STYLE::INSTANT
	STA $0E
	LDA #$000D
	JSL SET_TELEPORT_STATE
	.A16
	LDA #$0001
	STA .LOWORD(UNKNOWN_7EAA0E)
@UNKNOWN1:
	PLD
	RTL
