
BTLACT_CRYING:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @UNKNOWN1
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::flash_resist,X
	JSR SUCCESS_255
	.A16
	CMP #0
	BEQ @UNKNOWN0
	LDY #STATUS_2::CRYING
	;Status ID is same as status group
	TYX
	LDA CURRENT_TARGET
	JSR INFLICT_STATUS_BATTLE
	.A16
	CMP #0
	BEQ @UNKNOWN0
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NAMIDA_ON
	BRA @UNKNOWN1
@UNKNOWN0:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@UNKNOWN1:
	END_C_FUNCTION
