
BTLACT_CUTGUTS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @UNKNOWN1
	LDA CURRENT_TARGET
	CLC
	ADC #battler::guts
	TAX
	LDA __BSS_START__,X
	TAY
	OPTIMIZED_MULT $04, 3
	LSR
	LSR
	STA __BSS_START__,X
	LDA CURRENT_TARGET
	CLC
	ADC #battler::guts
	TAX
	STX @LOCAL03
	LDX CURRENT_TARGET
	LDA a:battler::base_guts,X
	AND #$00FF
	PHA
	ASL
	PLA
	ROR
	STA @LOCAL02
	STA @VIRTUAL02
	LDX @LOCAL03
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BCS @UNKNOWN0
	LDA @LOCAL02
	STA __BSS_START__,X
@UNKNOWN0:
	LOADPTR MSG_BTL_GUTS_DOWN, @LOCAL00
	LDX CURRENT_TARGET
	TYA
	SEC
	SBC a:battler::guts,X
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
@UNKNOWN1:
	END_C_FUNCTION
