
BTLACT_DEFENSE_SPRAY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @UNKNOWN0
	LDX CURRENT_TARGET
	LDY a:battler::defense,X
	STY @LOCAL02
	LDA CURRENT_TARGET
	JSR INCREASE_DEFENSE_16TH
	LOADPTR MSG_BTL_DEFENSE_UP, @LOCAL00
	LDY @LOCAL02
	STY @VIRTUAL02
	LDX CURRENT_TARGET
	LDA a:battler::defense,X
	SEC
	SBC @VIRTUAL02
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
@UNKNOWN0:
	END_C_FUNCTION
