
BTLACT_DIAMONDIZE: ;$C289CE
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	TDC
	ADC #$FFEE
	TCD
	JSR a:.LOWORD(ATK_FAIL_CHK)
	CMP #$0000
	BEQ @UNKNOWN0
	JMP a:.LOWORD(@UNKNOWN4)
@UNKNOWN0:
	LDX .LOWORD(CURRENT_TARGET)
	SEP #PROC_FLAGS::ACCUM8
	LDA a:.LOWORD(RAM)+55,X
	JSR a:.LOWORD(SUCCESS_255)
	.A16
	CMP #$0000
	BNE @UNKNOWN1
	JMP a:.LOWORD(@UNKNOWN3)
@UNKNOWN1:
	LDY #STATUS_0::DIAMONDIZED
	LDX #STATUS_GROUP::PERSISTENT_EASYHEAL
	LDA .LOWORD(CURRENT_TARGET)
	JSR a:.LOWORD(INFLICT_STATUS_BATTLE)
	CMP #$0000
	BNE @UNKNOWN2
	JMP a:.LOWORD(@UNKNOWN3)
@UNKNOWN2:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	LDX .LOWORD(CURRENT_TARGET)
	STA a:.LOWORD(RAM)+35,X
	LDX .LOWORD(CURRENT_TARGET)
	STA a:.LOWORD(RAM)+34,X
	LDX .LOWORD(CURRENT_TARGET)
	STA a:.LOWORD(RAM)+33,X
	LDX .LOWORD(CURRENT_TARGET)
	STA a:.LOWORD(RAM)+32,X
	LDX .LOWORD(CURRENT_TARGET)
	STA a:.LOWORD(RAM)+31,X
	LDX .LOWORD(CURRENT_TARGET)
	STA a:.LOWORD(RAM)+30,X
	REP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(CURRENT_TARGET)
	CLC
	ADC #$003F
	TAY
	LDA a:.LOWORD(RAM),Y
	STA $0A
	LDA a:.LOWORD(RAM)+2,Y
	STA $0C
	LDA .LOWORD(BATTLE_EXP_SCRATCH)
	STA $06
	LDA .LOWORD(BATTLE_EXP_SCRATCH)+2
	STA $08
	CLC
	LDA $06
	ADC $0A
	STA $06
	LDA $08
	ADC $0C
	STA $08
	LDA $06
	STA .LOWORD(BATTLE_EXP_SCRATCH)
	LDA $08
	STA .LOWORD(BATTLE_EXP_SCRATCH)+2
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:.LOWORD(RAM)+61,X
	CLC
	ADC .LOWORD(BATTLE_MONEY_SCRATCH)
	STA .LOWORD(BATTLE_MONEY_SCRATCH)
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF6AC7
	BRA @UNKNOWN4
@UNKNOWN3:
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF766E
@UNKNOWN4:
	PLD
	RTL
