
BTLACT_DIAMONDIZE: ;$C289CE
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	JSR FAIL_ATTACK_ON_NPCS
	CMP #$0000
	BNEL @UNKNOWN4
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::paralysis_resist,X
	JSR SUCCESS_255
	.A16
	CMP #$0000
	BEQL @UNKNOWN3
	LDY #STATUS_0::DIAMONDIZED
	LDX #STATUS_GROUP::PERSISTENT_EASYHEAL
	LDA CURRENT_TARGET
	JSR INFLICT_STATUS_BATTLE
	CMP #$0000
	BEQL @UNKNOWN3
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	LDX CURRENT_TARGET
	STA a:battler::afflictions + STATUS_GROUP::SHIELD,X
	LDX CURRENT_TARGET
	STA a:battler::afflictions + STATUS_GROUP::HOMESICKNESS,X
	LDX CURRENT_TARGET
	STA a:battler::afflictions + STATUS_GROUP::CONCENTRATION,X
	LDX CURRENT_TARGET
	STA a:battler::afflictions + STATUS_GROUP::STRANGENESS,X
	LDX CURRENT_TARGET
	STA a:battler::afflictions + STATUS_GROUP::TEMPORARY,X
	LDX CURRENT_TARGET
	STA a:battler::afflictions + STATUS_GROUP::PERSISTENT_HARDHEAL,X
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_TARGET
	CLC
	ADC #battler::exp
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, $0A
	MOVE_INT BATTLE_EXP_SCRATCH, $06
	CLC
	ADD_INT_ASSIGN $06, $0A
	MOVE_INT $06, BATTLE_EXP_SCRATCH
	LDX CURRENT_TARGET
	LDA a:battler::money,X
	CLC
	ADC BATTLE_MONEY_SCRATCH
	STA BATTLE_MONEY_SCRATCH
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_DAIYA_ON
	BRA @UNKNOWN4
@UNKNOWN3:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@UNKNOWN4:
	PLD
	RTL
