
BTLACT_DISTRACT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @UNKNOWN1
	JSR SUCCESS_LUCK40
	CMP #0
	BEQ @UNKNOWN0
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::paralysis_resist,X
	JSR SUCCESS_255
	.A16
	CMP #0
	BEQ @UNKNOWN0
	LDA CURRENT_TARGET
	CLC
	ADC #battler::afflictions + STATUS_GROUP::CONCENTRATION
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BNE @UNKNOWN0
	SEP #PROC_FLAGS::ACCUM8
	LDA #STATUS_4::CANT_CONCENTRATE4
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_FUUIN_ON
	BRA @UNKNOWN1
@UNKNOWN0:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@UNKNOWN1:
	END_C_FUNCTION
