
BTLACT_GIYGAS_PRAYER_4: ;$C2C623
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LOADPTR TEXT_BATTLE_GIYGAS_PRAYER_4, $0E
	LDX #MUSIC::GIYGAS_PHASE3
	LDA #BATTLE_GROUPS::GIYGAS_AFTER_PRAYER1
	JSR a:.LOWORD(UNKNOWN_C2C37A)
	LDA #GIYGAS_PRAYER_DAMAGE_3
	JSR a:.LOWORD(GIYGAS_HURT_PRAYER)
	LDA #GIYGAS_PHASES::PRAYER_4_USED
	STA .LOWORD(GIYGAS_PHASE)
	PLD
	RTL
