
BTLACT_HANDBAG_STRAP: ;$C2A5EC
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 20
	JSR FAIL_ATTACK_ON_NPCS
	CMP #$0000
	BNE @UNKNOWN3
	LDA #$00FA
	JSR SUCCESS_SPEED
	CMP #$0000
	BEQ @UNKNOWN2
	LDX CURRENT_TARGET
	LDA #HANDBAG_STRAP_BASE_DAMAGE
	SEC
	SBC a:battler::defense,X
	STA $12
	CLC
	SBC #$0000
	BRANCHLTEQS @UNKNOWN2
	LDX #$00FF
	LDA $12
	JSR CALC_RESIST_DAMAGE
	LDY #STATUS_2::SOLIDIFIED
	LDX #STATUS_GROUP::TEMPORARY
	LDA CURRENT_TARGET
	JSR INFLICT_STATUS_BATTLE
	CMP #$0000
	BEQ @UNKNOWN3
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KOORI_ON
	BRA @UNKNOWN3
@UNKNOWN2:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@UNKNOWN3:
	PLD
	RTL
