
BTLACT_HEALING_A: ;$C29AEA
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDA CURRENT_TARGET
	CLC
	ADC #$001D
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP #$0007
	BEQ @UNKNOWN0
	CMP #$0006
	BEQ @UNKNOWN1
	BRA @UNKNOWN2
@UNKNOWN0:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KAZE_OFF
	BRA @UNKNOWN4
@UNKNOWN1:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NISSYA_OFF
	BRA @UNKNOWN4
@UNKNOWN2:
	LDA CURRENT_TARGET
	CLC
	ADC #$001F
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN3
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NEMURI_OFF
	BRA @UNKNOWN4
@UNKNOWN3:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_HEAL_NG
@UNKNOWN4:
	PLD
	RTL
