
BTLACT_HEALING_O: ;$C29CB8
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDX CURRENT_TARGET
	LDA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN0
	LDX CURRENT_TARGET
	LDA a:battler::hp_max,X
	TAX
	LDA CURRENT_TARGET
	JSR REVIVE_TARGET
	BRA @UNKNOWN1
@UNKNOWN0:
	JSL BTLACT_HEALING_G
@UNKNOWN1:
	RTL
