
BTLACT_IMMOBILIZE: ;$C28CB8
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDY #STATUS_2::IMMOBILIZED
	LDX #STATUS_GROUP::TEMPORARY
	LDA CURRENT_TARGET
	JSR INFLICT_STATUS_BATTLE
	CMP #$0000
	BEQ @UNKNOWN0
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_SHIBARA_ON
	BRA @UNKNOWN1
@UNKNOWN0:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@UNKNOWN1:
	PLD
	RTL
