
BTLACT_LEVEL_2_ATK: ;$C28523
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 16
	LDX .LOWORD(CURRENT_ATTACKER)
	LDA a:.LOWORD(RAM)+38,X
	ASL
	LDX .LOWORD(CURRENT_TARGET)
	SEC
	SBC a:.LOWORD(RAM)+40,X
	STA $0E
	CLC
	SBC #$0000
	BVC @UNKNOWN0
	BPL @UNKNOWN2
	BRA @UNKNOWN1
@UNKNOWN0:
	BMI @UNKNOWN2
@UNKNOWN1:
	LDA $0E
	JSR a:.LOWORD(TWENTY_FIVE_PERCENT_VARIANCE)
	STA $0E
@UNKNOWN2:
	LDA $0E
	CLC
	SBC #$0000
	BVS @UNKNOWN3
	BPL @UNKNOWN5
	BRA @UNKNOWN4
@UNKNOWN3:
	BMI @UNKNOWN5
@UNKNOWN4:
	LDA #$0001
	STA $0E
@UNKNOWN5:
	LDX #$00FF
	LDA $0E
	JSR a:.LOWORD(CALC_RESIST_DAMAGE)
	PLD
	RTS

