
BTLACT_LVL_2_ATK_DIAMONDIZE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNEL @UNKNOWN7
	LDA #0
	JSR MISS_CALC
	CMP #0
	BNEL @UNKNOWN7
	JSR SMAAAASH
	CMP #0
	BNEL @UNKNOWN7
	JSR DETERMINE_DODGE
	CMP #0
	BNEL @UNKNOWN6
	JSR BTLACT_LEVEL_2_ATK
	JSR HEAL_STRANGENESS
	JSR SUCCESS_LUCK80
	CMP #0
	BEQL @UNKNOWN7
	LDY #STATUS_0::DIAMONDIZED
	LDX #STATUS_GROUP::PERSISTENT_EASYHEAL
	LDA CURRENT_TARGET
	JSR INFLICT_STATUS_BATTLE
	CMP #0
	BEQL @UNKNOWN7
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	LDX CURRENT_TARGET
	STA a:battler::afflictions + STATUS_GROUP::SHIELD,X
	LDX CURRENT_TARGET
	STA a:battler::afflictions + STATUS_GROUP::HOMESICKNESS,X
	LDX CURRENT_TARGET
	STA a:battler::afflictions + STATUS_GROUP::CONCENTRATION,X
	LDX CURRENT_TARGET
	STA a:battler::afflictions + STATUS_GROUP::STRANGENESS,X
	LDX CURRENT_TARGET
	STA a:battler::afflictions + STATUS_GROUP::TEMPORARY,X
	LDX CURRENT_TARGET
	STA a:battler::afflictions + STATUS_GROUP::PERSISTENT_HARDHEAL,X
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_TARGET
	CLC
	ADC #battler::exp
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	MOVE_INT BATTLE_EXP_SCRATCH, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, BATTLE_EXP_SCRATCH
	LDX CURRENT_TARGET
	LDA a:battler::money,X
	CLC
	ADC BATTLE_MONEY_SCRATCH
	STA BATTLE_MONEY_SCRATCH
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_DAIYA_ON
	BRA @UNKNOWN7
@UNKNOWN6:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TATAKU_YOKETA
@UNKNOWN7:
	END_C_FUNCTION
