
BTLACT_LEVEL_2_ATK_POISON: ;$C28F97
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	JSR FAIL_ATTACK_ON_NPCS
	CMP #$0000
	BNE @UNKNOWN1
	LDA #$0000
	JSR MISS_CALC
	CMP #$0000
	BNE @UNKNOWN1
	JSR SMAAAASH
	CMP #$0000
	BNE @UNKNOWN1
	JSR DETERMINE_DODGE
	CMP #$0000
	BNE @UNKNOWN0
	JSR BTLACT_LEVEL_2_ATK
	JSR HEAL_STRANGENESS
	LDY #STATUS_0::POISONED
	LDX #STATUS_GROUP::PERSISTENT_EASYHEAL
	LDA CURRENT_TARGET
	JSR INFLICT_STATUS_BATTLE
	CMP #$0000
	BEQ @UNKNOWN1
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_MODOKU_ON
	BRA @UNKNOWN1
@UNKNOWN0:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TATAKU_YOKETA
@UNKNOWN1:
	PLD
	RTL
