
BTLACT_OFFENSE_UP_A: ;$C29E38
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 24
	JSR a:.LOWORD(ATK_FAIL_CHK)
	CMP #$0000
	BNE @UNKNOWN0
	LDX .LOWORD(CURRENT_TARGET)
	LDY a:battler::offense,X
	STY $16
	LDA .LOWORD(CURRENT_TARGET)
	JSR a:.LOWORD(INCREASE_OFFENSE_16TH)
	LOADPTR TEXT_BATTLE_OFFENSE_WENT_UP, $0E
	LDY $16
	STY $02
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::offense,X
	SEC
	SBC $02
	STA $06
	STZ $08
	MOVE_INT $06, $12
	JSL DISPLAY_TEXT_WAIT
@UNKNOWN0:
	PLD
	RTL
