
BTLACT_OFFENSE_UP_A: ;$C29E38
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 24
	JSR FAIL_ATTACK_ON_NPCS
	CMP #$0000
	BNE @UNKNOWN0
	LDX CURRENT_TARGET
	LDY a:battler::offense,X
	STY $16
	LDA CURRENT_TARGET
	JSR INCREASE_OFFENSE_16TH
	LOADPTR MSG_BTL_OFFENSE_UP, $0E
	LDY $16
	STY $02
	LDX CURRENT_TARGET
	LDA a:battler::offense,X
	SEC
	SBC $02
	STORE_INT1632 $06
	MOVE_INT $06, $12
	JSL DISPLAY_TEXT_WAIT
@UNKNOWN0:
	PLD
	RTL
