
BTLACT_POSSESS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @UNKNOWN1
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @UNKNOWN0
	LDY #STATUS_1::POSSESSED
	LDX #STATUS_GROUP::PERSISTENT_HARDHEAL
	LDA CURRENT_TARGET
	JSR INFLICT_STATUS_BATTLE
	CMP #0
	BEQ @UNKNOWN0
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TORITSU_ON
	LDA BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::consciousness
	AND #$00FF
	BNE @UNKNOWN1
	LDX #.LOWORD(BATTLERS_TABLE) + (TOTAL_PARTY_COUNT)*.SIZEOF(battler)
	LDA #ENEMY::TINY_LIL_GHOST
	JSL BATTLE_INIT_ENEMY_STATS
	SEP #PROC_FLAGS::ACCUM8
	LDA #ENEMY::TINY_LIL_GHOST
	STA BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::npc_id
	LDA #1
	STA BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+13
	BRA @UNKNOWN1
@UNKNOWN0:
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@UNKNOWN1:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
