
BTLACT_POSSESS: ;$C28BFD
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	PHD
	TDC
	ADC #$FFEE
	TCD
	JSR a:.LOWORD(ATK_FAIL_CHK)
	CMP #$0000
	BNE @UNKNOWN1
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:.LOWORD(RAM)+battler::ally_or_enemy,X
	AND #$00FF
	BNE @UNKNOWN0
	LDY #STATUS_1::POSSESSED
	LDX #STATUS_GROUP::PERSISTENT_HARDHEAL
	LDA .LOWORD(CURRENT_TARGET)
	JSR a:.LOWORD(INFLICT_STATUS_BATTLE)
	CMP #$0000
	BEQ @UNKNOWN0
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF6B98
	LDA .LOWORD(BATTLERS_TABLE)+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::consciousness
	AND #$00FF
	BNE @UNKNOWN1
	LDX #.LOWORD(BATTLERS_TABLE) + (TOTAL_PARTY_COUNT)*.SIZEOF(battler)
	LDA #ENEMY::TINY_LIL_GHOST
	JSL BATTLE_INIT_ENEMY_STATS
	SEP #PROC_FLAGS::ACCUM8
	LDA #ENEMY::TINY_LIL_GHOST
	STA .LOWORD(BATTLERS_TABLE)+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::npc_id
	LDA #$0001
	STA .LOWORD(BATTLERS_TABLE)+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+13
	BRA @UNKNOWN1
@UNKNOWN0:
	.A16
	DISPLAY_BATTLE_TEXT_PTR TEXT_BLOCK_EF766E
@UNKNOWN1:
	REP #PROC_FLAGS::ACCUM8
	PLD
	RTL
