
BTLACT_PRAY_SUBTLE: ;$C2AC2A
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDX CURRENT_TARGET
	LDA a:battler::hp_max,X
	LSR
	LSR
	LSR
	LSR
	TAX
	LDA CURRENT_TARGET
	JSR RECOVER_HP
	RTL
