
BTLACT_PSI_SHIELD_A: ;$C29DBE
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDX #STATUS_6::PSI_SHIELD
	LDA CURRENT_TARGET
	JSR SHIELDS_COMMON
	CMP #$0000
	BEQ @UNKNOWN0
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_PSYCO_ADD
	BRA @UNKNOWN1
@UNKNOWN0:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_PSYCO_ON
@UNKNOWN1:
	PLD
	RTL
