
FLASH_IMMUNITY_TEST: ;$C298A1
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	JSR PSI_SHIELD_NULLIFY
	CMP #$0000
	BEQ @UNKNOWN0
	LDA #$0000
	BRA @UNKNOWN2
@UNKNOWN0:
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::flash_resist,X
	JSR SUCCESS_255
	.A16
	CMP #$0000
	BEQ @UNKNOWN1
	LDA #$0001
	BRA @UNKNOWN2
@UNKNOWN1:
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
	LDA #$0000
@UNKNOWN2:
	PLD
	RTS
