
PSI_ROCKIN_COMMON:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL02
	JSR PSI_SHIELD_NULLIFY
	CMP #0
	BNE @RETURN
	LDX @LOCAL02
	TXA
	JSR FIFTY_PERCENT_VARIANCE
	STA @LOCAL01
	JSR DETERMINE_DODGE
	TAX
	BEQ @UNKNOWN0
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
	BRA @UNKNOWN1
@UNKNOWN0:
	LDX #$00FF
	LDA @LOCAL01
	JSR CALC_RESIST_DAMAGE
@UNKNOWN1:
	JSR WEAKEN_SHIELD
@RETURN:
	END_C_FUNCTION
