
PSI_STARSTORM_COMMON:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL00
	JSR PSI_SHIELD_NULLIFY
	CMP #0
	BNE @UNKNOWN0
	LDX @LOCAL00
	TXA
	JSR TWENTY_FIVE_PERCENT_VARIANCE
	LDX #$00FF
	JSR CALC_RESIST_DAMAGE
	JSR WEAKEN_SHIELD
@UNKNOWN0:
	END_C_FUNCTION
