
BTLACT_RAINBOW_OF_COLOURS: ;$C2C14E
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 18
	LDX CURRENT_ATTACKER
	LDA a:battler::sprite_x,X
	AND #$00FF
	STA $02
	LDX CURRENT_ATTACKER
	LDA a:battler::sprite_y,X
	AND #$00FF
	TAY
	STY $10
	LDX CURRENT_ATTACKER
	STX $0E
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action_argument,X
	AND #$00FF
	LDX $0E
	JSL BATTLE_INIT_ENEMY_STATS
	LDA $02
	SEP #PROC_FLAGS::ACCUM8
	LDX CURRENT_ATTACKER
	STA a:battler::sprite_x,X
	LDY $10
	REP #PROC_FLAGS::ACCUM8
	TYA
	SEP #PROC_FLAGS::ACCUM8
	LDX CURRENT_ATTACKER
	STA a:battler::sprite_y,X
	LDX CURRENT_ATTACKER
	REP #PROC_FLAGS::ACCUM8
	LDA RAM,X
	JSR UNKNOWN_C2F09F
	SEP #PROC_FLAGS::ACCUM8
	LDX CURRENT_ATTACKER
	STA a:battler::vram_sprite_index,X
	LDA #$0001
	LDX CURRENT_ATTACKER
	STA a:battler::has_taken_turn,X
	REP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA UNKNOWN_7EAA92
	PLD
	RTL
