
BTLACT_RANDOM_STAT_UP_1D4:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #7
	JSR RAND_LIMIT
	CMP #0
	BEQ @UNKNOWN5
	CMP #1
	BEQ @UNKNOWN7
	CMP #2
	BEQL @UNKNOWN9
	CMP #3
	BEQL @UNKNOWN10
	CMP #4
	BEQL @UNKNOWN11
	CMP #5
	BEQL @UNKNOWN12
	CMP #6
	BEQL @UNKNOWN13
	JMP @UNKNOWN14
@UNKNOWN5:
	LDA #4
	JSR RAND_LIMIT
	INC
	STA @LOCAL02
	LDA CURRENT_TARGET
	CLC
	ADC #battler::defense
	TAX
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LOADPTR MSG_BTL_DEFENSE_UP, @LOCAL00
	MOVE_INT1632S @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @UNKNOWN14
@UNKNOWN7:
	LDA #4
	JSR RAND_LIMIT
	INC
	STA @LOCAL02
	LDA CURRENT_TARGET
	CLC
	ADC #battler::offense
	TAX
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LOADPTR MSG_BTL_OFFENSE_UP, @LOCAL00
	MOVE_INT1632S @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @UNKNOWN14
@UNKNOWN9:
	JSL BTLACT_SPEED_UP_1D4
	BRA @UNKNOWN14
@UNKNOWN10:
	JSL BTLACT_GUTS_UP_1D4
	BRA @UNKNOWN14
@UNKNOWN11:
	JSL BTLACT_VITALITY_UP_1D4
	BRA @UNKNOWN14
@UNKNOWN12:
	JSL BTLACT_IQ_UP_1D4
	BRA @UNKNOWN14
@UNKNOWN13:
	JSL BTLACT_LUCK_UP_1D4
@UNKNOWN14:
	END_C_FUNCTION
