
BTLACT_REDUCEPP: ;$C28E42
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 24
	LDX CURRENT_TARGET
	LDA a:battler::pp_target,X
	BNE @UNKNOWN0
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_PPSUCK_ZERO
	BRA @UNKNOWN3
@UNKNOWN0:
	LDX CURRENT_TARGET
	LDA a:battler::pp_max,X
	LSR
	LSR
	LSR
	LSR
	BEQ @UNKNOWN2
	JSR FIFTY_PERCENT_VARIANCE
	TAY
	STY $16
	TYX
	LDA CURRENT_TARGET
	JSR REDUCE_PP
	LOADPTR MSG_BTL_PPSUCK_OBJ, $0E
	LDY $16
	TYA
	STORE_INT1632S $06
	MOVE_INT $06, $12
	JSL DISPLAY_TEXT_WAIT
	BRA @UNKNOWN3
@UNKNOWN2:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@UNKNOWN3:
	PLD
	RTL
