
BTLACT_REDUCEOFFDEF:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @UNKNOWN0
	LDX CURRENT_TARGET
	LDY a:battler::offense,X
	STY @LOCAL02
	LDA CURRENT_TARGET
	JSR HEXADECIMATE_OFFENSE
	LOADPTR MSG_BTL_OFFENSE_DOWN, @LOCAL00
	LDX CURRENT_TARGET
	LDY @LOCAL02
	TYA
	SEC
	SBC a:battler::offense,X
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	LDX CURRENT_TARGET
	LDY a:battler::defense,X
	STY @LOCAL02
	LDA CURRENT_TARGET
	JSR HEXADECIMATE_DEFENSE
	LOADPTR MSG_BTL_DEFENSE_DOWN, @LOCAL00
	LDX CURRENT_TARGET
	LDY @LOCAL02
	TYA
	SEC
	SBC a:battler::defense,X
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
@UNKNOWN0:
	END_C_FUNCTION
