
RUST_SPRAY_COMMON:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL01
	JSR SUCCESS_LUCK80
	CMP #0
	BEQ @FAILURE
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @FAILURE
	LDX CURRENT_TARGET
	LDA a:battler::id,X
	JSR GET_ENEMY_TYPE
	CMP #2
	BNE @FAILURE
	LDX @LOCAL01
	TXA
	JSR FIFTY_PERCENT_VARIANCE
	LDX #$00FF
	JSR CALC_RESIST_DAMAGE
	BRA @RETURN
@FAILURE:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@RETURN:
	END_C_FUNCTION
