
BTLACT_SHIELD_B:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDX #STATUS_6::SHIELD_POWER
	LDA CURRENT_TARGET
	JSR SHIELDS_COMMON
	CMP #0
	BEQ @UNKNOWN0
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_POWER_ADD
	BRA @UNKNOWN1
@UNKNOWN0:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_POWER_ON
@UNKNOWN1:
	END_C_FUNCTION
