
BTLACT_SHOOT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA #1
	JSR MISS_CALC
	CMP #0
	BNE @UNKNOWN1
	JSR DETERMINE_DODGE
	CMP #0
	BNE @UNKNOWN0
	JSR BTLACT_LEVEL_2_ATK
	BRA @UNKNOWN1
@UNKNOWN0:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_UTU_YOKETA
@UNKNOWN1:
	END_C_FUNCTION
