
BTLACT_SPY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	END_STACK_VARS
	LOADPTR MSG_BTL_CHECK_OFFENSE, @LOCAL00
	LDX CURRENT_TARGET
	LDA a:battler::offense,X
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	LOADPTR MSG_BTL_CHECK_DEFENSE, @LOCAL00
	LDX CURRENT_TARGET
	LDA a:battler::defense,X
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	LDX CURRENT_TARGET
	LDA a:battler::fire_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @UNKNOWN0
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_ANTI_FIRE
@UNKNOWN0:
	LDX CURRENT_TARGET
	LDA a:battler::freeze_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @UNKNOWN1
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_ANTI_FREEZE
@UNKNOWN1:
	LDX CURRENT_TARGET
	LDA a:battler::flash_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @UNKNOWN2
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_ANTI_FLASH
@UNKNOWN2:
	LDX CURRENT_TARGET
	LDA a:battler::paralysis_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @UNKNOWN3
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_ANTI_PARALYSIS
@UNKNOWN3:
	LDX CURRENT_TARGET
	LDA a:battler::hypnosis_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @UNKNOWN4
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_BRAIN_LEVEL_0
@UNKNOWN4:
	LDX CURRENT_TARGET
	LDA a:battler::brainshock_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @UNKNOWN5
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_BRAIN_LEVEL_3
@UNKNOWN5:
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @UNKNOWN6
	LDA #3
	JSL FIND_INVENTORY_SPACE2
	CMP #0
	BEQ @UNKNOWN6
	LDA ITEM_DROPPED
	BEQ @UNKNOWN6
	SEP #PROC_FLAGS::ACCUM8
	LDA ITEM_DROPPED
	JSL REDIRECT_C1ACF8
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_PRESENT_GET
	STZ ITEM_DROPPED
@UNKNOWN6:
	END_C_FUNCTION
