
BTLACT_SPY: ;$C28770
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	LOADPTR TEXT_BATTLE_SPY_OFFENSE, $0E
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::offense,X
	STA $06
	STZ $08
	MOVE_INT $06, $12
	JSL DISPLAY_TEXT_WAIT
	LOADPTR TEXT_BATTLE_SPY_DEFENSE, $0E
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::defense,X
	STA $06
	STZ $08
	MOVE_INT $06, $12
	JSL DISPLAY_TEXT_WAIT
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::fire_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @UNKNOWN0
	DISPLAY_BATTLE_TEXT_PTR TEXT_BATTLE_SPY_VULNERABLE_TO_FIRE
@UNKNOWN0:
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::freeze_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @UNKNOWN1
	DISPLAY_BATTLE_TEXT_PTR TEXT_BATTLE_SPY_VULNERABLE_TO_ICE
@UNKNOWN1:
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::flash_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @UNKNOWN2
	DISPLAY_BATTLE_TEXT_PTR TEXT_BATTLE_SPY_VULNERABLE_TO_FLASH
@UNKNOWN2:
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::paralysis_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @UNKNOWN3
	DISPLAY_BATTLE_TEXT_PTR TEXT_BATTLE_SPY_VULNERABLE_TO_PARALYSIS
@UNKNOWN3:
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::hypnosis_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @UNKNOWN4
	DISPLAY_BATTLE_TEXT_PTR TEXT_BATTLE_SPY_VULNERABLE_TO_HYPNOSIS
@UNKNOWN4:
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::brainshock_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @UNKNOWN5
	DISPLAY_BATTLE_TEXT_PTR TEXT_BATTLE_SPY_VULNERABLE_TO_BRAINSHOCK
@UNKNOWN5:
	LDX .LOWORD(CURRENT_TARGET)
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @UNKNOWN6
	LDA #$0003
	JSL FIND_INVENTORY_SPACE2
	CMP #$0000
	BEQ @UNKNOWN6
	LDA .LOWORD(ITEM_DROPPED)
	BEQ @UNKNOWN6
	SEP #PROC_FLAGS::ACCUM8
	LDA .LOWORD(ITEM_DROPPED)
	JSL REDIRECT_C1ACF8
	.A16
	DISPLAY_BATTLE_TEXT_PTR TEXT_BATTLE_SPY_FOUND_ITEM
	STZ .LOWORD(ITEM_DROPPED)
@UNKNOWN6:
	PLD
	RTL
