
BTLACT_SWITCH_ARMOR:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #1
	JSR ENABLE_BLINKING_TRIANGLE
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action_argument,X
	AND #$00FF
	TAX
	STX @LOCAL05
	LDX CURRENT_ATTACKER
	LDA a:battler::id,X
	LDX @LOCAL05
	JSL UNKNOWN_C3EE14
	CMP #0
	BEQL @UNKNOWN1
	LDX CURRENT_ATTACKER
	LDA a:battler::row,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAY
	STY @LOCAL04
	LDX CURRENT_ATTACKER
	LDA a:battler::base_defense,X
	AND #$00FF
	STA @VIRTUAL04
	LDX CURRENT_ATTACKER
	LDA a:battler::defense,X
	SEC
	SBC @VIRTUAL04
	STA @VIRTUAL02
	STA @LOCAL03
	LDX CURRENT_ATTACKER
	LDA a:battler::base_speed,X
	AND #$00FF
	STA @VIRTUAL02
	LDX CURRENT_ATTACKER
	LDA a:battler::speed,X
	SEC
	SBC @VIRTUAL02
	STA @VIRTUAL04
	LDX CURRENT_ATTACKER
	LDA a:battler::base_luck,X
	AND #$00FF
	STA @VIRTUAL02
	LDX CURRENT_ATTACKER
	LDA a:battler::luck,X
	SEC
	SBC @VIRTUAL02
	STA @LOCAL02
	LDX CURRENT_ATTACKER
	LDA a:battler::action_item_slot,X
	AND #$00FF
	TAX
	STX @LOCAL01
	LDX CURRENT_ATTACKER
	LDA a:battler::id,X
	LDX @LOCAL01
	JSR EQUIP_ITEM
	DISPLAY_TEXT_PTR MSG_BTL_EQUIP_OK
	LDY @LOCAL04
	SEP #PROC_FLAGS::ACCUM8
	LDA a:char_struct::defense,Y
	LDX CURRENT_ATTACKER
	STA a:battler::base_defense,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL02
	LDX CURRENT_ATTACKER
	LDA a:battler::base_defense,X
	AND #$00FF
	CLC
	ADC @VIRTUAL02
	LDX CURRENT_ATTACKER
	STA a:battler::defense,X
	SEP #PROC_FLAGS::ACCUM8
	LDA a:char_struct::speed,Y
	LDX CURRENT_ATTACKER
	STA a:battler::base_speed,X
	LDX CURRENT_ATTACKER
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::base_speed,X
	AND #$00FF
	CLC
	ADC @VIRTUAL04
	LDX CURRENT_ATTACKER
	STA a:battler::speed,X
	SEP #PROC_FLAGS::ACCUM8
	LDA a:char_struct::luck,Y
	LDX CURRENT_ATTACKER
	STA a:battler::base_luck,X
	LDX CURRENT_ATTACKER
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::base_luck,X
	AND #$00FF
	CLC
	ADC @LOCAL02
	LDX CURRENT_ATTACKER
	STA a:battler::luck,X
	SEP #PROC_FLAGS::ACCUM8
	LDA a:char_struct::fire_resist,Y
	JSL CALC_PSI_DMG_MODIFIERS
	LDX CURRENT_ATTACKER
	STA a:battler::fire_resist,X
	LDY @LOCAL04
	LDA a:char_struct::freeze_resist,Y
	JSL CALC_PSI_DMG_MODIFIERS
	LDX CURRENT_ATTACKER
	STA a:battler::freeze_resist,X
	LDY @LOCAL04
	LDA a:char_struct::flash_resist,Y
	JSL CALC_PSI_RES_MODIFIERS
	LDX CURRENT_ATTACKER
	STA a:battler::flash_resist,X
	LDY @LOCAL04
	LDA a:char_struct::paralysis_resist,Y
	JSL CALC_PSI_RES_MODIFIERS
	LDX CURRENT_ATTACKER
	STA a:battler::paralysis_resist,X
	LDY @LOCAL04
	REP #PROC_FLAGS::ACCUM8
	TYA
	CLC
	ADC #char_struct::hypnosis_brainshock_resist
	TAX
	STX @LOCAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	JSL CALC_PSI_RES_MODIFIERS
	LDX CURRENT_ATTACKER
	STA a:battler::hypnosis_resist,X
	LDX @LOCAL02
	LDA __BSS_START__,X
	STA @VIRTUAL00
	LDA #3
	SEC
	SBC @VIRTUAL00
	JSL CALC_PSI_RES_MODIFIERS
	LDX CURRENT_ATTACKER
	STA a:battler::brainshock_resist,X
	BRA @UNKNOWN2
@UNKNOWN1:
	.A16
	DISPLAY_TEXT_PTR MSG_BTL_EQUIP_NG_WEAPON
@UNKNOWN2:
	JSR CLEAR_BLINKING_PROMPT
	END_C_FUNCTION
