
BTLACT_TELEPORT_BOX:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_ATTRS
	AND #$0080
	BNEL @TELEPORT_BOX_UNUSABLE
	LDA BATTLE_MODE_FLAG
	BEQ @UNKNOWN1
	LDA #100
	JSR RAND_LIMIT
	STA @LOCAL02
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action_argument,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CMP @VIRTUAL02
	BCS @TELEPORT_BOX_FAILURE
	JSR BOSS_BATTLE_CHECK
	CMP #0
	BEQ @TELEPORT_BOX_FAILURE
@UNKNOWN1:
	LDX CURRENT_ATTACKER
	LDA a:battler::action_item_slot,X
	AND #$00FF
	TAX
	STX @LOCAL01
	LDX CURRENT_ATTACKER
	LDA a:battler::id,X
	LDX @LOCAL01
	JSL REDIRECT_REMOVE_ITEM_FROM_INVENTORY
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TLPTBOX_OK
	SEP #PROC_FLAGS::ACCUM8
	LDA #TELEPORT_STYLE::INSTANT
	STA @LOCAL00
	LDA GAME_STATE + game_state::unknownC3
	JSL SET_TELEPORT_STATE
	.A16
	LDA #1
	STA SPECIAL_DEFEAT
	BRA @RETURN
@TELEPORT_BOX_FAILURE:
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TLPTBOX_NG
	BRA @RETURN
@TELEPORT_BOX_UNUSABLE:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TLPTBOX_CANT
@RETURN:
	END_C_FUNCTION
