
BTLACT_TELEPORT_BOX: ;$C2AB71
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	RESERVE_STACK_SPACE_CLOBBER 22
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_ATTRS
	AND #$0080
	BNEL @TELEPORT_BOX_UNUSABLE
	LDA BATTLE_MODE_FLAG
	BEQ @UNKNOWN1
	LDA #$0064
	JSR RAND_LIMIT
	STA $14
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action_argument,X
	AND #$00FF
	OPTIMIZED_MULT $04, .SIZEOF(item)
	CLC
	ADC #item::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA $02
	LDA $14
	CMP $02
	BCS @TELEPORT_BOX_FAILURE
	JSR BOSS_BATTLE_CHECK
	CMP #$0000
	BEQ @TELEPORT_BOX_FAILURE
@UNKNOWN1:
	LDX CURRENT_ATTACKER
	LDA a:battler::action_item_slot,X
	AND #$00FF
	TAX
	STX $12
	LDX CURRENT_ATTACKER
	LDA a:battler::id,X
	LDX $12
	JSL REDIRECT_REMOVE_ITEM_FROM_INVENTORY
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TLPTBOX_OK
	SEP #PROC_FLAGS::ACCUM8
	LDA #TELEPORT_STYLE::INSTANT
	STA $0E
	LDA GAME_STATE + game_state::unknownC3
	JSL SET_TELEPORT_STATE
	.A16
	LDA #$0001
	STA UNKNOWN_7EAA0E
	BRA @RETURN
@TELEPORT_BOX_FAILURE:
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TLPTBOX_NG
	BRA @RETURN
@TELEPORT_BOX_UNUSABLE:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TLPTBOX_CANT
@RETURN:
	PLD
	RTL
