
BTLACT_YOGURT_DISPENSER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA #250
	JSR SUCCESS_SPEED
	CMP #0
	BEQ @UNKNOWN0
	LDA #4
	JSR RAND_LIMIT
	LDX #$00FF
	INC
	JSR CALC_RESIST_DAMAGE
	BRA @UNKNOWN1
@UNKNOWN0:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@UNKNOWN1:
	END_C_FUNCTION
