
MOVEMENT_CODE_30: ;$C097B7
	LDX $88
	LDA [$80],Y
	INY
	INY
	STA $90
	AND #$00FF
	XBA
	CLC
	ADC .LOWORD(SPRITE_DELTA_Z_FRACTION_TABLE),X
	STA .LOWORD(SPRITE_DELTA_Z_FRACTION_TABLE),X
	LDA $90
	AND #$FF00
	BPL @UNKNOWN0
	ORA #$00FF
@UNKNOWN0:
	XBA
	ADC .LOWORD(SPRITE_DELTA_Z_TABLE),X
	STA .LOWORD(SPRITE_DELTA_Z_TABLE),X
	RTS
